import "./helpers/server-only";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

import manifest from "../app/manifest";
import robots from "../app/robots";
import sitemap from "../app/sitemap";
import { validatePublicSiteConfigForProduction } from "../lib/public-site-config";

test("root metadata is branded and canonical", async () => {
  const source = await readFile("app/layout.tsx", "utf8");
  assert.doesNotMatch(source, /Create Next App|Generated by create next app/);
  assert.match(source, /https:\/\/virtualkaksha\.com/);
  assert.match(source, /%s \| VirtualKaksha/);
  assert.match(source, /openGraph/);
});

test("sitemap, robots and manifest expose only approved public surfaces", () => {
  const urls = sitemap().map((item) => item.url);
  for (const route of ["", "/about", "/contact", "/privacy", "/terms", "/search"]) assert.ok(urls.includes(`https://virtualkaksha.com${route}`));
  assert.equal(urls.some((url) => /\/(?:admin|teacher|student)(?:\/|$)/.test(url)), false);
  assert.deepEqual(robots().rules, { userAgent: "*", allow: ["/", "/about", "/contact", "/privacy", "/terms", "/search"], disallow: ["/admin/", "/teacher/", "/student/", "/api/"] });
  assert.equal(manifest().icons?.[0]?.src, "/favicon.ico");
});

test("production readiness detects the unresolved legal effective date", () => {
  assert.throws(() => validatePublicSiteConfigForProduction(), /legal effective date requires owner confirmation/);
});
