export type ChapterSeed = {
  name: string;
  nameHindi: string;
  slug: string;
  chapterNumber: number;
};

function chapterSlug(name: string) {
  return name
    .toLowerCase()
    .replace(/[–—]/g, "-")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

function chapters(items: Array<[number, string, string]>): ChapterSeed[] {
  return items.map(([chapterNumber, name, nameHindi]) => ({
    chapterNumber,
    name,
    nameHindi,
    slug: chapterSlug(name),
  }));
}

const catalogue: Record<string, ChapterSeed[]> = {
  "5:mathematics": chapters([
    [1, "The Fish Tale", "मछली की कहानी"],
    [2, "Shapes and Angles", "आकृतियाँ और कोण"],
    [3, "How Many Squares?", "कितने वर्ग?"],
    [4, "Parts and Wholes", "भाग और पूर्ण"],
    [5, "Does it Look the Same?", "क्या यह वैसा ही दिखता है?"],
    [6, "Be My Multiple, I'll Be Your Factor", "गुणज और गुणनखंड"],
    [7, "Can You See the Pattern?", "क्या आप पैटर्न देख सकते हैं?"],
    [8, "Mapping Your Way", "रास्ता बनाना"],
    [9, "Boxes and Sketches", "डिब्बे और रेखाचित्र"],
    [10, "Tenths and Hundredths", "दशमलव"],
    [11, "Area and its Boundary", "क्षेत्रफल और परिमाप"],
    [12, "Smart Charts", "चार्ट"],
    [13, "Ways to Multiply and Divide", "गुणन और भाग"],
    [14, "How Big? How Heavy?", "कितना बड़ा? कितना भारी?"],
  ]),
  "5:science": chapters([
    [1, "Super Senses", "विशेष इंद्रियाँ"],
    [2, "From Tasting to Digesting", "चखने से पचाने तक"],
    [3, "Seeds and Seeds", "बीज"],
    [4, "Every Drop Counts", "हर बूँद मायने रखती है"],
    [5, "Experiments with Water", "पानी के प्रयोग"],
    [6, "A Treat for Mosquitoes", "मच्छरों के लिए दावत"],
    [7, "Walls Tell Stories", "दीवारें कहानी कहती हैं"],
    [8, "Sunita in Space", "अंतरिक्ष में सुनीता"],
    [9, "What if it Finishes?", "अगर यह खत्म हो जाए?"],
    [10, "When the Earth Shook", "जब धरती काँपी"],
    [11, "Blow Hot, Blow Cold", "गर्म-ठंडा"],
    [12, "Whose Forests?", "किसके वन?"],
    [13, "Like Father, Like Daughter", "जैसे पिता जैसे पुत्री"],
    [14, "On the Move Again", "फिर से पलायन"],
  ]),
  "6:mathematics": chapters([
    [1, "Knowing Our Numbers", "अपनी संख्याओं को जानना"],
    [2, "Whole Numbers", "पूर्ण संख्याएँ"],
    [3, "Playing with Numbers", "संख्याओं के साथ खेलना"],
    [4, "Basic Geometrical Ideas", "मूल ज्यामितीय अवधारणाएँ"],
    [5, "Understanding Elementary Shapes", "प्राथमिक आकृतियाँ"],
    [6, "Integers", "पूर्णांक"],
    [7, "Fractions", "भिन्न"],
    [8, "Decimals", "दशमलव"],
    [9, "Data Handling", "आँकड़ों का प्रबंधन"],
    [10, "Mensuration", "क्षेत्रमिति"],
    [11, "Algebra", "बीजगणित"],
    [12, "Ratio and Proportion", "अनुपात और समानुपात"],
    [13, "Symmetry", "सममिति"],
    [14, "Practical Geometry", "प्रायोगिक ज्यामिति"],
  ]),
  "6:science": chapters([
    [1, "Food: Where Does it Come From?", "भोजन: यह कहाँ से आता है?"],
    [2, "Components of Food", "भोजन के अवयव"],
    [3, "Fibre to Fabric", "रेशे से वस्त्र तक"],
    [4, "Sorting Materials into Groups", "पदार्थों का वर्गीकरण"],
    [5, "Separation of Substances", "पदार्थों का पृथक्करण"],
    [6, "Changes Around Us", "हमारे चारों ओर परिवर्तन"],
    [7, "Getting to Know Plants", "पौधों को जानना"],
    [8, "Body Movements", "शरीर की गतियाँ"],
    [9, "The Living Organisms and Their Surroundings", "जीव और उनका परिवेश"],
    [10, "Motion and Measurement of Distances", "गति और दूरी की माप"],
    [11, "Light, Shadows and Reflections", "प्रकाश, छाया और परावर्तन"],
    [12, "Electricity and Circuits", "विद्युत और परिपथ"],
    [13, "Fun with Magnets", "चुंबक से मज़ा"],
    [14, "Water", "जल"],
    [15, "Air Around Us", "हमारे चारों ओर वायु"],
    [16, "Garbage In, Garbage Out", "कचरा प्रबंधन"],
  ]),
  "7:mathematics": chapters([
    [1, "Integers", "पूर्णांक"],
    [2, "Fractions and Decimals", "भिन्न और दशमलव"],
    [3, "Data Handling", "आँकड़ों का प्रबंधन"],
    [4, "Simple Equations", "साधारण समीकरण"],
    [5, "Lines and Angles", "रेखाएँ और कोण"],
    [6, "The Triangle and its Properties", "त्रिभुज और उसके गुण"],
    [7, "Congruence of Triangles", "त्रिभुजों की सर्वांगसमता"],
    [8, "Comparing Quantities", "राशियों की तुलना"],
    [9, "Rational Numbers", "परिमेय संख्याएँ"],
    [10, "Practical Geometry", "प्रायोगिक ज्यामिति"],
    [11, "Perimeter and Area", "परिमाप और क्षेत्रफल"],
    [12, "Algebraic Expressions", "बीजीय व्यंजक"],
    [13, "Exponents and Powers", "घातांक और घात"],
    [14, "Symmetry", "सममिति"],
    [15, "Visualising Solid Shapes", "ठोस आकृतियाँ"],
  ]),
  "7:science": chapters([
    [1, "Nutrition in Plants", "पौधों में पोषण"],
    [2, "Nutrition in Animals", "जंतुओं में पोषण"],
    [3, "Heat", "ऊष्मा"],
    [4, "Acids, Bases and Salts", "अम्ल, क्षारक और लवण"],
    [5, "Physical and Chemical Changes", "भौतिक और रासायनिक परिवर्तन"],
    [6, "Respiration in Organisms", "जीवों में श्वसन"],
    [7, "Transportation in Animals and Plants", "जंतुओं और पौधों में परिवहन"],
    [8, "Reproduction in Plants", "पौधों में जनन"],
    [9, "Motion and Time", "गति और समय"],
    [10, "Electric Current and its Effects", "विद्युत धारा और इसके प्रभाव"],
    [11, "Light", "प्रकाश"],
    [12, "Forests: Our Lifeline", "वन: हमारी जीवन रेखा"],
    [13, "Wastewater Story", "अपशिष्ट जल"],
  ]),
  "8:mathematics": chapters([
    [1, "Rational Numbers", "परिमेय संख्याएँ"],
    [2, "Linear Equations in One Variable", "एक चर वाले रैखिक समीकरण"],
    [3, "Understanding Quadrilaterals", "चतुर्भुज"],
    [4, "Data Handling", "आँकड़ों का प्रबंधन"],
    [5, "Squares and Square Roots", "वर्ग और वर्गमूल"],
    [6, "Cubes and Cube Roots", "घन और घनमूल"],
    [7, "Comparing Quantities", "राशियों की तुलना"],
    [8, "Algebraic Expressions and Identities", "बीजीय व्यंजक और सर्वसमिकाएँ"],
    [9, "Mensuration", "क्षेत्रमिति"],
    [10, "Exponents and Powers", "घातांक और घात"],
    [11, "Direct and Inverse Proportions", "प्रत्यक्ष और व्युत्क्रमानुपात"],
    [12, "Factorisation", "गुणनखंड"],
    [13, "Introduction to Graphs", "आलेखों का परिचय"],
  ]),
  "8:science": chapters([
    [1, "Crop Production and Management", "फसल उत्पादन और प्रबंधन"],
    [2, "Microorganisms: Friend and Foe", "सूक्ष्मजीव: मित्र और शत्रु"],
    [3, "Coal and Petroleum", "कोयला और पेट्रोलियम"],
    [4, "Combustion and Flame", "दहन और ज्वाला"],
    [5, "Conservation of Plants and Animals", "पौधों और जंतुओं का संरक्षण"],
    [6, "Reproduction in Animals", "जंतुओं में जनन"],
    [7, "Reaching the Age of Adolescence", "किशोरावस्था"],
    [8, "Force and Pressure", "बल और दाब"],
    [9, "Friction", "घर्षण"],
    [10, "Sound", "ध्वनि"],
    [11, "Chemical Effects of Electric Current", "विद्युत धारा के रासायनिक प्रभाव"],
    [12, "Some Natural Phenomena", "कुछ प्राकृतिक घटनाएँ"],
    [13, "Light", "प्रकाश"],
  ]),
  "9:mathematics": chapters([
    [1, "Number Systems", "संख्या पद्धतियाँ"],
    [2, "Polynomials", "बहुपद"],
    [3, "Coordinate Geometry", "निर्देशांक ज्यामिति"],
    [4, "Linear Equations in Two Variables", "दो चर वाले रैखिक समीकरण"],
    [5, "Introduction to Euclid's Geometry", "यूक्लिड की ज्यामिति"],
    [6, "Lines and Angles", "रेखाएँ और कोण"],
    [7, "Triangles", "त्रिभुज"],
    [8, "Quadrilaterals", "चतुर्भुज"],
    [9, "Circles", "वृत्त"],
    [10, "Heron's Formula", "हीरोन का सूत्र"],
    [11, "Surface Areas and Volumes", "पृष्ठीय क्षेत्रफल और आयतन"],
    [12, "Statistics", "सांख्यिकी"],
    [13, "Probability", "प्रायिकता"],
  ]),
  "9:science": chapters([
    [1, "Matter in Our Surroundings", "हमारे परिवेश में पदार्थ"],
    [2, "Is Matter Around Us Pure?", "क्या हमारे चारों ओर के पदार्थ शुद्ध हैं?"],
    [3, "Atoms and Molecules", "परमाणु और अणु"],
    [4, "Structure of the Atom", "परमाणु की संरचना"],
    [5, "The Fundamental Unit of Life", "जीवन की मौलिक इकाई"],
    [6, "Tissues", "ऊतक"],
    [7, "Motion", "गति"],
    [8, "Force and Laws of Motion", "बल तथा गति के नियम"],
    [9, "Gravitation", "गुरुत्वाकर्षण"],
    [10, "Work and Energy", "कार्य और ऊर्जा"],
    [11, "Sound", "ध्वनि"],
    [12, "Improvement in Food Resources", "खाद्य संसाधनों में सुधार"],
  ]),
  "11:physics": chapters([
    [1, "Units and Measurements", "मात्रक और मापन"],
    [2, "Motion in a Straight Line", "सरल रेखा में गति"],
    [3, "Motion in a Plane", "समतल में गति"],
    [4, "Laws of Motion", "गति के नियम"],
    [5, "Work, Energy and Power", "कार्य, ऊर्जा और शक्ति"],
    [6, "System of Particles and Rotational Motion", "कणों का निकाय और घूर्णन गति"],
    [7, "Gravitation", "गुरुत्वाकर्षण"],
    [8, "Mechanical Properties of Solids", "ठोसों के यांत्रिक गुण"],
    [9, "Mechanical Properties of Fluids", "तरलों के यांत्रिक गुण"],
    [10, "Thermal Properties of Matter", "पदार्थ के तापीय गुण"],
    [11, "Thermodynamics", "ऊष्मागतिकी"],
    [12, "Kinetic Theory", "गतिज सिद्धांत"],
    [13, "Oscillations", "दोलन"],
    [14, "Waves", "तरंगें"],
  ]),
  "11:chemistry": chapters([
    [1, "Some Basic Concepts of Chemistry", "रसायन के कुछ मूल सिद्धांत"],
    [2, "Structure of Atom", "परमाणु की संरचना"],
    [3, "Classification of Elements and Periodicity", "तत्वों का वर्गीकरण और आवर्तिता"],
    [4, "Chemical Bonding and Molecular Structure", "रासायनिक आबंध और आण्विक संरचना"],
    [5, "Thermodynamics", "ऊष्मागतिकी"],
    [6, "Equilibrium", "साम्यावस्था"],
    [7, "Redox Reactions", "रेडॉक्स अभिक्रियाएँ"],
    [8, "Organic Chemistry: Some Basic Principles", "कार्बनिक रसायन: मूल सिद्धांत"],
    [9, "Hydrocarbons", "हाइड्रोकार्बन"],
  ]),
  "11:mathematics": chapters([
    [1, "Sets", "समुच्चय"],
    [2, "Relations and Functions", "संबंध और फलन"],
    [3, "Trigonometric Functions", "त्रिकोणमितीय फलन"],
    [4, "Complex Numbers and Quadratic Equations", "सम्मिश्र संख्याएँ और द्विघात समीकरण"],
    [5, "Linear Inequalities", "रैखिक असमिकाएँ"],
    [6, "Permutations and Combinations", "क्रमचय और संचय"],
    [7, "Binomial Theorem", "द्विपद प्रमेय"],
    [8, "Sequences and Series", "अनुक्रम तथा श्रेणी"],
    [9, "Straight Lines", "सरल रेखाएँ"],
    [10, "Conic Sections", "शंकु परिच्छेद"],
    [11, "Introduction to Three Dimensional Geometry", "त्रिविमीय ज्यामिति का परिचय"],
    [12, "Limits and Derivatives", "सीमाएँ और अवकलज"],
    [13, "Statistics", "सांख्यिकी"],
    [14, "Probability", "प्रायिकता"],
  ]),
  "12:physics": chapters([
    [1, "Electric Charges and Fields", "वैद्युत आवेश तथा क्षेत्र"],
    [2, "Electrostatic Potential and Capacitance", "स्थिरवैद्युत विभव तथा धारिता"],
    [3, "Current Electricity", "विद्युत धारा"],
    [4, "Moving Charges and Magnetism", "गतिमान आवेश और चुंबकत्व"],
    [5, "Magnetism and Matter", "चुंबकत्व और द्रव्य"],
    [6, "Electromagnetic Induction", "विद्युतचुंबकीय प्रेरण"],
    [7, "Alternating Current", "प्रत्यावर्ती धारा"],
    [8, "Electromagnetic Waves", "विद्युतचुंबकीय तरंगें"],
    [9, "Ray Optics and Optical Instruments", "किरण प्रकाशिकी"],
    [10, "Wave Optics", "तरंग प्रकाशिकी"],
    [11, "Dual Nature of Radiation and Matter", "विकिरण तथा द्रव्य की द्वैत प्रकृति"],
    [12, "Atoms", "परमाणु"],
    [13, "Nuclei", "नाभिक"],
    [14, "Semiconductor Electronics", "अर्धचालक इलेक्ट्रॉनिकी"],
  ]),
  "12:chemistry": chapters([
    [1, "Solutions", "विलयन"],
    [2, "Electrochemistry", "वैद्युत रसायन"],
    [3, "Chemical Kinetics", "रासायनिक बलगतिकी"],
    [4, "The d- and f-Block Elements", "d- तथा f- ब्लॉक के तत्व"],
    [5, "Coordination Compounds", "उपसहसंयोजन यौगिक"],
    [6, "Haloalkanes and Haloarenes", "हैलोऐल्केन तथा हैलोऐरीन"],
    [7, "Alcohols, Phenols and Ethers", "ऐल्कोहॉल, फीनॉल और ईथर"],
    [8, "Aldehydes, Ketones and Carboxylic Acids", "ऐल्डिहाइड, कीटोन एवं कार्बोक्सिलिक अम्ल"],
    [9, "Amines", "ऐमीन"],
    [10, "Biomolecules", "जैव-अणु"],
  ]),
  "12:mathematics": chapters([
    [1, "Relations and Functions", "संबंध तथा फलन"],
    [2, "Inverse Trigonometric Functions", "प्रतिलोम त्रिकोणमितीय फलन"],
    [3, "Matrices", "आव्यूह"],
    [4, "Determinants", "सारणिक"],
    [5, "Continuity and Differentiability", "सांतत्य तथा अवकलनीयता"],
    [6, "Application of Derivatives", "अवकलज के अनुप्रयोग"],
    [7, "Integrals", "समाकलन"],
    [8, "Application of Integrals", "समाकलनों के अनुप्रयोग"],
    [9, "Differential Equations", "अवकल समीकरण"],
    [10, "Vector Algebra", "सदिश बीजगणित"],
    [11, "Three Dimensional Geometry", "त्रिविमीय ज्यामिति"],
    [12, "Linear Programming", "रैखिक प्रोग्रामन"],
    [13, "Probability", "प्रायिकता"],
  ]),
};

export function chaptersForSubject(numericLevel: number, subjectSlug: string): ChapterSeed[] {
  return catalogue[`${numericLevel}:${subjectSlug}`] ?? [];
}
