import { NextResponse } from "next/server";
import { resolveCurrentIdentityForApi,currentIdentityFailureStatus,type CurrentIdentityResult } from "@/lib/auth/current-identity";
import { enforceRateLimitChecks,rateLimitResponse,resolveTrustedClientIp,type RateLimitAdapter } from "@/lib/rate-limit";
import { isSameOriginAction } from "@/lib/security/same-origin-action";
import { parseResourceImportCsv,RESOURCE_IMPORT_MAX_BYTES } from "@/lib/admin/resource-import-csv";
import { validateResourceImportRow } from "@/lib/admin/resource-import-validation";
import { previewResourceImport } from "@/lib/admin/resource-import-preview";
import { applyResourceImport } from "@/lib/admin/resource-import-apply";
import { revalidateResourceImport } from "@/lib/admin/resource-import-revalidation";
const PRIVATE={"Cache-Control":"private, no-store"}; const MAX_BODY=RESOURCE_IMPORT_MAX_BYTES+64*1024; const MAX_ROWS=25;
type Deps={resolveIdentity?:()=>Promise<CurrentIdentityResult>;resolveIp?:(r:Request)=>ReturnType<typeof resolveTrustedClientIp>;rateLimit?:RateLimitAdapter;parseFormData?:(r:Request)=>Promise<FormData>;preview?:typeof previewResourceImport;apply?:typeof applyResourceImport;revalidate?:typeof revalidateResourceImport};
const err=(status:number,code:string,message:string)=>NextResponse.json({ok:false,code,message},{status,headers:PRIVATE});
export async function handleResourceImportApply(request:Request,d:Deps={}){
 if(!isSameOriginAction(request.headers))return err(403,"INVALID_BATCH","The request could not be verified.");const identity=await(d.resolveIdentity??(()=>resolveCurrentIdentityForApi(["ADMIN"])))();if(!identity.ok)return err(currentIdentityFailureStatus(identity.code),"UNAVAILABLE",identity.message);
 const ip=(d.resolveIp??(r=>resolveTrustedClientIp({request:r,directAddress:process.env.NODE_ENV==="development"?"127.0.0.1":null})))(request);if(!ip.ok)return err(503,"UNAVAILABLE","CSV apply is temporarily unavailable.");const limit=await enforceRateLimitChecks([{policy:"admin-import-apply-user",identifier:identity.identity.id},{policy:"admin-import-apply-ip",identifier:ip.address}],d.rateLimit);if(limit)return limit.reason==="limited"?rateLimitResponse(limit):err(503,"UNAVAILABLE","CSV apply is temporarily unavailable.");
 const raw=request.headers.get("content-length");if(raw&&(!Number.isSafeInteger(Number(raw))||Number(raw)<0||Number(raw)>MAX_BODY))return err(413,"INVALID_BATCH","The CSV upload is too large.");if(!request.headers.get("content-type")?.toLowerCase().startsWith("multipart/form-data;"))return err(415,"INVALID_BATCH","A multipart CSV upload is required.");const form=await(d.parseFormData??(r=>r.formData()))(request).catch(()=>null);if(!form)return err(400,"INVALID_BATCH","The CSV upload is invalid.");if([...new Set(form.keys())].some(k=>k!=="file"&&k!=="confirmation")||form.getAll("file").length!==1||form.getAll("confirmation").length!==1)return err(400,"INVALID_BATCH","Exactly one file and confirmation are required.");const file=form.get("file"),confirmation=form.get("confirmation");if(!(file instanceof File)||!file.size||file.size>RESOURCE_IMPORT_MAX_BYTES||typeof confirmation!=="string")return err(400,"INVALID_BATCH","The CSV apply request is invalid.");
 try{const parsed=parseResourceImportCsv(new Uint8Array(await file.arrayBuffer()));if(parsed.length>MAX_ROWS)return err(400,"INVALID_BATCH","Apply supports at most 25 resource rows.");const preview=await(d.preview??previewResourceImport)(parsed);if(preview.summary.invalidRows)return err(400,"INVALID_BATCH","The batch contains invalid rows.");if(preview.summary.conflicts)return err(409,"CONFLICT","The batch is stale. Download and preview the latest template.");if(!preview.summary.validChanges)return err(400,"NO_CHANGES","The batch contains no changes.");const expected=`APPLY ${preview.summary.validChanges} RESOURCES`;if(confirmation.normalize("NFKC").trim()!==expected)return err(400,"CONFIRMATION_MISMATCH","The confirmation phrase does not match.");const rows=parsed.map(validateResourceImportRow);const applied=await(d.apply??applyResourceImport)(rows,identity.identity.id);if("error" in applied)return err(applied.error==="CONFLICT"?409:503,applied.error,applied.error==="CONFLICT"?"The batch changed before commit. Download and preview the latest template.":"The batch was rolled back.");let revalidation:"COMPLETED"|"DEFERRED"="COMPLETED";try{(d.revalidate??revalidateResourceImport)(applied.rows);}catch{revalidation="DEFERRED";}return NextResponse.json({ok:true,transactionOutcome:"COMMITTED",revalidation,...applied},{headers:PRIVATE});}catch(e){return err(e instanceof Error&&e.name==="ResourceImportCsvError"?400:503,e instanceof Error&&e.name==="ResourceImportCsvError"?"INVALID_BATCH":"UNAVAILABLE",e instanceof Error&&e.name==="ResourceImportCsvError"?e.message:"CSV apply is temporarily unavailable.");}
}
export async function POST(request:Request){return handleResourceImportApply(request);}
