import { assertTwentyPerChapter, cbsePyq, type PracticeQuestionSeed } from "./types";

export const class10MathematicsQuestions: PracticeQuestionSeed[] = [
  // 1. Real Numbers
  cbsePyq("class-10", "mathematics", "real-numbers", "Euclid's division lemma states that for any two positive integers a and b there exist unique integers q and r such that a = bq + r, where", ["0 ≤ r < b", "0 < r < b", "0 ≤ r ≤ b", "1 ≤ r < b"], 0, "The remainder r always satisfies 0 ≤ r < b."),
  cbsePyq("class-10", "mathematics", "real-numbers", "Using Euclid's algorithm, HCF(96, 404) is", ["4", "8", "12", "16"], 0, "404 = 96×4 + 20, 96 = 20×4 + 16, 20 = 16×1 + 4, 16 = 4×4 + 0, so HCF = 4."),
  cbsePyq("class-10", "mathematics", "real-numbers", "If HCF(26, 91) = 13, then LCM(26, 91) is", ["91", "182", "236", "364"], 1, "HCF × LCM = product of the numbers, so LCM = 26×91/13 = 182."),
  cbsePyq("class-10", "mathematics", "real-numbers", "The decimal expansion of 17/8 is", ["terminating", "non-terminating repeating", "non-terminating non-repeating", "none of these"], 0, "8 = 2³, so 17/8 has a terminating decimal expansion."),
  cbsePyq("class-10", "mathematics", "real-numbers", "The decimal expansion of 23/(2³ 5²) terminates after how many decimal places?", ["2", "3", "5", "6"], 1, "It terminates after max(3, 2) = 3 places."),
  cbsePyq("class-10", "mathematics", "real-numbers", "Which of the following is an irrational number?", ["√16", "22/7", "π", "0.¯3"], 2, "π is irrational; 22/7 is only a rational approximation to π."),
  cbsePyq("class-10", "mathematics", "real-numbers", "The product of two consecutive positive integers is always", ["an odd integer", "divisible by 2", "a prime number", "divisible by 3"], 1, "One of any two consecutive integers is even, so their product is divisible by 2."),
  cbsePyq("class-10", "mathematics", "real-numbers", "The LCM of 2³ × 3² and 2² × 3³ is", ["2² × 3²", "2³ × 3³", "2⁵ × 3⁵", "2 × 3"], 1, "LCM takes the highest powers of each prime: 2³ × 3³."),
  cbsePyq("class-10", "mathematics", "real-numbers", "If p is a prime number, then √p is", ["rational", "an integer", "irrational", "a whole number"], 2, "The square root of a prime cannot be written as p/q, so it is irrational."),
  cbsePyq("class-10", "mathematics", "real-numbers", "7 × 11 × 13 + 13 is a", ["prime number", "composite number", "neither prime nor composite", "multiple of 11 only"], 1, "13(7×11 + 1) = 13×78, which is composite."),
  cbsePyq("class-10", "mathematics", "real-numbers", "The HCF of the smallest composite number and the smallest prime number is", ["1", "2", "3", "4"], 1, "The smallest composite is 4 and the smallest prime is 2, so HCF = 2."),
  cbsePyq("class-10", "mathematics", "real-numbers", "The decimal expansion of 13/3125 terminates after", ["3 places", "4 places", "5 places", "it does not terminate"], 2, "3125 = 5⁵, so the expansion terminates after 5 decimal places."),
  cbsePyq("class-10", "mathematics", "real-numbers", "If a = x³y² and b = xy³, where x and y are distinct primes, then HCF(a, b) is", ["xy", "xy²", "x³y³", "x²y²"], 1, "HCF takes the lowest powers: x¹ y²."),
  cbsePyq("class-10", "mathematics", "real-numbers", "The LCM of two numbers is 1200. Which of the following cannot be their HCF?", ["600", "500", "400", "200"], 1, "HCF must divide LCM, and 500 does not divide 1200."),
  cbsePyq("class-10", "mathematics", "real-numbers", "n² − 1 is divisible by 8 if n is", ["an even integer", "an odd integer", "a natural number", "a multiple of 3"], 1, "For odd n = 2k + 1, n² − 1 = 4k(k + 1) and k(k + 1) is even, so 8 divides n² − 1."),
  cbsePyq("class-10", "mathematics", "real-numbers", "The largest number which divides 70 and 125, leaving remainders 5 and 8 respectively, is", ["13", "65", "875", "9"], 0, "The required number is HCF(70 − 5, 125 − 8) = HCF(65, 117) = 13."),
  cbsePyq("class-10", "mathematics", "real-numbers", "√2 is", ["a rational number", "an integer", "an irrational number", "a whole number"], 2, "√2 cannot be expressed as a fraction in lowest terms, so it is irrational."),
  cbsePyq("class-10", "mathematics", "real-numbers", "The prime factorisation of 240 is", ["2³ × 3 × 5", "2⁴ × 3 × 5", "2⁴ × 15", "2⁵ × 3 × 5"], 1, "240 = 16 × 15 = 2⁴ × 3 × 5."),
  cbsePyq("class-10", "mathematics", "real-numbers", "If HCF(a, 8) = 4 and LCM(a, 8) = 24, then a is", ["8", "12", "16", "24"], 1, "a × 8 = 4 × 24, so a = 12."),
  cbsePyq("class-10", "mathematics", "real-numbers", "The number 0.¯6 is", ["an irrational number", "a rational number", "neither rational nor irrational", "a natural number"], 1, "A repeating decimal is rational; 0.¯6 = 2/3."),

  // 2. Polynomials
  cbsePyq("class-10", "mathematics", "polynomials", "The degree of the polynomial 4x⁴ + 0x³ + 0x⁵ + 5x + 7 is", ["5", "4", "3", "1"], 1, "The x⁵ term has coefficient 0, so the degree is 4."),
  cbsePyq("class-10", "mathematics", "polynomials", "The zeroes of the polynomial x² − 2x − 8 are", ["2 and 4", "4 and −2", "−4 and 2", "8 and −1"], 1, "(x − 4)(x + 2) = 0, so the zeroes are 4 and −2."),
  cbsePyq("class-10", "mathematics", "polynomials", "The sum of the zeroes of 2x² − 8x + 6 is", ["4", "−4", "3", "−3"], 0, "Sum of zeroes = −b/a = 8/2 = 4."),
  cbsePyq("class-10", "mathematics", "polynomials", "The product of the zeroes of 2x² − 8x + 6 is", ["8", "3", "−3", "6"], 1, "Product of zeroes = c/a = 6/2 = 3."),
  cbsePyq("class-10", "mathematics", "polynomials", "A quadratic polynomial whose zeroes are 3 and −4 is", ["x² + x − 12", "x² − x − 12", "x² + x + 12", "x² − 7x − 12"], 0, "Sum = −1 and product = −12, so the polynomial is x² + x − 12."),
  cbsePyq("class-10", "mathematics", "polynomials", "If one zero of 2x² − (3 + 2k)x + 6k is 2, then k equals", ["−1", "1", "2", "−2"], 0, "Substituting x = 2 gives 8 − 2(3 + 2k) + 6k = 0, so k = −1."),
  cbsePyq("class-10", "mathematics", "polynomials", "If α and β are zeroes of x² + 7x + 10, then 1/α + 1/β equals", ["−7/10", "7/10", "−10/7", "10/7"], 0, "1/α + 1/β = (α + β)/αβ = −7/10."),
  cbsePyq("class-10", "mathematics", "polynomials", "The graph of y = x² + 1 intersects the x-axis at", ["two points", "one point", "no point", "three points"], 2, "x² + 1 > 0 for all real x, so there is no real zero."),
  cbsePyq("class-10", "mathematics", "polynomials", "A cubic polynomial can have at most", ["1 zero", "2 zeroes", "3 zeroes", "4 zeroes"], 2, "A polynomial of degree n has at most n zeroes."),
  cbsePyq("class-10", "mathematics", "polynomials", "If (x − 1) is a factor of x² + x + k, then k equals", ["−2", "2", "0", "−1"], 0, "p(1) = 0 gives 1 + 1 + k = 0, so k = −2."),
  cbsePyq("class-10", "mathematics", "polynomials", "The zeroes of 4x² − 4x + 1 are", ["1 and 1", "1/2 and 1/2", "2 and 1/2", "−1/2 and −1/2"], 1, "(2x − 1)² = 0, so both zeroes are 1/2."),
  cbsePyq("class-10", "mathematics", "polynomials", "If α and β are zeroes of 3x² − 6x + 4, then α² + β² equals", ["4", "8/3", "4/3", "2"], 2, "α + β = 2 and αβ = 4/3, so α² + β² = 4 − 8/3 = 4/3."),
  cbsePyq("class-10", "mathematics", "polynomials", "A quadratic polynomial with zeroes 1 and −1 is", ["x² − 1", "x² + 1", "x² − x − 1", "x² + x − 1"], 0, "Sum = 0 and product = −1, so the polynomial is x² − 1."),
  cbsePyq("class-10", "mathematics", "polynomials", "If the product of the zeroes of ax² − 6x − 6 is 4, then a equals", ["−3/2", "3/2", "−2/3", "6"], 0, "c/a = −6/a = 4, so a = −3/2."),
  cbsePyq("class-10", "mathematics", "polynomials", "If the sum of the zeroes of kx² + 2x + 3k equals their product, then k equals", ["−2/3", "2/3", "−3/2", "3/2"], 0, "−2/k = 3, so k = −2/3."),
  cbsePyq("class-10", "mathematics", "polynomials", "By the division algorithm, p(x) = g(x) q(x) + r(x), where", ["deg r(x) > deg g(x)", "deg r(x) < deg g(x) or r(x) = 0", "r(x) = g(x)", "q(x) = 0"], 1, "The remainder has degree less than the divisor, or is the zero polynomial."),
  cbsePyq("class-10", "mathematics", "polynomials", "If α and 1/α are zeroes of 4x² − 17x + k, then k equals", ["4", "17", "1", "0"], 0, "Product of zeroes = k/4 = 1, so k = 4."),
  cbsePyq("class-10", "mathematics", "polynomials", "For p(x) = x³ − 3x + 2, the value of p(1) is", ["0", "1", "2", "−1"], 0, "1 − 3 + 2 = 0, so (x − 1) is a factor."),
  cbsePyq("class-10", "mathematics", "polynomials", "A linear polynomial ax + b (a ≠ 0) has", ["no zero", "exactly one zero", "exactly two zeroes", "infinitely many zeroes"], 1, "ax + b = 0 has the unique root x = −b/a."),
  cbsePyq("class-10", "mathematics", "polynomials", "If the sum of the zeroes is −3 and the product is 2, a quadratic polynomial is", ["x² + 3x + 2", "x² − 3x + 2", "x² + 3x − 2", "x² − 3x − 2"], 0, "x² − (sum)x + product = x² + 3x + 2."),

  // 3. Pair of Linear Equations in Two Variables
  cbsePyq("class-10", "mathematics", "pair-of-linear-equations-in-two-variables", "The pair a1x + b1y + c1 = 0, a2x + b2y + c2 = 0 has a unique solution if", ["a1/a2 = b1/b2", "a1/a2 ≠ b1/b2", "a1/a2 = b1/b2 = c1/c2", "a1/a2 = b1/b2 ≠ c1/c2"], 1, "Intersecting lines occur when a1/a2 ≠ b1/b2."),
  cbsePyq("class-10", "mathematics", "pair-of-linear-equations-in-two-variables", "The pair a1x + b1y + c1 = 0, a2x + b2y + c2 = 0 has infinitely many solutions if", ["a1/a2 ≠ b1/b2", "a1/a2 = b1/b2 ≠ c1/c2", "a1/a2 = b1/b2 = c1/c2", "c1 = c2"], 2, "Coincident lines satisfy a1/a2 = b1/b2 = c1/c2."),
  cbsePyq("class-10", "mathematics", "pair-of-linear-equations-in-two-variables", "The pair a1x + b1y + c1 = 0, a2x + b2y + c2 = 0 has no solution if", ["a1/a2 = b1/b2 ≠ c1/c2", "a1/a2 ≠ b1/b2", "a1/a2 = b1/b2 = c1/c2", "a1 = b1"], 0, "Parallel distinct lines are inconsistent."),
  cbsePyq("class-10", "mathematics", "pair-of-linear-equations-in-two-variables", "The pair 2x − 3y = 8 and 4x − 6y = 9 is", ["consistent with a unique solution", "inconsistent", "consistent with infinitely many solutions", "dependent and unique"], 1, "2/4 = 3/6 ≠ 8/9, so the lines are parallel."),
  cbsePyq("class-10", "mathematics", "pair-of-linear-equations-in-two-variables", "The pair x + 2y = 4 and 2x + 4y = 8 has", ["no solution", "a unique solution", "infinitely many solutions", "exactly two solutions"], 2, "The second equation is a multiple of the first, so the lines coincide."),
  cbsePyq("class-10", "mathematics", "pair-of-linear-equations-in-two-variables", "Graphically, a unique solution of a linear pair is represented by", ["parallel lines", "intersecting lines", "coincident lines", "a single point not on any line"], 1, "Two intersecting lines meet at exactly one point."),
  cbsePyq("class-10", "mathematics", "pair-of-linear-equations-in-two-variables", "Parallel lines represent a linear pair that is", ["consistent", "inconsistent", "dependent", "always homogeneous"], 1, "Parallel lines never meet, so there is no solution."),
  cbsePyq("class-10", "mathematics", "pair-of-linear-equations-in-two-variables", "Coincident lines of a linear pair represent", ["no solution", "a unique solution", "infinitely many solutions", "exactly two solutions"], 2, "Every point on the common line is a solution."),
  cbsePyq("class-10", "mathematics", "pair-of-linear-equations-in-two-variables", "If 3x + 2y = 5 and 6x + ky = 10 have infinitely many solutions, then k equals", ["2", "4", "6", "8"], 1, "3/6 = 2/k = 5/10, so k = 4."),
  cbsePyq("class-10", "mathematics", "pair-of-linear-equations-in-two-variables", "The pair 2x + 3y = 5 and 4x + 6y = k has no solution if", ["k = 10", "k ≠ 10", "k = 5", "k = 0"], 1, "The ratios of the x- and y-coefficients are equal, so the pair is inconsistent precisely when k ≠ 10."),
  cbsePyq("class-10", "mathematics", "pair-of-linear-equations-in-two-variables", "The solution of x + y = 5 and 2x − y = 4 is", ["x = 3, y = 2", "x = 2, y = 3", "x = 1, y = 4", "x = 4, y = 1"], 0, "Adding the equations gives 3x = 9, so x = 3 and y = 2."),
  cbsePyq("class-10", "mathematics", "pair-of-linear-equations-in-two-variables", "For what value of k is the pair kx − y − 2 = 0 and 6x − 2y − 3 = 0 inconsistent?", ["3", "6", "2", "1"], 0, "k/6 = 1/2 ≠ 2/3, so k = 3."),
  cbsePyq("class-10", "mathematics", "pair-of-linear-equations-in-two-variables", "The pair x + y = 8 and 2x + 2y = 16 represents", ["intersecting lines", "parallel lines", "coincident lines", "perpendicular lines"], 2, "The second equation is twice the first."),
  cbsePyq("class-10", "mathematics", "pair-of-linear-equations-in-two-variables", "The number of solutions of 3x + 2y = 5 and 6x + 4y = 10 is", ["0", "1", "2", "infinitely many"], 3, "The equations represent the same line."),
  cbsePyq("class-10", "mathematics", "pair-of-linear-equations-in-two-variables", "If a1/a2 ≠ b1/b2, the two lines are", ["parallel", "coincident", "intersecting", "always perpendicular"], 2, "Unequal ratios of the x- and y-coefficients mean a unique intersection."),
  cbsePyq("class-10", "mathematics", "pair-of-linear-equations-in-two-variables", "The pair 2x + 3y − 5 = 0 and 4x + ky − 10 = 0 has a unique solution when", ["k = 6", "k ≠ 6", "k = 5", "k = 10"], 1, "Unique solution iff 2/4 ≠ 3/k, i.e. k ≠ 6."),
  cbsePyq("class-10", "mathematics", "pair-of-linear-equations-in-two-variables", "The pair x − 2y = 0 and 3x + 4y − 20 = 0 has the solution", ["x = 4, y = 2", "x = 2, y = 1", "x = 0, y = 0", "x = 6, y = 3"], 0, "x = 2y and 6y + 4y = 20 give y = 2, x = 4."),
  cbsePyq("class-10", "mathematics", "pair-of-linear-equations-in-two-variables", "The graphical method of solving a linear pair finds", ["the slope only", "the point(s) of intersection of the two lines", "the area between the lines", "the y-intercepts only"], 1, "Solutions are the common points of the two graphs."),
  cbsePyq("class-10", "mathematics", "pair-of-linear-equations-in-two-variables", "If the lines 3x + ky = 2 and 2x + 3y = 5 are parallel, then k equals", ["9/2", "2/9", "6", "3"], 0, "3/2 = k/3 and 3/2 ≠ 2/5, so k = 9/2."),
  cbsePyq("class-10", "mathematics", "pair-of-linear-equations-in-two-variables", "For the homogeneous pair a1x + b1y = 0, a2x + b2y = 0, (0, 0) is", ["never a solution", "always a solution", "the unique solution only if the lines are parallel", "never unique"], 1, "x = 0, y = 0 satisfies both equations for any coefficients."),

  // 4. Quadratic Equations
  cbsePyq("class-10", "mathematics", "quadratic-equations", "The quadratic equation ax² + bx + c = 0 (a ≠ 0) has real roots if", ["D > 0 only", "D ≥ 0", "D < 0", "D = 1"], 1, "Real roots exist when the discriminant b² − 4ac is non-negative."),
  cbsePyq("class-10", "mathematics", "quadratic-equations", "The roots of ax² + bx + c = 0 are real and equal if", ["D > 0", "D = 0", "D < 0", "a = 0"], 1, "A zero discriminant gives two equal real roots."),
  cbsePyq("class-10", "mathematics", "quadratic-equations", "The equation ax² + bx + c = 0 has no real roots if", ["D = 0", "D > 0", "D < 0", "c = 0"], 2, "A negative discriminant means the roots are not real."),
  cbsePyq("class-10", "mathematics", "quadratic-equations", "For x² − 3x + 2 = 0, the discriminant is", ["1", "0", "−1", "9"], 0, "D = 9 − 8 = 1 > 0, so there are two distinct real roots."),
  cbsePyq("class-10", "mathematics", "quadratic-equations", "The roots of x² − 7x + 12 = 0 are", ["3 and 4", "2 and 6", "1 and 12", "−3 and −4"], 0, "(x − 3)(x − 4) = 0."),
  cbsePyq("class-10", "mathematics", "quadratic-equations", "If the roots of kx² + 4x + 1 = 0 are equal, then k equals", ["2", "4", "1", "8"], 1, "16 − 4k = 0, so k = 4."),
  cbsePyq("class-10", "mathematics", "quadratic-equations", "The sum of the roots of 2x² − 3x + 1 = 0 is", ["3/2", "−3/2", "1/2", "−1/2"], 0, "Sum of roots = −b/a = 3/2."),
  cbsePyq("class-10", "mathematics", "quadratic-equations", "The product of the roots of 2x² − 3x + 1 = 0 is", ["3/2", "1/2", "−1/2", "2"], 1, "Product of roots = c/a = 1/2."),
  cbsePyq("class-10", "mathematics", "quadratic-equations", "The nature of the roots of 2x² − 6x + 3 = 0 is", ["real, equal and rational", "real, distinct and irrational", "not real", "real, distinct and rational"], 1, "D = 36 − 24 = 12, which is positive but not a perfect square."),
  cbsePyq("class-10", "mathematics", "quadratic-equations", "If one root of x² − 5x + k = 0 is 2, then k equals", ["6", "10", "4", "−6"], 0, "4 − 10 + k = 0, so k = 6."),
  cbsePyq("class-10", "mathematics", "quadratic-equations", "The quadratic equation with roots 2 and −3 is", ["x² + x − 6 = 0", "x² − x − 6 = 0", "x² + x + 6 = 0", "x² − 5x − 6 = 0"], 0, "Sum = −1 and product = −6, so x² + x − 6 = 0."),
  cbsePyq("class-10", "mathematics", "quadratic-equations", "If D is a perfect square (with a, b, c rational and a ≠ 0), the roots of ax² + bx + c = 0 are", ["irrational", "not real", "rational", "always integers"], 2, "A perfect-square discriminant over the rationals gives rational roots."),
  cbsePyq("class-10", "mathematics", "quadratic-equations", "The roots of x² + x + 1 = 0 are", ["real and equal", "real and distinct", "not real", "both zero"], 2, "D = 1 − 4 = −3 < 0."),
  cbsePyq("class-10", "mathematics", "quadratic-equations", "The product of the roots of √3 x² − 2√2 x − 2√3 = 0 is", ["−2", "2", "−2√2", "2√2"], 0, "Product = c/a = −2√3 / √3 = −2."),
  cbsePyq("class-10", "mathematics", "quadratic-equations", "If x² − 2x(1 + 3k) + 7(3 + 2k) = 0 has equal roots, one value of k is", ["2", "3", "1", "0"], 0, "The discriminant condition yields k = 2 or k = −10/9."),
  cbsePyq("class-10", "mathematics", "quadratic-equations", "If x = 2 is a root of x² − 4x + k = 0, then k equals", ["4", "2", "8", "0"], 0, "4 − 8 + k = 0, so k = 4."),
  cbsePyq("class-10", "mathematics", "quadratic-equations", "If the roots of px² + qx + r = 0 are real and equal, then", ["q² = 4pr", "q² = pr", "p = q = r", "q² = −4pr"], 0, "D = 0 if and only if q² = 4pr."),
  cbsePyq("class-10", "mathematics", "quadratic-equations", "The roots of x² − 2x − 3 = 0 are", ["3 and −1", "1 and −3", "3 and 1", "−3 and −1"], 0, "(x − 3)(x + 1) = 0."),
  cbsePyq("class-10", "mathematics", "quadratic-equations", "A quadratic equation can have at most how many real roots?", ["1", "2", "3", "infinitely many"], 1, "A polynomial of degree 2 has at most two roots."),
  cbsePyq("class-10", "mathematics", "quadratic-equations", "If x² + 4x + k = 0 has real roots, then", ["k ≤ 4", "k ≥ 4", "k = 0", "k > 4"], 0, "D = 16 − 4k ≥ 0, so k ≤ 4."),

  // 5. Arithmetic Progressions
  cbsePyq("class-10", "mathematics", "arithmetic-progressions", "The nth term of an AP with first term a and common difference d is", ["a + nd", "a + (n − 1)d", "a − (n − 1)d", "nd − a"], 1, "an = a + (n − 1)d."),
  cbsePyq("class-10", "mathematics", "arithmetic-progressions", "The sum of the first n terms of an AP is", ["n/2 [2a + (n − 1)d]", "n[2a + (n − 1)d]", "n/2 (a + d)", "na + d"], 0, "Sn = n/2 [2a + (n − 1)d] = n/2 (a + l)."),
  cbsePyq("class-10", "mathematics", "arithmetic-progressions", "The 10th term of the AP 2, 7, 12, … is", ["47", "45", "52", "42"], 0, "a10 = 2 + 9×5 = 47."),
  cbsePyq("class-10", "mathematics", "arithmetic-progressions", "The 11th term of the AP −3, −1/2, 2, … is", ["22", "20", "−22", "25"], 0, "d = 5/2, so a11 = −3 + 10×(5/2) = 22."),
  cbsePyq("class-10", "mathematics", "arithmetic-progressions", "The sum of the first 10 terms of 2, 7, 12, … is", ["245", "240", "250", "230"], 0, "S10 = 5[4 + 45] = 245."),
  cbsePyq("class-10", "mathematics", "arithmetic-progressions", "Which term of the AP 3, 8, 13, … is 78?", ["15th", "16th", "17th", "18th"], 1, "3 + (n − 1)5 = 78, so n = 16."),
  cbsePyq("class-10", "mathematics", "arithmetic-progressions", "If the 4th term of an AP is 11 and the 7th term is 20, then the first term is", ["2", "3", "5", "1"], 0, "a + 3d = 11 and a + 6d = 20 give d = 3 and a = 2."),
  cbsePyq("class-10", "mathematics", "arithmetic-progressions", "The sum of the first n natural numbers is", ["n(n + 1)/2", "n(n − 1)/2", "n²", "2n + 1"], 0, "1 + 2 + … + n is an AP with this sum."),
  cbsePyq("class-10", "mathematics", "arithmetic-progressions", "The nth term of the AP 2, 5/2, 3, … is", ["(n + 3)/2", "(n + 1)/2", "n/2", "(n + 4)/2"], 0, "a = 2 and d = 1/2, so an = 2 + (n − 1)/2 = (n + 3)/2."),
  cbsePyq("class-10", "mathematics", "arithmetic-progressions", "If Sn = 3n² + 2n, then the nth term an is", ["6n − 1", "6n + 1", "3n + 2", "6n + 2"], 0, "an = Sn − S(n − 1) = 6n − 1."),
  cbsePyq("class-10", "mathematics", "arithmetic-progressions", "The middle term of an AP with 2n + 1 terms is the", ["nth term", "(n + 1)th term", "(n − 1)th term", "2nth term"], 1, "An odd number of terms has the (n + 1)th term in the middle."),
  cbsePyq("class-10", "mathematics", "arithmetic-progressions", "If a, b, c are in AP, then", ["2b = a + c", "2a = b + c", "2c = a + b", "b² = ac"], 0, "Equal common difference means b − a = c − b."),
  cbsePyq("class-10", "mathematics", "arithmetic-progressions", "The 20th term from the end of the AP 3, 8, 13, …, 253 is", ["158", "163", "148", "153"], 0, "253 − 19×5 = 158."),
  cbsePyq("class-10", "mathematics", "arithmetic-progressions", "The number of terms of the AP 7, 13, 19, …, 205 is", ["33", "34", "35", "32"], 1, "7 + (n − 1)6 = 205, so n = 34."),
  cbsePyq("class-10", "mathematics", "arithmetic-progressions", "The sum of the first 15 multiples of 4 is", ["480", "460", "500", "450"], 0, "4 + 8 + … + 60 = 15/2 × 64 = 480."),
  cbsePyq("class-10", "mathematics", "arithmetic-progressions", "If the 5th term of an AP is 12 and the 8th term is 21, the common difference is", ["3", "2", "4", "5"], 0, "3d = 9, so d = 3."),
  cbsePyq("class-10", "mathematics", "arithmetic-progressions", "If the 4th term of an AP is 0, then the 25th term is", ["3 times the 11th term", "equal to the 11th term", "twice the 11th term", "half the 11th term"], 0, "a = −3d, so a25 = 21d and a11 = 7d, hence a25 = 3 a11."),
  cbsePyq("class-10", "mathematics", "arithmetic-progressions", "If the sum of n terms of an AP is n², then the common difference is", ["2", "1", "0", "n"], 0, "a1 = 1 and S2 = 4, so a2 = 3 and d = 2."),
  cbsePyq("class-10", "mathematics", "arithmetic-progressions", "The number of two-digit numbers divisible by 3 is", ["30", "31", "32", "29"], 1, "12, 15, …, 99 is an AP with 31 terms."),
  cbsePyq("class-10", "mathematics", "arithmetic-progressions", "Three numbers in AP have sum 27 and product 504. The numbers are", ["4, 9, 14", "7, 9, 11", "3, 9, 15", "2, 9, 16"], 0, "They are 9 − d, 9, 9 + d with 9(81 − d²) = 504, so d = 5."),

  // 6. Triangles
  cbsePyq("class-10", "mathematics", "triangles", "DE ∥ BC in ΔABC with D on AB and E on AC. By the basic proportionality theorem,", ["AD/DB = AE/EC", "AD/AB = DE/BC always as the statement of BPT", "AD = AE", "AB/AC = DE/BC only"], 0, "Thales' theorem: a line parallel to one side divides the other two in the same ratio."),
  cbsePyq("class-10", "mathematics", "triangles", "Two triangles are similar by AA if", ["two angles of one equal two angles of the other", "two sides are equal", "all three sides are equal", "one angle is 90°"], 0, "AA similarity is a standard Class 10 criterion."),
  cbsePyq("class-10", "mathematics", "triangles", "The ratio of the areas of two similar triangles is equal to the", ["ratio of corresponding sides", "square of the ratio of corresponding sides", "cube of the ratio of corresponding sides", "ratio of corresponding angles"], 1, "ar(Δ1)/ar(Δ2) = (side1/side2)²."),
  cbsePyq("class-10", "mathematics", "triangles", "In a right triangle, the square of the hypotenuse equals", ["the sum of the squares of the other two sides", "the difference of the squares of the other two sides", "twice the product of the other two sides", "the product of the other two sides"], 0, "This is the Pythagoras theorem."),
  cbsePyq("class-10", "mathematics", "triangles", "The converse of the basic proportionality theorem states that if a line divides two sides of a triangle in the same ratio, then the line is", ["perpendicular to the third side", "parallel to the third side", "the median", "the altitude"], 1, "This is the converse of BPT (Thales' theorem)."),
  cbsePyq("class-10", "mathematics", "triangles", "If ΔABC ~ ΔDEF and AB/DE = 2/3, then ar(ABC)/ar(DEF) equals", ["2/3", "4/9", "8/27", "3/2"], 1, "The area ratio is (2/3)² = 4/9."),
  cbsePyq("class-10", "mathematics", "triangles", "If the sides of a triangle are 6 cm, 8 cm and 10 cm, the triangle is", ["acute-angled", "obtuse-angled", "right-angled", "equilateral"], 2, "6² + 8² = 10², so the triangle is right-angled."),
  cbsePyq("class-10", "mathematics", "triangles", "If the ratio of the areas of two similar triangles is 16 : 25, the ratio of corresponding sides is", ["16 : 25", "4 : 5", "256 : 625", "8 : 10"], 1, "The side ratio is √16 : √25 = 4 : 5."),
  cbsePyq("class-10", "mathematics", "triangles", "In ΔABC, DE ∥ BC, AD = 1.5 cm, DB = 3 cm and AE = 1 cm. Then EC equals", ["2 cm", "1.5 cm", "3 cm", "0.5 cm"], 0, "AD/DB = AE/EC ⇒ 1.5/3 = 1/EC ⇒ EC = 2 cm."),
  cbsePyq("class-10", "mathematics", "triangles", "The basic proportionality theorem is also known as", ["Pythagoras theorem", "Thales' theorem", "mid-point theorem", "converse of Pythagoras"], 1, "BPT is Thales' theorem."),
  cbsePyq("class-10", "mathematics", "triangles", "Corresponding sides of similar triangles are", ["equal", "proportional", "perpendicular", "always parallel"], 1, "Similarity means equal corresponding angles and proportional corresponding sides."),
  cbsePyq("class-10", "mathematics", "triangles", "In right ΔABC right-angled at B, if AB = 5 cm and BC = 12 cm, then AC equals", ["13 cm", "17 cm", "7 cm", "60 cm"], 0, "AC = √(25 + 144) = 13 cm."),
  cbsePyq("class-10", "mathematics", "triangles", "If corresponding sides of two similar triangles are in the ratio 2 : 3, the ratio of their perimeters is", ["4 : 9", "2 : 3", "8 : 27", "3 : 2"], 1, "Perimeters scale with the same ratio as corresponding sides."),
  cbsePyq("class-10", "mathematics", "triangles", "A line drawn through the mid-points of two sides of a triangle is", ["parallel to the third side and half as long", "perpendicular to the third side", "equal to the third side", "a median"], 0, "This is the mid-point theorem."),
  cbsePyq("class-10", "mathematics", "triangles", "SSS similarity requires that", ["three angles are equal", "three pairs of corresponding sides are proportional", "two sides and the included angle are equal", "one angle is 90°"], 1, "SSS similarity is the three-sides-proportional criterion."),
  cbsePyq("class-10", "mathematics", "triangles", "SAS similarity requires", ["two sides proportional and the included angles equal", "two angles equal", "three sides equal", "a right angle"], 0, "The included angles must be the corresponding equal angles."),
  cbsePyq("class-10", "mathematics", "triangles", "If P and Q are mid-points of AB and AC of ΔABC, then PQ equals", ["BC", "½ BC", "2 BC", "⅓ BC"], 1, "By the mid-point theorem, PQ = ½ BC and PQ ∥ BC."),
  cbsePyq("class-10", "mathematics", "triangles", "A line parallel to one side of a triangle intersecting the other two sides", ["divides the two sides in the same ratio", "bisects the third side", "is a median", "makes the triangle isosceles"], 0, "This is the basic proportionality theorem."),
  cbsePyq("class-10", "mathematics", "triangles", "In a right triangle, the altitude to the hypotenuse creates", ["two triangles similar to each other and to the original", "two congruent triangles", "an equilateral triangle", "two isosceles triangles always"], 0, "The geometric-mean relations follow from this similarity."),
  cbsePyq("class-10", "mathematics", "triangles", "If ΔABC ~ ΔPQR and ∠A = 50°, ∠B = 70°, then ∠R equals", ["50°", "70°", "60°", "80°"], 2, "∠C = 60°, and ∠R corresponds to ∠C."),

  // 7. Coordinate Geometry
  cbsePyq("class-10", "mathematics", "coordinate-geometry", "The distance of the point (x, y) from the origin is", ["x + y", "√(x² + y²)", "xy", "x² + y²"], 1, "This is the distance formula with the origin (0, 0)."),
  cbsePyq("class-10", "mathematics", "coordinate-geometry", "The distance between (2, 3) and (4, 1) is", ["2√2", "√2", "4", "2"], 0, "√[(2)² + (−2)²] = √8 = 2√2."),
  cbsePyq("class-10", "mathematics", "coordinate-geometry", "The mid-point of the segment joining (2, 3) and (4, 7) is", ["(3, 5)", "(6, 10)", "(2, 4)", "(1, 2)"], 0, "((2 + 4)/2, (3 + 7)/2) = (3, 5)."),
  cbsePyq("class-10", "mathematics", "coordinate-geometry", "The point dividing the join of (x1, y1) and (x2, y2) internally in the ratio m : n is", ["((nx1 + mx2)/(m + n), (ny1 + my2)/(m + n))", "((mx1 + nx2)/(m + n), (my1 + ny2)/(m + n))", "((x1 + x2)/2, (y1 + y2)/2)", "((m − n)x, (m − n)y)"], 0, "Section formula: internally m : n weights the second point with m."),
  cbsePyq("class-10", "mathematics", "coordinate-geometry", "The point dividing (1, 2) and (3, 4) in the ratio 1 : 1 is", ["(2, 3)", "(1, 1)", "(4, 6)", "(3, 2)"], 0, "The 1 : 1 section is the mid-point (2, 3)."),
  cbsePyq("class-10", "mathematics", "coordinate-geometry", "The area of the triangle with vertices (0, 0), (4, 0) and (0, 3) is", ["6", "12", "7", "24"], 0, "Area = (1/2)×4×3 = 6."),
  cbsePyq("class-10", "mathematics", "coordinate-geometry", "The points (1, 5), (2, 3) and (3, 1) are", ["vertices of an equilateral triangle", "collinear", "vertices of a right triangle", "vertices of an isosceles triangle only"], 1, "The area formula gives 0, so the points are collinear."),
  cbsePyq("class-10", "mathematics", "coordinate-geometry", "The distance of (3, 4) from the origin is", ["5", "7", "12", "1"], 0, "√(9 + 16) = 5."),
  cbsePyq("class-10", "mathematics", "coordinate-geometry", "The point on the x-axis equidistant from (2, −5) and (−2, 9) is", ["(−7, 0)", "(7, 0)", "(0, −7)", "(−5, 0)"], 0, "Let the point be (x, 0); equating distances gives x = −7."),
  cbsePyq("class-10", "mathematics", "coordinate-geometry", "The centroid of the triangle with vertices (1, 2), (3, 4) and (5, 0) is", ["(3, 2)", "(9, 6)", "(2, 3)", "(3, 3)"], 0, "((1 + 3 + 5)/3, (2 + 4 + 0)/3) = (3, 2)."),
  cbsePyq("class-10", "mathematics", "coordinate-geometry", "If P divides AB in the ratio k : 1, the x-coordinate of P is", ["(kx2 + x1)/(k + 1)", "(x2 + kx1)/(k + 1)", "(x1 + x2)/k", "k(x1 + x2)"], 0, "This is the section formula with m : n = k : 1."),
  cbsePyq("class-10", "mathematics", "coordinate-geometry", "The point (3, 0) lies on the", ["y-axis", "x-axis", "origin", "line y = 3"], 1, "Any point with y-coordinate 0 lies on the x-axis."),
  cbsePyq("class-10", "mathematics", "coordinate-geometry", "The distance between (a, b) and (−a, −b) is", ["2√(a² + b²)", "√(a² + b²)", "0", "2(a + b)"], 0, "√[(2a)² + (2b)²] = 2√(a² + b²)."),
  cbsePyq("class-10", "mathematics", "coordinate-geometry", "If (x, y) is equidistant from (3, 6) and (−3, 4), then", ["3x + y = 5", "x + 3y = 5", "3x − y = 5", "x + y = 5"], 0, "Expanding the equal-distance condition yields 3x + y = 5."),
  cbsePyq("class-10", "mathematics", "coordinate-geometry", "The area of ΔABC with vertices (x1, y1), (x2, y2), (x3, y3) is", ["(1/2)|x1(y2 − y3) + x2(y3 − y1) + x3(y1 − y2)|", "x1y1 + x2y2 + x3y3", "|x1 + y1|", "(x1 + x2 + x3)/2"], 0, "This is the shoelace formula used in Class 10."),
  cbsePyq("class-10", "mathematics", "coordinate-geometry", "The origin has coordinates", ["(1, 1)", "(0, 0)", "(0, 1)", "(1, 0)"], 1, "The axes meet at (0, 0)."),
  cbsePyq("class-10", "mathematics", "coordinate-geometry", "The point (−2, 4) lies in the", ["first quadrant", "second quadrant", "third quadrant", "fourth quadrant"], 1, "x < 0 and y > 0 is the second quadrant."),
  cbsePyq("class-10", "mathematics", "coordinate-geometry", "The point which divides the join of (4, −3) and (8, 5) internally in the ratio 3 : 1 is", ["(7, 3)", "(5, 1)", "(6, 1)", "(7, −3)"], 0, "((3×8 + 1×4)/4, (3×5 + 1×(−3))/4) = (7, 3)."),
  cbsePyq("class-10", "mathematics", "coordinate-geometry", "The distance between (0, 4) and (0, −4) is", ["8", "4", "0", "16"], 0, "The points are 8 units apart on the y-axis."),
  cbsePyq("class-10", "mathematics", "coordinate-geometry", "If the mid-point of (x, y) and (3, 4) is (5, 6), then (x, y) is", ["(7, 8)", "(2, 2)", "(8, 10)", "(4, 5)"], 0, "(x + 3)/2 = 5 and (y + 4)/2 = 6, so (x, y) = (7, 8)."),

  // 8. Introduction to Trigonometry
  cbsePyq("class-10", "mathematics", "introduction-to-trigonometry", "sin²θ + cos²θ equals", ["0", "1", "tan²θ", "2"], 1, "This is the fundamental trigonometric identity."),
  cbsePyq("class-10", "mathematics", "introduction-to-trigonometry", "1 + tan²θ equals", ["sin²θ", "cos²θ", "sec²θ", "csc²θ"], 2, "Dividing sin²θ + cos²θ = 1 by cos²θ gives this identity."),
  cbsePyq("class-10", "mathematics", "introduction-to-trigonometry", "1 + cot²θ equals", ["sec²θ", "csc²θ", "tan²θ", "1"], 1, "Dividing sin²θ + cos²θ = 1 by sin²θ gives 1 + cot²θ = csc²θ."),
  cbsePyq("class-10", "mathematics", "introduction-to-trigonometry", "The value of sin 30° is", ["1", "1/2", "√3/2", "0"], 1, "sin 30° = 1/2."),
  cbsePyq("class-10", "mathematics", "introduction-to-trigonometry", "The value of cos 60° is", ["1/2", "√3/2", "1", "0"], 0, "cos 60° = 1/2."),
  cbsePyq("class-10", "mathematics", "introduction-to-trigonometry", "The value of tan 45° is", ["0", "1", "√3", "1/√3"], 1, "tan 45° = 1."),
  cbsePyq("class-10", "mathematics", "introduction-to-trigonometry", "The value of sin 90° is", ["0", "1", "1/2", "undefined"], 1, "sin 90° = 1."),
  cbsePyq("class-10", "mathematics", "introduction-to-trigonometry", "The value of cos 0° is", ["0", "1", "1/2", "undefined"], 1, "cos 0° = 1."),
  cbsePyq("class-10", "mathematics", "introduction-to-trigonometry", "The value of tan 0° is", ["0", "1", "undefined", "∞"], 0, "tan 0° = 0."),
  cbsePyq("class-10", "mathematics", "introduction-to-trigonometry", "sin(90° − θ) equals", ["sin θ", "cos θ", "tan θ", "sec θ"], 1, "Cofunction identity: sin(90° − θ) = cos θ."),
  cbsePyq("class-10", "mathematics", "introduction-to-trigonometry", "If sin θ = 3/5 and θ is acute, then cos θ equals", ["4/5", "3/4", "5/3", "5/4"], 0, "A 3-4-5 right triangle gives adjacent side 4."),
  cbsePyq("class-10", "mathematics", "introduction-to-trigonometry", "If tan θ = 1/√3 and θ is acute, then θ equals", ["30°", "45°", "60°", "90°"], 0, "tan 30° = 1/√3."),
  cbsePyq("class-10", "mathematics", "introduction-to-trigonometry", "sec²θ − tan²θ equals", ["0", "1", "sin²θ", "−1"], 1, "This follows from 1 + tan²θ = sec²θ."),
  cbsePyq("class-10", "mathematics", "introduction-to-trigonometry", "The value of sin 60° is", ["1/2", "√3/2", "1", "√3"], 1, "sin 60° = √3/2."),
  cbsePyq("class-10", "mathematics", "introduction-to-trigonometry", "sin² 30° + cos² 30° equals", ["1", "1/2", "0", "√3/2"], 0, "sin²θ + cos²θ = 1 for every θ."),
  cbsePyq("class-10", "mathematics", "introduction-to-trigonometry", "If cos θ = 1/2 and θ is acute, then θ equals", ["30°", "60°", "45°", "90°"], 1, "cos 60° = 1/2."),
  cbsePyq("class-10", "mathematics", "introduction-to-trigonometry", "tan θ equals", ["sin θ / cos θ", "cos θ / sin θ", "1 / sin θ", "sin θ cos θ"], 0, "This is the definition of tan θ."),
  cbsePyq("class-10", "mathematics", "introduction-to-trigonometry", "The value of sin 0° is", ["1", "0", "1/2", "undefined"], 1, "sin 0° = 0."),
  cbsePyq("class-10", "mathematics", "introduction-to-trigonometry", "2 sin 30° cos 30° equals", ["1/2", "√3/2", "1", "√3"], 1, "This is sin 60° = √3/2, or 2 × (1/2) × (√3/2) = √3/2."),
  cbsePyq("class-10", "mathematics", "introduction-to-trigonometry", "If tan θ = 4/3 and θ is acute, then sin θ equals", ["4/5", "3/5", "4/3", "3/4"], 0, "A 3-4-5 triangle has hypotenuse 5, so sin θ = 4/5."),

  // 9. Applications of Trigonometry
  cbsePyq("class-10", "mathematics", "applications-of-trigonometry", "The angle of elevation is the angle which the line of sight makes with the horizontal when the observer", ["looks upward", "looks downward", "looks horizontally", "walks towards the object"], 0, "Elevation is used when the object is above eye level."),
  cbsePyq("class-10", "mathematics", "applications-of-trigonometry", "The angle of depression is formed when the observer", ["looks upward at an object", "looks downward at an object", "looks along the horizon only", "stands at the foot of the object"], 1, "Depression is the downward angle from the horizontal."),
  cbsePyq("class-10", "mathematics", "applications-of-trigonometry", "The angle of elevation of the top of a 50 m tower from a point on the ground is 45°. The distance of the point from the foot of the tower is", ["25 m", "50 m", "50√3 m", "25√3 m"], 1, "tan 45° = 1 = height/distance, so the distance is 50 m."),
  cbsePyq("class-10", "mathematics", "applications-of-trigonometry", "If the angle of elevation of the top of a tower of height h from a point on the ground is 30°, the distance of the point from the foot is", ["h", "h√3", "h/√3", "2h"], 1, "tan 30° = 1/√3 = h/d, so d = h√3."),
  cbsePyq("class-10", "mathematics", "applications-of-trigonometry", "If the angle of elevation is 60° and the height of the tower is h, the distance from the foot is", ["h√3", "h/√3", "h", "2h"], 1, "tan 60° = √3 = h/d, so d = h/√3."),
  cbsePyq("class-10", "mathematics", "applications-of-trigonometry", "The length of the shadow of a 10 m pole when the sun's elevation is 45° is", ["10 m", "10√3 m", "10/√3 m", "5 m"], 0, "tan 45° = 1, so the shadow equals the height, 10 m."),
  cbsePyq("class-10", "mathematics", "applications-of-trigonometry", "The shadow of a 50 m tower when the sun's altitude is 30° is", ["50 m", "50√3 m", "50/√3 m", "25 m"], 1, "tan 30° = 50/shadow, so the shadow is 50√3 m."),
  cbsePyq("class-10", "mathematics", "applications-of-trigonometry", "From a point 20 m from the foot of a tower, the angle of elevation of the top is 60°. The height of the tower is", ["20 m", "20√3 m", "10√3 m", "40 m"], 1, "tan 60° = √3 = h/20, so h = 20√3 m."),
  cbsePyq("class-10", "mathematics", "applications-of-trigonometry", "The angle of elevation of the top of a tower from a point is 30°. After walking 20 m towards the tower it becomes 60°. The height of the tower is", ["10√3 m", "20√3 m", "10 m", "20 m"], 0, "If the nearer distance is x, then x√3 = (x + 20)/√3, so x = 10 and h = 10√3 m."),
  cbsePyq("class-10", "mathematics", "applications-of-trigonometry", "If the shadow of a tree is equal to its height, the angle of elevation of the sun is", ["30°", "45°", "60°", "90°"], 1, "tan θ = 1, so θ = 45°."),
  cbsePyq("class-10", "mathematics", "applications-of-trigonometry", "The line of sight is", ["the horizontal line from the observer", "the line from the observer's eye to the object", "the vertical from the object", "the shadow of the object"], 1, "Heights-and-distances problems use the line of sight to define elevation and depression."),
  cbsePyq("class-10", "mathematics", "applications-of-trigonometry", "From the top of a 75 m tower, the angle of depression of a car is 30°. The car is", ["75 m away", "75√3 m away", "25√3 m away", "150 m away"], 1, "tan 30° = 75/d, so d = 75√3 m."),
  cbsePyq("class-10", "mathematics", "applications-of-trigonometry", "If the shadow of a pole is √3 times its height, the altitude of the sun is", ["30°", "45°", "60°", "90°"], 0, "tan θ = 1/√3, so θ = 30°."),
  cbsePyq("class-10", "mathematics", "applications-of-trigonometry", "A kite is flying at a height of 75 m with the string making 60° with the horizontal. The length of the string is", ["50√3 m", "75√3 m", "150 m", "25√3 m"], 0, "sin 60° = 75/l, so l = 75 × 2/√3 = 50√3 m."),
  cbsePyq("class-10", "mathematics", "applications-of-trigonometry", "If the angle of elevation of an object is 0°, the object is", ["vertically above the observer", "at the same horizontal level as the observer's eye", "below the observer", "at infinity vertically"], 1, "Zero elevation means the line of sight is horizontal."),
  cbsePyq("class-10", "mathematics", "applications-of-trigonometry", "From a window 10 m above the ground, the angle of depression of a parked car is 30°. The car is", ["10 m from the building", "10√3 m from the building", "10/√3 m from the building", "5 m from the building"], 1, "tan 30° = 10/d, so d = 10√3 m."),
  cbsePyq("class-10", "mathematics", "applications-of-trigonometry", "A boy 1.5 m tall is 10 m away from a flagstaff. If the angle of elevation of the top of the flagstaff from his eye is 45°, the height of the flagstaff is", ["11.5 m", "10 m", "8.5 m", "13 m"], 0, "The top is 10 m above eye level, so the flagstaff is 11.5 m high."),
  cbsePyq("class-10", "mathematics", "applications-of-trigonometry", "If the height of a tower is √3 times the distance of the observer from its foot, the angle of elevation is", ["30°", "45°", "60°", "15°"], 2, "tan θ = √3, so θ = 60°."),
  cbsePyq("class-10", "mathematics", "applications-of-trigonometry", "From a point 30 m from the foot of a tower, the angle of elevation of the top is 30°. The height of the tower is", ["10√3 m", "30√3 m", "15 m", "30 m"], 0, "tan 30° = h/30, so h = 10√3 m."),
  cbsePyq("class-10", "mathematics", "applications-of-trigonometry", "The shadow of a tower is 20 m when the sun's elevation is 60°. The height of the tower is", ["20√3 m", "20 m", "20/√3 m", "10√3 m"], 0, "tan 60° = √3 = h/20, so h = 20√3 m."),

  // 10. Circles
  cbsePyq("class-10", "mathematics", "circles", "The tangent at any point of a circle is", ["parallel to the radius through the point of contact", "perpendicular to the radius through the point of contact", "equal to the radius", "a chord of the circle"], 1, "The radius is perpendicular to the tangent at the point of contact."),
  cbsePyq("class-10", "mathematics", "circles", "From an external point, the two tangents to a circle are", ["unequal", "equal in length", "perpendicular", "parallel"], 1, "Tangents drawn from a common external point are equal."),
  cbsePyq("class-10", "mathematics", "circles", "The number of tangents that can be drawn to a circle from an external point is", ["1", "2", "3", "infinitely many"], 1, "Exactly two tangents can be drawn from an external point."),
  cbsePyq("class-10", "mathematics", "circles", "The number of tangents that can be drawn to a circle from a point on the circle is", ["0", "1", "2", "infinitely many"], 1, "There is a unique tangent at a given point of the circle."),
  cbsePyq("class-10", "mathematics", "circles", "The number of tangents that can be drawn to a circle from a point inside it is", ["0", "1", "2", "infinitely many"], 0, "No real tangent can be drawn from an interior point."),
  cbsePyq("class-10", "mathematics", "circles", "A point is 13 cm from the centre of a circle of radius 5 cm. The length of the tangent from the point is", ["12 cm", "8 cm", "18 cm", "√194 cm"], 0, "Tangent² = 13² − 5² = 144, so the length is 12 cm."),
  cbsePyq("class-10", "mathematics", "circles", "The line joining the centre to an external point", ["bisects the angle between the two tangents from that point", "is parallel to the tangents", "is equal to the radius", "never bisects the chord of contact"], 0, "The two tangent triangles are congruent, so the angles at the external point are equal."),
  cbsePyq("class-10", "mathematics", "circles", "The angle between a tangent and the radius at the point of contact is", ["0°", "45°", "60°", "90°"], 3, "The radius and tangent are perpendicular."),
  cbsePyq("class-10", "mathematics", "circles", "A tangent to a circle intersects the circle in", ["two points", "exactly one point", "no point", "three points"], 1, "The point of contact is the unique intersection."),
  cbsePyq("class-10", "mathematics", "circles", "If TP and TQ are tangents from an external point T, then", ["TP = TQ", "TP ⊥ TQ always", "∠TPQ = 90° always", "OP = TQ"], 0, "The two tangents from an external point are equal, so ΔTPQ is isosceles."),
  cbsePyq("class-10", "mathematics", "circles", "At a given point of a circle, the number of tangents is", ["0", "1", "2", "infinitely many"], 1, "The tangent at a point of a circle is unique."),
  cbsePyq("class-10", "mathematics", "circles", "If the angle between two radii drawn to the points of contact of two tangents from an external point is 120°, the angle between the tangents is", ["60°", "90°", "120°", "30°"], 0, "The quadrilateral of two radii and two tangents has two right angles, so the remaining angle is 60°."),
  cbsePyq("class-10", "mathematics", "circles", "Two circles touch externally. The distance between their centres is", ["|r1 − r2|", "r1 + r2", "r1 r2", "√(r1² + r2²)"], 1, "External contact means the centres are r1 + r2 apart."),
  cbsePyq("class-10", "mathematics", "circles", "Two circles touch internally. The distance between their centres is", ["r1 + r2", "|r1 − r2|", "2(r1 + r2)", "0"], 1, "Internal contact means the centres are |r1 − r2| apart."),
  cbsePyq("class-10", "mathematics", "circles", "A point P is 25 cm from the centre of a circle of radius 7 cm. The length of the tangent from P is", ["24 cm", "18 cm", "32 cm", "26 cm"], 0, "√(25² − 7²) = √(625 − 49) = 24 cm."),
  cbsePyq("class-10", "mathematics", "circles", "In two concentric circles, a chord of the larger circle that touches the smaller circle is", ["bisected at the point of contact", "equal to the radius of the larger circle", "a diameter of the smaller circle", "a tangent to the larger circle"], 0, "The radius to the point of contact is perpendicular to that chord and therefore bisects it."),
  cbsePyq("class-10", "mathematics", "circles", "If PA and PB are tangents from P and O is the centre, then OA is", ["parallel to PA", "perpendicular to PA", "equal to PA", "a tangent"], 1, "The radius to the point of contact is perpendicular to the tangent."),
  cbsePyq("class-10", "mathematics", "circles", "A chord of a circle is equal to its radius. The angle subtended by the chord at the centre is", ["30°", "60°", "90°", "120°"], 1, "The triangle formed by two radii and the chord is equilateral."),
  cbsePyq("class-10", "mathematics", "circles", "The length of the tangent from a point 10 cm away from the centre of a circle of radius 6 cm is", ["8 cm", "4 cm", "16 cm", "√136 cm"], 0, "√(100 − 36) = 8 cm."),
  cbsePyq("class-10", "mathematics", "circles", "If two tangents from an external point are inclined at 70° to each other, the angle between the radii to the points of contact is", ["110°", "70°", "20°", "140°"], 0, "Two right angles plus 70° leave 110° at the centre."),

  // 11. Areas Related to Circles
  cbsePyq("class-10", "mathematics", "areas-related-to-circles", "The area of a circle of radius r is", ["2πr", "πr²", "πr", "2πr²"], 1, "Area = πr²."),
  cbsePyq("class-10", "mathematics", "areas-related-to-circles", "The circumference of a circle of radius r is", ["πr²", "2πr", "πr/2", "4πr"], 1, "Circumference = 2πr."),
  cbsePyq("class-10", "mathematics", "areas-related-to-circles", "The area of a sector of angle θ (in degrees) is", ["(θ/360) πr²", "(θ/180) πr²", "θ πr²", "(θ/2) r²"], 0, "The sector is the θ/360 fraction of the circle."),
  cbsePyq("class-10", "mathematics", "areas-related-to-circles", "The length of an arc of angle θ (in degrees) is", ["(θ/360) 2πr", "(θ/180) 2πr", "θ r", "(θ/360) πr²"], 0, "Arc length is the same fraction of the circumference."),
  cbsePyq("class-10", "mathematics", "areas-related-to-circles", "The area of a sector of 60° in a circle of radius 7 cm (take π = 22/7) is", ["77/3 cm²", "77 cm²", "22 cm²", "154 cm²"], 0, "(60/360)×(22/7)×49 = 77/3 cm²."),
  cbsePyq("class-10", "mathematics", "areas-related-to-circles", "The area of a quadrant of a circle of radius 7 cm (π = 22/7) is", ["77/2 cm²", "77 cm²", "22 cm²", "154 cm²"], 0, "(1/4)×(22/7)×49 = 77/2 cm²."),
  cbsePyq("class-10", "mathematics", "areas-related-to-circles", "The perimeter of a sector of radius r and arc length l is", ["2r + l", "r + l", "2πr", "2l + r"], 0, "The perimeter consists of two radii and the arc."),
  cbsePyq("class-10", "mathematics", "areas-related-to-circles", "The area of a segment of a circle is", ["area of the sector minus the area of the corresponding triangle", "area of the sector plus the triangle", "πr² − 2r", "half the sector"], 0, "A minor segment equals sector minus triangle."),
  cbsePyq("class-10", "mathematics", "areas-related-to-circles", "The area of a sector of 60° in a circle of radius 21 cm (π = 22/7) is", ["231 cm²", "462 cm²", "154 cm²", "132 cm²"], 0, "(1/6)×(22/7)×441 = 231 cm²."),
  cbsePyq("class-10", "mathematics", "areas-related-to-circles", "A horse is tied to a peg with a 14 m rope. The area it can graze (π = 22/7) is", ["616 m²", "308 m²", "154 m²", "88 m²"], 0, "π × 14² = (22/7)×196 = 616 m²."),
  cbsePyq("class-10", "mathematics", "areas-related-to-circles", "The area of a ring with outer radius R and inner radius r is", ["π(R² − r²)", "π(R − r)²", "2π(R − r)", "π(R + r)"], 0, "The annulus area is the difference of the two circular areas."),
  cbsePyq("class-10", "mathematics", "areas-related-to-circles", "A circle is inscribed in a square of side 14 cm. The area of the circle (in terms of π) is", ["49π cm²", "196π cm²", "14π cm²", "28π cm²"], 0, "The diameter is 14 cm, so r = 7 and area = 49π."),
  cbsePyq("class-10", "mathematics", "areas-related-to-circles", "If the circumference of a circle is 44 cm (π = 22/7), its radius is", ["7 cm", "14 cm", "22 cm", "3.5 cm"], 0, "2πr = 44, so r = 7 cm."),
  cbsePyq("class-10", "mathematics", "areas-related-to-circles", "The area of a semicircle of radius 7 cm (π = 22/7) is", ["77 cm²", "154 cm²", "44 cm²", "22 cm²"], 0, "(1/2)×(22/7)×49 = 77 cm²."),
  cbsePyq("class-10", "mathematics", "areas-related-to-circles", "The length of a 90° arc in a circle of radius 14 cm (π = 22/7) is", ["22 cm", "44 cm", "11 cm", "7 cm"], 0, "(90/360)×2×(22/7)×14 = 22 cm."),
  cbsePyq("class-10", "mathematics", "areas-related-to-circles", "The area of a sector of radius 10 cm with arc length 10 cm is", ["50 cm²", "100 cm²", "25 cm²", "10π cm²"], 0, "Sector area = (1/2) r × (arc length) = 50 cm²."),
  cbsePyq("class-10", "mathematics", "areas-related-to-circles", "A sector of 90° of a circle is a", ["semicircle", "quadrant", "segment", "annulus"], 1, "90° is one-fourth of 360°."),
  cbsePyq("class-10", "mathematics", "areas-related-to-circles", "The area of a 2 m wide circular path around a circle of radius 10 m is", ["44π m²", "24π m²", "100π m²", "4π m²"], 0, "π(12² − 10²) = 44π m²."),
  cbsePyq("class-10", "mathematics", "areas-related-to-circles", "The minute hand of a clock is 14 cm long. The area swept in 5 minutes (π = 22/7) is", ["154/3 cm²", "154 cm²", "22 cm²", "308 cm²"], 0, "5 minutes correspond to 30°, so the area is 154/3 cm²."),
  cbsePyq("class-10", "mathematics", "areas-related-to-circles", "If the perimeter of a sector is 56 cm and the radius is 14 cm, the arc length is", ["28 cm", "42 cm", "14 cm", "56 cm"], 0, "2r + l = 56, so l = 28 cm."),

  // 12. Surface Areas and Volumes
  cbsePyq("class-10", "mathematics", "surface-areas-and-volumes", "The curved surface area of a cylinder is", ["2πrh", "2πr(h + r)", "πr²h", "πrl"], 0, "CSA of a cylinder is 2πrh."),
  cbsePyq("class-10", "mathematics", "surface-areas-and-volumes", "The total surface area of a cylinder is", ["2πrh", "2πr(h + r)", "πr²h", "4πr²"], 1, "TSA = 2πrh + 2πr²."),
  cbsePyq("class-10", "mathematics", "surface-areas-and-volumes", "The volume of a cylinder is", ["2πrh", "πr²h", "(1/3)πr²h", "(4/3)πr³"], 1, "Volume = base area × height."),
  cbsePyq("class-10", "mathematics", "surface-areas-and-volumes", "The curved surface area of a cone is", ["πrl", "2πrh", "πr(l + r)", "4πr²"], 0, "CSA of a cone is πrl, where l is the slant height."),
  cbsePyq("class-10", "mathematics", "surface-areas-and-volumes", "The volume of a cone is", ["πr²h", "(1/3)πr²h", "(2/3)πr³", "(4/3)πr³"], 1, "A cone is one-third of the cylinder on the same base and height."),
  cbsePyq("class-10", "mathematics", "surface-areas-and-volumes", "The volume of a sphere is", ["4πr²", "(4/3)πr³", "(2/3)πr³", "πr³"], 1, "Volume of a sphere is (4/3)πr³."),
  cbsePyq("class-10", "mathematics", "surface-areas-and-volumes", "The total surface area of a sphere is", ["2πr²", "3πr²", "4πr²", "πr²"], 2, "TSA of a sphere is 4πr²."),
  cbsePyq("class-10", "mathematics", "surface-areas-and-volumes", "The curved surface area of a hemisphere is", ["2πr²", "3πr²", "4πr²", "πr²"], 0, "The curved (dome) surface is 2πr²."),
  cbsePyq("class-10", "mathematics", "surface-areas-and-volumes", "The total surface area of a hemisphere is", ["2πr²", "3πr²", "4πr²", "πr²"], 1, "TSA includes the circular base: 2πr² + πr² = 3πr²."),
  cbsePyq("class-10", "mathematics", "surface-areas-and-volumes", "The volume of a hemisphere is", ["(4/3)πr³", "(2/3)πr³", "(1/3)πr³", "2πr³"], 1, "A hemisphere is half a sphere."),
  cbsePyq("class-10", "mathematics", "surface-areas-and-volumes", "The slant height l of a cone satisfies", ["l = √(r² + h²)", "l = r + h", "l = r² + h²", "l = rh"], 0, "l, r and h form a right triangle."),
  cbsePyq("class-10", "mathematics", "surface-areas-and-volumes", "The volume of a cuboid is", ["2(lb + bh + hl)", "lbh", "l + b + h", "6a²"], 1, "Volume = length × breadth × height."),
  cbsePyq("class-10", "mathematics", "surface-areas-and-volumes", "A cone is melted and recast into a sphere of the same radius. The height of the cone is", ["2r", "3r", "4r", "r"], 2, "(1/3)πr²h = (4/3)πr³, so h = 4r."),
  cbsePyq("class-10", "mathematics", "surface-areas-and-volumes", "A solid sphere of radius 6 cm is melted into a cylinder of radius 6 cm. The height of the cylinder is", ["8 cm", "6 cm", "4 cm", "12 cm"], 0, "(4/3)πr³ = πr²h, so h = (4/3)r = 8 cm."),
  cbsePyq("class-10", "mathematics", "surface-areas-and-volumes", "The lateral surface area of a cube of side a is", ["6a²", "4a²", "a²", "2a²"], 1, "Four side faces give 4a²."),
  cbsePyq("class-10", "mathematics", "surface-areas-and-volumes", "The space diagonal of a cube of side a is", ["a√2", "a√3", "2a", "3a"], 1, "√(a² + a² + a²) = a√3."),
  cbsePyq("class-10", "mathematics", "surface-areas-and-volumes", "The volume of a cube of side a is", ["6a²", "a³", "4a²", "3a²"], 1, "Volume = a³."),
  cbsePyq("class-10", "mathematics", "surface-areas-and-volumes", "The volume of a frustum of a cone is", ["(1/3)πh(R² + Rr + r²)", "πh(R² + r²)", "(1/3)πh(R + r)²", "πh(R − r)²"], 0, "This is the standard frustum formula."),
  cbsePyq("class-10", "mathematics", "surface-areas-and-volumes", "A metallic sphere of radius 9 cm is melted into 27 identical smaller spheres. The radius of each small sphere is", ["3 cm", "1 cm", "9 cm", "6 cm"], 0, "Volume scales as the cube of radius: 27 = (9/r)³, so r = 3 cm."),
  cbsePyq("class-10", "mathematics", "surface-areas-and-volumes", "The total surface area of a cube of side 7 cm is", ["294 cm²", "196 cm²", "343 cm²", "84 cm²"], 0, "6a² = 6×49 = 294 cm²."),

  // 13. Statistics
  cbsePyq("class-10", "mathematics", "statistics", "The mean of 2, 4, 6, 8, 10 is", ["6", "5", "8", "4"], 0, "Sum = 30, so the mean is 6."),
  cbsePyq("class-10", "mathematics", "statistics", "The median of 3, 5, 7, 9, 11 is", ["7", "5", "9", "6"], 0, "The middle observation of the ordered list is 7."),
  cbsePyq("class-10", "mathematics", "statistics", "The mode of a data set is", ["the middle value", "the observation with the highest frequency", "the average", "the difference of max and min"], 1, "Mode is the most frequent observation."),
  cbsePyq("class-10", "mathematics", "statistics", "The empirical relation between mean, median and mode is", ["3 median = mode + 2 mean", "3 mean = mode + 2 median", "mode = 3 mean − 2 median", "mean = 3 median − 2 mode"], 0, "The Class 10 empirical formula is 3 Median = Mode + 2 Mean."),
  cbsePyq("class-10", "mathematics", "statistics", "The class mark of a class is", ["(upper limit + lower limit)/2", "upper limit − lower limit", "frequency / width", "the upper limit"], 0, "Class mark is the mid-value of the class."),
  cbsePyq("class-10", "mathematics", "statistics", "In the step-deviation method, the mean is", ["a + (Σfi ui / Σfi) × h", "a + Σfi / h", "Σ fi xi", "h / a"], 0, "ui = (xi − a)/h, so mean = a + h × (Σfi ui / Σfi)."),
  cbsePyq("class-10", "mathematics", "statistics", "The cumulative frequency of a class is", ["the frequency of that class only", "the frequency of that class plus all preceding frequencies", "n − frequency", "the class width"], 1, "Less-than cumulative frequency is a running total."),
  cbsePyq("class-10", "mathematics", "statistics", "The median class is the class whose cumulative frequency is", ["equal to n", "just greater than n/2", "the maximum frequency", "just greater than n"], 1, "The median lies in the class where the less-than cf first exceeds n/2."),
  cbsePyq("class-10", "mathematics", "statistics", "The modal class is the class with", ["the maximum frequency", "the minimum frequency", "cf just above n/2", "the largest class mark"], 0, "Mode is estimated from the class of highest frequency."),
  cbsePyq("class-10", "mathematics", "statistics", "An ogive is", ["a cumulative frequency curve", "a bar graph", "a pie chart", "a histogram of class marks"], 0, "An ogive plots cumulative frequency against class limits."),
  cbsePyq("class-10", "mathematics", "statistics", "From an ogive, the median is the", ["x-coordinate corresponding to n/2", "y-coordinate corresponding to n/2", "highest point", "class width"], 0, "Draw y = n/2 and read the corresponding x-value."),
  cbsePyq("class-10", "mathematics", "statistics", "If mean = 20 and median = 22, then mode equals", ["26", "24", "18", "16"], 0, "Mode = 3×22 − 2×20 = 26."),
  cbsePyq("class-10", "mathematics", "statistics", "The range of a data set is", ["maximum − minimum", "mean − median", "sum of observations", "mode − mean"], 0, "Range is the difference between the extreme values."),
  cbsePyq("class-10", "mathematics", "statistics", "The mean of the first n natural numbers is", ["(n + 1)/2", "n/2", "n(n + 1)/2", "n + 1"], 0, "The sum is n(n + 1)/2, so the mean is (n + 1)/2."),
  cbsePyq("class-10", "mathematics", "statistics", "If each observation is increased by 5, the mean", ["increases by 5", "remains the same", "is multiplied by 5", "decreases by 5"], 0, "Adding a constant to every value adds that constant to the mean."),
  cbsePyq("class-10", "mathematics", "statistics", "The mode of 1, 2, 2, 3, 4, 4, 4, 5 is", ["2", "4", "3", "1"], 1, "4 occurs three times, more than any other value."),
  cbsePyq("class-10", "mathematics", "statistics", "If the mean of 5, 7, 9 and x is 8, then x equals", ["11", "8", "9", "10"], 0, "5 + 7 + 9 + x = 32, so x = 11."),
  cbsePyq("class-10", "mathematics", "statistics", "The abscissa of the intersection of the less-than and more-than ogives gives the", ["mean", "median", "mode", "range"], 1, "The two ogives intersect at the median."),
  cbsePyq("class-10", "mathematics", "statistics", "Frequency density is", ["frequency / class width", "class width / frequency", "cf / n", "mean / h"], 0, "Histograms of unequal class widths use frequency density."),
  cbsePyq("class-10", "mathematics", "statistics", "If the mean of 10 observations is 20, their sum is", ["200", "20", "2", "10"], 0, "Sum = mean × n = 200."),

  // 14. Probability
  cbsePyq("class-10", "mathematics", "probability", "The probability of an event E is", ["n(E) / n(S)", "n(S) / n(E)", "n(E) + n(S)", "1 − n(E)"], 0, "P(E) is the ratio of favourable outcomes to the total, when outcomes are equally likely."),
  cbsePyq("class-10", "mathematics", "probability", "For any event E,", ["0 ≤ P(E) ≤ 1", "P(E) > 1", "P(E) < 0", "P(E) = 2"], 0, "Probability lies between 0 and 1 inclusive."),
  cbsePyq("class-10", "mathematics", "probability", "P(not E) equals", ["P(E)", "1 − P(E)", "1 + P(E)", "0"], 1, "Complementary events partition the sample space."),
  cbsePyq("class-10", "mathematics", "probability", "The probability of a sure event is", ["0", "1", "1/2", "undefined"], 1, "A sure event is the whole sample space."),
  cbsePyq("class-10", "mathematics", "probability", "The probability of an impossible event is", ["1", "0", "1/2", "−1"], 1, "An impossible event has no favourable outcomes."),
  cbsePyq("class-10", "mathematics", "probability", "A fair coin is tossed once. P(head) is", ["1", "1/2", "0", "2"], 1, "There are two equally likely outcomes."),
  cbsePyq("class-10", "mathematics", "probability", "A fair die is thrown. P(an even number) is", ["1/2", "1/3", "1/6", "2/3"], 0, "Even faces are 2, 4 and 6 — three out of six."),
  cbsePyq("class-10", "mathematics", "probability", "A fair die is thrown. P(a prime number) is", ["1/2", "1/3", "2/3", "1"], 0, "Prime faces are 2, 3 and 5 — three out of six."),
  cbsePyq("class-10", "mathematics", "probability", "A fair die is thrown. P(a number greater than 4) is", ["1/3", "1/2", "1/6", "2/3"], 0, "Favourable faces are 5 and 6."),
  cbsePyq("class-10", "mathematics", "probability", "Two fair coins are tossed. P(two heads) is", ["1/2", "1/4", "1/3", "3/4"], 1, "HH is one of four equally likely outcomes."),
  cbsePyq("class-10", "mathematics", "probability", "A card is drawn from a well-shuffled deck of 52 cards. P(an ace) is", ["1/13", "1/52", "4/13", "1/4"], 0, "There are 4 aces, so 4/52 = 1/13."),
  cbsePyq("class-10", "mathematics", "probability", "P(a red card) from a deck of 52 is", ["1/2", "1/4", "1/13", "26"], 0, "There are 26 red cards out of 52."),
  cbsePyq("class-10", "mathematics", "probability", "P(the king of hearts) from a deck of 52 is", ["1/52", "1/13", "1/4", "4/52"], 0, "There is only one king of hearts."),
  cbsePyq("class-10", "mathematics", "probability", "A bag contains 3 red and 5 black balls. P(drawing a red ball) is", ["3/8", "3/5", "5/8", "1/2"], 0, "There are 3 red balls out of 8."),
  cbsePyq("class-10", "mathematics", "probability", "The sum of the probabilities of all elementary events of a sample space is", ["0", "1", "1/2", "n(S)"], 1, "Elementary events partition the sample space."),
  cbsePyq("class-10", "mathematics", "probability", "A fair die is thrown. P(a multiple of 3) is", ["1/3", "1/2", "1/6", "2/3"], 0, "Faces 3 and 6 — two out of six."),
  cbsePyq("class-10", "mathematics", "probability", "Two fair dice are thrown. P(the sum is 7) is", ["1/6", "1/36", "7/36", "1/12"], 0, "Six outcomes (1,6), (2,5), (3,4), (4,3), (5,2), (6,1) out of 36."),
  cbsePyq("class-10", "mathematics", "probability", "P(E) + P(not E) equals", ["0", "1", "2", "P(E)"], 1, "An event and its complement are exhaustive and mutually exclusive."),
  cbsePyq("class-10", "mathematics", "probability", "A number is chosen at random from 1 to 10. P(a prime) is", ["2/5", "1/2", "3/10", "4/5"], 0, "The primes are 2, 3, 5 and 7 — four out of ten."),
  cbsePyq("class-10", "mathematics", "probability", "If P(E) = 0.05, then P(not E) is", ["0.95", "0.05", "1.05", "0"], 0, "1 − 0.05 = 0.95."),
];

assertTwentyPerChapter(class10MathematicsQuestions, [
  "real-numbers",
  "polynomials",
  "pair-of-linear-equations-in-two-variables",
  "quadratic-equations",
  "arithmetic-progressions",
  "triangles",
  "coordinate-geometry",
  "introduction-to-trigonometry",
  "applications-of-trigonometry",
  "circles",
  "areas-related-to-circles",
  "surface-areas-and-volumes",
  "statistics",
  "probability",
]);
