import { assertTwentyPerChapter, class12Pyq, type PracticeQuestionSeed } from "./types";

export const class12ChemistryQuestions: PracticeQuestionSeed[] = [
  // --- Solutions ---
  class12Pyq(
    "chemistry",
    "solutions",
    "According to Raoult's law, the relative lowering of vapour pressure of a dilute solution of a non-volatile solute is equal to the",
    [
      "mole fraction of the solvent",
      "mole fraction of the solute",
      "molality of the solution",
      "molarity of the solution",
    ],
    1,
    "Raoult's law gives (P° − P)/P° = x_solute for a non-volatile solute.",
  ),
  class12Pyq(
    "chemistry",
    "solutions",
    "For an ideal binary liquid solution, which statement is correct?",
    [
      "ΔmixH = 0 and ΔmixV = 0",
      "ΔmixH > 0 and ΔmixV = 0",
      "ΔmixH = 0 and ΔmixV > 0",
      "ΔmixH < 0 and ΔmixV < 0",
    ],
    0,
    "Ideal solutions obey Raoult's law and have zero enthalpy and volume of mixing.",
  ),
  class12Pyq(
    "chemistry",
    "solutions",
    "A liquid mixture that distils without any change in composition is called an",
    ["ideal solution", "azeotrope", "isotonic solution", "colloidal solution"],
    1,
    "An azeotrope boils at constant temperature with the same composition in liquid and vapour.",
  ),
  class12Pyq(
    "chemistry",
    "solutions",
    "The van't Hoff factor (i) for complete dissociation of K2SO4 in water is",
    ["2", "3", "4", "1"],
    1,
    "K2SO4 → 2K+ + SO4^2−, so three particles and i = 3.",
  ),
  class12Pyq(
    "chemistry",
    "solutions",
    "Which colligative property is preferred for determining molar masses of polymers?",
    [
      "depression in freezing point",
      "elevation in boiling point",
      "relative lowering of vapour pressure",
      "osmotic pressure",
    ],
    3,
    "Osmotic pressure of polymer solutions is measurable even when other colligative changes are too small.",
  ),
  class12Pyq(
    "chemistry",
    "solutions",
    "Henry's law relating the partial pressure of a gas to its mole fraction in solution is written as",
    ["p = KH x", "p = x / KH", "p = KH / x", "p = KH + x"],
    0,
    "Henry's law: p = KH x, where KH is Henry's law constant.",
  ),
  class12Pyq(
    "chemistry",
    "solutions",
    "When a solute associates in solution, the van't Hoff factor i is",
    ["equal to 1", "greater than 1", "less than 1", "equal to zero"],
    2,
    "Association reduces the number of particles, so i < 1.",
  ),
  class12Pyq(
    "chemistry",
    "solutions",
    "Which pair is expected to form a nearly ideal solution?",
    ["HNO3 + H2O", "benzene + toluene", "acetone + chloroform", "ethanol + water"],
    1,
    "Benzene and toluene are similar non-polar liquids and obey Raoult's law closely.",
  ),
  class12Pyq(
    "chemistry",
    "solutions",
    "A solution showing positive deviation from Raoult's law forms a",
    [
      "maximum boiling azeotrope",
      "minimum boiling azeotrope",
      "solid solution",
      "saturated solution only",
    ],
    1,
    "Positive deviation raises vapour pressure, so the azeotrope boils below the boiling points of the pure components (e.g. ethanol–water).",
  ),
  class12Pyq(
    "chemistry",
    "solutions",
    "Desalination of sea water is commercially carried out by",
    ["osmosis", "reverse osmosis", "simple distillation only", "filtration through cloth"],
    1,
    "Pressure greater than osmotic pressure forces solvent through a semi-permeable membrane (reverse osmosis).",
  ),
  class12Pyq(
    "chemistry",
    "solutions",
    "The van't Hoff equation for the osmotic pressure of a dilute solution is",
    ["π = iCRT", "π = iC / RT", "π = CRT / i", "π = iRT / C"],
    0,
    "Osmotic pressure π = iCRT, where C is molar concentration.",
  ),
  class12Pyq(
    "chemistry",
    "solutions",
    "Which concentration term does not change with temperature?",
    ["molarity", "molality", "normality", "formality"],
    1,
    "Molality is moles of solute per kg of solvent, so it is independent of volume (and temperature).",
  ),
  class12Pyq(
    "chemistry",
    "solutions",
    "If a solute associates in solution, the observed molar mass is",
    [
      "equal to the normal molar mass",
      "lower than the normal molar mass",
      "higher than the normal molar mass",
      "always zero",
    ],
    2,
    "Fewer particles make colligative effects smaller, so the calculated (abnormal) molar mass is higher.",
  ),
  class12Pyq(
    "chemistry",
    "solutions",
    "The unit of molal elevation constant Kb is",
    ["K kg mol−1", "K kg mol", "mol kg−1 K−1", "K mol"],
    0,
    "From ΔTb = Kb m, Kb has the unit K kg mol−1.",
  ),
  class12Pyq(
    "chemistry",
    "solutions",
    "Two solutions that have the same osmotic pressure at a given temperature are said to be",
    ["hypertonic", "hypotonic", "isotonic", "azeotropic"],
    2,
    "Isotonic solutions have equal osmotic pressures and cause no net osmosis.",
  ),
  class12Pyq(
    "chemistry",
    "solutions",
    "For a dilute solution of a non-volatile solute, (P° − P)/P° equals the",
    ["mole fraction of solvent", "mole fraction of solute", "molality", "molarity"],
    1,
    "Relative lowering of vapour pressure equals the mole fraction of the non-volatile solute.",
  ),
  class12Pyq(
    "chemistry",
    "solutions",
    "Which liquid pair shows negative deviation from Raoult's law?",
    ["ethanol + acetone", "n-hexane + n-heptane", "acetone + chloroform", "benzene + toluene"],
    2,
    "Hydrogen bonding between acetone and chloroform lowers vapour pressure (negative deviation).",
  ),
  class12Pyq(
    "chemistry",
    "solutions",
    "Addition of a non-volatile solute to a pure solvent",
    [
      "increases the vapour pressure",
      "decreases the vapour pressure",
      "does not affect vapour pressure",
      "makes vapour pressure equal to 1 atm always",
    ],
    1,
    "Solute particles occupy surface sites and lower the escaping tendency of solvent molecules.",
  ),
  class12Pyq(
    "chemistry",
    "solutions",
    "Depression in freezing point of a solution is given by",
    ["ΔTf = i Kf m", "ΔTf = i Kb m", "ΔTf = Kf / m", "ΔTf = i m / Kf"],
    0,
    "ΔTf = i Kf m, where m is molality and Kf is the molal depression constant.",
  ),
  class12Pyq(
    "chemistry",
    "solutions",
    "If NaCl is completely dissociated in water, the van't Hoff factor i is",
    ["1", "2", "3", "0.5"],
    1,
    "NaCl → Na+ + Cl−, so two particles and i = 2.",
  ),

  // --- Electrochemistry ---
  class12Pyq(
    "chemistry",
    "electrochemistry",
    "The Nernst equation for an electrochemical cell at 298 K is",
    [
      "E = E° − (0.059/n) log Q",
      "E = E° + (0.059/n) log Q",
      "E = E° − n log Q",
      "E = (0.059/n) log Q",
    ],
    0,
    "At 298 K, (2.303 RT/F) ≈ 0.059 V, so E = E° − (0.059/n) log Q.",
  ),
  class12Pyq(
    "chemistry",
    "electrochemistry",
    "Kohlrausch's law is especially useful to obtain the limiting molar conductivity of",
    ["strong electrolytes only", "weak electrolytes", "metals", "non-electrolytes"],
    1,
    "Λ°m of a weak electrolyte cannot be found by extrapolation and is calculated using Kohlrausch's law.",
  ),
  class12Pyq(
    "chemistry",
    "electrochemistry",
    "Faraday's first law of electrolysis states that the mass deposited is proportional to the",
    ["current only", "time only", "quantity of electricity passed", "resistance of the electrolyte"],
    2,
    "m ∝ Q = It; mass is proportional to the charge passed.",
  ),
  class12Pyq(
    "chemistry",
    "electrochemistry",
    "The SI unit of conductivity (κ) is",
    ["S m−1", "S m2 mol−1", "ohm", "S mol−1"],
    0,
    "Conductivity κ = 1/ρ and has the unit siemens per metre (S m−1).",
  ),
  class12Pyq(
    "chemistry",
    "electrochemistry",
    "Molar conductivity of an electrolyte generally",
    [
      "decreases with dilution",
      "increases with dilution",
      "is independent of dilution",
      "first increases then becomes zero",
    ],
    1,
    "Λm increases with dilution because interionic attractions decrease and, for weak electrolytes, the degree of dissociation rises.",
  ),
  class12Pyq(
    "chemistry",
    "electrochemistry",
    "The standard electrode potential of the standard hydrogen electrode is taken as",
    ["1.00 V", "0.00 V", "0.059 V", "−1.00 V"],
    1,
    "By convention, E°(H+/H2) = 0.00 V at all temperatures.",
  ),
  class12Pyq(
    "chemistry",
    "electrochemistry",
    "Standard Gibbs energy of a cell reaction is related to E°cell by",
    ["ΔG° = nFE°cell", "ΔG° = −nFE°cell", "ΔG° = E°cell / nF", "ΔG° = nF / E°cell"],
    1,
    "Electrical work is nFE, so ΔG° = −nFE°cell for a spontaneous cell.",
  ),
  class12Pyq(
    "chemistry",
    "electrochemistry",
    "During discharge of a lead storage battery, the concentration of H2SO4",
    ["increases", "decreases", "remains unchanged", "becomes zero instantly"],
    1,
    "The cell reaction consumes H2SO4 and forms PbSO4, so acid concentration falls.",
  ),
  class12Pyq(
    "chemistry",
    "electrochemistry",
    "Λ°m(CH3COOH) according to Kohlrausch's law is equal to",
    [
      "Λ°m(CH3COONa) + Λ°m(HCl) − Λ°m(NaCl)",
      "Λ°m(CH3COONa) + Λ°m(NaCl) − Λ°m(HCl)",
      "Λ°m(HCl) − Λ°m(NaCl)",
      "Λ°m(CH3COONa) only",
    ],
    0,
    "λ°(H+) + λ°(CH3COO−) is obtained by adding the strong electrolytes and subtracting NaCl.",
  ),
  class12Pyq(
    "chemistry",
    "electrochemistry",
    "The cell constant of a conductivity cell is",
    ["l × A", "l / A", "A / l", "κ × R × A"],
    1,
    "Cell constant = l/A (distance between electrodes / area).",
  ),
  class12Pyq(
    "chemistry",
    "electrochemistry",
    "The product formed in a hydrogen–oxygen fuel cell is",
    ["CO2", "H2O", "H2O2", "O3"],
    1,
    "H2 is oxidised and O2 is reduced to give water.",
  ),
  class12Pyq(
    "chemistry",
    "electrochemistry",
    "Rusting of iron is best described as",
    ["electrochemical corrosion", "electrolytic refining", "electroplating", "galvanization"],
    0,
    "Different regions of iron act as anode and cathode in the presence of water and oxygen.",
  ),
  class12Pyq(
    "chemistry",
    "electrochemistry",
    "If conductivity κ is in S cm−1 and molarity C is in mol L−1, molar conductivity Λm (S cm2 mol−1) is",
    ["κ × 1000 / C", "κ × C / 1000", "κ / C", "C / κ"],
    0,
    "Λm = κ / c with unit conversion 1000 cm3 L−1 gives Λm = 1000 κ / C.",
  ),
  class12Pyq(
    "chemistry",
    "electrochemistry",
    "A dry cell (Leclanche cell) is an example of a",
    ["primary cell", "secondary cell", "fuel cell", "concentration cell"],
    0,
    "Primary cells cannot be recharged; the dry cell is a commercial primary cell.",
  ),
  class12Pyq(
    "chemistry",
    "electrochemistry",
    "For the cell Zn | Zn2+(1 M) || Cu2+(1 M) | Cu, Ecell equals E°cell because",
    ["reaction quotient Q = 1", "n = 1 always", "temperature must be 0 K", "Zn is more reactive only"],
    0,
    "Nernst: E = E° − (0.059/n) log([Zn2+]/[Cu2+]); here Q = 1 so log Q = 0.",
  ),
  class12Pyq(
    "chemistry",
    "electrochemistry",
    "Faraday's second law of electrolysis relates masses of substances deposited to their",
    ["atomic numbers", "equivalent masses", "densities", "melting points"],
    1,
    "Masses deposited by the same charge are in the ratio of their equivalent masses.",
  ),
  class12Pyq(
    "chemistry",
    "electrochemistry",
    "On dilution of an electrolytic solution, its conductivity (specific conductance) generally",
    ["increases", "decreases", "remains constant", "becomes equal to Λm"],
    1,
    "The number of ions per unit volume falls, so κ decreases even though Λm increases.",
  ),
  class12Pyq(
    "chemistry",
    "electrochemistry",
    "The chemical composition of rust is",
    ["FeO", "Fe3O4", "Fe2O3 · xH2O", "Fe(OH)2 only"],
    2,
    "Rust is hydrated ferric oxide, Fe2O3 · xH2O.",
  ),
  class12Pyq(
    "chemistry",
    "electrochemistry",
    "The number of faradays required to deposit 1 mol of Al from Al3+ is",
    ["1", "2", "3", "6"],
    2,
    "Al3+ + 3e− → Al, so 3 F are needed per mole of aluminium.",
  ),
  class12Pyq(
    "chemistry",
    "electrochemistry",
    "Kohlrausch's law states that the limiting molar conductivity of an electrolyte is the",
    [
      "product of ionic conductivities",
      "sum of the limiting ionic conductivities of its cations and anions (weighted by stoichiometric numbers)",
      "same as conductivity κ",
      "inversely proportional to √c for all electrolytes equally",
    ],
    1,
    "Λ°m = ν+ λ°+ + ν− λ°− at infinite dilution.",
  ),

  // --- Chemical kinetics ---
  class12Pyq(
    "chemistry",
    "chemical-kinetics",
    "For a first-order reaction, the half-life is given by",
    ["t1/2 = 0.693 / k", "t1/2 = k / 0.693", "t1/2 = [A]0 / 2k", "t1/2 = 2k / [A]0"],
    0,
    "Integrated first-order law gives t1/2 = ln 2 / k = 0.693 / k.",
  ),
  class12Pyq(
    "chemistry",
    "chemical-kinetics",
    "Which of the following is always a whole number?",
    ["order of a reaction", "molecularity of an elementary reaction", "rate constant", "half-life"],
    1,
    "Molecularity is the number of molecules in an elementary step and is a positive integer; order can be fractional.",
  ),
  class12Pyq(
    "chemistry",
    "chemical-kinetics",
    "The unit of the rate constant for a first-order reaction is",
    ["mol L−1 s−1", "s−1", "L mol−1 s−1", "L2 mol−2 s−1"],
    1,
    "For first order, rate = k[A], so k has the unit time−1 (s−1).",
  ),
  class12Pyq(
    "chemistry",
    "chemical-kinetics",
    "The unit of k for a second-order reaction is",
    ["s−1", "mol L−1 s−1", "L mol−1 s−1", "L2 mol−2 s−1"],
    2,
    "Rate = k[A]2, so k has the unit concentration−1 time−1.",
  ),
  class12Pyq(
    "chemistry",
    "chemical-kinetics",
    "The Arrhenius equation is",
    ["k = A e−Ea/RT", "k = A eEa/RT", "k = A e−RT/Ea", "k = Ea e−A/RT"],
    0,
    "k = A exp(−Ea/RT), where A is the frequency factor and Ea the activation energy.",
  ),
  class12Pyq(
    "chemistry",
    "chemical-kinetics",
    "A plot of ln k versus 1/T is a straight line with slope",
    ["Ea / R", "−Ea / R", "−Ea", "R / Ea"],
    1,
    "ln k = ln A − (Ea/R)(1/T), so slope = −Ea/R.",
  ),
  class12Pyq(
    "chemistry",
    "chemical-kinetics",
    "For a zero-order reaction, t1/2 is equal to",
    ["0.693 / k", "[A]0 / 2k", "2k / [A]0", "independent of [A]0"],
    1,
    "For zero order, t1/2 = [A]0 / 2k and depends on the initial concentration.",
  ),
  class12Pyq(
    "chemistry",
    "chemical-kinetics",
    "For a first-order reaction, the time required for 75% completion is",
    ["equal to t1/2", "twice t1/2", "thrice t1/2", "half of t1/2"],
    1,
    "75% completion leaves 25% reactant, which is two half-lives.",
  ),
  class12Pyq(
    "chemistry",
    "chemical-kinetics",
    "A catalyst increases the rate of a reaction by",
    [
      "increasing the temperature",
      "providing an alternative path of lower activation energy",
      "increasing the activation energy",
      "increasing the concentration of products only",
    ],
    1,
    "The catalyst lowers Ea of the rate-determining path without being consumed.",
  ),
  class12Pyq(
    "chemistry",
    "chemical-kinetics",
    "The order of a reaction is obtained from the",
    [
      "stoichiometric coefficients always",
      "molecularity of the overall equation",
      "experimentally determined rate law",
      "heat of reaction",
    ],
    2,
    "Order is an experimental quantity and need not match stoichiometry.",
  ),
  class12Pyq(
    "chemistry",
    "chemical-kinetics",
    "Inversion of cane sugar is a classic example of a",
    ["zero-order reaction", "second-order reaction", "pseudo first-order reaction", "third-order reaction"],
    2,
    "Water is in large excess, so the reaction appears first-order in sucrose.",
  ),
  class12Pyq(
    "chemistry",
    "chemical-kinetics",
    "The instantaneous rate of a reaction is obtained from the",
    [
      "intercept of the concentration–time graph",
      "slope of the tangent to the concentration–time curve at that instant",
      "average of initial and final concentrations only",
      "half-life alone",
    ],
    1,
    "Instantaneous rate = −d[A]/dt evaluated from the tangent at time t.",
  ),
  class12Pyq(
    "chemistry",
    "chemical-kinetics",
    "The integrated rate law for a first-order reaction is",
    [
      "k = (2.303 / t) log ([A]0 / [A])",
      "k = [A]0 − [A]",
      "k = 1 / t[A]",
      "k = t log [A]",
    ],
    0,
    "k = (2.303/t) log([A]0/[A]) is the integrated first-order equation.",
  ),
  class12Pyq(
    "chemistry",
    "chemical-kinetics",
    "For a first-order reaction, a straight line is obtained by plotting",
    ["[A] vs t", "ln[A] vs t", "1/[A] vs t", "[A] vs 1/t"],
    1,
    "ln[A] = ln[A]0 − kt, so ln[A] versus t is linear with slope −k.",
  ),
  class12Pyq(
    "chemistry",
    "chemical-kinetics",
    "The half-life of a first-order reaction",
    [
      "depends on the initial concentration",
      "is independent of the initial concentration",
      "is proportional to [A]0",
      "is inversely proportional to [A]0",
    ],
    1,
    "t1/2 = 0.693/k does not involve [A]0.",
  ),
  class12Pyq(
    "chemistry",
    "chemical-kinetics",
    "If the concentration of a reactant is doubled and the rate becomes four times, the order with respect to that reactant is",
    ["0", "1", "2", "3"],
    2,
    "rate ∝ [A]^n; 4 = 2^n gives n = 2.",
  ),
  class12Pyq(
    "chemistry",
    "chemical-kinetics",
    "According to collision theory, an effective collision requires",
    [
      "any energy of collision",
      "energy greater than the threshold energy and proper orientation",
      "only proper orientation",
      "only high pressure",
    ],
    1,
    "Molecules must collide with E ≥ threshold and with the correct orientation.",
  ),
  class12Pyq(
    "chemistry",
    "chemical-kinetics",
    "The rate of most chemical reactions",
    [
      "decreases with increase in temperature",
      "increases with increase in temperature",
      "is independent of temperature",
      "becomes zero at 298 K",
    ],
    1,
    "Higher T increases the fraction of molecules with E ≥ Ea (Arrhenius).",
  ),
  class12Pyq(
    "chemistry",
    "chemical-kinetics",
    "In a multi-step reaction, the overall rate is determined by the",
    ["fastest step", "slowest (rate-determining) step", "last step only", "first step only always"],
    1,
    "The slowest elementary step limits the observed rate.",
  ),
  class12Pyq(
    "chemistry",
    "chemical-kinetics",
    "In the Arrhenius equation k = A e−Ea/RT, A is called the",
    ["activation energy", "frequency (pre-exponential) factor", "rate constant", "half-life"],
    1,
    "A is the frequency factor, related to the collision frequency and orientation.",
  ),

  // --- The d- and f-block elements ---
  class12Pyq(
    "chemistry",
    "the-d-and-f-block-elements",
    "Lanthanoid contraction arises mainly because of",
    [
      "perfect shielding by 4f electrons",
      "imperfect shielding of nuclear charge by 4f electrons",
      "filling of 5d orbitals only",
      "increase in mass number alone",
    ],
    1,
    "4f electrons shield poorly, so the effective nuclear charge rises and radii fall from La to Lu.",
  ),
  class12Pyq(
    "chemistry",
    "the-d-and-f-block-elements",
    "In acidic medium, MnO4− is reduced to",
    ["MnO2", "MnO4^2−", "Mn2+", "Mn metal"],
    2,
    "In acid, Mn(VII) gains five electrons and forms Mn2+.",
  ),
  class12Pyq(
    "chemistry",
    "the-d-and-f-block-elements",
    "Transition metals show variable oxidation states mainly because of",
    [
      "their large atomic size only",
      "participation of both ns and (n−1)d electrons",
      "the inert pair effect",
      "lanthanoid contraction only",
    ],
    1,
    "ns and (n−1)d energies are close, so both sets of electrons can be used in bonding.",
  ),
  class12Pyq(
    "chemistry",
    "the-d-and-f-block-elements",
    "Zinc is not regarded as a typical transition element because",
    [
      "it is not a metal",
      "it has a completely filled d10 configuration in the ground state and in its common oxidation state",
      "it is always paramagnetic",
      "it does not form alloys",
    ],
    1,
    "A typical transition element has an incomplete d subshell in the ground state or a common ion; Zn/Zn2+ is d10.",
  ),
  class12Pyq(
    "chemistry",
    "the-d-and-f-block-elements",
    "The colour of many transition-metal compounds is due to",
    ["s–s transitions", "d–d transitions", "p–p transitions", "nuclear transitions"],
    1,
    "Visible light promotes electrons between split d orbitals (d–d transitions).",
  ),
  class12Pyq(
    "chemistry",
    "the-d-and-f-block-elements",
    "The highest oxidation state of manganese is shown in",
    ["MnO2", "KMnO4", "Mn2O3", "MnSO4"],
    1,
    "In KMnO4, Mn is in the +7 oxidation state.",
  ),
  class12Pyq(
    "chemistry",
    "the-d-and-f-block-elements",
    "Interstitial compounds are formed when small atoms occupy",
    [
      "substitutional sites of large metal atoms only",
      "voids (interstices) in the metal lattice",
      "only the surface of the metal",
      "gaseous cavities outside the crystal",
    ],
    1,
    "H, C or N atoms fit into interstitial voids of the transition-metal lattice.",
  ),
  class12Pyq(
    "chemistry",
    "the-d-and-f-block-elements",
    "Orange K2Cr2O7 turns yellow on adding alkali due to the formation of",
    ["Cr3+", "CrO4^2−", "CrO2Cl2", "Cr metal"],
    1,
    "Cr2O7^2− + 2OH− ⇌ 2CrO4^2− + H2O; chromate is yellow.",
  ),
  class12Pyq(
    "chemistry",
    "the-d-and-f-block-elements",
    "Mn2+ is more stable than Mn3+ because Mn2+ has a",
    ["d4 configuration", "half-filled d5 configuration", "d10 configuration", "empty d shell"],
    1,
    "Mn2+ is d5 (half-filled), which is extra stable.",
  ),
  class12Pyq(
    "chemistry",
    "the-d-and-f-block-elements",
    "Misch metal is an alloy of",
    ["actinoids only", "lanthanoids with a little iron", "Cu and Zn only", "Fe and C only"],
    1,
    "Misch metal is a lanthanoid alloy (~95% lanthanoids + Fe) used in flints.",
  ),
  class12Pyq(
    "chemistry",
    "the-d-and-f-block-elements",
    "Actinoids show a greater range of oxidation states than lanthanoids because",
    [
      "5f, 6d and 7s energies are comparable",
      "they have smaller size only",
      "they are radioactive only",
      "4f electrons are more exposed than 5f",
    ],
    0,
    "The close energies of 5f, 6d and 7s allow many oxidation states.",
  ),
  class12Pyq(
    "chemistry",
    "the-d-and-f-block-elements",
    "Cu2+ salts are coloured whereas Zn2+ salts are colourless because",
    [
      "Cu2+ is d9 (unpaired electron) while Zn2+ is d10",
      "both ions are d10",
      "Cu2+ is d10 while Zn2+ is d9",
      "Zn2+ has unpaired electrons",
    ],
    0,
    "d–d transitions need a partially filled d shell; Zn2+ (d10) cannot show them.",
  ),
  class12Pyq(
    "chemistry",
    "the-d-and-f-block-elements",
    "Transition metals and their compounds are good catalysts mainly due to",
    [
      "high melting points",
      "variable oxidation states and the ability to form intermediates",
      "low density",
      "their colour",
    ],
    1,
    "They provide a path via unstable intermediates and can change oxidation state easily.",
  ),
  class12Pyq(
    "chemistry",
    "the-d-and-f-block-elements",
    "Zr and Hf have almost identical atomic radii because of",
    ["actinoid contraction", "lanthanoid contraction", "diagonal relationship", "inert pair effect"],
    1,
    "Lanthanoid contraction offsets the expected size increase from 4d to 5d.",
  ),
  class12Pyq(
    "chemistry",
    "the-d-and-f-block-elements",
    "The number of moles of KMnO4 required to oxidise one mole of oxalate ion in acidic medium is",
    ["1/5", "2/5", "2", "5"],
    1,
    "2 MnO4− + 5 C2O4^2− + 16 H+ → 2 Mn2+ + 10 CO2 + 8 H2O, so 2/5 mol KMnO4 per mol oxalate.",
  ),
  class12Pyq(
    "chemistry",
    "the-d-and-f-block-elements",
    "The chromyl chloride test is used to detect",
    ["sulphate ions", "chloride ions", "nitrate ions", "phosphate ions"],
    1,
    "Chlorides give reddish-brown chromyl chloride (CrO2Cl2) vapours with K2Cr2O7/conc. H2SO4.",
  ),
  class12Pyq(
    "chemistry",
    "the-d-and-f-block-elements",
    "The most common oxidation state of lanthanoids is",
    ["+2", "+3", "+4", "+6"],
    1,
    "Almost all lanthanoids form stable Ln3+ compounds.",
  ),
  class12Pyq(
    "chemistry",
    "the-d-and-f-block-elements",
    "In strongly alkaline medium, KMnO4 is reduced to",
    ["Mn2+", "MnO2", "MnO4^2−", "Mn metal"],
    2,
    "In concentrated alkali, MnO4− gains one electron to give green manganate, MnO4^2−.",
  ),
  class12Pyq(
    "chemistry",
    "the-d-and-f-block-elements",
    "Transition metals readily form alloys because of their",
    [
      "similar atomic sizes",
      "large differences in electronegativity",
      "noble-gas configurations",
      "radioactivity",
    ],
    0,
    "Comparable radii allow atoms of one metal to occupy the lattice of another.",
  ),
  class12Pyq(
    "chemistry",
    "the-d-and-f-block-elements",
    "The equivalent mass of KMnO4 in acidic medium is",
    ["M/1", "M/3", "M/5", "M/7"],
    2,
    "Mn(VII) → Mn(II) is a 5-electron change, so equivalent mass = molar mass / 5.",
  ),

  // --- Coordination compounds ---
  class12Pyq(
    "chemistry",
    "coordination-compounds",
    "According to Werner's theory, the primary valence of a coordination compound corresponds to the",
    ["coordination number", "oxidation number (ionizable valence)", "magnetic moment", "colour"],
    1,
    "Primary valence is the oxidation state and is satisfied by ionizable negative groups.",
  ),
  class12Pyq(
    "chemistry",
    "coordination-compounds",
    "The number of ions produced on dissolving [Co(NH3)6]Cl3 in water is",
    ["2", "3", "4", "6"],
    2,
    "The complex ion and three Cl− ions give four ions in solution.",
  ),
  class12Pyq(
    "chemistry",
    "coordination-compounds",
    "In an octahedral crystal field, the d orbitals split into",
    ["t2g and eg sets", "only t2g", "only eg", "s and p orbitals"],
    0,
    "CFT splits d orbitals into lower t2g (dxy, dxz, dyz) and higher eg (dx2−y2, dz2).",
  ),
  class12Pyq(
    "chemistry",
    "coordination-compounds",
    "In the spectrochemical series, the strongest field ligand among the following is",
    ["I−", "Cl−", "H2O", "CN−"],
    3,
    "CN− is a strong-field ligand; I− and Cl− are weak-field.",
  ),
  class12Pyq(
    "chemistry",
    "coordination-compounds",
    "[Ni(CN)4]2− is",
    [
      "tetrahedral and paramagnetic",
      "square planar and diamagnetic",
      "octahedral and paramagnetic",
      "linear and diamagnetic",
    ],
    1,
    "CN− is strong-field; Ni2+ (d8) forms a square-planar dsp2 complex with no unpaired electrons.",
  ),
  class12Pyq(
    "chemistry",
    "coordination-compounds",
    "[NiCl4]2− is tetrahedral and paramagnetic because",
    ["Cl− is a weak-field ligand", "CN− is a weak-field ligand", "Ni2+ is d10", "the complex is square planar"],
    0,
    "Cl− does not cause pairing; Ni2+ (d8) in a tetrahedral field has two unpaired electrons.",
  ),
  class12Pyq(
    "chemistry",
    "coordination-compounds",
    "The extra stability of complexes containing chelating ligands is called the",
    ["chelate effect", "trans effect", "inductive effect", "lanthanoid contraction"],
    0,
    "Chelate rings make complexes thermodynamically more stable than analogous monodentate complexes.",
  ),
  class12Pyq(
    "chemistry",
    "coordination-compounds",
    "The IUPAC name of [Co(NH3)5Cl]Cl2 is",
    [
      "pentaamminechloridocobalt(III) chloride",
      "pentaamminecobalt(II) chloride",
      "cobalt pentaammine chloride",
      "chloropentaamminecobalt(II) chloride",
    ],
    0,
    "Five ammine ligands, one chlorido, Co(III), and two ionizable chlorides.",
  ),
  class12Pyq(
    "chemistry",
    "coordination-compounds",
    "[Co(en)3]3+ shows",
    ["geometrical isomerism only", "optical isomerism", "linkage isomerism", "ionization isomerism only"],
    1,
    "The tris(ethylenediamine) complex is chiral and exists as Δ and Λ enantiomers.",
  ),
  class12Pyq(
    "chemistry",
    "coordination-compounds",
    "Linkage isomerism is shown by complexes containing the ligand",
    ["en", "NH3", "NO2− (ambidentate)", "Cl−"],
    2,
    "NO2− can bind through N (nitro) or O (nitrito).",
  ),
  class12Pyq(
    "chemistry",
    "coordination-compounds",
    "The coordination number of cobalt in [Co(en)3]3+ is",
    ["3", "4", "6", "2"],
    2,
    "Each en is bidentate, so three en ligands give coordination number 6.",
  ),
  class12Pyq(
    "chemistry",
    "coordination-compounds",
    "A homoleptic complex among the following is",
    ["[Co(NH3)4Cl2]+", "[Co(NH3)6]3+", "[Pt(NH3)2Cl2]", "[Co(en)2Cl2]+"],
    1,
    "Homoleptic complexes have only one kind of ligand; [Co(NH3)6]3+ has only NH3.",
  ),
  class12Pyq(
    "chemistry",
    "coordination-compounds",
    "[Fe(CN)6]4− is",
    [
      "high-spin and paramagnetic",
      "low-spin and diamagnetic",
      "high-spin and diamagnetic",
      "low-spin and paramagnetic",
    ],
    1,
    "Fe2+ is d6; CN− is strong-field, so t2g6 with no unpaired electrons.",
  ),
  class12Pyq(
    "chemistry",
    "coordination-compounds",
    "Which of the following is an ambidentate ligand?",
    ["NH3", "H2O", "SCN−", "en"],
    2,
    "SCN− can coordinate through S or N.",
  ),
  class12Pyq(
    "chemistry",
    "coordination-compounds",
    "Cisplatin, used as an anticancer drug, is",
    ["cis-[Pt(NH3)2Cl2]", "trans-[Pt(NH3)2Cl2]", "[Pt(NH3)4]2+", "[Ni(CO)4]"],
    0,
    "cis-Diamminedichloridoplatinum(II) binds DNA and is the active anticancer isomer.",
  ),
  class12Pyq(
    "chemistry",
    "coordination-compounds",
    "According to CFT, the colour of many coordination compounds is due to",
    ["d–d electron transitions", "nuclear transitions", "vibration of ligands only", "s–p transitions"],
    0,
    "Absorption of visible light for t2g ⇌ eg (or e ⇌ t2) transitions produces colour.",
  ),
  class12Pyq(
    "chemistry",
    "coordination-compounds",
    "High-spin octahedral complexes are generally formed with",
    ["strong-field ligands", "weak-field ligands", "chelating ligands only", "CO only"],
    1,
    "When Δo is small (weak field), electrons occupy eg before pairing in t2g.",
  ),
  class12Pyq(
    "chemistry",
    "coordination-compounds",
    "EDTA is a",
    ["monodentate ligand", "bidentate ligand", "hexadentate ligand", "ambidentate ligand only"],
    2,
    "EDTA has six donor atoms (2 N + 4 O) and is hexadentate.",
  ),
  class12Pyq(
    "chemistry",
    "coordination-compounds",
    "[Co(NH3)3Cl3] exhibits",
    [
      "optical isomerism only",
      "facial and meridional geometrical isomerism",
      "linkage isomerism",
      "no isomerism",
    ],
    1,
    "MA3B3 octahedral complexes exist as fac and mer isomers.",
  ),
  class12Pyq(
    "chemistry",
    "coordination-compounds",
    "Ionization isomerism is illustrated by the pair",
    [
      "[Co(NH3)5Br]SO4 and [Co(NH3)5SO4]Br",
      "[Co(NH3)6]Cl3 and [Co(NH3)5Cl]Cl2",
      "[Cr(H2O)6]Cl3 only",
      "[Ni(CO)4] and [Ni(CN)4]2−",
    ],
    0,
    "The same composition gives different ions in solution (Br− vs SO4^2− outside the coordination sphere).",
  ),

  // --- Haloalkanes and haloarenes ---
  class12Pyq(
    "chemistry",
    "haloalkanes-and-haloarenes",
    "The reactivity order of alkyl halides towards SN2 is",
    ["3° > 2° > 1°", "1° > 2° > 3°", "2° > 3° > 1°", "3° > 1° > 2°"],
    1,
    "SN2 is backside attack; steric hindrance makes tertiary halides slowest.",
  ),
  class12Pyq(
    "chemistry",
    "haloalkanes-and-haloarenes",
    "Tertiary alkyl halides undergo nucleophilic substitution mainly by the",
    ["SN2 mechanism", "SN1 mechanism", "free-radical path only", "electrophilic addition path"],
    1,
    "Tertiary carbocations are stable, so SN1 (two-step, via carbocation) is favoured.",
  ),
  class12Pyq(
    "chemistry",
    "haloalkanes-and-haloarenes",
    "Racemisation of an optically active alkyl halide is typically associated with",
    ["SN2 reaction", "SN1 reaction", "E2 only", "Wurtz reaction"],
    1,
    "The planar carbocation in SN1 can be attacked from either face, giving a racemic mixture.",
  ),
  class12Pyq(
    "chemistry",
    "haloalkanes-and-haloarenes",
    "An SN2 reaction of an optically active alkyl halide proceeds with",
    ["retention of configuration", "racemisation", "inversion of configuration", "no stereochemical change"],
    2,
    "Backside attack causes Walden inversion.",
  ),
  class12Pyq(
    "chemistry",
    "haloalkanes-and-haloarenes",
    "The Finkelstein reaction prepares alkyl iodides by treating alkyl chlorides/bromides with",
    ["NaI in acetone", "HF", "Cl2 in CCl4", "AgF"],
    0,
    "NaI in dry acetone exchanges I for Cl/Br; NaCl/NaBr precipitates (Finkelstein).",
  ),
  class12Pyq(
    "chemistry",
    "haloalkanes-and-haloarenes",
    "Alkyl fluorides are conveniently prepared by the Swarts reaction using",
    ["NaI", "AgF (or Hg2F2 / CoF2)", "Na metal", "Zn dust"],
    1,
    "Swarts reaction: alkyl chloride/bromide + metal fluoride → alkyl fluoride.",
  ),
  class12Pyq(
    "chemistry",
    "haloalkanes-and-haloarenes",
    "The Wurtz reaction of an alkyl halide with sodium in dry ether gives a",
    ["alkene", "alkyne", "higher alkane", "alcohol"],
    2,
    "2 RX + 2 Na → R–R + 2 NaX.",
  ),
  class12Pyq(
    "chemistry",
    "haloalkanes-and-haloarenes",
    "Haloarenes are less reactive than haloalkanes towards nucleophilic substitution because of",
    [
      "the +I effect of halogen only",
      "partial double-bond character of C–X (resonance) and the sp2 carbon",
      "the larger size of the halogen only",
      "their low boiling points",
    ],
    1,
    "Resonance gives C–X partial double-bond character and the carbon is sp2, so substitution is difficult.",
  ),
  class12Pyq(
    "chemistry",
    "haloalkanes-and-haloarenes",
    "Chlorobenzene can be prepared from benzene diazonium chloride by the",
    ["Sandmeyer reaction (CuCl)", "Wurtz reaction", "Finkelstein reaction", "Kolbe reaction"],
    0,
    "ArN2+ + CuCl → ArCl + N2 (Sandmeyer).",
  ),
  class12Pyq(
    "chemistry",
    "haloalkanes-and-haloarenes",
    "The Fittig reaction is used to prepare",
    [
      "diphenyl from bromobenzene and sodium",
      "ethane from CH3Br",
      "phenol from chlorobenzene",
      "a Grignard reagent",
    ],
    0,
    "2 ArX + 2 Na → Ar–Ar (Fittig).",
  ),
  class12Pyq(
    "chemistry",
    "haloalkanes-and-haloarenes",
    "A Grignard reagent is prepared by the action of Mg on an alkyl halide in",
    ["water", "dry ether", "alcohol", "aqueous NaOH"],
    1,
    "RX + Mg in dry ether → RMgX; moisture destroys the reagent.",
  ),
  class12Pyq(
    "chemistry",
    "haloalkanes-and-haloarenes",
    "The order of reactivity of alkyl halides towards SN2 is",
    ["RF > RCl > RBr > RI", "RI > RBr > RCl > RF", "RCl > RF > RI > RBr", "RBr > RI > RF > RCl"],
    1,
    "C–I is the weakest bond, so iodides react fastest; C–F is strongest.",
  ),
  class12Pyq(
    "chemistry",
    "haloalkanes-and-haloarenes",
    "Which halide is least reactive towards SN1 and SN2?",
    ["CH3CH2Cl", "(CH3)3CCl", "CH2=CH–CH2Cl", "CH2=CH–Cl (vinyl chloride)"],
    3,
    "The C–Cl bond in vinyl chloride has partial double-bond character and the carbon is sp2.",
  ),
  class12Pyq(
    "chemistry",
    "haloalkanes-and-haloarenes",
    "Chlorobenzene does not give a white precipitate with alcoholic AgNO3 readily because",
    [
      "the C–Cl bond is ionic",
      "the C–Cl bond has partial double-bond character",
      "chlorobenzene is a gas",
      "AgNO3 cannot ionize",
    ],
    1,
    "The halogen is not easily ionized, unlike in alkyl chlorides.",
  ),
  class12Pyq(
    "chemistry",
    "haloalkanes-and-haloarenes",
    "DDT is",
    [
      "2,2-bis(4-chlorophenyl)-1,1,1-trichloroethane",
      "a chlorofluorocarbon refrigerant",
      "iodoform",
      "chloroform",
    ],
    0,
    "DDT is dichlorodiphenyltrichloroethane, an organochlorine insecticide.",
  ),
  class12Pyq(
    "chemistry",
    "haloalkanes-and-haloarenes",
    "Chloroform on oxidation in air and light forms the poisonous gas",
    ["phosgene (COCl2)", "mustard gas", "chlorine", "carbon monoxide only"],
    0,
    "CHCl3 is oxidised to carbonyl chloride (phosgene); ethanol is added as a stabilizer.",
  ),
  class12Pyq(
    "chemistry",
    "haloalkanes-and-haloarenes",
    "Freons used as refrigerants are",
    ["chlorofluorocarbons", "only hydrocarbons", "alcohols", "amines"],
    0,
    "Freons are chlorofluoroalkanes (e.g. CCl2F2) formerly used in refrigeration.",
  ),
  class12Pyq(
    "chemistry",
    "haloalkanes-and-haloarenes",
    "Dehydrohalogenation of an alkyl halide with alcoholic KOH gives an",
    ["alcohol", "alkene", "ether", "aldehyde"],
    1,
    "Alc. KOH promotes elimination (β-elimination) to form an alkene.",
  ),
  class12Pyq(
    "chemistry",
    "haloalkanes-and-haloarenes",
    "Chlorobenzene undergoes electrophilic substitution mainly at the",
    ["meta position", "ortho and para positions", "only the ipso carbon", "all three positions equally"],
    1,
    "The halogen is an ortho/para director due to resonance donation, though it is deactivating by −I.",
  ),
  class12Pyq(
    "chemistry",
    "haloalkanes-and-haloarenes",
    "Allyl chloride is more reactive than n-propyl chloride towards SN1 because the",
    [
      "allyl carbocation is resonance stabilised",
      "allyl chloride is tertiary",
      "Cl is ionic in allyl chloride",
      "allyl chloride is vinylic",
    ],
    0,
    "The allylic carbocation is resonance-stabilised, so SN1 is faster.",
  ),

  // --- Alcohols, phenols and ethers ---
  class12Pyq(
    "chemistry",
    "alcohols-phenols-and-ethers",
    "Lucas reagent is",
    ["anhydrous ZnCl2 + conc. HCl", "anhydrous AlCl3 + HCl", "Zn + dilute HCl", "FeCl3 solution"],
    0,
    "Lucas reagent is conc. HCl and anhydrous ZnCl2, used to distinguish 1°, 2° and 3° alcohols.",
  ),
  class12Pyq(
    "chemistry",
    "alcohols-phenols-and-ethers",
    "Which class of alcohols gives immediate turbidity with Lucas reagent at room temperature?",
    ["primary", "secondary", "tertiary", "all alcohols equally"],
    2,
    "Tertiary alcohols form carbocations rapidly and give an alkyl chloride (turbidity) at once.",
  ),
  class12Pyq(
    "chemistry",
    "alcohols-phenols-and-ethers",
    "Kolbe's reaction of sodium phenoxide with CO2, followed by acidification, gives",
    ["salicylaldehyde", "salicylic acid", "benzene", "anisole"],
    1,
    "Kolbe–Schmitt carboxylation of phenoxide yields 2-hydroxybenzoic acid (salicylic acid).",
  ),
  class12Pyq(
    "chemistry",
    "alcohols-phenols-and-ethers",
    "The Reimer–Tiemann reaction of phenol with chloroform and NaOH gives",
    ["salicylic acid", "salicylaldehyde", "benzoquinone", "picric acid"],
    1,
    "Dichlorocarbene attacks phenoxide at the ortho position to give salicylaldehyde.",
  ),
  class12Pyq(
    "chemistry",
    "alcohols-phenols-and-ethers",
    "Williamson synthesis is used to prepare",
    ["alcohols", "phenols", "ethers", "aldehydes"],
    2,
    "An alkoxide (or phenoxide) reacts with an alkyl halide to give an ether.",
  ),
  class12Pyq(
    "chemistry",
    "alcohols-phenols-and-ethers",
    "Phenol reacts with bromine water to give",
    ["o-bromophenol only", "p-bromophenol only", "2,4,6-tribromophenol", "3-bromophenol"],
    2,
    "The OH group strongly activates the ring; a white ppt of 2,4,6-tribromophenol forms.",
  ),
  class12Pyq(
    "chemistry",
    "alcohols-phenols-and-ethers",
    "Phenol is more acidic than ethanol because the",
    [
      "phenoxide ion is resonance stabilised",
      "ethanol has more carbon atoms",
      "phenol has a higher boiling point",
      "ethoxide ion is more stable",
    ],
    0,
    "Negative charge in phenoxide is delocalised over the ring, so phenol is more acidic.",
  ),
  class12Pyq(
    "chemistry",
    "alcohols-phenols-and-ethers",
    "Ethanol on heating with conc. H2SO4 at 443 K gives",
    ["ethene", "ethoxyethane", "ethanal", "ethane"],
    0,
    "At 443 K intramolecular dehydration of ethanol yields ethene (at 413 K the product is diethyl ether).",
  ),
  class12Pyq(
    "chemistry",
    "alcohols-phenols-and-ethers",
    "Anisole on cleavage with HI gives",
    ["phenol and iodomethane", "iodobenzene and methanol", "benzene and methanol", "phenol and methanol"],
    0,
    "The phenyl–oxygen bond has partial double-bond character, so CH3–O is cleaved: C6H5OH + CH3I.",
  ),
  class12Pyq(
    "chemistry",
    "alcohols-phenols-and-ethers",
    "In the cumene process, phenol is manufactured from",
    [
      "benzene and propene via cumene hydroperoxide",
      "toluene only",
      "aniline",
      "chlorobenzene and water at room temperature",
    ],
    0,
    "Cumene is oxidised to the hydroperoxide, which rearranges to phenol and acetone.",
  ),
  class12Pyq(
    "chemistry",
    "alcohols-phenols-and-ethers",
    "Phenol on heating with zinc dust gives",
    ["benzene", "toluene", "benzoquinone", "anisole"],
    0,
    "Zn reduces the phenolic OH, converting phenol to benzene.",
  ),
  class12Pyq(
    "chemistry",
    "alcohols-phenols-and-ethers",
    "o-Nitrophenol is steam volatile due to",
    [
      "intermolecular hydrogen bonding",
      "intramolecular hydrogen bonding",
      "ionic bonding",
      "a very high molecular mass",
    ],
    1,
    "Intramolecular H-bonding in o-nitrophenol lowers intermolecular association, so it is steam volatile.",
  ),
  class12Pyq(
    "chemistry",
    "alcohols-phenols-and-ethers",
    "Among the following, the strongest acid is",
    ["phenol", "p-cresol", "p-nitrophenol", "ethanol"],
    2,
    "The −NO2 group stabilises the phenoxide ion by −R and −I effects.",
  ),
  class12Pyq(
    "chemistry",
    "alcohols-phenols-and-ethers",
    "CH3CH2OH reacts with SOCl2 to give",
    ["CH3CH2Cl", "CH3CH2SO2Cl", "CH2=CH2", "CH3CHO"],
    0,
    "Alcohols with thionyl chloride give alkyl chlorides: ROH + SOCl2 → RCl + SO2 + HCl.",
  ),
  class12Pyq(
    "chemistry",
    "alcohols-phenols-and-ethers",
    "In Williamson synthesis of unsymmetrical ethers, a primary alkyl halide is preferred to avoid",
    ["substitution", "elimination (alkene formation)", "oxidation", "polymerisation"],
    1,
    "Secondary/tertiary alkyl halides favour E2 with the alkoxide base.",
  ),
  class12Pyq(
    "chemistry",
    "alcohols-phenols-and-ethers",
    "Phenol dissolves in aqueous NaOH but ethanol does not because",
    [
      "phenol is more acidic than ethanol",
      "ethanol is more acidic than phenol",
      "both have the same acidity",
      "phenol is a base",
    ],
    0,
    "Phenol forms sodium phenoxide with NaOH; alcohols are too weakly acidic to react with NaOH.",
  ),
  class12Pyq(
    "chemistry",
    "alcohols-phenols-and-ethers",
    "The reaction of a carboxylic acid with an alcohol in the presence of conc. H2SO4 is called",
    ["Williamson synthesis", "Fischer esterification", "Kolbe reaction", "Reimer–Tiemann reaction"],
    1,
    "Fischer esterification: RCOOH + R′OH ⇌ RCOOR′ + H2O (acid catalysed).",
  ),
  class12Pyq(
    "chemistry",
    "alcohols-phenols-and-ethers",
    "The correct order of acidic strength is",
    [
      "p-nitrophenol > phenol > p-methylphenol",
      "p-methylphenol > phenol > p-nitrophenol",
      "phenol > p-nitrophenol > ethanol",
      "ethanol > phenol > p-nitrophenol",
    ],
    0,
    "Electron-withdrawing NO2 increases acidity; electron-donating CH3 decreases it.",
  ),
  class12Pyq(
    "chemistry",
    "alcohols-phenols-and-ethers",
    "A primary alcohol with Lucas reagent at room temperature",
    [
      "gives immediate turbidity",
      "gives turbidity after a few minutes",
      "does not react appreciably",
      "gives a red colour",
    ],
    2,
    "Primary alcohols react only on heating; no turbidity appears at room temperature.",
  ),
  class12Pyq(
    "chemistry",
    "alcohols-phenols-and-ethers",
    "Cleavage of tert-butyl methyl ether with HI gives",
    [
      "(CH3)3CI + CH3OH",
      "(CH3)3COH + CH3I",
      "only the two alcohols",
      "(CH3)3C–CH3 + HOI",
    ],
    1,
    "SN2 attack occurs at the less hindered methyl carbon, yielding tert-butanol and iodomethane.",
  ),

  // --- Aldehydes, ketones and carboxylic acids ---
  class12Pyq(
    "chemistry",
    "aldehydes-ketones-and-carboxylic-acids",
    "Aldol condensation is given by aldehydes/ketones that have",
    ["no α-hydrogen", "at least one α-hydrogen", "only an aromatic ring", "only a COOH group"],
    1,
    "The enolate from an α-H adds to another carbonyl (aldol).",
  ),
  class12Pyq(
    "chemistry",
    "aldehydes-ketones-and-carboxylic-acids",
    "Cannizzaro reaction is given by",
    ["CH3CHO", "HCHO", "CH3COCH3", "CH3CH2CHO"],
    1,
    "Formaldehyde has no α-H and undergoes disproportionation in conc. NaOH.",
  ),
  class12Pyq(
    "chemistry",
    "aldehydes-ketones-and-carboxylic-acids",
    "Tollens' reagent is used to distinguish",
    ["alkenes and alkanes", "aldehydes and ketones", "alcohols and phenols", "1° and 2° amines"],
    1,
    "Aldehydes reduce [Ag(NH3)2]+ to a silver mirror; ketones generally do not.",
  ),
  class12Pyq(
    "chemistry",
    "aldehydes-ketones-and-carboxylic-acids",
    "Which of the following does not reduce Fehling's solution?",
    ["CH3CHO", "HCHO", "C6H5CHO", "CH3CH2CHO"],
    2,
    "Aromatic aldehydes such as benzaldehyde do not reduce Fehling's solution.",
  ),
  class12Pyq(
    "chemistry",
    "aldehydes-ketones-and-carboxylic-acids",
    "Rosenmund reduction of an acid chloride with H2 / Pd–BaSO4 gives an",
    ["alcohol", "aldehyde", "alkane", "ketone"],
    1,
    "Pd/BaSO4 (poisoned catalyst) stops reduction at the aldehyde.",
  ),
  class12Pyq(
    "chemistry",
    "aldehydes-ketones-and-carboxylic-acids",
    "The Hell–Volhard–Zelinsky reaction is used to prepare",
    ["α-halo carboxylic acids", "aldehydes", "ketones", "ethers"],
    0,
    "Carboxylic acids with α-H react with X2/red P to give α-halo acids.",
  ),
  class12Pyq(
    "chemistry",
    "aldehydes-ketones-and-carboxylic-acids",
    "Clemmensen reduction converts a carbonyl group into CH2 using",
    ["Zn–Hg / conc. HCl", "NH2NH2 / KOH", "LiAlH4 only", "KMnO4"],
    0,
    "Clemmensen: C=O → CH2 in acidic medium with amalgamated zinc.",
  ),
  class12Pyq(
    "chemistry",
    "aldehydes-ketones-and-carboxylic-acids",
    "Wolff–Kishner reduction is carried out with",
    ["Zn–Hg / HCl", "NH2NH2 / KOH (glycol)", "Pd / BaSO4", "LiAlH4 only"],
    1,
    "Hydrazine then strong base (Wolff–Kishner) reduces C=O to CH2 in basic medium.",
  ),
  class12Pyq(
    "chemistry",
    "aldehydes-ketones-and-carboxylic-acids",
    "The characteristic reaction of aldehydes and ketones is",
    [
      "nucleophilic addition",
      "electrophilic addition",
      "nucleophilic substitution",
      "free-radical substitution",
    ],
    0,
    "The polar C=O carbon is attacked by nucleophiles (addition).",
  ),
  class12Pyq(
    "chemistry",
    "aldehydes-ketones-and-carboxylic-acids",
    "Formaldehyde with concentrated NaOH undergoes Cannizzaro reaction to give",
    ["methanol and sodium formate", "only methanol", "only formic acid", "ethanol"],
    0,
    "One molecule is reduced to CH3OH and the other is oxidised to HCOONa.",
  ),
  class12Pyq(
    "chemistry",
    "aldehydes-ketones-and-carboxylic-acids",
    "Which of the following gives the iodoform test?",
    ["CH3COCH3", "C6H5CHO", "HCHO", "CH3COOH"],
    0,
    "Methyl ketones (CH3CO–) give yellow CHI3 with I2/NaOH.",
  ),
  class12Pyq(
    "chemistry",
    "aldehydes-ketones-and-carboxylic-acids",
    "Carboxylic acids are more acidic than phenols because the",
    [
      "carboxylate ion is more resonance-stabilised (two equivalent structures)",
      "phenol has no OH group",
      "they have higher molecular mass",
      "they are gases",
    ],
    0,
    "The two equivalent resonance forms of RCOO− make carboxylic acids stronger acids than phenols.",
  ),
  class12Pyq(
    "chemistry",
    "aldehydes-ketones-and-carboxylic-acids",
    "LiAlH4 reduces carboxylic acids to",
    ["aldehydes", "primary alcohols", "ketones", "alkanes"],
    1,
    "LiAlH4 reduces –COOH all the way to –CH2OH.",
  ),
  class12Pyq(
    "chemistry",
    "aldehydes-ketones-and-carboxylic-acids",
    "Benzaldehyde can be prepared from benzene by the Gattermann–Koch reaction using",
    ["CO + HCl + anhyd. AlCl3 / CuCl", "CHCl3 / NaOH", "CrO2Cl2 only", "alkaline KMnO4"],
    0,
    "Gattermann–Koch formylation introduces –CHO onto benzene.",
  ),
  class12Pyq(
    "chemistry",
    "aldehydes-ketones-and-carboxylic-acids",
    "The haloform test is given by compounds containing the",
    ["CH3CO– or CH3CH(OH)– group", "only COOH group", "only CHO without a methyl", "only a benzene ring"],
    0,
    "CH3CO– (or oxidisable CH3CH(OH)–) yields CHI3 with I2/NaOH.",
  ),
  class12Pyq(
    "chemistry",
    "aldehydes-ketones-and-carboxylic-acids",
    "Benzaldehyde undergoes",
    ["aldol condensation", "Cannizzaro reaction", "HVZ reaction", "iodoform test"],
    1,
    "Benzaldehyde has no α-H, so it gives Cannizzaro, not aldol.",
  ),
  class12Pyq(
    "chemistry",
    "aldehydes-ketones-and-carboxylic-acids",
    "The Etard reaction is used to convert toluene into",
    ["benzaldehyde (CrO2Cl2)", "benzoic acid directly", "benzyl alcohol", "phenol"],
    0,
    "Chromyl chloride oxidises the methyl group of toluene to benzaldehyde (Etard).",
  ),
  class12Pyq(
    "chemistry",
    "aldehydes-ketones-and-carboxylic-acids",
    "The strongest carboxylic acid among the following is",
    ["HCOOH", "CH3COOH", "(CH3)2CHCOOH", "CH3CH2COOH"],
    0,
    "Alkyl groups have +I effect and weaken acidity; formic acid is strongest in this set.",
  ),
  class12Pyq(
    "chemistry",
    "aldehydes-ketones-and-carboxylic-acids",
    "Towards nucleophilic acyl substitution, the most reactive derivative is",
    ["an ester", "an acid chloride", "an amide", "a carboxylate ion"],
    1,
    "Cl− is a good leaving group; acid chlorides are the most reactive carboxylic derivatives.",
  ),
  class12Pyq(
    "chemistry",
    "aldehydes-ketones-and-carboxylic-acids",
    "Acetaldehyde can take part in aldol condensation whereas formaldehyde cannot, because",
    [
      "both lack α-hydrogen",
      "acetaldehyde has α-hydrogen",
      "both are ketones",
      "formaldehyde has two α-hydrogens",
    ],
    1,
    "Aldol needs an α-H; HCHO has none, CH3CHO has three.",
  ),

  // --- Amines ---
  class12Pyq(
    "chemistry",
    "amines",
    "Hinsberg's reagent is",
    ["benzenesulphonyl chloride", "benzene diazonium chloride", "chloroform", "bromine water"],
    0,
    "Hinsberg's reagent is C6H5SO2Cl, used to distinguish 1°, 2° and 3° amines.",
  ),
  class12Pyq(
    "chemistry",
    "amines",
    "A primary amine on treatment with Hinsberg's reagent gives a product that is",
    ["insoluble in alkali", "soluble in alkali", "unreactive towards alkali or acid", "a gas"],
    1,
    "The sulphonamide from a 1° amine still has an acidic N–H and dissolves in alkali.",
  ),
  class12Pyq(
    "chemistry",
    "amines",
    "The carbylamine test is given by",
    ["1° amines", "2° amines only", "3° amines only", "amides"],
    0,
    "Only primary amines give a foul-smelling isocyanide with CHCl3/alc. KOH.",
  ),
  class12Pyq(
    "chemistry",
    "amines",
    "Aniline reacts with bromine water to give",
    ["p-bromoaniline only", "2,4,6-tribromoaniline", "m-bromoaniline", "N-bromoaniline"],
    1,
    "The –NH2 group strongly activates the ring, giving a white ppt of 2,4,6-tribromoaniline.",
  ),
  class12Pyq(
    "chemistry",
    "amines",
    "Diazotisation of aniline is carried out with NaNO2 / HCl at",
    ["0–5 °C", "100 °C", "room temperature in alkali", "250 °C"],
    0,
    "Aromatic diazonium salts are stable only in ice-cold (0–5 °C) acidic solution.",
  ),
  class12Pyq(
    "chemistry",
    "amines",
    "Gabriel phthalimide synthesis is used to prepare",
    ["primary aliphatic amines", "aromatic amines", "secondary amines", "tertiary amines"],
    0,
    "Aryl halides do not undergo the required SN2, so aromatic 1° amines cannot be made this way.",
  ),
  class12Pyq(
    "chemistry",
    "amines",
    "Hoffmann bromamide degradation of an amide gives an amine with",
    ["one carbon more", "one carbon less", "the same number of carbons", "no nitrogen"],
    1,
    "RCONH2 + Br2/KOH → RNH2; the product has one carbon atom fewer.",
  ),
  class12Pyq(
    "chemistry",
    "amines",
    "Aniline is a weaker base than methylamine because the",
    [
      "lone pair on nitrogen is delocalised into the benzene ring",
      "aniline molecule is larger",
      "methylamine is aromatic",
      "aniline has no lone pair",
    ],
    0,
    "Resonance makes the lone pair less available for protonation.",
  ),
  class12Pyq(
    "chemistry",
    "amines",
    "The correct order of basic strength in aqueous solution is",
    [
      "(CH3)2NH > CH3NH2 > (CH3)3N > NH3",
      "NH3 > all methyl amines",
      "(CH3)3N > (CH3)2NH > CH3NH2",
      "CH3NH2 > (CH3)2NH > NH3 > (CH3)3N",
    ],
    0,
    "In water, solvation and inductive effects make dimethylamine the strongest of the methyl amines.",
  ),
  class12Pyq(
    "chemistry",
    "amines",
    "Benzene diazonium chloride couples with phenol in mild alkali to give",
    ["p-hydroxyazobenzene (an azo dye)", "aniline", "chlorobenzene", "nitrobenzene"],
    0,
    "Electrophilic coupling of ArN2+ at the para position of phenoxide gives an azo dye.",
  ),
  class12Pyq(
    "chemistry",
    "amines",
    "Aniline is acetylated before nitration in order to",
    [
      "increase the activating power of NH2",
      "protect NH2 and reduce its activating effect",
      "remove the aromatic ring",
      "convert it into phenol",
    ],
    1,
    "Acetanilide is less activating, so polysubstitution and oxidation are avoided.",
  ),
  class12Pyq(
    "chemistry",
    "amines",
    "Nitrobenzene on reduction with Sn / HCl gives",
    ["aniline", "azobenzene", "phenylhydroxylamine", "nitrosobenzene"],
    0,
    "Sn/HCl (or Fe/HCl) reduces ArNO2 to ArNH2.",
  ),
  class12Pyq(
    "chemistry",
    "amines",
    "A tertiary amine with Hinsberg's reagent",
    [
      "forms an alkali-soluble sulphonamide",
      "forms an alkali-insoluble sulphonamide",
      "does not form a sulphonamide",
      "gives the carbylamine test",
    ],
    2,
    "3° amines have no N–H and do not react with C6H5SO2Cl to give a sulphonamide.",
  ),
  class12Pyq(
    "chemistry",
    "amines",
    "The weakest base among the following is",
    ["aniline", "p-toluidine", "p-nitroaniline", "methylamine"],
    2,
    "The nitro group withdraws electron density from nitrogen, making p-nitroaniline least basic.",
  ),
  class12Pyq(
    "chemistry",
    "amines",
    "Aniline does not undergo Friedel–Crafts reaction because",
    [
      "it forms a salt with AlCl3 and the ring is deactivated",
      "it has no aromatic ring",
      "it is a gas",
      "Cl is a meta director in aniline",
    ],
    0,
    "The Lewis acid complexes with –NH2, withdrawing electrons from the ring.",
  ),
  class12Pyq(
    "chemistry",
    "amines",
    "Hoffmann mustard oil reaction is used to detect",
    ["1° amines", "2° alcohols", "phenols", "aldehydes"],
    0,
    "1° amines with CS2 then HgCl2 give a pungent alkyl isothiocyanate (mustard oil odour).",
  ),
  class12Pyq(
    "chemistry",
    "amines",
    "Quaternary ammonium salts are used as",
    ["phase-transfer catalysts", "primary amines", "diazonium salts", "Grignard reagents"],
    0,
    "They transfer anions between aqueous and organic phases (PTC).",
  ),
  class12Pyq(
    "chemistry",
    "amines",
    "The Gattermann reaction converts ArN2+ to ArCl / ArBr using",
    ["Cu powder and HX", "CuCN", "KI", "H3PO2"],
    0,
    "Gattermann uses copper powder and the hydrogen halide instead of Cu(I) halide (Sandmeyer).",
  ),
  class12Pyq(
    "chemistry",
    "amines",
    "Aniline on heating with chloroform and alcoholic KOH gives",
    ["phenyl isocyanide (carbylamine)", "phenol", "acetanilide", "a diazonium salt"],
    0,
    "This is the carbylamine reaction of a primary amine.",
  ),
  class12Pyq(
    "chemistry",
    "amines",
    "The Hinsberg test is used to distinguish",
    ["1°, 2° and 3° amines", "aldehydes and ketones", "1°, 2° and 3° alcohols", "glucose and fructose"],
    0,
    "Different solubility behaviour of the sulphonamides (or lack of reaction) identifies the class of amine.",
  ),

  // --- Biomolecules ---
  class12Pyq(
    "chemistry",
    "biomolecules",
    "DNA differs from RNA in having",
    ["ribose and uracil", "deoxyribose and thymine", "deoxyribose and uracil", "ribose and thymine"],
    1,
    "DNA contains 2-deoxyribose and the base thymine; RNA has ribose and uracil.",
  ),
  class12Pyq(
    "chemistry",
    "biomolecules",
    "Essential amino acids are those which",
    [
      "are synthesized in the human body",
      "cannot be synthesized in the body and must be supplied in the diet",
      "contain no nitrogen",
      "are always acidic",
    ],
    1,
    "Humans cannot make essential amino acids such as valine, leucine and lysine.",
  ),
  class12Pyq(
    "chemistry",
    "biomolecules",
    "A peptide bond has the structure",
    ["–CO–NH–", "–C–C–", "–O–O–", "–S–S– only"],
    0,
    "Amino acids are joined by an amide (peptide) linkage –CO–NH–.",
  ),
  class12Pyq(
    "chemistry",
    "biomolecules",
    "Deficiency of vitamin C causes",
    ["rickets", "scurvy", "beriberi", "night blindness"],
    1,
    "Vitamin C (ascorbic acid) deficiency leads to scurvy.",
  ),
  class12Pyq(
    "chemistry",
    "biomolecules",
    "Deficiency of vitamin D causes",
    ["scurvy", "rickets", "beriberi", "pellagra"],
    1,
    "Vitamin D is needed for Ca/P metabolism; deficiency causes rickets in children.",
  ),
  class12Pyq(
    "chemistry",
    "biomolecules",
    "Prolonged heating of glucose with HI gives",
    ["n-hexane", "n-pentane", "hexanoic acid", "sorbitol"],
    0,
    "n-Hexane proves that glucose has a straight chain of six carbon atoms.",
  ),
  class12Pyq(
    "chemistry",
    "biomolecules",
    "Mutarotation is the",
    [
      "change in pH of a sugar solution",
      "change in specific rotation of a freshly prepared sugar solution",
      "inversion of configuration of amino acids",
      "denaturation of proteins",
    ],
    1,
    "α- and β-anomers equilibrate via the open-chain form, changing the observed rotation.",
  ),
  class12Pyq(
    "chemistry",
    "biomolecules",
    "Invert sugar is",
    ["sucrose itself", "an equimolar mixture of glucose and fructose", "only fructose", "starch"],
    1,
    "Hydrolysis of sucrose (invertase or acid) gives glucose + fructose and inverts the sign of rotation.",
  ),
  class12Pyq(
    "chemistry",
    "biomolecules",
    "The linkage between two monosaccharide units in a disaccharide is called a",
    ["peptide bond", "glycosidic linkage", "phosphodiester bond", "hydrogen bond"],
    1,
    "An acetal (glycosidic) bond joins the anomeric carbon of one sugar to an OH of another.",
  ),
  class12Pyq(
    "chemistry",
    "biomolecules",
    "Amino acids exist as zwitter ions which contain",
    ["both –NH3+ and –COO−", "only –NH2", "only –COOH", "no charge"],
    0,
    "The carboxylic proton transfers to the amino group, giving a dipolar ion.",
  ),
  class12Pyq(
    "chemistry",
    "biomolecules",
    "Denaturation of proteins involves",
    [
      "breaking of peptide bonds",
      "loss of secondary and tertiary structure without hydrolysis of peptide bonds",
      "hydrolysis to free amino acids",
      "formation of DNA",
    ],
    1,
    "Heat or pH change unfolds H-bonds and other weak interactions; the primary sequence remains.",
  ),
  class12Pyq(
    "chemistry",
    "biomolecules",
    "A nucleotide differs from a nucleoside in having",
    ["a phosphate group", "a sugar", "a nitrogenous base", "a peptide bond"],
    0,
    "Nucleoside = base + sugar; nucleotide = nucleoside + phosphate.",
  ),
  class12Pyq(
    "chemistry",
    "biomolecules",
    "Vitamin B12 contains the metal",
    ["Fe", "Co", "Mg", "Zn"],
    1,
    "Cobalamin (vitamin B12) has cobalt at the centre of a corrin ring.",
  ),
  class12Pyq(
    "chemistry",
    "biomolecules",
    "Amylose is a",
    [
      "linear polymer of D-glucose with α-1,4 glycosidic links",
      "branched polymer with β-1,4 links",
      "polymer of fructose",
      "protein",
    ],
    0,
    "Amylose is unbranched α-1,4-glucan; amylopectin also has α-1,6 branches.",
  ),
  class12Pyq(
    "chemistry",
    "biomolecules",
    "Cellulose contains",
    ["α-1,4 glycosidic linkages", "β-1,4 glycosidic linkages", "peptide bonds", "phosphodiester bonds"],
    1,
    "Cellulose is a linear β-1,4 polymer of D-glucose.",
  ),
  class12Pyq(
    "chemistry",
    "biomolecules",
    "Which of the following is a non-reducing sugar?",
    ["glucose", "maltose", "sucrose", "lactose"],
    2,
    "In sucrose both anomeric carbons are tied in the glycosidic bond, so it does not reduce Tollens'/Fehling's.",
  ),
  class12Pyq(
    "chemistry",
    "biomolecules",
    "α-Helix and β-pleated sheet are examples of the",
    [
      "primary structure of proteins",
      "secondary structure of proteins",
      "tertiary structure of proteins",
      "quaternary structure of proteins",
    ],
    1,
    "Secondary structure is the regular H-bonded folding of the polypeptide backbone.",
  ),
  class12Pyq(
    "chemistry",
    "biomolecules",
    "Enzymes are",
    ["biological catalysts (generally globular proteins)", "lipids", "nucleic acids only", "vitamins"],
    0,
    "Most enzymes are globular proteins that speed up biochemical reactions.",
  ),
  class12Pyq(
    "chemistry",
    "biomolecules",
    "In DNA, adenine pairs with",
    ["guanine", "cytosine", "thymine (two hydrogen bonds)", "uracil"],
    2,
    "A–T pairing uses two hydrogen bonds; G–C uses three.",
  ),
  class12Pyq(
    "chemistry",
    "biomolecules",
    "Deficiency of vitamin A causes",
    ["night blindness", "scurvy", "rickets", "beriberi"],
    0,
    "Vitamin A (retinol) is required for rhodopsin; deficiency causes night blindness.",
  ),
];

assertTwentyPerChapter(class12ChemistryQuestions, [
  "solutions",
  "electrochemistry",
  "chemical-kinetics",
  "the-d-and-f-block-elements",
  "coordination-compounds",
  "haloalkanes-and-haloarenes",
  "alcohols-phenols-and-ethers",
  "aldehydes-ketones-and-carboxylic-acids",
  "amines",
  "biomolecules",
]);
