import { assertTwentyPerChapter, cbsePyq, type PracticeQuestionSeed } from "./types";

export const class11MathematicsQuestions: PracticeQuestionSeed[] = [
  // 1. Sets
  cbsePyq("class-11", "mathematics", "sets", "If A = {1, 2, 3, 4} and B = {3, 4, 5, 6}, then A ∩ B is", ["{3, 4}", "{1, 2}", "{5, 6}", "{1, 2, 3, 4, 5, 6}"], 0, "The common elements of A and B are 3 and 4."),
  cbsePyq("class-11", "mathematics", "sets", "By De Morgan's law, (A ∪ B)′ equals", ["A′ ∪ B′", "A′ ∩ B′", "A ∩ B", "(A ∩ B)′"], 1, "The complement of a union is the intersection of the complements."),
  cbsePyq("class-11", "mathematics", "sets", "If n(A) = 12, n(B) = 15 and n(A ∩ B) = 7, then n(A ∪ B) is", ["20", "27", "19", "10"], 0, "n(A ∪ B) = n(A) + n(B) − n(A ∩ B) = 12 + 15 − 7 = 20."),
  cbsePyq("class-11", "mathematics", "sets", "The number of elements in the power set of {a, b, c} is", ["3", "6", "8", "9"], 2, "A set of 3 elements has 2³ = 8 subsets."),
  cbsePyq("class-11", "mathematics", "sets", "The empty set is a subset of", ["no set", "every set", "only infinite sets", "only itself"], 1, "∅ ⊆ A holds for every set A."),
  cbsePyq("class-11", "mathematics", "sets", "A − B equals", ["B − A", "A ∪ B", "A ∩ B′", "A′ ∩ B"], 2, "The difference consists of elements of A that are not in B, i.e. A ∩ B′."),
  cbsePyq("class-11", "mathematics", "sets", "If A ⊂ B, then A ∪ B equals", ["A", "B", "A ∩ B", "∅"], 1, "Union with a subset does not enlarge the larger set."),
  cbsePyq("class-11", "mathematics", "sets", "The number of subsets of a set with n elements is", ["n", "n²", "2n", "2ⁿ"], 3, "Each element may independently be included or excluded."),
  cbsePyq("class-11", "mathematics", "sets", "If U is the universal set, then A ∪ A′ equals", ["∅", "A", "U", "A′"], 2, "A set and its complement together make up the universal set."),
  cbsePyq("class-11", "mathematics", "sets", "If n(U) = 40 and n(A) = 25, then n(A′) is", ["15", "25", "40", "65"], 0, "n(A′) = n(U) − n(A) = 15."),
  cbsePyq("class-11", "mathematics", "sets", "Sets A and B are disjoint if and only if", ["A ∪ B = ∅", "A ∩ B = ∅", "A ⊂ B", "A = B"], 1, "Disjoint sets share no common element."),
  cbsePyq("class-11", "mathematics", "sets", "The set {x ∈ R : x² = 9} equals", ["{9}", "{3}", "{−3, 3}", "{−9, 9}"], 2, "The real solutions of x² = 9 are x = ±3."),
  cbsePyq("class-11", "mathematics", "sets", "If n(A) = 2 and n(B) = 3, then n(A × B) is", ["5", "6", "8", "9"], 1, "The Cartesian product has 2 × 3 = 6 ordered pairs."),
  cbsePyq("class-11", "mathematics", "sets", "If n(A) = 20, n(B) = 15, n(C) = 10, n(A ∩ B) = 8, n(B ∩ C) = 5, n(A ∩ C) = 4 and n(A ∩ B ∩ C) = 2, then n(A ∪ B ∪ C) is", ["30", "28", "32", "25"], 0, "20 + 15 + 10 − 8 − 5 − 4 + 2 = 30."),
  cbsePyq("class-11", "mathematics", "sets", "The interval (2, 5] ∩ [4, 7) equals", ["(2, 7)", "[4, 5]", "(4, 5]", "[2, 7)"], 1, "The overlap of (2, 5] and [4, 7) is the closed interval [4, 5]."),
  cbsePyq("class-11", "mathematics", "sets", "A ∩ ∅ equals", ["A", "U", "∅", "A′"], 2, "Intersection with the empty set is empty."),
  cbsePyq("class-11", "mathematics", "sets", "If A is the set of prime numbers less than 10, then A equals", ["{1, 2, 3, 5, 7}", "{2, 3, 5, 7}", "{2, 3, 5, 7, 9}", "{1, 3, 5, 7, 9}"], 1, "1 is not prime and 9 is not prime."),
  cbsePyq("class-11", "mathematics", "sets", "Two finite sets are equal if they have", ["the same number of elements", "exactly the same elements", "a non-empty intersection", "equal complements in different universes"], 1, "Set equality means they contain precisely the same members."),
  cbsePyq("class-11", "mathematics", "sets", "The number of elements in P(P(∅)) is", ["0", "1", "2", "4"], 2, "P(∅) = {∅} has one element, so its power set has 2¹ = 2 elements."),
  cbsePyq("class-11", "mathematics", "sets", "(A ∩ B) ∪ (A ∩ B′) equals", ["B", "A", "U", "∅"], 1, "The left side is A ∩ (B ∪ B′) = A ∩ U = A."),

  // 2. Relations and Functions
  cbsePyq("class-11", "mathematics", "relations-and-functions", "If n(A) = 3 and n(B) = 2, then n(A × B) is", ["5", "6", "8", "9"], 1, "There are 3 × 2 = 6 ordered pairs in the Cartesian product."),
  cbsePyq("class-11", "mathematics", "relations-and-functions", "The number of relations from a set of 2 elements to a set of 3 elements is", ["6", "8", "32", "64"], 3, "There are 6 ordered pairs, so 2⁶ = 64 possible relations."),
  cbsePyq("class-11", "mathematics", "relations-and-functions", "The domain of f(x) = √(x − 2) is", ["R", "[0, ∞)", "[2, ∞)", "(2, ∞)"], 2, "The expression under the square root is non-negative precisely when x ≥ 2."),
  cbsePyq("class-11", "mathematics", "relations-and-functions", "The domain of f(x) = 1/(x − 3) is", ["R", "R − {0}", "R − {3}", "[3, ∞)"], 2, "The denominator is zero at x = 3, so that point is excluded."),
  cbsePyq("class-11", "mathematics", "relations-and-functions", "The range of f : R → R given by f(x) = x² is", ["R", "(0, ∞)", "[0, ∞)", "(−∞, 0]"], 2, "Every square is non-negative, and every non-negative real is a square."),
  cbsePyq("class-11", "mathematics", "relations-and-functions", "The number of functions from a set of 3 elements to a set of 2 elements is", ["6", "8", "9", "5"], 1, "Each of 3 domain elements has 2 possible images, so 2³ = 8 functions."),
  cbsePyq("class-11", "mathematics", "relations-and-functions", "The identity function f(x) = x on R is", ["one-one but not onto", "onto but not one-one", "one-one and onto", "neither one-one nor onto"], 2, "Every real is the image of exactly one real."),
  cbsePyq("class-11", "mathematics", "relations-and-functions", "The range of the signum function is", ["{0, 1}", "{−1, 1}", "{−1, 0, 1}", "R"], 2, "sgn(x) takes only the three values −1, 0 and 1."),
  cbsePyq("class-11", "mathematics", "relations-and-functions", "The value of [2.7], where [x] denotes the greatest integer ≤ x, is", ["2", "3", "2.7", "0"], 0, "The greatest integer not exceeding 2.7 is 2."),
  cbsePyq("class-11", "mathematics", "relations-and-functions", "The function f(x) = |x| is", ["odd", "even", "neither even nor odd", "periodic"], 1, "|−x| = |x| for every real x."),
  cbsePyq("class-11", "mathematics", "relations-and-functions", "The domain of √(9 − x²) is", ["R", "[0, 3]", "[−3, 3]", "(−3, 3)"], 2, "9 − x² ≥ 0 if and only if |x| ≤ 3."),
  cbsePyq("class-11", "mathematics", "relations-and-functions", "If f(x) = 2x + 3, then f(2) equals", ["5", "7", "1", "4"], 1, "2(2) + 3 = 7."),
  cbsePyq("class-11", "mathematics", "relations-and-functions", "A relation from A to B is", ["an element of A × B", "a subset of A × B", "equal to A ∪ B", "a subset of A ∪ B"], 1, "By definition a relation is any subset of the Cartesian product."),
  cbsePyq("class-11", "mathematics", "relations-and-functions", "The number of one-one functions from {1, 2} to {a, b, c} is", ["3", "6", "8", "9"], 1, "P(3, 2) = 3 × 2 = 6 injections."),
  cbsePyq("class-11", "mathematics", "relations-and-functions", "A constant function f(x) = k has range", ["R", "{0}", "{k}", "[k, ∞)"], 2, "The only value attained is k."),
  cbsePyq("class-11", "mathematics", "relations-and-functions", "The domain of f(x) = x/(x² − 1) is", ["R", "R − {0}", "R − {1}", "R − {−1, 1}"], 3, "The denominator vanishes at x = ±1."),
  cbsePyq("class-11", "mathematics", "relations-and-functions", "If a set A has 3 elements, the number of relations on A is", ["9", "27", "256", "512"], 3, "A × A has 9 ordered pairs, so there are 2⁹ = 512 relations."),
  cbsePyq("class-11", "mathematics", "relations-and-functions", "The range of f(x) = cos x, x ∈ R, is", ["R", "[0, 1]", "[−1, 1]", "(0, π)"], 2, "Cosine attains every value in [−1, 1]."),
  cbsePyq("class-11", "mathematics", "relations-and-functions", "The function f(x) = x³ is", ["even", "odd", "neither even nor odd", "constant"], 1, "f(−x) = −x³ = −f(x)."),
  cbsePyq("class-11", "mathematics", "relations-and-functions", "If f(x) = x + 1 and g(x) = 2x, then (f ∘ g)(x) equals", ["2x + 2", "2x + 1", "2(x + 1)", "x + 2"], 1, "f(g(x)) = 2x + 1."),

  // 3. Trigonometric Functions
  cbsePyq("class-11", "mathematics", "trigonometric-functions", "sin² θ + cos² θ equals", ["0", "1", "2", "tan² θ"], 1, "This is the fundamental Pythagorean identity."),
  cbsePyq("class-11", "mathematics", "trigonometric-functions", "sin 2θ equals", ["2 sin θ", "2 cos θ", "2 sin θ cos θ", "sin² θ"], 2, "This is the double-angle formula for sine."),
  cbsePyq("class-11", "mathematics", "trigonometric-functions", "The general solution of sin x = 0 is", ["x = nπ", "x = 2nπ", "x = (2n + 1)π/2", "x = nπ/2"], 0, "Sine vanishes at every integer multiple of π."),
  cbsePyq("class-11", "mathematics", "trigonometric-functions", "The general solution of sin x = 1/2 is", ["x = nπ + π/6", "x = nπ + (−1)ⁿ (π/6)", "x = 2nπ + π/6", "x = nπ − π/6"], 1, "sin x = sin(π/6) gives x = nπ + (−1)ⁿ (π/6)."),
  cbsePyq("class-11", "mathematics", "trigonometric-functions", "The period of tan x is", ["π/2", "π", "2π", "4π"], 1, "Tangent repeats every π radians."),
  cbsePyq("class-11", "mathematics", "trigonometric-functions", "The range of the sine function is", ["R", "[0, 1]", "[−1, 1]", "(0, π)"], 2, "Sine attains every value in [−1, 1]."),
  cbsePyq("class-11", "mathematics", "trigonometric-functions", "sin 15° equals", ["(√6 + √2)/4", "(√6 − √2)/4", "(√3 − 1)/2", "1/2"], 1, "sin(45° − 30°) = (√6 − √2)/4."),
  cbsePyq("class-11", "mathematics", "trigonometric-functions", "cos(π/2 − x) equals", ["sin x", "−sin x", "cos x", "−cos x"], 0, "This is a standard cofunction identity."),
  cbsePyq("class-11", "mathematics", "trigonometric-functions", "tan(A + B) equals", ["(tan A + tan B)/(1 + tan A tan B)", "(tan A + tan B)/(1 − tan A tan B)", "tan A + tan B", "tan A tan B"], 1, "This is the addition formula for tangent (when defined)."),
  cbsePyq("class-11", "mathematics", "trigonometric-functions", "The maximum value of 3 sin x + 4 cos x is", ["3", "4", "5", "7"], 2, "The maximum of a sin x + b cos x is √(a² + b²) = 5."),
  cbsePyq("class-11", "mathematics", "trigonometric-functions", "cos 2θ equals", ["2 cos² θ", "1 − 2 sin² θ", "2 sin θ cos θ", "sin² θ − cos² θ"], 1, "One of the standard double-angle formulae for cosine."),
  cbsePyq("class-11", "mathematics", "trigonometric-functions", "The general solution of cos x = 0 is", ["x = nπ", "x = 2nπ", "x = (2n + 1)π/2", "x = nπ/2"], 2, "Cosine is zero at the odd multiples of π/2."),
  cbsePyq("class-11", "mathematics", "trigonometric-functions", "sin(−θ) equals", ["sin θ", "−sin θ", "cos θ", "−cos θ"], 1, "Sine is an odd function."),
  cbsePyq("class-11", "mathematics", "trigonometric-functions", "sin 75° equals", ["(√6 − √2)/4", "(√6 + √2)/4", "(√3 + 1)/2", "√3/2"], 1, "sin(45° + 30°) = (√6 + √2)/4."),
  cbsePyq("class-11", "mathematics", "trigonometric-functions", "If sin θ = 3/5 and θ is acute, then cos θ equals", ["4/5", "3/5", "5/4", "5/3"], 0, "cos θ = √(1 − 9/25) = 4/5."),
  cbsePyq("class-11", "mathematics", "trigonometric-functions", "The period of sin x is", ["π", "π/2", "2π", "4π"], 2, "Sine has fundamental period 2π."),
  cbsePyq("class-11", "mathematics", "trigonometric-functions", "1 + tan² θ equals", ["sin² θ", "cos² θ", "sec² θ", "cot² θ"], 2, "This is the Pythagorean identity involving tangent."),
  cbsePyq("class-11", "mathematics", "trigonometric-functions", "The principal solutions of sin x = √3/2 in [0, 2π) are", ["π/3 and 2π/3", "π/6 and 5π/6", "π/3 and 5π/3", "2π/3 and 4π/3"], 0, "Sine equals √3/2 at π/3 and in the second quadrant at 2π/3."),
  cbsePyq("class-11", "mathematics", "trigonometric-functions", "If cos x = cos α, then", ["x = nπ ± α", "x = 2nπ ± α", "x = nπ + (−1)ⁿ α", "x = 2nπ + α"], 1, "This is the general solution of the cosine equation."),
  cbsePyq("class-11", "mathematics", "trigonometric-functions", "2 sin A cos B equals", ["sin(A + B) + sin(A − B)", "sin(A + B) − sin(A − B)", "cos(A + B) + cos(A − B)", "2 sin A sin B"], 0, "This is a standard product-to-sum identity."),

  // 4. Complex Numbers and Quadratic Equations
  cbsePyq("class-11", "mathematics", "complex-numbers-and-quadratic-equations", "i² equals", ["1", "−1", "i", "−i"], 1, "By definition i = √(−1), so i² = −1."),
  cbsePyq("class-11", "mathematics", "complex-numbers-and-quadratic-equations", "The value of i¹⁰⁰ is", ["1", "−1", "i", "−i"], 0, "i⁴ = 1, so i¹⁰⁰ = (i⁴)²⁵ = 1."),
  cbsePyq("class-11", "mathematics", "complex-numbers-and-quadratic-equations", "If z = 3 + 4i, then |z| equals", ["3", "4", "5", "7"], 2, "|z| = √(9 + 16) = 5."),
  cbsePyq("class-11", "mathematics", "complex-numbers-and-quadratic-equations", "The conjugate of 2 − 3i is", ["−2 + 3i", "2 + 3i", "−2 − 3i", "3 − 2i"], 1, "Conjugation changes the sign of the imaginary part."),
  cbsePyq("class-11", "mathematics", "complex-numbers-and-quadratic-equations", "For any complex number z, z z̄ equals", ["0", "z²", "|z|", "|z|²"], 3, "A complex number times its conjugate is the square of its modulus."),
  cbsePyq("class-11", "mathematics", "complex-numbers-and-quadratic-equations", "The multiplicative inverse of a non-zero z is", ["z̄", "1/z̄", "z̄/|z|²", "|z|²/z̄"], 2, "1/z = z̄/|z|²."),
  cbsePyq("class-11", "mathematics", "complex-numbers-and-quadratic-equations", "arg(i) equals", ["0", "π/4", "π/2", "π"], 2, "i lies on the positive imaginary axis, so its argument is π/2."),
  cbsePyq("class-11", "mathematics", "complex-numbers-and-quadratic-equations", "|z₁ z₂| equals", ["|z₁| + |z₂|", "|z₁| |z₂|", "|z₁| − |z₂|", "|z₁|/|z₂|"], 1, "The modulus of a product is the product of the moduli."),
  cbsePyq("class-11", "mathematics", "complex-numbers-and-quadratic-equations", "The real part of (1 + i)² is", ["0", "1", "2", "−1"], 0, "(1 + i)² = 1 + 2i − 1 = 2i, which is purely imaginary."),
  cbsePyq("class-11", "mathematics", "complex-numbers-and-quadratic-equations", "The polar form of 1 + i is", ["√2 (cos π/4 + i sin π/4)", "√2 (cos π/2 + i sin π/2)", "2 (cos π/4 + i sin π/4)", "cos π/4 + i sin π/4"], 0, "|1 + i| = √2 and arg(1 + i) = π/4."),
  cbsePyq("class-11", "mathematics", "complex-numbers-and-quadratic-equations", "For ax² + bx + c = 0, the sum of the roots is", ["c/a", "−b/a", "b/a", "−c/a"], 1, "This is Vieta's formula for the sum of roots."),
  cbsePyq("class-11", "mathematics", "complex-numbers-and-quadratic-equations", "The discriminant of x² − 4x + 4 = 0 is", ["0", "4", "8", "16"], 0, "b² − 4ac = 16 − 16 = 0, so the roots are equal."),
  cbsePyq("class-11", "mathematics", "complex-numbers-and-quadratic-equations", "The roots of x² + 1 = 0 are", ["±1", "±i", "0 and 1", "1 and i"], 1, "x² = −1 gives x = ±i."),
  cbsePyq("class-11", "mathematics", "complex-numbers-and-quadratic-equations", "The product of the roots of 2x² − 3x + 5 = 0 is", ["−3/2", "3/2", "5/2", "−5/2"], 2, "Product of roots = c/a = 5/2."),
  cbsePyq("class-11", "mathematics", "complex-numbers-and-quadratic-equations", "If the roots of x² − 5x + k = 0 are equal, then k equals", ["5", "25", "25/4", "5/4"], 2, "Discriminant 25 − 4k = 0, so k = 25/4."),
  cbsePyq("class-11", "mathematics", "complex-numbers-and-quadratic-equations", "arg(z₁ z₂) equals", ["arg z₁ − arg z₂", "arg z₁ + arg z₂", "arg z₁ · arg z₂", "|z₁| |z₂|"], 1, "Arguments add under multiplication (modulo 2π)."),
  cbsePyq("class-11", "mathematics", "complex-numbers-and-quadratic-equations", "1/(1 + i) equals", ["(1 + i)/2", "(1 − i)/2", "1 − i", "1 + i"], 1, "Multiply numerator and denominator by the conjugate 1 − i."),
  cbsePyq("class-11", "mathematics", "complex-numbers-and-quadratic-equations", "The equation |z − 1| = 2 represents", ["a straight line", "a circle of radius 2 centred at (1, 0)", "a circle centred at the origin", "a single point"], 1, "It is the locus of points at distance 2 from 1 + 0i."),
  cbsePyq("class-11", "mathematics", "complex-numbers-and-quadratic-equations", "i³ equals", ["i", "−i", "1", "−1"], 1, "i³ = i² · i = −i."),
  cbsePyq("class-11", "mathematics", "complex-numbers-and-quadratic-equations", "If D > 0 for a quadratic with real coefficients, the roots are", ["equal", "complex conjugates", "real and distinct", "purely imaginary"], 2, "A positive discriminant gives two distinct real roots."),

  // 5. Linear Inequalities
  cbsePyq("class-11", "mathematics", "linear-inequalities", "The solution of 2x − 3 < 5 is", ["x < 4", "x > 4", "x < 1", "x > 1"], 0, "2x < 8, so x < 4."),
  cbsePyq("class-11", "mathematics", "linear-inequalities", "|x| < 3 is equivalent to", ["x < 3", "x > −3", "−3 < x < 3", "x ≤ −3 or x ≥ 3"], 2, "The distance from the origin is less than 3."),
  cbsePyq("class-11", "mathematics", "linear-inequalities", "|x| ≥ 2 is equivalent to", ["−2 ≤ x ≤ 2", "x ≤ −2 or x ≥ 2", "x > 2", "−2 < x < 2"], 1, "Points lying at distance at least 2 from the origin."),
  cbsePyq("class-11", "mathematics", "linear-inequalities", "The solution of x² − 5x + 6 < 0 is", ["x < 2", "x > 3", "2 < x < 3", "x < 2 or x > 3"], 2, "(x − 2)(x − 3) < 0 between the roots."),
  cbsePyq("class-11", "mathematics", "linear-inequalities", "The graphical solution of a linear inequality in two variables is", ["a line", "a half-plane", "a point", "a circle"], 1, "The corresponding line divides the plane into two half-planes."),
  cbsePyq("class-11", "mathematics", "linear-inequalities", "The solution of 3x + 2 ≥ 11 is", ["x ≥ 3", "x ≤ 3", "x ≥ 13/3", "x > 3"], 0, "3x ≥ 9, so x ≥ 3."),
  cbsePyq("class-11", "mathematics", "linear-inequalities", "The solution of −2 < 3x − 5 ≤ 7 is", ["[1, 4]", "(1, 4]", "[1, 4)", "(−1, 4]"], 1, "x > 1 from the left part and x ≤ 4 from the right part."),
  cbsePyq("class-11", "mathematics", "linear-inequalities", "If x > 0 and y > 0, the corresponding region is", ["the first quadrant", "the second quadrant", "the third quadrant", "the fourth quadrant"], 0, "Both coordinates are positive in the first quadrant."),
  cbsePyq("class-11", "mathematics", "linear-inequalities", "The inequality x + y < 1 represents", ["the line x + y = 1", "the half-plane below x + y = 1, excluding the line", "the half-plane above the line", "the first quadrant"], 1, "The strict inequality excludes the boundary line."),
  cbsePyq("class-11", "mathematics", "linear-inequalities", "|2x − 1| < 3 is equivalent to", ["−1 < x < 2", "−2 < x < 1", "0 < x < 2", "x < 2"], 0, "−3 < 2x − 1 < 3 simplifies to −1 < x < 2."),
  cbsePyq("class-11", "mathematics", "linear-inequalities", "The solution of 5x − 3 > 3x + 1 is", ["x > 2", "x < 2", "x > 1", "x < −2"], 0, "2x > 4, so x > 2."),
  cbsePyq("class-11", "mathematics", "linear-inequalities", "The solution set of x ≤ 2 on the number line is", ["an open ray to the left of 2", "a closed ray to the left of 2, including 2", "only the point 2", "all real numbers"], 1, "The endpoint 2 is included and the ray extends to −∞."),
  cbsePyq("class-11", "mathematics", "linear-inequalities", "The feasible region of x ≥ 0, y ≥ 0, x + y ≤ 1 is", ["an unbounded half-plane", "a closed triangle with vertices (0, 0), (1, 0) and (0, 1)", "a square", "empty"], 1, "These inequalities describe the closed unit simplex in the first quadrant."),
  cbsePyq("class-11", "mathematics", "linear-inequalities", "x² > 4 is equivalent to", ["|x| < 2", "x < −2 or x > 2", "−2 < x < 2", "x > 2"], 1, "|x| > 2."),
  cbsePyq("class-11", "mathematics", "linear-inequalities", "The solution of 1/x > 2 is", ["x > 1/2", "0 < x < 1/2", "x < 1/2", "x < 0"], 1, "For x > 0 one gets x < 1/2; if x < 0 then 1/x is negative."),
  cbsePyq("class-11", "mathematics", "linear-inequalities", "The inequality −x > 3 is equivalent to", ["x > −3", "x < −3", "x > 3", "x < 3"], 1, "Multiplying by −1 reverses the inequality."),
  cbsePyq("class-11", "mathematics", "linear-inequalities", "The solution of 4x + 3 ≤ 2x + 7 is", ["x ≤ 2", "x ≥ 2", "x < 2", "x ≤ 5"], 0, "2x ≤ 4, so x ≤ 2."),
  cbsePyq("class-11", "mathematics", "linear-inequalities", "|x − 3| ≤ 5 is equivalent to", ["−2 ≤ x ≤ 8", "−5 ≤ x ≤ 5", "x ≤ 8", "0 ≤ x ≤ 8"], 0, "−5 ≤ x − 3 ≤ 5 rearranges to −2 ≤ x ≤ 8."),
  cbsePyq("class-11", "mathematics", "linear-inequalities", "The solution set of 2x + y ≥ 6, x ≥ 0, y ≥ 0 is", ["a bounded triangle", "an unbounded closed region in the first quadrant", "a single point", "empty"], 1, "The half-plane is cut by the axes but remains unbounded."),
  cbsePyq("class-11", "mathematics", "linear-inequalities", "If a < b, then for every real c", ["a + c > b + c", "a + c < b + c", "ac < bc always", "a − c > b − c"], 1, "Adding the same real number preserves a strict inequality."),

  // 6. Permutations and Combinations
  cbsePyq("class-11", "mathematics", "permutations-and-combinations", "⁵P₂ equals", ["10", "20", "25", "5"], 1, "⁵P₂ = 5 × 4 = 20."),
  cbsePyq("class-11", "mathematics", "permutations-and-combinations", "ⁿCᵣ equals", ["n! / (n − r)!", "n! / r!", "n! / (r! (n − r)!)", "nʳ"], 2, "This is the formula for combinations."),
  cbsePyq("class-11", "mathematics", "permutations-and-combinations", "⁵C₂ equals", ["5", "10", "20", "15"], 1, "⁵C₂ = 5 × 4 / 2 = 10."),
  cbsePyq("class-11", "mathematics", "permutations-and-combinations", "ⁿCᵣ equals ⁿCₖ when k is", ["r + 1", "n − r", "n + r", "n"], 1, "Choosing r objects is the same as leaving out n − r of them."),
  cbsePyq("class-11", "mathematics", "permutations-and-combinations", "0! equals", ["0", "1", "undefined", "∞"], 1, "By convention 0! = 1."),
  cbsePyq("class-11", "mathematics", "permutations-and-combinations", "The number of permutations of n distinct objects is", ["n", "2ⁿ", "n!", "n²"], 2, "n positions can be filled in n! ways."),
  cbsePyq("class-11", "mathematics", "permutations-and-combinations", "The number of ways to arrange the letters of MATHS is", ["24", "60", "120", "720"], 2, "The five letters are distinct, so 5! = 120."),
  cbsePyq("class-11", "mathematics", "permutations-and-combinations", "The number of circular permutations of n distinct objects is", ["n!", "(n − 1)!", "(n + 1)!", "n"], 1, "Rotations are regarded as the same arrangement, leaving (n − 1)! ways."),
  cbsePyq("class-11", "mathematics", "permutations-and-combinations", "ⁿPᵣ equals", ["n! / r!", "n! / (n − r)!", "n! / (r! (n − r)!)", "(n − r)!"], 1, "This is the formula for permutations of r objects from n."),
  cbsePyq("class-11", "mathematics", "permutations-and-combinations", "The number of ways to choose a committee of 3 from 7 people is", ["21", "35", "210", "343"], 1, "⁷C₃ = 35."),
  cbsePyq("class-11", "mathematics", "permutations-and-combinations", "ⁿC₀ + ⁿC₁ + ⋯ + ⁿCₙ equals", ["n", "n!", "2ⁿ", "2n"], 2, "Put x = 1 in (1 + x)ⁿ."),
  cbsePyq("class-11", "mathematics", "permutations-and-combinations", "ⁿCᵣ + ⁿCᵣ₋₁ equals", ["ⁿCᵣ₊₁", "ⁿ⁺¹Cᵣ", "ⁿ⁻¹Cᵣ", "2 ⁿCᵣ"], 1, "This is Pascal's identity."),
  cbsePyq("class-11", "mathematics", "permutations-and-combinations", "The number of 3-letter words from {A, B, C, D, E} without repetition is", ["10", "60", "125", "15"], 1, "⁵P₃ = 5 × 4 × 3 = 60."),
  cbsePyq("class-11", "mathematics", "permutations-and-combinations", "If ⁿC₂ = 10, then n equals", ["4", "5", "10", "20"], 1, "n(n − 1)/2 = 10 implies n = 5."),
  cbsePyq("class-11", "mathematics", "permutations-and-combinations", "Five distinct people can sit in a row in", ["24", "60", "120", "20"], 2, "5! = 120 linear arrangements."),
  cbsePyq("class-11", "mathematics", "permutations-and-combinations", "Five distinct people can sit at a round table in", ["120", "24", "60", "5"], 1, "(5 − 1)! = 24 circular arrangements."),
  cbsePyq("class-11", "mathematics", "permutations-and-combinations", "¹⁰C₃ equals", ["120", "720", "30", "210"], 0, "10 × 9 × 8 / 6 = 120."),
  cbsePyq("class-11", "mathematics", "permutations-and-combinations", "The number of diagonals of a hexagon is", ["6", "9", "12", "15"], 1, "n(n − 3)/2 = 6 × 3 / 2 = 9."),
  cbsePyq("class-11", "mathematics", "permutations-and-combinations", "The number of distinct arrangements of the letters of MISSISSIPPI is", ["11!", "34650", "39916800", "11!/4!"], 1, "11! / (4! 4! 2!) = 34650."),
  cbsePyq("class-11", "mathematics", "permutations-and-combinations", "The number of ways to select at least one item from 4 distinct items is", ["4", "8", "15", "16"], 2, "2⁴ − 1 = 15, excluding the empty selection."),

  // 7. Binomial Theorem
  cbsePyq("class-11", "mathematics", "binomial-theorem", "The general term T_{r+1} in the expansion of (a + b)ⁿ is", ["C(n, r) aⁿ bʳ", "C(n, r) a^{n−r} bʳ", "C(n, r) aʳ bⁿ", "a^{n−r} bʳ"], 1, "This is the standard general-term formula."),
  cbsePyq("class-11", "mathematics", "binomial-theorem", "The expansion of (x + y)ⁿ contains", ["n terms", "n + 1 terms", "2n terms", "n − 1 terms"], 1, "The powers of y run from 0 through n."),
  cbsePyq("class-11", "mathematics", "binomial-theorem", "The middle term in the expansion of (x + a)^{2n} is", ["Tₙ", "T_{n+1}", "T_{2n}", "T_{n−1}"], 1, "There are 2n + 1 terms, so the middle term is the (n + 1)th."),
  cbsePyq("class-11", "mathematics", "binomial-theorem", "C(n, 0) + C(n, 1) + ⋯ + C(n, n) equals", ["n", "2ⁿ", "n!", "2n"], 1, "(1 + 1)ⁿ = 2ⁿ."),
  cbsePyq("class-11", "mathematics", "binomial-theorem", "The coefficient of x² in (1 + x)⁵ is", ["5", "10", "15", "20"], 1, "C(5, 2) = 10."),
  cbsePyq("class-11", "mathematics", "binomial-theorem", "The first two terms in the expansion of (1 + x)ⁿ are", ["1 + x", "1 + n x", "n + x", "1 + n"], 1, "The binomial series begins 1 + n x + ⋯."),
  cbsePyq("class-11", "mathematics", "binomial-theorem", "The 4th term in the expansion of (x + y)⁶ is", ["15 x⁴ y²", "20 x³ y³", "15 x² y⁴", "6 x⁵ y"], 1, "T₄ = C(6, 3) x³ y³ = 20 x³ y³."),
  cbsePyq("class-11", "mathematics", "binomial-theorem", "The sum of the coefficients of (1 + x)ⁿ is", ["n", "0", "2ⁿ", "1"], 2, "Substitute x = 1 in the expansion."),
  cbsePyq("class-11", "mathematics", "binomial-theorem", "C(n, 0) + C(n, 2) + C(n, 4) + ⋯ equals", ["2ⁿ", "2^{n−1}", "2^{n+1}", "n"], 1, "The even-indexed binomial coefficients sum to 2^{n−1}."),
  cbsePyq("class-11", "mathematics", "binomial-theorem", "The constant term in (x + 1/x)⁶ is", ["0", "15", "20", "6"], 2, "The exponent 6 − 2r vanishes when r = 3, and C(6, 3) = 20."),
  cbsePyq("class-11", "mathematics", "binomial-theorem", "The greatest binomial coefficient in (1 + x)⁸ is", ["C(8, 2)", "C(8, 3)", "C(8, 4)", "C(8, 8)"], 2, "For even n the largest coefficient is C(n, n/2) = C(8, 4)."),
  cbsePyq("class-11", "mathematics", "binomial-theorem", "(a + b)⁴ equals", ["a⁴ + b⁴", "a⁴ + 4a³b + 6a²b² + 4ab³ + b⁴", "a⁴ + 4a³b + 4ab³ + b⁴", "(a + b)(a³ + b³)"], 1, "This is the binomial expansion of degree 4."),
  cbsePyq("class-11", "mathematics", "binomial-theorem", "The coefficient of x³ in (1 + 2x)⁵ is", ["10", "40", "80", "160"], 2, "C(5, 3) · 2³ = 10 × 8 = 80."),
  cbsePyq("class-11", "mathematics", "binomial-theorem", "The expansion of (1 + x)⁹ has two middle terms, namely", ["T₄ and T₅", "T₅ and T₆", "T₉ and T₁₀", "T₁ and T₁₀"], 1, "There are 10 terms, so the 5th and 6th are the middle terms."),
  cbsePyq("class-11", "mathematics", "binomial-theorem", "¹¹C₄ equals", ["330", "165", "792", "11"], 0, "11 × 10 × 9 × 8 / 24 = 330."),
  cbsePyq("class-11", "mathematics", "binomial-theorem", "Σ C(n, r) xʳ equals", ["(1 − x)ⁿ", "(1 + x)ⁿ", "xⁿ", "n!"], 1, "This is the binomial theorem for (1 + x)ⁿ."),
  cbsePyq("class-11", "mathematics", "binomial-theorem", "The term independent of x in (√x − 1/√x)¹⁰ is", ["252", "−252", "210", "0"], 1, "The exponent vanishes when r = 5, giving C(10, 5)(−1)⁵ = −252."),
  cbsePyq("class-11", "mathematics", "binomial-theorem", "The last term of (2x − y)⁵ is", ["32 x⁵", "−y⁵", "y⁵", "−32 x⁵"], 1, "(−y)⁵ = −y⁵."),
  cbsePyq("class-11", "mathematics", "binomial-theorem", "2ⁿ equals", ["(1 − 1)ⁿ", "(1 + 1)ⁿ", "n²", "2n"], 1, "Put x = 1 in (1 + x)ⁿ."),
  cbsePyq("class-11", "mathematics", "binomial-theorem", "The ratio T_{r+1}/T_r in the expansion of (1 + x)ⁿ equals", ["(n − r + 1)x / r", "r x / (n − r)", "n / r", "x"], 0, "C(n, r)/C(n, r − 1) = (n − r + 1)/r, then multiply by x."),

  // 8. Sequences and Series
  cbsePyq("class-11", "mathematics", "sequences-and-series", "The nth term of an AP with first term a and common difference d is", ["a + n d", "a + (n − 1)d", "a n d", "a − (n − 1)d"], 1, "This is the standard formula for an arithmetic progression."),
  cbsePyq("class-11", "mathematics", "sequences-and-series", "The sum of n terms of an AP is", ["n(a + d)", "n/2 [2a + (n − 1)d]", "n a d", "a + n d"], 1, "This is the arithmetic-series formula."),
  cbsePyq("class-11", "mathematics", "sequences-and-series", "If a, b, c are in AP, then", ["2b = a + c", "2a = b + c", "b² = a c", "a + b = c"], 0, "Equal common differences give 2b = a + c."),
  cbsePyq("class-11", "mathematics", "sequences-and-series", "The nth term of a GP with first term a and common ratio r is", ["a rⁿ", "a r^{n−1}", "a + (n − 1)r", "a n r"], 1, "This is the standard geometric-term formula."),
  cbsePyq("class-11", "mathematics", "sequences-and-series", "The sum of an infinite GP with |r| < 1 is", ["a r", "a / (1 − r)", "a / (1 + r)", "a(1 − r)"], 1, "This is the sum of an infinite geometric series."),
  cbsePyq("class-11", "mathematics", "sequences-and-series", "1 + 2 + ⋯ + n equals", ["n²", "n(n + 1)/2", "n(n − 1)/2", "2n"], 1, "This is the sum of the first n natural numbers."),
  cbsePyq("class-11", "mathematics", "sequences-and-series", "For positive a and b, the AM–GM inequality states that", ["(a + b)/2 ≤ √(ab)", "(a + b)/2 ≥ √(ab)", "ab ≥ a + b", "a + b ≥ ab"], 1, "The arithmetic mean is at least the geometric mean."),
  cbsePyq("class-11", "mathematics", "sequences-and-series", "The 3rd term of the AP 5, 8, 11, … is", ["8", "11", "14", "5"], 1, "a + 2d = 5 + 6 = 11."),
  cbsePyq("class-11", "mathematics", "sequences-and-series", "The sum of the first n odd natural numbers is", ["n(n + 1)", "n²", "2n", "n(n − 1)"], 1, "1 + 3 + ⋯ + (2n − 1) = n²."),
  cbsePyq("class-11", "mathematics", "sequences-and-series", "If a, b, c are in GP, then", ["2b = a + c", "b² = a c", "a² = b c", "b = a + c"], 1, "Equal common ratios give b² = ac."),
  cbsePyq("class-11", "mathematics", "sequences-and-series", "The sum of n terms of a GP with r ≠ 1 is", ["a(rⁿ − 1)/(r − 1)", "a rⁿ", "n a r", "a/(1 − r)"], 0, "This is the finite geometric-series formula."),
  cbsePyq("class-11", "mathematics", "sequences-and-series", "The 5th term of the GP 3, 6, 12, … is", ["24", "36", "48", "96"], 2, "a r⁴ = 3 × 2⁴ = 48."),
  cbsePyq("class-11", "mathematics", "sequences-and-series", "If n arithmetic means are inserted between a and b, the common difference is", ["(b − a)/n", "(b − a)/(n + 1)", "(b + a)/(n + 1)", "b − a"], 1, "There are n + 1 equal steps from a to b."),
  cbsePyq("class-11", "mathematics", "sequences-and-series", "The sum of the first 10 natural numbers is", ["45", "50", "55", "100"], 2, "10 × 11 / 2 = 55."),
  cbsePyq("class-11", "mathematics", "sequences-and-series", "The geometric mean of 4 and 9 is", ["6", "6.5", "36", "13/2"], 0, "√(4 × 9) = 6."),
  cbsePyq("class-11", "mathematics", "sequences-and-series", "If the 4th term of an AP is 10 and the 7th term is 19, then the first term is", ["1", "3", "4", "7"], 0, "a + 3d = 10 and a + 6d = 19 give d = 3 and a = 1."),
  cbsePyq("class-11", "mathematics", "sequences-and-series", "The sum of the infinite GP 1 + 1/2 + 1/4 + ⋯ is", ["1", "2", "3/2", "∞"], 1, "a/(1 − r) = 1 / (1/2) = 2."),
  cbsePyq("class-11", "mathematics", "sequences-and-series", "The 10th term of the AP 2, 7, 12, … is", ["42", "47", "52", "45"], 1, "a = 2, d = 5, so a + 9d = 2 + 45 = 47."),
  cbsePyq("class-11", "mathematics", "sequences-and-series", "The harmonic mean of positive numbers a and b is", ["(a + b)/2", "√(ab)", "2ab/(a + b)", "ab/(a + b)"], 2, "It is the reciprocal of the AM of the reciprocals."),
  cbsePyq("class-11", "mathematics", "sequences-and-series", "1³ + 2³ + ⋯ + n³ equals", ["[n(n + 1)/2]²", "n²(n + 1)²", "n(n + 1)(2n + 1)/6", "n³"], 0, "The sum of cubes is the square of the sum of the first n naturals."),

  // 9. Straight Lines
  cbsePyq("class-11", "mathematics", "straight-lines", "The slope of the line through (1, 2) and (3, 6) is", ["1", "2", "3", "4"], 1, "(6 − 2)/(3 − 1) = 2."),
  cbsePyq("class-11", "mathematics", "straight-lines", "The slope of the x-axis is", ["1", "0", "undefined", "−1"], 1, "A horizontal line has slope 0."),
  cbsePyq("class-11", "mathematics", "straight-lines", "The slope of the y-axis is", ["0", "1", "undefined", "−1"], 2, "A vertical line has undefined slope."),
  cbsePyq("class-11", "mathematics", "straight-lines", "Two lines with slopes m₁ and m₂ are perpendicular if and only if", ["m₁ = m₂", "m₁ m₂ = 1", "m₁ m₂ = −1", "m₁ + m₂ = 0"], 2, "The product of the slopes is −1 whenever both slopes exist."),
  cbsePyq("class-11", "mathematics", "straight-lines", "Two parallel lines have", ["product of slopes equal to −1", "equal slopes", "slopes adding to 1", "undefined slopes"], 1, "Parallel (non-vertical) lines have the same slope."),
  cbsePyq("class-11", "mathematics", "straight-lines", "In y = mx + c, the constant c is the", ["x-intercept", "y-intercept", "origin", "distance from the origin"], 1, "This is slope–intercept form."),
  cbsePyq("class-11", "mathematics", "straight-lines", "The intercept form of a line is", ["y = mx + c", "x/a + y/b = 1", "(y − y₁) = m(x − x₁)", "ax + by = 0"], 1, "Here a and b are the intercepts on the axes."),
  cbsePyq("class-11", "mathematics", "straight-lines", "The distance from (0, 0) to the line 3x + 4y − 10 = 0 is", ["1", "2", "10", "5"], 1, "|−10|/5 = 2."),
  cbsePyq("class-11", "mathematics", "straight-lines", "The slope of the line 2x + 3y − 6 = 0 is", ["2/3", "−2/3", "3/2", "−3/2"], 1, "Rewriting as y = −(2/3)x + 2 gives slope −2/3."),
  cbsePyq("class-11", "mathematics", "straight-lines", "If θ is the angle between two lines of slopes m₁ and m₂, then tan θ equals", ["(m₁ + m₂)/(1 − m₁ m₂)", "|(m₁ − m₂)/(1 + m₁ m₂)|", "m₁ m₂", "m₁ − m₂"], 1, "This is the formula for the tangent of the included angle."),
  cbsePyq("class-11", "mathematics", "straight-lines", "The line through (2, 3) with slope 1 has equation", ["y = x + 1", "y = x − 1", "y = x + 5", "y = 2x"], 0, "y − 3 = 1(x − 2) simplifies to y = x + 1."),
  cbsePyq("class-11", "mathematics", "straight-lines", "The lines 2x − y + 3 = 0 and 4x − 2y + 7 = 0 are", ["perpendicular", "coincident", "parallel", "intersecting at right angles"], 2, "Both have slope 2, and the intercepts differ, so they are distinct parallel lines."),
  cbsePyq("class-11", "mathematics", "straight-lines", "The x-intercept of 2x + 3y = 6 is", ["2", "3", "6", "1"], 1, "Putting y = 0 gives 2x = 6, so x = 3."),
  cbsePyq("class-11", "mathematics", "straight-lines", "The distance between the parallel lines x + y + 1 = 0 and x + y − 3 = 0 is", ["2", "4", "2√2", "√2"], 2, "|1 − (−3)|/√2 = 4/√2 = 2√2."),
  cbsePyq("class-11", "mathematics", "straight-lines", "The midpoint of the segment joining (2, 4) and (4, 8) is", ["(3, 6)", "(6, 12)", "(2, 4)", "(1, 2)"], 0, "Average the corresponding coordinates."),
  cbsePyq("class-11", "mathematics", "straight-lines", "A line perpendicular to a line of slope 2 has slope", ["2", "1/2", "−1/2", "−2"], 2, "The negative reciprocal of 2 is −1/2."),
  cbsePyq("class-11", "mathematics", "straight-lines", "The point (1, 2) lies on the line", ["2x − y = 0", "x + y = 0", "x − y = 2", "2x + y = 1"], 0, "2(1) − 2 = 0."),
  cbsePyq("class-11", "mathematics", "straight-lines", "The equation of the line joining (0, 0) and (2, 2) is", ["y = 2x", "y = x", "x = 2", "y = 2"], 1, "The slope is 1 and the line passes through the origin."),
  cbsePyq("class-11", "mathematics", "straight-lines", "A line making an angle of 45° with the positive x-axis has slope", ["0", "1", "√3", "1/√3"], 1, "tan 45° = 1."),
  cbsePyq("class-11", "mathematics", "straight-lines", "The equation ax + by + c = 0, with a and b not both zero, represents", ["a circle", "a straight line", "a parabola", "a pair of points"], 1, "This is the general equation of a line in the plane."),

  // 10. Conic Sections
  cbsePyq("class-11", "mathematics", "conic-sections", "The eccentricity of a parabola is", ["0", "1", "less than 1", "greater than 1"], 1, "By definition a parabola has eccentricity 1."),
  cbsePyq("class-11", "mathematics", "conic-sections", "The eccentricity of an ellipse is", ["always 0", "always 1", "less than 1", "greater than 1"], 2, "For an ellipse, 0 ≤ e < 1."),
  cbsePyq("class-11", "mathematics", "conic-sections", "The eccentricity of a hyperbola is", ["0", "1", "less than 1", "greater than 1"], 3, "A hyperbola has e > 1."),
  cbsePyq("class-11", "mathematics", "conic-sections", "The eccentricity of a circle is", ["0", "1", "2", "undefined"], 0, "A circle is an ellipse with e = 0."),
  cbsePyq("class-11", "mathematics", "conic-sections", "For the parabola y² = 4ax, the focus is", ["(0, a)", "(a, 0)", "(−a, 0)", "(2a, 0)"], 1, "The standard focus of y² = 4ax is (a, 0)."),
  cbsePyq("class-11", "mathematics", "conic-sections", "The length of the latus rectum of y² = 4ax is", ["a", "2a", "4a", "a/2"], 2, "The latus rectum of this parabola has length 4a."),
  cbsePyq("class-11", "mathematics", "conic-sections", "The directrix of y² = 4ax is", ["x = a", "x = −a", "y = a", "y = −a"], 1, "The directrix is the line x = −a."),
  cbsePyq("class-11", "mathematics", "conic-sections", "For the ellipse x²/a² + y²/b² = 1 with a > b, the eccentricity e equals", ["√(1 + b²/a²)", "√(1 − b²/a²)", "b/a", "a/b"], 1, "This is the standard formula for the eccentricity of an ellipse."),
  cbsePyq("class-11", "mathematics", "conic-sections", "The foci of the ellipse x²/a² + y²/b² = 1 (a > b) are", ["(±a, 0)", "(±ae, 0)", "(0, ±ae)", "(±e, 0)"], 1, "The foci lie on the major axis at (±ae, 0)."),
  cbsePyq("class-11", "mathematics", "conic-sections", "The length of the latus rectum of the ellipse x²/a² + y²/b² = 1 is", ["2a", "2b", "2b²/a", "2a²/b"], 2, "The standard length is 2b²/a."),
  cbsePyq("class-11", "mathematics", "conic-sections", "For the hyperbola x²/a² − y²/b² = 1, the eccentricity e equals", ["√(1 − b²/a²)", "√(1 + b²/a²)", "1", "b/a"], 1, "This is the standard formula for a hyperbola."),
  cbsePyq("class-11", "mathematics", "conic-sections", "The circle x² + y² = r² has", ["centre (r, 0) and radius r", "centre the origin and radius r", "centre the origin and radius r²", "centre (r, r)"], 1, "This is the standard equation of a circle centred at the origin."),
  cbsePyq("class-11", "mathematics", "conic-sections", "The vertex of the parabola y² = 4ax is", ["(a, 0)", "(0, 0)", "(−a, 0)", "(0, a)"], 1, "The vertex is at the origin."),
  cbsePyq("class-11", "mathematics", "conic-sections", "For the ellipse x²/16 + y²/9 = 1, the eccentricity is", ["1/4", "√7 / 4", "3/4", "4/5"], 1, "a = 4, b = 3, so e = √(1 − 9/16) = √7 / 4."),
  cbsePyq("class-11", "mathematics", "conic-sections", "The parabola x² = 4ay opens", ["to the right", "to the left", "upwards", "downwards"], 2, "Its axis is the positive y-axis."),
  cbsePyq("class-11", "mathematics", "conic-sections", "The length of the latus rectum of x²/a² − y²/b² = 1 is", ["2a", "2b", "2b²/a", "2a²/b"], 2, "The latus rectum of this hyperbola has length 2b²/a."),
  cbsePyq("class-11", "mathematics", "conic-sections", "For the parabola y² = 16x, the focus is", ["(4, 0)", "(16, 0)", "(2, 0)", "(8, 0)"], 0, "4a = 16 so a = 4, and the focus is (4, 0)."),
  cbsePyq("class-11", "mathematics", "conic-sections", "The locus of a point equidistant from a fixed point and a fixed line is", ["a circle", "an ellipse", "a parabola", "a hyperbola"], 2, "This is the focus–directrix definition of a parabola."),
  cbsePyq("class-11", "mathematics", "conic-sections", "The length of the major axis of x²/25 + y²/9 = 1 is", ["5", "10", "3", "6"], 1, "a = 5, so the major axis has length 2a = 10."),
  cbsePyq("class-11", "mathematics", "conic-sections", "The asymptotes of x²/a² − y²/b² = 1 are", ["y = ± (a/b) x", "y = ± (b/a) x", "x = ± a", "y = ± b"], 1, "The pair of asymptotes is y = ± (b/a) x."),

  // 11. Introduction to Three Dimensional Geometry
  cbsePyq("class-11", "mathematics", "introduction-to-three-dimensional-geometry", "The distance between the points (1, 2, 3) and (4, 6, 3) is", ["5", "6", "7", "4"], 0, "√[(4 − 1)² + (6 − 2)² + (3 − 3)²] = √(9 + 16) = 5."),
  cbsePyq("class-11", "mathematics", "introduction-to-three-dimensional-geometry", "The coordinates of the origin in three-dimensional space are", ["(1, 1, 1)", "(0, 0, 0)", "(1, 0, 0)", "(0, 1, 0)"], 1, "The origin is the intersection of the three coordinate axes."),
  cbsePyq("class-11", "mathematics", "introduction-to-three-dimensional-geometry", "The number of octants in three-dimensional space is", ["4", "6", "8", "2"], 2, "The three coordinate planes divide space into eight octants."),
  cbsePyq("class-11", "mathematics", "introduction-to-three-dimensional-geometry", "The distance of the point (1, 2, 2) from the origin is", ["3", "5", "√5", "1"], 0, "√(1 + 4 + 4) = 3."),
  cbsePyq("class-11", "mathematics", "introduction-to-three-dimensional-geometry", "The direction cosines l, m, n of a line satisfy", ["l + m + n = 1", "l² + m² + n² = 1", "l m n = 1", "l² + m² = n²"], 1, "They are the components of a unit vector along the line."),
  cbsePyq("class-11", "mathematics", "introduction-to-three-dimensional-geometry", "If the direction ratios of a line are 2, 3, 6, then its direction cosines are", ["2, 3, 6", "2/7, 3/7, 6/7", "2/6, 3/6, 1", "1, 1, 1"], 1, "Divide by √(4 + 9 + 36) = 7."),
  cbsePyq("class-11", "mathematics", "introduction-to-three-dimensional-geometry", "The midpoint of the segment joining (2, 0, 0) and (0, 2, 0) is", ["(1, 1, 0)", "(2, 2, 0)", "(1, 0, 0)", "(0, 1, 1)"], 0, "Average the corresponding coordinates."),
  cbsePyq("class-11", "mathematics", "introduction-to-three-dimensional-geometry", "The xy-plane consists of all points with", ["x = 0", "y = 0", "z = 0", "x = y = 0"], 2, "Every point of the xy-plane has vanishing z-coordinate."),
  cbsePyq("class-11", "mathematics", "introduction-to-three-dimensional-geometry", "The distance between (1, 1, 1) and (1, 1, 2) is", ["0", "1", "√2", "3"], 1, "Only the z-coordinate changes, and it changes by 1."),
  cbsePyq("class-11", "mathematics", "introduction-to-three-dimensional-geometry", "The point (−1, 2, −3) lies in octant", ["I", "II", "V", "VI"], 3, "The sign pattern (−, +, −) belongs to the sixth octant."),
  cbsePyq("class-11", "mathematics", "introduction-to-three-dimensional-geometry", "The three coordinate axes are", ["pairwise parallel", "pairwise perpendicular", "coplanar only", "coincident"], 1, "They meet at right angles at the origin."),
  cbsePyq("class-11", "mathematics", "introduction-to-three-dimensional-geometry", "The distance between (x₁, y₁, z₁) and (x₂, y₂, z₂) is", ["|x₂ − x₁| + |y₂ − y₁| + |z₂ − z₁|", "√[(x₂ − x₁)² + (y₂ − y₁)² + (z₂ − z₁)²]", "(x₂ − x₁)(y₂ − y₁)(z₂ − z₁)", "max(|x₂ − x₁|, |y₂ − y₁|, |z₂ − z₁|)"], 1, "This is the three-dimensional distance formula."),
  cbsePyq("class-11", "mathematics", "introduction-to-three-dimensional-geometry", "The coordinates of a point on the y-axis are of the form", ["(x, 0, 0)", "(0, y, 0)", "(0, 0, z)", "(x, y, 0)"], 1, "On the y-axis one has x = 0 and z = 0."),
  cbsePyq("class-11", "mathematics", "introduction-to-three-dimensional-geometry", "Direction ratios of the x-axis may be taken as", ["1, 0, 0", "0, 1, 0", "0, 0, 1", "1, 1, 1"], 0, "The x-axis is parallel to the vector ⟨1, 0, 0⟩."),
  cbsePyq("class-11", "mathematics", "introduction-to-three-dimensional-geometry", "If a line makes angles α, β, γ with the coordinate axes, then", ["cos α + cos β + cos γ = 1", "cos² α + cos² β + cos² γ = 1", "sin² α + sin² β + sin² γ = 1", "α + β + γ = 180°"], 1, "These cosines are the direction cosines of the line."),
  cbsePyq("class-11", "mathematics", "introduction-to-three-dimensional-geometry", "The equation of the yz-plane is", ["y = 0", "z = 0", "x = 0", "x = y"], 2, "Every point of the yz-plane has x-coordinate 0."),
  cbsePyq("class-11", "mathematics", "introduction-to-three-dimensional-geometry", "The distance between (0, 0, 0) and (2, 3, 6) is", ["6", "7", "11", "√11"], 1, "√(4 + 9 + 36) = √49 = 7."),
  cbsePyq("class-11", "mathematics", "introduction-to-three-dimensional-geometry", "Direction cosines of a given line are unique up to", ["an arbitrary scalar multiple", "sign (the two opposite senses of the line)", "adding 1 to each cosine", "nothing; they are always unique"], 1, "l, m, n and −l, −m, −n describe the two directions along the same line."),
  cbsePyq("class-11", "mathematics", "introduction-to-three-dimensional-geometry", "The point which divides the join of (1, 0, 0) and (0, 1, 0) in the ratio 1 : 1 is", ["(1, 1, 0)", "(1/2, 1/2, 0)", "(0, 0, 0)", "(1, 0, 1)"], 1, "The section formula with equal weights gives the midpoint."),
  cbsePyq("class-11", "mathematics", "introduction-to-three-dimensional-geometry", "If l, m, n are direction cosines of a line, they may themselves be used as", ["direction ratios", "coordinates of a unique point", "a unit normal to every plane", "octant numbers"], 0, "Direction cosines are direction ratios of unit length."),

  // 12. Limits and Derivatives
  cbsePyq("class-11", "mathematics", "limits-and-derivatives", "lim_{x→0} (sin x)/x equals", ["0", "1", "∞", "x"], 1, "This is a standard trigonometric limit."),
  cbsePyq("class-11", "mathematics", "limits-and-derivatives", "lim_{x→0} (1 − cos x)/x² equals", ["0", "1", "1/2", "2"], 2, "Using 1 − cos x = 2 sin²(x/2) the limit is 1/2."),
  cbsePyq("class-11", "mathematics", "limits-and-derivatives", "lim_{x→0} (tan x)/x equals", ["0", "1", "∞", "tan x"], 1, "(sin x / x)/cos x → 1/1 = 1."),
  cbsePyq("class-11", "mathematics", "limits-and-derivatives", "The derivative of f at x from first principles is", ["lim_{h→0} [f(x + h) + f(x)]/h", "lim_{h→0} [f(x + h) − f(x)]/h", "f(x + h) − f(x)", "lim_{h→∞} [f(x + h) − f(x)]/h"], 1, "This is the definition of f′(x)."),
  cbsePyq("class-11", "mathematics", "limits-and-derivatives", "d/dx (xⁿ) equals", ["x^{n−1}", "n x^{n−1}", "n xⁿ", "n x"], 1, "This is the power rule."),
  cbsePyq("class-11", "mathematics", "limits-and-derivatives", "d/dx (sin x) equals", ["−cos x", "cos x", "sin x", "−sin x"], 1, "The derivative of sine is cosine."),
  cbsePyq("class-11", "mathematics", "limits-and-derivatives", "The derivative of a constant function is", ["1", "the constant itself", "0", "x"], 2, "A constant does not change with x."),
  cbsePyq("class-11", "mathematics", "limits-and-derivatives", "lim_{x→a} (xⁿ − aⁿ)/(x − a) equals", ["n aⁿ", "n a^{n−1}", "aⁿ", "0"], 1, "This limit is the derivative of xⁿ at x = a."),
  cbsePyq("class-11", "mathematics", "limits-and-derivatives", "The derivative of x² obtained from first principles is", ["x", "2x", "2", "x²"], 1, "[(x + h)² − x²]/h = 2x + h, which tends to 2x."),
  cbsePyq("class-11", "mathematics", "limits-and-derivatives", "lim_{x→0} (1 − cos x)/x equals", ["1", "1/2", "0", "∞"], 2, "The numerator is of order x², so the ratio tends to 0."),
  cbsePyq("class-11", "mathematics", "limits-and-derivatives", "d/dx (cos x) equals", ["sin x", "−sin x", "cos x", "−cos x"], 1, "The derivative of cosine is −sine."),
  cbsePyq("class-11", "mathematics", "limits-and-derivatives", "d/dx (x³) equals", ["3x", "3x²", "x²", "3"], 1, "By the power rule the derivative is 3x²."),
  cbsePyq("class-11", "mathematics", "limits-and-derivatives", "lim_{x→∞} 1/x equals", ["1", "∞", "0", "−1"], 2, "The reciprocal of x vanishes as x tends to infinity."),
  cbsePyq("class-11", "mathematics", "limits-and-derivatives", "If u and v are differentiable, then (uv)′ equals", ["u′ v′", "u′ v + u v′", "u v", "u′ + v′"], 1, "This is the product rule."),
  cbsePyq("class-11", "mathematics", "limits-and-derivatives", "d/dx (2x + 3) equals", ["2x", "5", "2", "3"], 2, "The derivative of a linear polynomial is its slope."),
  cbsePyq("class-11", "mathematics", "limits-and-derivatives", "lim_{x→1} (x² − 1)/(x − 1) equals", ["0", "1", "2", "undefined"], 2, "Factor as (x − 1)(x + 1)/(x − 1) → 2."),
  cbsePyq("class-11", "mathematics", "limits-and-derivatives", "The derivative of sin x at x = 0 is", ["0", "1", "−1", "π"], 1, "cos 0 = 1."),
  cbsePyq("class-11", "mathematics", "limits-and-derivatives", "lim_{x→0} (sin 5x)/x equals", ["1", "5", "1/5", "0"], 1, "5 · (sin 5x)/(5x) tends to 5."),
  cbsePyq("class-11", "mathematics", "limits-and-derivatives", "d/dx (tan x) equals", ["sec x", "sec² x", "−sec² x", "cot x"], 1, "The derivative of tangent is sec² x."),
  cbsePyq("class-11", "mathematics", "limits-and-derivatives", "If f(x) = x² + 1, then f′(x) equals", ["2x + 1", "2x", "x", "1"], 1, "The derivative of x² is 2x and the constant vanishes."),

  // 13. Statistics
  cbsePyq("class-11", "mathematics", "statistics", "The mean of 1, 2, 3, 4, 5 is", ["3", "4", "2.5", "15"], 0, "The sum is 15, so the mean is 15/5 = 3."),
  cbsePyq("class-11", "mathematics", "statistics", "The variance of 1, 2, 3, 4, 5 (divisor n) is", ["1", "2", "√2", "10"], 1, "Σ(x − 3)² = 10, so the variance is 10/5 = 2."),
  cbsePyq("class-11", "mathematics", "statistics", "The standard deviation is", ["the square of the variance", "the square root of the variance", "the mean", "the range"], 1, "σ = √(variance)."),
  cbsePyq("class-11", "mathematics", "statistics", "Two groups of sizes 10 and 15 have means 20 and 30. The combined mean is", ["25", "26", "24", "50"], 1, "(10 × 20 + 15 × 30)/25 = 650/25 = 26."),
  cbsePyq("class-11", "mathematics", "statistics", "The median of 3, 5, 7, 9, 11 is", ["5", "7", "9", "8"], 1, "For an odd number of observations the median is the middle value."),
  cbsePyq("class-11", "mathematics", "statistics", "The mode of a data set is", ["the middle value", "the average", "the most frequent value", "the largest value"], 2, "Mode is the observation with the highest frequency."),
  cbsePyq("class-11", "mathematics", "statistics", "For the data 2, 2, 3, 4, 4, 4, 5 the mode is", ["2", "3", "4", "5"], 2, "The value 4 occurs three times, more often than any other."),
  cbsePyq("class-11", "mathematics", "statistics", "The mean of the first n natural numbers is", ["n/2", "(n + 1)/2", "n", "n(n + 1)/2"], 1, "[n(n + 1)/2]/n = (n + 1)/2."),
  cbsePyq("class-11", "mathematics", "statistics", "The coefficient of variation is", ["σ x̄", "(σ / x̄) × 100", "x̄ / σ", "σ − x̄"], 1, "CV is the percentage of the standard deviation relative to the mean."),
  cbsePyq("class-11", "mathematics", "statistics", "If the mean is 10 and the standard deviation is 2, then the CV is", ["5%", "20%", "12%", "2%"], 1, "(2/10) × 100 = 20%."),
  cbsePyq("class-11", "mathematics", "statistics", "The sum of the deviations of observations from their mean is", ["the variance", "0", "the standard deviation", "n"], 1, "Σ(xᵢ − x̄) = 0 identically."),
  cbsePyq("class-11", "mathematics", "statistics", "Variance is always", ["positive", "negative", "non-negative", "equal to the mean"], 2, "Variance is a mean of squared deviations, hence ≥ 0."),
  cbsePyq("class-11", "mathematics", "statistics", "The mean of 10, 20, 30 is", ["15", "20", "30", "60"], 1, "60/3 = 20."),
  cbsePyq("class-11", "mathematics", "statistics", "If each observation is increased by 5, then", ["the mean is unchanged", "the mean increases by 5 and the variance is unchanged", "both mean and variance increase by 5", "the variance increases by 25"], 1, "A constant shift changes the mean but not the spread."),
  cbsePyq("class-11", "mathematics", "statistics", "If each observation is multiplied by 2, the variance is multiplied by", ["2", "4", "1/2", "1"], 1, "Var(kX) = k² Var(X), so the factor is 4."),
  cbsePyq("class-11", "mathematics", "statistics", "The median of 2, 4, 6, 8 is", ["4", "5", "6", "4.5"], 1, "The average of the two central values 4 and 6 is 5."),
  cbsePyq("class-11", "mathematics", "statistics", "The range of a data set is", ["max + min", "max − min", "max / min", "the standard deviation"], 1, "Range is the difference of the extreme observations."),
  cbsePyq("class-11", "mathematics", "statistics", "For a frequency distribution the mean is", ["Σ xᵢ", "Σ fᵢ xᵢ / Σ fᵢ", "Σ fᵢ / Σ xᵢ", "the mode"], 1, "The mean is the frequency-weighted average of the class marks."),
  cbsePyq("class-11", "mathematics", "statistics", "The empirical relation connecting mean, median and mode is", ["Mode = 2 Median − 3 Mean", "Mode = 3 Median − 2 Mean", "Mean = 3 Median − 2 Mode", "Mode = Median + Mean"], 1, "This is Karl Pearson's approximate relation."),
  cbsePyq("class-11", "mathematics", "statistics", "A measure of dispersion that uses every observation is", ["the range", "the standard deviation", "the mode", "the median"], 1, "The standard deviation (and the variance) involve all data values."),

  // 14. Probability
  cbsePyq("class-11", "mathematics", "probability", "For a fair coin, P(head) is", ["0", "1", "1/2", "1/3"], 2, "The two faces are equally likely."),
  cbsePyq("class-11", "mathematics", "probability", "For a fair die, P(getting 6) is", ["1/2", "1/6", "1", "0"], 1, "One favourable face out of six equally likely faces."),
  cbsePyq("class-11", "mathematics", "probability", "P(A′) equals", ["P(A)", "1 − P(A)", "1 + P(A)", "0"], 1, "This is the complement rule."),
  cbsePyq("class-11", "mathematics", "probability", "When two fair coins are tossed, P(two heads) is", ["1/2", "1/3", "1/4", "1"], 2, "HH is one of the four equally likely outcomes."),
  cbsePyq("class-11", "mathematics", "probability", "P(an even number) on a fair die is", ["1/6", "1/3", "1/2", "2/3"], 2, "The faces 2, 4 and 6 are even."),
  cbsePyq("class-11", "mathematics", "probability", "From a pack of 52 cards, P(an ace) is", ["1/13", "1/52", "4/13", "1/4"], 0, "There are 4 aces in 52 cards, so 4/52 = 1/13."),
  cbsePyq("class-11", "mathematics", "probability", "If A and B are mutually exclusive, then P(A ∪ B) equals", ["P(A) P(B)", "P(A) + P(B)", "P(A) − P(B)", "0"], 1, "Mutually exclusive events have empty intersection, so probabilities add."),
  cbsePyq("class-11", "mathematics", "probability", "The sample space of a throw of two dice has", ["12", "6", "36", "18"], 2, "There are 6 × 6 = 36 ordered pairs."),
  cbsePyq("class-11", "mathematics", "probability", "P(sum = 7) when two fair dice are thrown is", ["1/6", "1/12", "7/36", "1/36"], 0, "The six pairs (1, 6), (2, 5), (3, 4), (4, 3), (5, 2), (6, 1) give 6/36 = 1/6."),
  cbsePyq("class-11", "mathematics", "probability", "In general, P(A ∪ B) equals", ["P(A) + P(B)", "P(A) + P(B) − P(A ∩ B)", "P(A ∩ B)", "P(A) P(B)"], 1, "This is the addition theorem for two events."),
  cbsePyq("class-11", "mathematics", "probability", "The probability of an impossible event is", ["1", "1/2", "0", "−1"], 2, "An impossible event has no favourable outcome."),
  cbsePyq("class-11", "mathematics", "probability", "The probability of a sure event is", ["0", "1/2", "1", "2"], 2, "A sure event is the whole sample space."),
  cbsePyq("class-11", "mathematics", "probability", "P(a prime number) on a fair die is", ["1/6", "1/3", "1/2", "2/3"], 2, "The prime faces are 2, 3 and 5."),
  cbsePyq("class-11", "mathematics", "probability", "A bag contains 3 red and 2 white balls. P(drawing a red ball) is", ["2/5", "3/5", "1/2", "1"], 1, "There are 3 red balls out of 5."),
  cbsePyq("class-11", "mathematics", "probability", "P(king of hearts) from a 52-card pack is", ["1/13", "1/4", "1/52", "1/12"], 2, "Exactly one card in the pack is the king of hearts."),
  cbsePyq("class-11", "mathematics", "probability", "P(a number greater than 4) on a fair die is", ["1/6", "1/3", "1/2", "2/3"], 1, "The favourable faces are 5 and 6, so 2/6 = 1/3."),
  cbsePyq("class-11", "mathematics", "probability", "Complementary events A and A′ satisfy", ["P(A) + P(A′) = 0", "P(A) + P(A′) = 1", "A ∩ A′ ≠ ∅", "P(A) = P(A′) always"], 1, "They partition the sample space."),
  cbsePyq("class-11", "mathematics", "probability", "If P(A) = 0.3, P(B) = 0.4 and P(A ∩ B) = 0.1, then P(A ∪ B) is", ["0.6", "0.8", "0.12", "0.7"], 0, "0.3 + 0.4 − 0.1 = 0.6."),
  cbsePyq("class-11", "mathematics", "probability", "A coin tossed three times has sample space of size", ["3", "6", "8", "9"], 2, "Each toss has 2 outcomes, so 2³ = 8."),
  cbsePyq("class-11", "mathematics", "probability", "P(at least one head) in two tosses of a fair coin is", ["1/4", "1/2", "3/4", "1"], 2, "1 − P(TT) = 1 − 1/4 = 3/4."),
];

assertTwentyPerChapter(class11MathematicsQuestions, [
  "sets",
  "relations-and-functions",
  "trigonometric-functions",
  "complex-numbers-and-quadratic-equations",
  "linear-inequalities",
  "permutations-and-combinations",
  "binomial-theorem",
  "sequences-and-series",
  "straight-lines",
  "conic-sections",
  "introduction-to-three-dimensional-geometry",
  "limits-and-derivatives",
  "statistics",
  "probability",
]);
