import { assertTwentyPerChapter, cbsePyq, type PracticeQuestionSeed } from "./types";

const unitsAndMeasurements: PracticeQuestionSeed[] = [
  cbsePyq(
    "class-11",
    "physics",
    "units-and-measurements",
    "The number of significant figures in 0.007 m² is",
    ["1", "2", "3", "4"],
    0,
    "Leading zeros after the decimal are not significant; 0.007 has one significant figure.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "units-and-measurements",
    "The dimensional formula of Planck's constant h is",
    ["[ML²T⁻¹]", "[MLT⁻¹]", "[ML²T⁻²]", "[ML⁻¹T⁻¹]"],
    0,
    "From E = hν, [h] = [E]/[ν] = [ML²T⁻²]/[T⁻¹] = [ML²T⁻¹].",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "units-and-measurements",
    "Which pair of physical quantities has the same dimensions?",
    ["impulse and force", "impulse and linear momentum", "power and momentum", "force and energy"],
    1,
    "Impulse = Δp, so both have dimensions [MLT⁻¹].",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "units-and-measurements",
    "The dimensional formula of torque is",
    ["[ML²T⁻²]", "[MLT⁻²]", "[ML²T⁻¹]", "[ML⁻¹T⁻²]"],
    0,
    "τ = r × F, so [τ] = [L][MLT⁻²] = [ML²T⁻²] (same as work, but a different quantity).",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "units-and-measurements",
    "If the error in measuring the radius of a sphere is 2%, the percentage error in its volume is",
    ["2%", "4%", "6%", "8%"],
    2,
    "V ∝ r³, so ΔV/V = 3 Δr/r = 6%.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "units-and-measurements",
    "The SI unit of solid angle is",
    ["degree", "radian", "steradian", "candela"],
    2,
    "Solid angle is measured in steradian (sr); plane angle is in radian.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "units-and-measurements",
    "Which pair has the same dimensions?",
    ["work and torque", "force and work", "momentum and power", "stress and energy"],
    0,
    "Both work and torque have [ML²T⁻²], though they are physically distinct.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "units-and-measurements",
    "The number of significant figures in 2.3080 is",
    ["3", "4", "5", "6"],
    2,
    "Trailing zeros after a decimal point are significant, so 2.3080 has five.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "units-and-measurements",
    "The dimensional formula of the universal gravitational constant G is",
    ["[M⁻¹L³T⁻²]", "[ML³T⁻²]", "[M⁻¹L²T⁻²]", "[ML⁻¹T⁻²]"],
    0,
    "From F = GMm/r², [G] = [FL²/M²] = [M⁻¹L³T⁻²].",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "units-and-measurements",
    "A vernier caliper has 1 MSD = 1 mm and 10 VSD = 9 mm. Its least count is",
    ["0.01 mm", "0.1 mm", "1 mm", "0.001 mm"],
    1,
    "Least count = 1 MSD − 1 VSD = 1.0 − 0.9 = 0.1 mm.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "units-and-measurements",
    "Percentage errors in a and b are 2% and 3%. The percentage error in a²b is",
    ["5%", "7%", "8%", "12%"],
    1,
    "Δ(a²b)/(a²b) = 2(Δa/a) + Δb/b = 4% + 3% = 7%.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "units-and-measurements",
    "Which of the following is a dimensionless quantity?",
    ["strain", "stress", "Young's modulus", "pressure"],
    0,
    "Strain = ΔL/L is a ratio of lengths and is dimensionless.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "units-and-measurements",
    "The dimensional formula of the coefficient of viscosity is",
    ["[ML⁻¹T⁻¹]", "[MLT⁻¹]", "[ML⁻¹T⁻²]", "[MT⁻²]"],
    0,
    "From F = ηA dv/dx, [η] = [MLT⁻²]/([L²][T⁻¹]) = [ML⁻¹T⁻¹].",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "units-and-measurements",
    "If x = at + bt², where x is in metres and t in seconds, the dimensions of b are",
    ["[LT⁻²]", "[LT⁻¹]", "[L]", "[T⁻²]"],
    0,
    "bt² must have dimensions of length, so [b] = [L]/[T²] = [LT⁻²].",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "units-and-measurements",
    "The number of significant figures in 6.320 × 10³ is",
    ["1", "2", "3", "4"],
    3,
    "All digits in 6.320 are significant; scientific notation does not drop trailing zeros after the decimal.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "units-and-measurements",
    "Which physical quantity has the dimensional formula [ML⁻¹T⁻²]?",
    ["energy", "force", "pressure", "momentum"],
    2,
    "Pressure = force/area → [MLT⁻²]/[L²] = [ML⁻¹T⁻²] (also stress, Young's modulus).",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "units-and-measurements",
    "In the parallax method, the distance of a nearby star is obtained from",
    ["the stellar parallax angle and the radius of Earth's orbit", "the star's colour only", "gravitational red shift", "the Doppler effect of sound"],
    0,
    "d = b/θ, where b is the baseline (Earth's orbital radius) and θ is the parallax angle.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "units-and-measurements",
    "The dimensions of angular momentum are the same as those of",
    ["Planck's constant", "linear momentum", "energy", "force"],
    0,
    "L = mvr → [ML²T⁻¹], which is also [h] from E = hν.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "units-and-measurements",
    "A product 2.5 × 1.25 should be reported with",
    ["2 significant figures", "3 significant figures", "4 significant figures", "5 significant figures"],
    0,
    "The factor 2.5 has two significant figures, which limits the product.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "units-and-measurements",
    "The dimensional formula [M⁰L⁰T⁰] corresponds to",
    ["strain", "force", "velocity", "acceleration"],
    0,
    "Strain (and plane/solid angle, refractive index) is dimensionless: [M⁰L⁰T⁰].",
  ),
];

const motionInAStraightLine: PracticeQuestionSeed[] = [
  cbsePyq(
    "class-11",
    "physics",
    "motion-in-a-straight-line",
    "The area under a velocity–time graph represents",
    ["acceleration", "displacement", "jerk", "force"],
    1,
    "Δx = ∫ v dt, which is the area under the v–t curve.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "motion-in-a-straight-line",
    "The slope of a velocity–time graph gives",
    ["displacement", "acceleration", "speed", "distance"],
    1,
    "a = dv/dt, so the slope of v versus t is acceleration.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "motion-in-a-straight-line",
    "For uniformly accelerated motion starting from rest, displacement is proportional to",
    ["t", "t²", "t³", "1/t"],
    1,
    "s = (1/2)at² with u = 0, so s ∝ t².",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "motion-in-a-straight-line",
    "A body thrown vertically upward has, at the highest point,",
    ["maximum velocity", "zero acceleration", "zero velocity but acceleration g downward", "zero velocity and zero acceleration"],
    2,
    "v = 0 at the top, but gravity still acts, so a = g downward.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "motion-in-a-straight-line",
    "Average velocity equals instantaneous velocity throughout when the motion is",
    ["uniform (constant velocity)", "uniformly accelerated", "along a curved path", "starting from rest only"],
    0,
    "If v is constant, average velocity over any interval equals that same v.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "motion-in-a-straight-line",
    "Two trains 120 m and 80 m long move toward each other at 10 m s⁻¹ and 20 m s⁻¹. Time to cross is",
    ["4 s", "6.67 s", "10 s", "20 s"],
    1,
    "Relative speed = 30 m s⁻¹; distance = 200 m; t = 200/30 ≈ 6.67 s.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "motion-in-a-straight-line",
    "If v = 4t + 3 (SI units), the acceleration is",
    ["4 m s⁻² (constant)", "3 m s⁻²", "4t m s⁻²", "zero"],
    0,
    "a = dv/dt = 4 m s⁻², independent of t.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "motion-in-a-straight-line",
    "A particle goes from x = 2 m to x = 8 m in 2 s. Its average velocity is",
    ["3 m s⁻¹", "4 m s⁻¹", "5 m s⁻¹", "6 m s⁻¹"],
    0,
    "v_av = Δx/Δt = (8 − 2)/2 = 3 m s⁻¹.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "motion-in-a-straight-line",
    "Instantaneous velocity is defined as",
    ["Δx/Δt for a large interval", "lim Δt→0 (Δx/Δt)", "total distance / total time", "acceleration × time always"],
    1,
    "v = dx/dt is the limit of average velocity as Δt → 0.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "motion-in-a-straight-line",
    "A straight line parallel to the time axis on a v–t graph means",
    ["constant acceleration", "constant velocity", "zero velocity", "increasing speed"],
    1,
    "v does not change with t, so motion is uniform.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "motion-in-a-straight-line",
    "The relative velocity of A with respect to B (collinear motion) is",
    ["v_A + v_B", "v_A − v_B", "v_B − v_A always as a scalar only", "v_A · v_B"],
    1,
    "v_AB = v_A − v_B (vector subtraction).",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "motion-in-a-straight-line",
    "A car accelerates from rest at 2 m s⁻² for 5 s. Distance travelled is",
    ["10 m", "25 m", "50 m", "5 m"],
    1,
    "s = (1/2)at² = (1/2)×2×25 = 25 m.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "motion-in-a-straight-line",
    "If a body covers equal distances in equal time intervals along a straight line in one direction, it has",
    ["uniform velocity", "uniform acceleration that is non-zero", "variable speed", "zero displacement"],
    0,
    "Equal displacements in equal times, same direction ⇒ constant velocity.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "motion-in-a-straight-line",
    "From v² = u² + 2as, if u = 0 then v equals",
    ["√(2as)", "2as", "as", "s/(2a)"],
    0,
    "v² = 2as ⇒ v = √(2as) (taking the appropriate sign).",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "motion-in-a-straight-line",
    "A particle has v = 2t + 3 (SI) and x = 0 at t = 0. Displacement in the first 2 s is",
    ["10 m", "7 m", "4 m", "14 m"],
    0,
    "x = ∫₀² (2t + 3) dt = [t² + 3t]₀² = 4 + 6 = 10 m.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "motion-in-a-straight-line",
    "A freely falling body from rest covers in the nth second a distance",
    ["g(n − 1/2)", "gn", "g(n + 1/2)", "(1/2)gn²"],
    0,
    "s_nth = u + a(n − 1/2) = g(n − 1/2) = (g/2)(2n − 1).",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "motion-in-a-straight-line",
    "A straight-line displacement–time graph inclined to the t-axis represents",
    ["uniform acceleration", "uniform velocity", "rest", "non-uniform speed"],
    1,
    "Constant slope dx/dt means constant velocity.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "motion-in-a-straight-line",
    "Cars A and B start from the same point: v_A = 40 km h⁻¹ east, v_B = 30 km h⁻¹ west. Velocity of A relative to B is",
    ["10 km h⁻¹ east", "70 km h⁻¹ east", "70 km h⁻¹ west", "10 km h⁻¹ west"],
    1,
    "v_AB = 40 − (−30) = 70 km h⁻¹ due east.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "motion-in-a-straight-line",
    "Acceleration is the time rate of change of",
    ["distance", "displacement", "velocity", "speed only"],
    2,
    "a = dv/dt; it is the derivative of the velocity vector.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "motion-in-a-straight-line",
    "A body moving at 10 m s⁻¹ is brought to rest in 5 s. The magnitude of retardation is",
    ["2 m s⁻²", "5 m s⁻²", "50 m s⁻²", "0.5 m s⁻²"],
    0,
    "a = (0 − 10)/5 = −2 m s⁻²; retardation is 2 m s⁻².",
  ),
];

const motionInAPlane: PracticeQuestionSeed[] = [
  cbsePyq(
    "class-11",
    "physics",
    "motion-in-a-plane",
    "For a given speed, the horizontal range of a projectile is maximum when the angle of projection is",
    ["30°", "45°", "60°", "90°"],
    1,
    "R = u² sin 2θ / g is maximum when 2θ = 90°, i.e. θ = 45°.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "motion-in-a-plane",
    "Projectiles launched at complementary angles with the same speed have",
    ["the same time of flight", "the same maximum height", "the same horizontal range", "zero range"],
    2,
    "sin 2θ = sin 2(90° − θ), so R(θ) = R(90° − θ).",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "motion-in-a-plane",
    "In projectile motion (no air resistance), the horizontal component of velocity",
    ["decreases uniformly", "increases uniformly", "remains constant", "is zero at the top"],
    2,
    "No horizontal acceleration, so u_x = u cos θ stays constant.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "motion-in-a-plane",
    "Time of flight of a projectile on horizontal ground is",
    ["u sin θ / g", "2u sin θ / g", "u² sin 2θ / g", "u cos θ / g"],
    1,
    "Vertical displacement 0 ⇒ T = 2u sin θ / g.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "motion-in-a-plane",
    "Maximum height of a projectile is",
    ["u² sin²θ / (2g)", "u² sin²θ / g", "u² sin 2θ / g", "2u sin θ / g"],
    0,
    "From v_y² = 0 at the top: H = u² sin²θ / (2g).",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "motion-in-a-plane",
    "Centripetal acceleration of a particle in uniform circular motion of speed v and radius r is",
    ["v/r toward the centre", "v²/r toward the centre", "vr away from the centre", "zero"],
    1,
    "a_c = v²/r = ω²r, radially inward.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "motion-in-a-plane",
    "In uniform circular motion",
    ["speed and velocity are both constant", "velocity is constant but speed changes", "speed is constant but velocity changes", "acceleration is zero"],
    2,
    "Speed is constant; direction of v changes, so velocity and centripetal acceleration are non-zero.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "motion-in-a-plane",
    "Two vectors of equal magnitude have maximum resultant when the angle between them is",
    ["0°", "90°", "120°", "180°"],
    0,
    "|A + B| = 2A cos(θ/2) is largest for θ = 0°.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "motion-in-a-plane",
    "A man walks in rain with velocity v_m. If rain falls vertically with v_r, the relative velocity of rain w.r.t. the man is",
    ["v_r − v_m (vector)", "v_r + v_m always vertically", "v_m only", "zero"],
    0,
    "v_rain,man = v_rain − v_man; rain appears to come from the front.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "motion-in-a-plane",
    "At the highest point of a projectile, the velocity is",
    ["zero", "u sin θ vertical", "u cos θ horizontal", "u"],
    2,
    "v_y = 0 at the top; v_x = u cos θ remains.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "motion-in-a-plane",
    "The trajectory of a projectile is",
    ["y = x tan θ − (gx²)/(2u² cos²θ)", "y = x tan θ + gx²", "a circle", "a straight line at θ"],
    0,
    "Eliminating t from x = (u cos θ)t and y = (u sin θ)t − (1/2)gt² gives a parabola.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "motion-in-a-plane",
    "Angular speed ω is related to time period T by",
    ["ω = 2πT", "ω = 2π/T", "ω = T/2π", "ω = π/T"],
    1,
    "One revolution is 2π rad in time T, so ω = 2π/T.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "motion-in-a-plane",
    "If a particle has tangential acceleration a_t and centripetal acceleration a_c, the magnitude of total acceleration is",
    ["a_t + a_c", "√(a_t² + a_c²)", "a_t − a_c", "a_c only"],
    1,
    "a_t ⟂ a_c, so a = √(a_t² + a_c²).",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "motion-in-a-plane",
    "The scalar (dot) product A · B equals",
    ["AB sin θ", "AB cos θ", "A + B", "AB"],
    1,
    "A · B = AB cos θ; it is a scalar.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "motion-in-a-plane",
    "The magnitude of A × B is",
    ["AB cos θ", "AB sin θ", "AB", "zero always"],
    1,
    "|A × B| = AB sin θ, direction by the right-hand rule.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "motion-in-a-plane",
    "The acceleration of a projectile at every point of its trajectory (no air) is",
    ["zero at the top", "g downward", "along the velocity", "u²/r toward the launch point"],
    1,
    "The only acceleration is gravity, g vertically downward, throughout.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "motion-in-a-plane",
    "For a banked road of radius r (no friction), the banking angle θ satisfies",
    ["tan θ = v²/(rg)", "tan θ = rg/v²", "sin θ = v²/rg", "θ = v²/rg"],
    0,
    "Horizontal component of normal provides centripetal force: tan θ = v²/(rg).",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "motion-in-a-plane",
    "Displacement is a",
    ["scalar equal to path length", "vector from initial to final position", "always positive", "the same as distance"],
    1,
    "Displacement is the shortest directed interval from start to end.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "motion-in-a-plane",
    "Time period of uniform circular motion of radius r and speed v is",
    ["2πr/v", "v/(2πr)", "2πv/r", "r/v"],
    0,
    "Circumference 2πr is covered at speed v, so T = 2πr/v.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "motion-in-a-plane",
    "If |A + B| = |A − B|, the angle between A and B is",
    ["0°", "60°", "90°", "180°"],
    2,
    "|A+B|² = |A−B|² ⇒ 4 A·B = 0 ⇒ A ⟂ B.",
  ),
];

const lawsOfMotion: PracticeQuestionSeed[] = [
  cbsePyq(
    "class-11",
    "physics",
    "laws-of-motion",
    "Newton's first law of motion defines the concept of",
    ["force as ma only", "inertia", "momentum conservation in explosions only", "energy"],
    1,
    "The first law is the law of inertia: a body remains in its state unless acted on by a net external force.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "laws-of-motion",
    "Newton's second law can be written as",
    ["F = mv", "F = dp/dt", "F = m/a", "F = dx/dt"],
    1,
    "F_net = dp/dt; for constant mass this is F = ma.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "laws-of-motion",
    "Impulse of a force equals",
    ["force × acceleration", "change in momentum", "change in kinetic energy", "mass × velocity²"],
    1,
    "J = ∫ F dt = Δp.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "laws-of-motion",
    "Linear momentum of a system is conserved when",
    ["kinetic energy is conserved", "the net external force is zero", "friction is present", "mass is variable"],
    1,
    "From F_ext = dP/dt, P is constant if F_ext = 0.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "laws-of-motion",
    "The kinetic friction on a body sliding on a surface of normal reaction N is",
    ["μ_s N", "μ_k N", "always mg", "zero"],
    1,
    "f_k = μ_k N, opposite to the relative sliding velocity.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "laws-of-motion",
    "Static friction is",
    ["always μ_s N", "self-adjusting up to a maximum μ_s N", "independent of the applied force", "always less than kinetic friction"],
    1,
    "f_s ≤ μ_s N; it matches the applied force until limiting friction.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "laws-of-motion",
    "The angle of repose α is related to the coefficient of static friction by",
    ["tan α = μ_s", "sin α = μ_s", "cos α = μ_s", "α = μ_s"],
    0,
    "At impending slide on an incline, mg sin α = μ_s mg cos α ⇒ tan α = μ_s.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "laws-of-motion",
    "Apparent weight of a person of mass m in a lift accelerating upward with a is",
    ["mg", "m(g + a)", "m(g − a)", "zero"],
    1,
    "N − mg = ma ⇒ N = m(g + a).",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "laws-of-motion",
    "A gun of mass M fires a bullet of mass m with speed v. Recoil speed of the gun is",
    ["Mv/m", "mv/M", "v", "(M + m)v/M"],
    1,
    "Momentum conservation: Mv_g + mv = 0 ⇒ v_g = −(m/M)v.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "laws-of-motion",
    "Action and reaction forces (Newton's third law)",
    ["act on the same body and cancel", "act on different bodies and do not cancel as a net force on one body", "are unequal in magnitude", "exist only in contact"],
    1,
    "They are equal, opposite, and act on two different bodies.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "laws-of-motion",
    "Inertia of a body is measured by its",
    ["velocity", "mass", "acceleration", "momentum only"],
    1,
    "Mass is the quantitative measure of inertia.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "laws-of-motion",
    "In a non-inertial frame accelerating with a, a pseudo force on mass m is",
    ["ma in the direction of a", "−ma (opposite to the frame acceleration)", "mg", "zero"],
    1,
    "F_pseudo = −ma_frame, so Newton's laws can be used in that frame.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "laws-of-motion",
    "A 2 kg body has acceleration 3 m s⁻². The net force on it is",
    ["1.5 N", "5 N", "6 N", "0.67 N"],
    2,
    "F = ma = 2 × 3 = 6 N.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "laws-of-motion",
    "In an Atwood machine with masses m1 > m2, the acceleration of the system is",
    ["(m1 + m2)g / (m1 − m2)", "(m1 − m2)g / (m1 + m2)", "g", "(m1/m2)g"],
    1,
    "From Newton's laws on both masses, a = (m1 − m2)g / (m1 + m2).",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "laws-of-motion",
    "Minimum horizontal force to start a mass m on a rough horizontal floor (coefficient μ_s) is",
    ["μ_s mg", "μ_k mg", "mg", "μ_s m"],
    0,
    "Limiting friction is μ_s N = μ_s mg.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "laws-of-motion",
    "Rocket propulsion is based on",
    ["conservation of energy only", "conservation of linear momentum", "Bernoulli's principle", "Pascal's law"],
    1,
    "Exhaust gases carry momentum backward; the rocket gains equal forward momentum.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "laws-of-motion",
    "Newton's third law states that",
    ["F = ma", "to every action there is an equal and opposite reaction", "P is conserved always", "inertia depends on speed"],
    1,
    "Forces occur in equal and opposite pairs between two interacting bodies.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "laws-of-motion",
    "Linear momentum is a",
    ["scalar", "vector", "dimensionless quantity", "tensor of rank 0 only"],
    1,
    "p = mv is a vector in the direction of velocity.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "laws-of-motion",
    "When a lift is in free fall, the apparent weight of a person inside is",
    ["mg", "2mg", "zero", "infinite"],
    2,
    "a = g downward ⇒ N = m(g − g) = 0 (weightlessness).",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "laws-of-motion",
    "Friction always acts",
    ["in the direction of motion", "opposite to the relative motion or its tendency", "normal to the surface only", "independent of the surface"],
    1,
    "Friction opposes relative slipping (or the tendency to slip) between surfaces.",
  ),
];

const workEnergyAndPower: PracticeQuestionSeed[] = [
  cbsePyq(
    "class-11",
    "physics",
    "work-energy-and-power",
    "Work done by a constant force F for displacement s is",
    ["Fs", "F × s always as magnitudes only", "F · s = Fs cos θ", "F/s"],
    2,
    "W = F · s = Fs cos θ, a scalar.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "work-energy-and-power",
    "The work–energy theorem states that the net work done on a particle equals",
    ["change in potential energy", "change in kinetic energy", "change in momentum", "force × time"],
    1,
    "W_net = ΔK = K_f − K_i.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "work-energy-and-power",
    "Kinetic energy of a particle of mass m and speed v is",
    ["mv", "mv²", "(1/2)mv²", "m/v²"],
    2,
    "K = (1/2)mv².",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "work-energy-and-power",
    "Elastic potential energy stored in a spring of stiffness k stretched by x is",
    ["kx", "(1/2)kx²", "kx²", "(1/2)kx"],
    1,
    "U = (1/2)kx², from W = ∫ kx dx.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "work-energy-and-power",
    "Work done by a conservative force is",
    ["always positive", "path-dependent", "independent of path and equal to −ΔU", "zero only if F = 0"],
    2,
    "W_c = −ΔU; it depends only on initial and final positions.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "work-energy-and-power",
    "Instantaneous power delivered by a force is",
    ["F / v", "F · v", "F × v magnitude only as energy", "mv"],
    1,
    "P = dW/dt = F · v.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "work-energy-and-power",
    "1 kWh is equal to",
    ["3.6 × 10³ J", "3.6 × 10⁶ J", "10³ J", "1 J"],
    1,
    "1 kWh = 1000 W × 3600 s = 3.6 × 10⁶ J.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "work-energy-and-power",
    "Gravitational potential energy near Earth (taking U = 0 at ground) of mass m at height h is",
    ["mgh", "−mgh", "(1/2)mgh", "mg/h"],
    0,
    "U = mgh for h ≪ R, with the usual ground reference.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "work-energy-and-power",
    "In a perfectly elastic collision",
    ["only momentum is conserved", "only kinetic energy is conserved", "both momentum and kinetic energy are conserved", "neither is conserved"],
    2,
    "Elastic: K conserved and, with no external force, p conserved.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "work-energy-and-power",
    "In a perfectly inelastic collision the two bodies",
    ["bounce with the same speed", "stick together after collision", "lose all momentum", "gain kinetic energy"],
    1,
    "They move as one mass; K is not conserved (some energy is dissipated).",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "work-energy-and-power",
    "Work done by the centripetal force in uniform circular motion is",
    ["maximum", "mv²/r", "zero", "negative"],
    2,
    "F_c is perpendicular to displacement (along the tangent), so W = 0.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "work-energy-and-power",
    "If force is perpendicular to displacement, work done is",
    ["Fs", "maximum", "zero", "negative"],
    2,
    "cos 90° = 0 ⇒ W = 0.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "work-energy-and-power",
    "Potential energy can be defined for",
    ["friction", "viscous drag", "conservative forces", "all forces"],
    2,
    "U exists only when work is path-independent (conservative F).",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "work-energy-and-power",
    "Mechanical energy is conserved if",
    ["friction is present", "only conservative forces do work", "the collision is inelastic", "air resistance acts"],
    1,
    "K + U = constant when non-conservative work is zero.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "work-energy-and-power",
    "If no external force acts on a system of colliding particles, then",
    ["kinetic energy is always conserved", "linear momentum is conserved", "mass is not conserved", "temperature is constant"],
    1,
    "P_total is conserved; K is conserved only if the collision is elastic.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "work-energy-and-power",
    "The SI unit of power is",
    ["joule", "watt", "newton", "pascal"],
    1,
    "Watt = joule/second; also 1 hp ≈ 746 W.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "work-energy-and-power",
    "Work done by kinetic friction on a sliding block is usually",
    ["positive", "negative", "zero always", "equal to μN"],
    1,
    "Friction opposes displacement, so cos θ = −1 and W < 0.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "work-energy-and-power",
    "Kinetic energy of a particle",
    ["can be negative", "is always non-negative", "is a vector", "depends on the potential zero"],
    1,
    "K = (1/2)mv² ≥ 0 for real v.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "work-energy-and-power",
    "Work is a",
    ["vector along F", "scalar", "always positive", "the same as energy only in units never numerically"],
    1,
    "W is a scalar (can be positive, negative, or zero); it has the same dimensions as energy.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "work-energy-and-power",
    "Work done by a variable force F(x) from x1 to x2 is",
    ["F(x1)(x2 − x1)", "∫_{x1}^{x2} F dx", "F_avg × t", "Δp"],
    1,
    "W = ∫ F · dx; in one dimension, ∫ F_x dx.",
  ),
];

const systemOfParticlesAndRotationalMotion: PracticeQuestionSeed[] = [
  cbsePyq(
    "class-11",
    "physics",
    "system-of-particles-and-rotational-motion",
    "Magnitude of torque τ = r × F is",
    ["rF cos θ", "rF sin θ", "r + F", "r/F"],
    1,
    "|τ| = rF sin θ = r_⊥ F, with θ the angle between r and F.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "system-of-particles-and-rotational-motion",
    "Angular momentum of a rigid body about a fixed axis is",
    ["Iα", "Iω", "mv", "τt always"],
    1,
    "L = Iω along the axis for rotation about a principal axis.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "system-of-particles-and-rotational-motion",
    "The parallel-axis theorem states that I =",
    ["I_cm − Md²", "I_cm + Md²", "I_cm + M/d²", "Md² only"],
    1,
    "I about a parallel axis at distance d from the CM is I_cm + Md².",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "system-of-particles-and-rotational-motion",
    "The perpendicular-axis theorem (planar lamina) is",
    ["I_z = I_x + I_y", "I_z = I_x − I_y", "I_x = I_y + I_z", "I_z = I_x I_y"],
    0,
    "For a plane lamina, I_z (perpendicular to plane) = I_x + I_y (in-plane axes).",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "system-of-particles-and-rotational-motion",
    "Moment of inertia of a thin ring of mass M and radius R about its central axis perpendicular to its plane is",
    ["(1/2)MR²", "MR²", "(2/5)MR²", "(1/12)MR²"],
    1,
    "All mass is at distance R, so I = MR².",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "system-of-particles-and-rotational-motion",
    "Moment of inertia of a uniform disc about its central axis perpendicular to its plane is",
    ["MR²", "(1/2)MR²", "(2/5)MR²", "(2/3)MR²"],
    1,
    "I_disc = (1/2)MR² about the symmetry axis.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "system-of-particles-and-rotational-motion",
    "Moment of inertia of a uniform solid sphere about a diameter is",
    ["(2/5)MR²", "(2/3)MR²", "(1/2)MR²", "MR²"],
    0,
    "I_solid sphere = (2/5)MR² about a diameter.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "system-of-particles-and-rotational-motion",
    "The centre of mass of a uniform thin rod lies",
    ["at one end", "at its geometric centre", "outside the rod", "at a distance L/3 from an end always"],
    1,
    "By symmetry, COM is at the midpoint.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "system-of-particles-and-rotational-motion",
    "Angular momentum of a system about a point is conserved if",
    ["kinetic energy is constant", "net external torque about that point is zero", "net external force is non-zero", "mass changes"],
    1,
    "τ_ext = dL/dt, so L is constant when τ_ext = 0.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "system-of-particles-and-rotational-motion",
    "The rotational analogue of F = ma is",
    ["τ = Iα", "τ = Iω", "L = Iα", "τ = Lω"],
    0,
    "Net torque = Iα about a fixed axis (or CM axis).",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "system-of-particles-and-rotational-motion",
    "Total kinetic energy of a rigid body in pure rolling is",
    ["(1/2)mv² only", "(1/2)Iω² only", "(1/2)mv² + (1/2)Iω²", "Iω²"],
    2,
    "Translational K of the CM plus rotational K about the CM.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "system-of-particles-and-rotational-motion",
    "Radius of gyration k is defined by I =",
    ["Mk", "Mk²", "M/k²", "2Mk"],
    1,
    "I = Mk², so k = √(I/M).",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "system-of-particles-and-rotational-motion",
    "Angular impulse equals",
    ["change in angular momentum", "change in torque", "Iω²", "linear impulse"],
    0,
    "∫ τ dt = ΔL.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "system-of-particles-and-rotational-motion",
    "For pure rolling without slipping on a fixed surface, v_cm and ω are related by",
    ["v_cm = ωR", "v_cm = ω/R", "v_cm = ωR²", "v_cm = 0"],
    0,
    "The point of contact is instantaneously at rest: v_cm = ωR.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "system-of-particles-and-rotational-motion",
    "Torque is equal to",
    ["dL/dt", "dI/dt", "L/t always", "I/ω"],
    0,
    "τ = dL/dt (rotational analogue of F = dp/dt).",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "system-of-particles-and-rotational-motion",
    "Moment of inertia of a thin uniform rod of length L about an axis through its centre, perpendicular to its length, is",
    ["ML²/3", "ML²/12", "ML²/2", "ML²"],
    1,
    "I_cm = ML²/12; about an end it is ML²/3 by the parallel-axis theorem.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "system-of-particles-and-rotational-motion",
    "Moment of inertia of a thin uniform rod about an axis through one end, perpendicular to its length, is",
    ["ML²/12", "ML²/3", "ML²/2", "MR²"],
    1,
    "I_end = I_cm + M(L/2)² = ML²/12 + ML²/4 = ML²/3.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "system-of-particles-and-rotational-motion",
    "Linear momentum of a system of particles is",
    ["Σ m_i v_i = M v_cm", "zero always", "Iω", "only the heaviest particle's momentum"],
    0,
    "P_total = M v_cm.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "system-of-particles-and-rotational-motion",
    "Position of the centre of mass of a system is",
    ["Σ m_i r_i / Σ m_i", "Σ r_i / n always", "the heaviest particle's position", "independent of masses"],
    0,
    "r_cm = (Σ m_i r_i) / M.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "system-of-particles-and-rotational-motion",
    "A couple consists of two equal and opposite forces whose",
    ["net force and net torque are both zero", "net force is zero but net torque is non-zero", "net torque is always zero", "lines of action coincide"],
    1,
    "The forces cancel; torque of a couple = force × perpendicular separation of lines of action.",
  ),
];

const gravitation: PracticeQuestionSeed[] = [
  cbsePyq(
    "class-11",
    "physics",
    "gravitation",
    "Kepler's third law for planets (a = semi-major axis) states that",
    ["T ∝ a", "T² ∝ a³", "T³ ∝ a²", "T ∝ a²"],
    1,
    "T² = (4π²/GM) a³, so T² ∝ a³.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "gravitation",
    "Kepler's second law implies that a planet",
    ["moves at constant speed", "sweeps equal areas in equal times", "has circular orbit only", "has constant acceleration"],
    1,
    "Areal velocity is constant, equivalent to conservation of angular momentum.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "gravitation",
    "Acceleration due to gravity at the surface of a planet of mass M and radius R is",
    ["GM/R", "GM/R²", "GM²/R", "G/R²"],
    1,
    "mg = GMm/R² ⇒ g = GM/R².",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "gravitation",
    "Escape speed from the surface of a planet is",
    ["√(gR)", "√(2gR)", "2√(gR)", "gR"],
    1,
    "v_e = √(2GM/R) = √(2gR).",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "gravitation",
    "Orbital speed of a satellite in a circular orbit of radius r is",
    ["√(GM/r)", "√(2GM/r)", "GM/r", "gR"],
    0,
    "GMm/r² = mv²/r ⇒ v_o = √(GM/r).",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "gravitation",
    "For a circular orbit just above the surface, escape speed and orbital speed are related by",
    ["v_e = v_o", "v_e = √2 v_o", "v_e = 2 v_o", "v_e = v_o/√2"],
    1,
    "v_e = √(2gR) and v_o = √(gR), so v_e = √2 v_o.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "gravitation",
    "Variation of g with small height h above the surface is",
    ["g(1 − 2h/R)", "g(1 + 2h/R)", "g(1 − h/R)", "g(1 + h/R)"],
    0,
    "g_h = GM/(R+h)² ≈ g(1 − 2h/R) for h ≪ R.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "gravitation",
    "Variation of g at depth d below the surface (uniform Earth) is",
    ["g(1 − d/R)", "g(1 + d/R)", "g(1 − 2d/R)", "g"],
    0,
    "g_d = g(1 − d/R); g decreases linearly toward the centre.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "gravitation",
    "Gravitational potential due to a point mass M at distance r is",
    ["GM/r", "−GM/r", "GM/r²", "−GM/r²"],
    1,
    "V = −GM/r with V(∞) = 0.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "gravitation",
    "Gravitational field intensity due to a point mass M at distance r has magnitude",
    ["GM/r", "GM/r²", "GM/r³", "G/r²"],
    1,
    "E = GM/r² toward the mass (E = −dV/dr).",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "gravitation",
    "An astronaut in a satellite orbiting Earth feels weightless because",
    ["g is zero in orbit", "the satellite is in free fall (centripetal acceleration = g_local)", "mass becomes zero", "Earth's gravity does not extend that far"],
    1,
    "Both astronaut and satellite accelerate toward Earth at the same rate; normal reaction is zero.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "gravitation",
    "Total energy (binding energy magnitude) of a satellite of mass m in circular orbit of radius r is",
    ["GMm/r", "GMm/(2r)", "−GMm/(2r) for total E; |E| = GMm/(2r)", "2GMm/r"],
    2,
    "E = K + U = GMm/(2r) − GMm/r = −GMm/(2r); binding energy is GMm/(2r).",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "gravitation",
    "Acceleration due to gravity is maximum at the",
    ["equator", "poles", "centre of Earth", "a height R above the surface"],
    1,
    "Poles are closer to Earth's centre and have no centrifugal reduction; g is largest there.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "gravitation",
    "Newton's law of gravitation is",
    ["F = GMm/r", "F = GMm/r²", "F = Gm/r²", "F = gMm"],
    1,
    "The force is attractive and inversely proportional to r².",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "gravitation",
    "Time period of a satellite in circular orbit of radius r is",
    ["2π √(r³/GM)", "2π √(GM/r³)", "2πr/GM", "√(r/g)"],
    0,
    "T = 2πr/v_o = 2π √(r³/GM).",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "gravitation",
    "Kepler's first law states that a planet moves in an",
    ["circle with Earth at the centre", "ellipse with the Sun at one focus", "ellipse with the Sun at the centre", "parabola"],
    1,
    "Planetary orbits are ellipses; the Sun occupies one focus.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "gravitation",
    "In vacuum, acceleration due to gravity of a falling body",
    ["depends on its mass", "is independent of its mass", "is larger for heavier bodies", "is zero"],
    1,
    "From F = GMm/r² = ma, a = GM/r², independent of m.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "gravitation",
    "Gravitational potential energy of two point masses is",
    ["GMm/r", "−GMm/r", "GMm/r²", "mgh always at all r"],
    1,
    "U = −GMm/r with U(∞) = 0.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "gravitation",
    "A geostationary satellite has an orbital period of about",
    ["90 minutes", "12 hours", "24 hours", "1 year"],
    2,
    "It stays fixed relative to a point on Earth, so T equals Earth's sidereal rotation period ≈ 24 h; orbit is equatorial.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "gravitation",
    "Gravitational field inside a uniform thin spherical shell is",
    ["GM/R²", "maximum at the centre", "zero", "GM/r²"],
    2,
    "By Gauss's law (or Newton's shell theorem), E = 0 for r < R; potential is constant −GM/R.",
  ),
];

const mechanicalPropertiesOfSolids: PracticeQuestionSeed[] = [
  cbsePyq(
    "class-11",
    "physics",
    "mechanical-properties-of-solids",
    "Young's modulus Y is defined as",
    ["(F/A) / (ΔL/L)", "(ΔL/L) / (F/A)", "F ΔL", "stress × strain"],
    0,
    "Y = longitudinal stress / longitudinal strain = (F/A)/(ΔL/L).",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "mechanical-properties-of-solids",
    "Hooke's law states that, within the elastic limit,",
    ["stress is independent of strain", "stress is proportional to strain", "strain is proportional to the square of stress", "stress equals strain"],
    1,
    "Stress ∝ strain; the constant of proportionality is the relevant modulus.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "mechanical-properties-of-solids",
    "Bulk modulus B is given by",
    ["−ΔP / (ΔV/V)", "ΔP × (ΔV/V)", "ΔV/ΔP", "P V"],
    0,
    "B = −ΔP / (ΔV/V); the minus sign makes B positive when volume decreases under pressure.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "mechanical-properties-of-solids",
    "Shear modulus (modulus of rigidity) is",
    ["longitudinal stress / longitudinal strain", "shear stress / shear strain", "hydraulic stress / volume strain", "force / extension"],
    1,
    "η = (F/A)/θ for small shear angle θ (in radians).",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "mechanical-properties-of-solids",
    "Poisson's ratio is",
    ["longitudinal strain / lateral strain", "lateral strain / longitudinal strain", "stress / strain", "Y / η"],
    1,
    "σ = −(lateral strain)/(longitudinal strain); typically 0.2–0.4 for most solids.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "mechanical-properties-of-solids",
    "Elastic potential energy per unit volume stored in a stretched wire is",
    ["stress × strain", "(1/2) × stress × strain", "Y × strain", "(1/2) Y²"],
    1,
    "Energy density = (1/2) × stress × strain = (1/2) Y (strain)².",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "mechanical-properties-of-solids",
    "Steel is said to be more elastic than rubber because",
    ["rubber is harder", "Young's modulus of steel is larger", "steel has larger strain for the same stress", "rubber obeys Hooke's law better"],
    1,
    "Elasticity is restoring ability; larger Y means smaller strain for a given stress.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "mechanical-properties-of-solids",
    "Compressibility of a material is",
    ["B", "1/B", "Y", "1/Y"],
    1,
    "Compressibility κ = 1/B, the reciprocal of the bulk modulus.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "mechanical-properties-of-solids",
    "Breaking stress of a wire is",
    ["the maximum stress it can withstand before fracture", "Young's modulus", "the strain at the yield point", "always equal to Y"],
    0,
    "Breaking (ultimate) stress = breaking force / original area of cross-section.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "mechanical-properties-of-solids",
    "The SI unit of Young's modulus is",
    ["N m", "N m⁻² (pascal)", "joule", "dimensionless"],
    1,
    "Y has the dimensions of stress, so the unit is N/m² or Pa.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "mechanical-properties-of-solids",
    "Longitudinal stress on a rod is",
    ["F/A", "F A", "F L", "A/F"],
    0,
    "Stress = restoring force per unit area = F/A.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "mechanical-properties-of-solids",
    "The elastic limit of a material is the",
    ["maximum stress up to which it recovers its original shape on unloading", "breaking point", "yield point of a fluid", "same as Poisson's ratio"],
    0,
    "Beyond the elastic limit, permanent (plastic) deformation remains.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "mechanical-properties-of-solids",
    "For a given load, the extension of a wire is proportional to",
    ["A/L", "L/A", "A L", "1/(A L)"],
    1,
    "ΔL = (F L)/(A Y), so ΔL ∝ L/A for fixed F and Y.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "mechanical-properties-of-solids",
    "The relation among Y, η (rigidity modulus) and Poisson's ratio σ is",
    ["Y = 2η(1 + σ)", "Y = 2η(1 − σ)", "Y = η(1 + σ)", "Y = 3η σ"],
    0,
    "Y = 2η(1 + σ). Also Y = 3B(1 − 2σ).",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "mechanical-properties-of-solids",
    "The slope of the linear portion of a stress–strain curve equals",
    ["Poisson's ratio", "Young's modulus", "bulk modulus", "breaking stress"],
    1,
    "In the proportional region, stress/strain = Y, which is that slope.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "mechanical-properties-of-solids",
    "A ductile material, compared with a brittle one, typically",
    ["fractures with almost no plastic deformation", "shows a large plastic region before fracture", "has zero Young's modulus", "cannot be drawn into wires"],
    1,
    "Ductile solids (e.g. copper, steel) yield and deform plastically; brittle solids (e.g. glass) break near the elastic limit.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "mechanical-properties-of-solids",
    "Hooke's law remains valid up to the",
    ["breaking point", "proportional limit", "plastic region only", "melting point"],
    1,
    "Stress is strictly proportional to strain only up to the proportional (elastic) limit.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "mechanical-properties-of-solids",
    "Hydraulic stress on a body immersed in a fluid is equal to the",
    ["shear strain", "applied pressure", "Young's modulus", "surface tension"],
    1,
    "Hydraulic stress is the pressure exerted by the fluid, ΔP.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "mechanical-properties-of-solids",
    "The SI unit of longitudinal strain is",
    ["N m⁻²", "none (it is dimensionless)", "metre", "pascal"],
    1,
    "Strain = ΔL/L is a ratio of lengths, so it has no unit.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "mechanical-properties-of-solids",
    "In the plastic region of a stress–strain curve, unloading the specimen",
    ["retraces the loading curve to the origin", "leaves a permanent set (residual strain)", "increases Y", "makes strain zero instantly"],
    1,
    "Plastic deformation is irreversible; a residual strain remains after unloading.",
  ),
];

const mechanicalPropertiesOfFluids: PracticeQuestionSeed[] = [
  cbsePyq(
    "class-11",
    "physics",
    "mechanical-properties-of-fluids",
    "Pascal's law states that a pressure applied to an enclosed fluid is",
    ["transmitted undiminished to every portion of the fluid and the walls", "transmitted only downward", "inversely proportional to area", "zero at the surface"],
    0,
    "Pressure in a static confined fluid is transmitted equally in all directions (basis of the hydraulic lift).",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "mechanical-properties-of-fluids",
    "Bernoulli's equation along a streamline for an ideal incompressible fluid is",
    ["P + ρgh + (1/2)ρv² = constant", "P + ρgh = (1/2)ρv²", "P v = constant", "P + (1/2)ρv² = ρgh"],
    0,
    "It is conservation of mechanical energy per unit volume: pressure + gravitational + kinetic.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "mechanical-properties-of-fluids",
    "The equation of continuity for incompressible flow is",
    ["A/v = constant", "A v = constant", "A + v = constant", "P A = constant"],
    1,
    "Mass flux is conserved: ρ A v = constant; if ρ is constant, A v = constant.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "mechanical-properties-of-fluids",
    "Stokes' law for the viscous drag on a sphere of radius r moving with speed v is",
    ["F = 6π η r v", "F = 6π η r² v", "F = 4π η r v", "F = η A v"],
    0,
    "F_d = 6π η r v, opposite to the velocity, for small Reynolds number.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "mechanical-properties-of-fluids",
    "Terminal velocity of a spherical body of density ρ falling in a fluid of density σ is",
    ["2r²(ρ − σ)g / (9η)", "2r(ρ − σ)g / (9η)", "9η / [2r²(ρ − σ)g]", "6π η r"],
    0,
    "At terminal speed, weight = buoyancy + viscous drag, giving v_t = 2r²(ρ − σ)g/(9η).",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "mechanical-properties-of-fluids",
    "Surface tension is defined as",
    ["force per unit length acting on a line in the surface", "force per unit area", "energy per unit volume", "pressure × radius"],
    0,
    "T = F/ℓ; equivalently, surface energy per unit area.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "mechanical-properties-of-fluids",
    "Capillary rise of a liquid in a narrow tube is",
    ["h = 2T cos θ / (ρ g r)", "h = ρ g r / (2T)", "h = 2T / (ρ g)", "h = T r / (ρ g)"],
    0,
    "h = 2S cos θ / (ρ g r). Rise if θ is acute (wetting); depression if obtuse (e.g. mercury).",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "mechanical-properties-of-fluids",
    "Reynolds number is",
    ["ρ v d / η", "η / (ρ v d)", "ρ η / v", "v d / ρ"],
    0,
    "Re = ρ v d / η. Flow is typically laminar for small Re and turbulent for large Re.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "mechanical-properties-of-fluids",
    "Newton's law of viscosity states that viscous force is",
    ["F = η A (dv/dx)", "F = η A / (dv/dx)", "F = η (dv/dx) / A", "F = 6π r η only always"],
    0,
    "Shear stress = η × velocity gradient: F/A = η dv/dx.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "mechanical-properties-of-fluids",
    "Speed of efflux from an orifice at depth h below a free surface (Torricelli) is",
    ["gh", "√(2gh)", "2gh", "√(gh)"],
    1,
    "Bernoulli between surface and orifice gives v = √(2gh), like free fall from height h.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "mechanical-properties-of-fluids",
    "Excess pressure inside a liquid drop of radius r is",
    ["T/r", "2T/r", "4T/r", "8T/r"],
    1,
    "A drop has one surface, so ΔP = 2T/r.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "mechanical-properties-of-fluids",
    "Excess pressure inside a soap bubble of radius r is",
    ["2T/r", "4T/r", "T/r", "8T/r"],
    1,
    "A soap bubble has two free surfaces, so ΔP = 4T/r.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "mechanical-properties-of-fluids",
    "Normal atmospheric pressure is about",
    ["1.01 × 10³ Pa", "1.01 × 10⁵ Pa (76 cm of Hg)", "76 Pa", "10 Pa"],
    1,
    "1 atm ≈ 1.013 × 10⁵ N m⁻² = 76 cm Hg = 10.3 m of water.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "mechanical-properties-of-fluids",
    "Gauge pressure at depth h in a liquid of density ρ is",
    ["ρ g h", "ρ g / h", "g h / ρ", "P_atm + ρ g h is gauge"],
    0,
    "P_gauge = ρgh; absolute pressure is P_atm + ρgh.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "mechanical-properties-of-fluids",
    "Archimedes' principle states that the buoyant force equals the",
    ["weight of the body", "weight of the fluid displaced", "mass of the body", "viscous drag"],
    1,
    "Upthrust = weight of displaced fluid, acting through the centre of buoyancy.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "mechanical-properties-of-fluids",
    "In streamline (laminar) flow",
    ["the path of every particle is random", "each particle follows a smooth path that does not cross others", "Re is always greater than 3000", "Bernoulli's equation never applies"],
    1,
    "Streamlines do not intersect; velocity at a point is steady in time for steady flow.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "mechanical-properties-of-fluids",
    "The SI unit of the coefficient of viscosity is",
    ["N s m⁻² (pascal-second)", "N m⁻²", "poiseuille⁻¹", "kg m⁻¹"],
    0,
    "η has unit Pa s = N s m⁻². The CGS unit poise is 0.1 Pa s.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "mechanical-properties-of-fluids",
    "The angle of contact for a liquid that wets glass is typically",
    ["obtuse (> 90°)", "acute (< 90°)", "180°", "exactly 90° always"],
    1,
    "Water–glass: θ acute and the meniscus is concave; mercury–glass: θ obtuse, convex meniscus.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "mechanical-properties-of-fluids",
    "A Venturimeter measures flow speed using",
    ["Stokes' law", "Bernoulli's principle and continuity", "Pascal's law only", "capillarity"],
    1,
    "Narrowing raises speed and lowers pressure; the pressure drop gives v from Bernoulli + Av = constant.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "mechanical-properties-of-fluids",
    "Where the speed of an ideal fluid is higher along a horizontal streamline, the pressure is",
    ["higher", "lower", "unchanged", "infinite"],
    1,
    "From P + (1/2)ρv² = constant (horizontal), larger v means smaller P (e.g. atomiser, aerofoil lift).",
  ),
];

const thermalPropertiesOfMatter: PracticeQuestionSeed[] = [
  cbsePyq(
    "class-11",
    "physics",
    "thermal-properties-of-matter",
    "Linear expansion of a rod is given by",
    ["ΔL = α L ΔT", "ΔL = α ΔT / L", "ΔL = L / (α ΔT)", "ΔL = α / (L ΔT)"],
    0,
    "ΔL = α L ΔT, where α is the coefficient of linear expansion.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "thermal-properties-of-matter",
    "The coefficient of volume expansion γ and linear expansion α of an isotropic solid satisfy",
    ["γ = α", "γ = 2α", "γ = 3α", "γ = α/3"],
    2,
    "ΔV/V = 3 ΔL/L for isotropic expansion, so γ = 3α. Also β ≈ 2α for area.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "thermal-properties-of-matter",
    "The coefficient of areal expansion β is approximately",
    ["α", "2α", "3α", "α/2"],
    1,
    "ΔA/A = 2 ΔL/L, so β = 2α.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "thermal-properties-of-matter",
    "Heat required to raise the temperature of mass m by ΔT (no phase change) is",
    ["Q = m L", "Q = m c ΔT", "Q = c ΔT / m", "Q = m / (c ΔT)"],
    1,
    "Q = m c ΔT, where c is specific heat capacity.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "thermal-properties-of-matter",
    "Heat absorbed during a change of state at constant temperature is",
    ["Q = m c ΔT", "Q = m L", "Q = L / m", "Q = m / L"],
    1,
    "Q = mL, where L is the latent heat of fusion or vaporisation.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "thermal-properties-of-matter",
    "Newton's law of cooling states that the rate of fall of temperature is proportional to",
    ["the square of excess temperature", "the excess temperature over the surroundings", "absolute temperature only", "the mass of the body only"],
    1,
    "dT/dt ∝ (T − T₀) when the excess temperature is not too large.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "thermal-properties-of-matter",
    "Rate of heat flow by conduction through a slab is",
    ["KA ΔT / d", "K d ΔT / A", "A d / (K ΔT)", "K ΔT / (A d)"],
    0,
    "H = dQ/dt = KA(T₁ − T₂)/d.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "thermal-properties-of-matter",
    "The specific heat capacity of water is about",
    ["1 J kg⁻¹ K⁻¹", "4200 J kg⁻¹ K⁻¹", "80 J kg⁻¹ K⁻¹", "540 J g⁻¹"],
    1,
    "c_water ≈ 4.2 × 10³ J kg⁻¹ K⁻¹ = 1 cal g⁻¹ °C⁻¹.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "thermal-properties-of-matter",
    "Water shows anomalous expansion between",
    ["0 °C and 4 °C", "4 °C and 100 °C", "−4 °C and 0 °C", "90 °C and 100 °C"],
    0,
    "Density of water is maximum at 4 °C; it expands on cooling from 4 °C to 0 °C.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "thermal-properties-of-matter",
    "Thermal stress in a rod rigidly fixed at both ends and heated is",
    ["Y α ΔT", "Y / (α ΔT)", "α ΔT / Y", "Y α / ΔT"],
    0,
    "If expansion is prevented, strain = α ΔT, so stress = Y α ΔT.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "thermal-properties-of-matter",
    "Absolute zero on the Celsius scale is",
    ["0 °C", "−100 °C", "−273.15 °C", "273 °C"],
    2,
    "0 K = −273.15 °C. T(K) = t(°C) + 273.15.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "thermal-properties-of-matter",
    "Wien's displacement law states that",
    ["λ_m T = constant", "λ_m / T = constant", "λ_m T² = constant", "T / λ_m² = constant"],
    0,
    "λ_m T = b (Wien's constant). Hotter bodies radiate at shorter peak wavelengths.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "thermal-properties-of-matter",
    "A good absorber of radiation is also a",
    ["poor emitter", "good emitter (Kirchhoff's law)", "perfect reflector", "thermal insulator"],
    1,
    "Kirchhoff: absorptivity equals emissivity for a given wavelength at thermal equilibrium.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "thermal-properties-of-matter",
    "Latent heat of fusion of ice is about",
    ["80 cal g⁻¹ (3.34 × 10⁵ J kg⁻¹)", "540 cal g⁻¹", "1 cal g⁻¹", "4.2 J g⁻¹"],
    0,
    "L_f ≈ 3.34 × 10⁵ J/kg = 80 cal/g. Latent heat of vaporisation of water is ≈ 540 cal/g.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "thermal-properties-of-matter",
    "In calorimetry, if no heat is lost to the surroundings,",
    ["heat lost by hot body = heat gained by cold body", "temperatures remain unequal always", "latent heat is never involved", "c must be the same for both"],
    0,
    "Energy conservation: m₁ c₁ ΔT₁ + m L + … balances on both sides.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "thermal-properties-of-matter",
    "The SI unit of the coefficient of linear expansion is",
    ["K", "K⁻¹", "m K⁻¹", "dimensionless"],
    1,
    "α = ΔL /(L ΔT) has unit K⁻¹ (or °C⁻¹).",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "thermal-properties-of-matter",
    "The apparent expansion of a liquid in a vessel is",
    ["γ_real − γ_vessel", "γ_real + γ_vessel", "γ_real", "3α_liquid only"],
    0,
    "γ_app = γ_real − γ_glass, because the vessel also expands.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "thermal-properties-of-matter",
    "Metals are generally good thermal conductors because they have",
    ["free electrons that transport energy", "zero specific heat", "no lattice vibrations", "only radiative transfer"],
    0,
    "Delocalised electrons carry thermal energy quickly; non-metals conduct mainly via lattice vibrations.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "thermal-properties-of-matter",
    "Stefan–Boltzmann law for a black body gives the energy flux as",
    ["σ T", "σ T²", "σ T⁴", "σ / T⁴"],
    2,
    "E = σ T⁴. For a grey body, E = e σ T⁴.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "thermal-properties-of-matter",
    "Heat current (rate of heat flow) in the steady state through a composite slab is",
    ["the same through each layer", "largest through the thickest layer", "zero", "inversely proportional to K only, independent of area"],
    0,
    "In series, H is the same in each layer (like current); temperature drop is larger across the poorer conductor.",
  ),
];

const thermodynamics: PracticeQuestionSeed[] = [
  cbsePyq(
    "class-11",
    "physics",
    "thermodynamics",
    "The first law of thermodynamics (NCERT convention) is",
    ["ΔQ = ΔU + ΔW", "ΔU = ΔQ + ΔW", "ΔW = ΔQ + ΔU", "ΔQ = ΔU − ΔW"],
    0,
    "Heat supplied ΔQ equals the rise in internal energy plus work ΔW done by the system.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "thermodynamics",
    "For an ideal gas in an isothermal process",
    ["ΔU = 0", "ΔQ = 0", "ΔW = 0", "T increases"],
    0,
    "U of an ideal gas depends only on T, so ΔT = 0 ⇒ ΔU = 0 and ΔQ = ΔW.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "thermodynamics",
    "In an adiabatic process",
    ["ΔQ = 0", "ΔU = 0", "ΔW = 0", "T is always constant"],
    0,
    "No heat is exchanged. For an ideal gas, ΔU = −ΔW, so temperature changes if work is done.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "thermodynamics",
    "For one mole of an ideal gas, Mayer's relation is",
    ["C_p − C_v = R", "C_p + C_v = R", "C_p / C_v = R", "C_v − C_p = R"],
    0,
    "C_p − C_v = R (molar heat capacities).",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "thermodynamics",
    "The ratio γ is defined as",
    ["C_v / C_p", "C_p / C_v", "C_p − C_v", "R / C_v"],
    1,
    "γ = C_p / C_v > 1. For a diatomic gas at room temperature, γ ≈ 1.4.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "thermodynamics",
    "Efficiency of a Carnot engine working between T₁ (source) and T₂ (sink) is",
    ["1 − T₂/T₁", "1 − T₁/T₂", "T₂/T₁", "T₁ − T₂"],
    0,
    "η = 1 − T₂/T₁ with temperatures in kelvin. η = 1 only if T₂ = 0 K, which is unattainable.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "thermodynamics",
    "Work done by n moles of an ideal gas in a reversible isothermal expansion is",
    ["nRT ln(V₂/V₁)", "nR ΔT", "P ΔV only with ΔT ≠ 0 necessarily", "zero"],
    0,
    "W = ∫ P dV = nRT ln(V₂/V₁) = nRT ln(P₁/P₂).",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "thermodynamics",
    "Internal energy of a thermodynamic system is a",
    ["path function", "state function", "not a property of the system", "form of heat only"],
    1,
    "U depends only on the state (for an ideal gas, on T and n). Q and W are path functions.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "thermodynamics",
    "Efficiency of a heat engine is",
    ["W/Q₁ = 1 − Q₂/Q₁", "Q₁/W", "Q₂/Q₁", "always 100%"],
    0,
    "η = work output / heat absorbed from the source = 1 − |Q₂|/Q₁.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "thermodynamics",
    "The Kelvin–Planck statement of the second law is that",
    ["heat cannot flow from cold to hot by itself", "no engine can convert heat completely into work in a cyclic process without rejecting heat", "entropy always decreases", "ΔU = 0 always"],
    1,
    "A 100% efficient heat engine (converting all Q into W with no sink) is impossible.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "thermodynamics",
    "The Clausius statement of the second law is that",
    ["heat cannot flow unaided from a colder to a hotter body", "U is conserved", "W = PΔV always", "η_Carnot can exceed 1"],
    0,
    "Heat does not spontaneously flow from cold to hot; a refrigerator needs external work.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "thermodynamics",
    "In an isochoric process the work done by the gas is",
    ["PΔV", "nRT ln(V₂/V₁)", "zero", "maximum"],
    2,
    "V is constant ⇒ ΔV = 0 ⇒ W = 0. Then ΔQ = ΔU.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "thermodynamics",
    "Work done by a gas in an isobaric expansion is",
    ["zero", "P ΔV", "nRT ln(V₂/V₁)", "C_v ΔT"],
    1,
    "W = P(V₂ − V₁) = nR ΔT for an ideal gas at constant pressure.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "thermodynamics",
    "For a reversible adiabatic process on an ideal gas",
    ["T V^{γ−1} = constant", "T V = constant", "P V = constant", "T / V = constant"],
    0,
    "Also P V^γ = constant and T^γ P^{1−γ} = constant.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "thermodynamics",
    "Work done by the system in a cyclic process equals",
    ["zero always", "the area enclosed by the cycle on the P–V diagram", "ΔU", "Q₂ only"],
    1,
    "ΔU = 0 over a cycle, so W = Q_net, equal to the enclosed P–V area.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "thermodynamics",
    "For a diatomic ideal gas at room temperature, C_p / C_v is about",
    ["1.33", "1.40", "1.67", "1.00"],
    1,
    "f = 5 ⇒ γ = 1 + 2/f = 7/5 = 1.4. Monatomic: γ = 5/3 ≈ 1.67.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "thermodynamics",
    "Coefficient of performance of a refrigerator is",
    ["Q₂ / W", "W / Q₂", "Q₁ / Q₂", "η of a heat engine"],
    0,
    "COP = heat extracted from the cold body / work input. For Carnot, T₂/(T₁ − T₂).",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "thermodynamics",
    "A quasi-static process is one that",
    ["occurs infinitely fast", "passes through a succession of equilibrium states", "cannot be shown on a P–V diagram", "has ΔQ = 0 necessarily"],
    1,
    "The system is always infinitesimally close to equilibrium; it is reversible if there is no friction/dissipation.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "thermodynamics",
    "In an adiabatic free expansion of an ideal gas into vacuum",
    ["T decreases", "T remains the same and W = 0, Q = 0", "T increases", "U increases"],
    1,
    "Q = 0, W = 0 against vacuum, so ΔU = 0 ⇒ ΔT = 0 for an ideal gas.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "thermodynamics",
    "For a reversible adiabatic process, P and V are related by",
    ["P V = constant", "P V^γ = constant", "P / V^γ = constant", "P^γ V = constant"],
    1,
    "P V^γ = constant, with γ = C_p/C_v.",
  ),
];

const kineticTheory: PracticeQuestionSeed[] = [
  cbsePyq(
    "class-11",
    "physics",
    "kinetic-theory",
    "Pressure of an ideal gas is related to rms speed by",
    ["P = (1/3) ρ v_rms²", "P = ρ v_rms²", "P = (1/2) ρ v_rms", "P = 3 ρ / v_rms²"],
    0,
    "From KTG, P = (1/3) ρ c² with c = v_rms.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "kinetic-theory",
    "The rms speed of gas molecules is",
    ["√(3RT/M)", "√(2RT/M)", "√(RT/M)", "√(8RT/πM)"],
    0,
    "v_rms = √(3P/ρ) = √(3RT/M) = √(3kT/m).",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "kinetic-theory",
    "Average translational kinetic energy per molecule of an ideal gas is",
    ["(1/2) kT", "(3/2) kT", "kT", "(5/2) kT always"],
    1,
    "Three translational degrees of freedom: (3/2)kT, independent of the gas as long as T is the same.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "kinetic-theory",
    "According to the law of equipartition, energy associated with each degree of freedom per molecule is",
    ["kT", "(1/2) kT", "(3/2) kT", "R T"],
    1,
    "Each quadratic term in energy contributes (1/2)kT per molecule.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "kinetic-theory",
    "A diatomic gas at room temperature has (translational + rotational) degrees of freedom",
    ["3", "5", "6", "7"],
    1,
    "3 translational + 2 rotational. Vibration is frozen at ordinary temperature, so f = 5.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "kinetic-theory",
    "Molar specific heat at constant volume is",
    ["C_v = f R / 2", "C_v = f R", "C_v = R / f", "C_v = 2 R / f"],
    0,
    "U = (f/2) nRT ⇒ C_v = (∂U/∂T)_V / n = fR/2. Then C_p = C_v + R.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "kinetic-theory",
    "Mean free path of a gas molecule is",
    ["λ = 1 / (√2 π d² n)", "λ = √2 π d² n", "λ = π d² n", "λ = n / (π d²)"],
    0,
    "λ = 1/(√2 π d² n), where d is molecular diameter and n is number density.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "kinetic-theory",
    "The ratio v_mp : v_av : v_rms equals",
    ["√2 : √(8/π) : √3", "√3 : √2 : √(8/π)", "1 : 1 : 1", "√3 : √2 : 1"],
    0,
    "v_mp = √(2RT/M), v_av = √(8RT/πM), v_rms = √(3RT/M), so v_mp < v_av < v_rms.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "kinetic-theory",
    "Absolute temperature of an ideal gas is proportional to the",
    ["total number of molecules", "average kinetic energy of molecules", "volume only", "molecular diameter"],
    1,
    "(1/2) m v_rms² = (3/2) kT, so T ∝ mean translational KE.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "kinetic-theory",
    "Boyle's law follows from kinetic theory if, at constant T,",
    ["v_rms is constant so P ∝ ρ ∝ 1/V", "v_rms ∝ V", "P ∝ V", "n changes"],
    0,
    "P = (1/3) ρ v_rms² with v_rms fixed at fixed T ⇒ P ∝ 1/V at constant mass.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "kinetic-theory",
    "A monatomic ideal gas has degrees of freedom",
    ["2", "3", "5", "6"],
    1,
    "Only three translational degrees of freedom; C_v = 3R/2, γ = 5/3.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "kinetic-theory",
    "γ in terms of degrees of freedom f is",
    ["1 + 2/f", "1 + f/2", "2/f", "f/(f+2)"],
    0,
    "γ = C_p/C_v = (fR/2 + R)/(fR/2) = 1 + 2/f.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "kinetic-theory",
    "At the same temperature, the rms speed of H₂ relative to O₂ is",
    ["the same", "4 times", "16 times", "1/4"],
    1,
    "v_rms ∝ 1/√M. M_O₂/M_H₂ = 32/2 = 16, so v_H / v_O = 4.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "kinetic-theory",
    "Average translational KE of molecules of different ideal gases at the same T is",
    ["larger for heavier gases", "the same for all gases", "larger for lighter gases", "zero"],
    1,
    "(3/2)kT is independent of molar mass.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "kinetic-theory",
    "Boltzmann's constant k is equal to",
    ["R N_A", "R / N_A", "N_A / R", "3R/2"],
    1,
    "k = R/N_A ≈ 1.38 × 10⁻²³ J K⁻¹.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "kinetic-theory",
    "The most probable speed of gas molecules is",
    ["√(2RT/M)", "√(3RT/M)", "√(8RT/πM)", "√(RT/2M)"],
    0,
    "v_mp is the speed at the peak of the Maxwell speed distribution: √(2RT/M).",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "kinetic-theory",
    "In the Maxwell speed distribution, raising the temperature",
    ["shifts the peak to higher speed and flattens the curve", "makes all molecules have the same speed", "shifts the peak to lower speed", "does not change v_mp"],
    0,
    "The distribution broadens and v_mp, v_av, v_rms all increase as √T.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "kinetic-theory",
    "An assumption of the kinetic theory of ideal gases is that",
    ["molecules have negligible volume and exert no forces except during collisions", "molecules attract strongly at all distances", "collisions are perfectly inelastic", "gravity between molecules dominates"],
    0,
    "Point molecules, random motion, elastic collisions, and no intermolecular forces except at impact.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "kinetic-theory",
    "Internal energy of an ideal gas depends on",
    ["volume only", "pressure only", "temperature (and amount of gas) only", "the path of compression"],
    2,
    "U = (f/2) nRT for an ideal gas; it is independent of V or P at given T, n.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "kinetic-theory",
    "The average speed of gas molecules is",
    ["√(8RT/πM)", "√(3RT/M)", "√(2RT/M)", "√(RT/M)"],
    0,
    "v_av = √(8RT/πM) = √(8kT/πm), between v_mp and v_rms.",
  ),
];

const oscillations: PracticeQuestionSeed[] = [
  cbsePyq(
    "class-11",
    "physics",
    "oscillations",
    "Time period of a mass m on a spring of stiffness k is",
    ["2π √(m/k)", "2π √(k/m)", "2π m/k", "√(k/m)"],
    0,
    "ω = √(k/m), so T = 2π/ω = 2π √(m/k).",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "oscillations",
    "Time period of a simple pendulum of length ℓ (small amplitude) is",
    ["2π √(ℓ/g)", "2π √(g/ℓ)", "2π ℓ/g", "2π √(m/ℓ)"],
    0,
    "T = 2π √(ℓ/g), independent of mass and (for small θ) of amplitude.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "oscillations",
    "The defining relation for SHM is that acceleration is",
    ["constant", "proportional to velocity", "a = −ω² x", "a = ω² x"],
    2,
    "Restoring acceleration is opposite to displacement and proportional to it.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "oscillations",
    "Maximum speed in SHM of amplitude A and angular frequency ω is",
    ["ω A", "ω² A", "A / ω", "ω / A"],
    0,
    "v = ω √(A² − x²), so v_max = ωA at the mean position.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "oscillations",
    "Maximum acceleration in SHM is",
    ["ω A", "ω² A", "A / ω²", "zero at the extreme"],
    1,
    "a = −ω² x, so |a|_max = ω² A at the extreme positions.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "oscillations",
    "Total energy of a particle in SHM is",
    ["(1/2) k A²", "(1/2) k x² only", "m ω A", "zero at the mean position"],
    0,
    "E = (1/2) m ω² A² = (1/2) k A², constant for undamped SHM.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "oscillations",
    "In SHM, kinetic energy is maximum at the",
    ["extreme position", "mean position", "half amplitude only never at mean", "all positions equally"],
    1,
    "K = (1/2) m ω² (A² − x²) is maximum at x = 0, where PE is minimum.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "oscillations",
    "Potential energy in SHM is maximum at the",
    ["mean position", "extreme positions", "point where v is maximum", "centre of the spring only if A = 0"],
    1,
    "U = (1/2) m ω² x² is maximum at x = ±A, where K = 0.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "oscillations",
    "For small-amplitude SHM (isochronous motion), the time period",
    ["increases with amplitude", "decreases with amplitude", "is independent of amplitude", "is proportional to A²"],
    2,
    "T = 2π/ω depends on m and k (or ℓ and g), not on A, for true SHM.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "oscillations",
    "Displacement in SHM can be written as",
    ["x = A sin(ωt + φ)", "x = A t", "x = A ω t²", "x = A / t"],
    0,
    "x = A sin(ωt + φ) or A cos(ωt + φ); A is amplitude and φ is the phase constant.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "oscillations",
    "Angular frequency ω is related to time period by",
    ["ω = 2π T", "ω = 2π / T", "ω = T / 2π", "ω = π T"],
    1,
    "ω = 2π/T = 2π f.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "oscillations",
    "The restoring force in a spring–mass SHM is",
    ["F = kx (away from mean)", "F = −kx", "F = −k/x", "F = m g"],
    1,
    "Hooke's law gives a linear restoring force toward the mean position.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "oscillations",
    "A seconds pendulum has a time period of",
    ["1 s and length about 0.25 m", "2 s and length about 1 m", "2 s and length about 2 m", "0.5 s"],
    1,
    "T = 2 s by definition; ℓ = g T²/(4π²) ≈ 0.99 m ≈ 1 m on Earth.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "oscillations",
    "Time period of a simple pendulum is proportional to",
    ["ℓ", "√ℓ", "1/ℓ", "ℓ²"],
    1,
    "T ∝ √ℓ and T ∝ 1/√g.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "oscillations",
    "If a simple pendulum is taken to the Moon, its time period",
    ["decreases", "increases", "remains the same", "becomes zero"],
    1,
    "g_Moon ≈ g_Earth/6, so T_Moon ≈ T √6, i.e. the pendulum runs slow.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "oscillations",
    "In undamped SHM the total mechanical energy",
    ["decreases with time", "increases with time", "remains constant", "is always purely kinetic"],
    2,
    "No non-conservative work, so K + U = (1/2)kA² is constant; they interchange.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "oscillations",
    "At the mean position of SHM",
    ["velocity is zero and acceleration is maximum", "velocity is maximum and acceleration is zero", "both are maximum", "both are zero"],
    1,
    "x = 0 ⇒ a = −ω²x = 0 and |v| = ωA = maximum.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "oscillations",
    "Two springs of constants k₁ and k₂ in series have equivalent k",
    ["k₁ + k₂", "k₁ k₂ / (k₁ + k₂)", "√(k₁ k₂)", "(k₁ + k₂)/2"],
    1,
    "1/k_eq = 1/k₁ + 1/k₂, so k_eq = k₁k₂/(k₁+k₂) (weaker than either spring).",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "oscillations",
    "Two springs of constants k₁ and k₂ in parallel have equivalent k",
    ["k₁ + k₂", "k₁ k₂ / (k₁ + k₂)", "k₁ − k₂", "k₁ k₂"],
    0,
    "k_eq = k₁ + k₂ (stiffer combination); T = 2π √(m/k_eq) decreases.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "oscillations",
    "At displacement x = A/√2 in SHM, kinetic energy is",
    ["zero", "equal to potential energy", "twice the potential energy", "total energy"],
    1,
    "K = (1/2)k(A² − x²) and U = (1/2)kx². At x² = A²/2, K = U = E/2.",
  ),
];

const waves: PracticeQuestionSeed[] = [
  cbsePyq(
    "class-11",
    "physics",
    "waves",
    "The relation among speed, frequency and wavelength of a wave is",
    ["v = f / λ", "v = f λ", "v = λ / f", "v = f + λ"],
    1,
    "v = fλ = ω/k.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "waves",
    "Speed of a transverse wave on a stretched string is",
    ["√(T/μ)", "√(μ/T)", "T μ", "T / μ"],
    0,
    "v = √(T/μ), where T is tension and μ is linear mass density.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "waves",
    "The beat frequency produced by two notes of frequencies n₁ and n₂ is",
    ["n₁ + n₂", "|n₁ − n₂|", "n₁ n₂", "(n₁ + n₂)/2"],
    1,
    "Beats arise from superposition; the envelope repeats at |n₁ − n₂|.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "waves",
    "The principle of superposition of waves states that the resultant displacement is",
    ["the product of individual displacements", "the algebraic (vector) sum of individual displacements", "the difference of intensities", "always zero"],
    1,
    "In a linear medium, y = y₁ + y₂ + … at each point and time.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "waves",
    "In a standing wave, a node is a point of",
    ["maximum displacement always", "zero displacement at all times", "maximum energy flux", "unbounded amplitude"],
    1,
    "Destructive interference is permanent at a node; y = 0 for all t.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "waves",
    "The distance between two consecutive nodes in a standing wave is",
    ["λ", "λ/2", "λ/4", "2λ"],
    1,
    "Nodes (and antinodes) are spaced λ/2 apart; node to neighbouring antinode is λ/4.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "waves",
    "The fundamental wavelength in an open organ pipe of length L is",
    ["L", "2L", "4L", "L/2"],
    1,
    "Both ends are antinodes, so L = λ/2 ⇒ λ = 2L and f = v/(2L).",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "waves",
    "The fundamental wavelength in a closed organ pipe of length L is",
    ["2L", "4L", "L", "L/4"],
    1,
    "Closed end is a node, open end an antinode, so L = λ/4 ⇒ λ = 4L and f = v/(4L).",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "waves",
    "In the Doppler effect, when a source moves toward a stationary observer the apparent frequency",
    ["decreases", "increases", "is unchanged", "becomes zero"],
    1,
    "f' = f v / (v − v_s) when the source approaches; wavelength in front is compressed.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "waves",
    "Sound waves in air are",
    ["transverse", "longitudinal", "electromagnetic", "stationary only"],
    1,
    "Oscillations of air are along the direction of propagation (compressions and rarefactions).",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "waves",
    "Intensity of a wave is proportional to",
    ["amplitude", "the square of amplitude", "1/amplitude", "frequency only, never A"],
    1,
    "I ∝ A² (and for a spherical wave also I ∝ 1/r²).",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "waves",
    "A progressive wave travelling in the +x direction can be written as",
    ["y = A sin(ωt − kx)", "y = A sin(ωt + kx)", "y = A sin kx only", "y = A ω t"],
    0,
    "y = f(ωt − kx) travels toward +x; y = f(ωt + kx) toward −x.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "waves",
    "The angular wave number k is",
    ["2π / λ", "2π λ", "ω λ", "λ / 2π"],
    0,
    "k = 2π/λ. Also ω = 2πf and v = ω/k.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "waves",
    "Laplace's correction to Newton's formula for the speed of sound in a gas is",
    ["v = √(P/ρ)", "v = √(γ P/ρ)", "v = √(P ρ)", "v = γ P / ρ"],
    1,
    "Compressions are adiabatic, not isothermal, so Newton's √(P/ρ) is replaced by √(γP/ρ).",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "waves",
    "Newton's original formula for the speed of sound in air (isothermal) was",
    ["√(P/ρ)", "√(γ P/ρ)", "√(γ ρ / P)", "f λ only"],
    0,
    "It underestimates the measured speed because sound propagation is adiabatic.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "waves",
    "Phase difference corresponding to a path difference Δx is",
    ["(2π/λ) Δx", "(λ/2π) Δx", "2π λ Δx", "Δx / λ only in degrees always"],
    0,
    "δ = (2π/λ) Δx = k Δx. A path of λ/2 gives phase π (destructive if amplitudes equal).",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "waves",
    "The speed of sound in an ideal gas varies with absolute temperature as",
    ["T", "√T", "1/T", "T²"],
    1,
    "v = √(γRT/M) ∝ √T. At constant T it is independent of pressure.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "waves",
    "Waves on a stretched string are",
    ["longitudinal", "transverse", "electromagnetic", "pressure waves in the string material only"],
    1,
    "Particles oscillate perpendicular to the wave velocity along the string.",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "waves",
    "A closed organ pipe of length L overtones are",
    ["all integer harmonics n v/(2L)", "only odd harmonics (2n−1) v/(4L)", "only even harmonics", "independent of L"],
    1,
    "Allowed frequencies: v/4L, 3v/4L, 5v/4L, … (odd harmonics of the fundamental).",
  ),
  cbsePyq(
    "class-11",
    "physics",
    "waves",
    "When a wave on a string is reflected from a rigid (fixed) end, it undergoes a phase change of",
    ["0", "π (inversion)", "π/2", "2π only as a path of λ"],
    1,
    "Reflection at a denser/fixed boundary inverts the wave (phase shift of π); a free end does not invert.",
  ),
];

export const class11PhysicsQuestions: PracticeQuestionSeed[] = [
  ...unitsAndMeasurements,
  ...motionInAStraightLine,
  ...motionInAPlane,
  ...lawsOfMotion,
  ...workEnergyAndPower,
  ...systemOfParticlesAndRotationalMotion,
  ...gravitation,
  ...mechanicalPropertiesOfSolids,
  ...mechanicalPropertiesOfFluids,
  ...thermalPropertiesOfMatter,
  ...thermodynamics,
  ...kineticTheory,
  ...oscillations,
  ...waves,
];

assertTwentyPerChapter(class11PhysicsQuestions, [
  "units-and-measurements",
  "motion-in-a-straight-line",
  "motion-in-a-plane",
  "laws-of-motion",
  "work-energy-and-power",
  "system-of-particles-and-rotational-motion",
  "gravitation",
  "mechanical-properties-of-solids",
  "mechanical-properties-of-fluids",
  "thermal-properties-of-matter",
  "thermodynamics",
  "kinetic-theory",
  "oscillations",
  "waves",
]);
