import { assertTwentyPerChapter, class12Pyq, type PracticeQuestionSeed } from "./types";

const electricChargesAndFields: PracticeQuestionSeed[] = [
  class12Pyq(
    "physics",
    "electric-charges-and-fields",
    "According to Coulomb's law, the electrostatic force between two point charges is",
    ["inversely proportional to the separation r", "inversely proportional to r²", "directly proportional to r²", "independent of r"],
    1,
    "F = (1/4πε0) q1 q2 / r², so F ∝ 1/r².",
  ),
  class12Pyq(
    "physics",
    "electric-charges-and-fields",
    "If the distance between two point charges is doubled, the electrostatic force becomes",
    ["twice", "four times", "half", "one-fourth"],
    3,
    "F ∝ 1/r². Doubling r makes the force F/4.",
  ),
  class12Pyq(
    "physics",
    "electric-charges-and-fields",
    "The SI unit of electric field intensity is",
    ["N", "N C⁻¹", "C N⁻¹", "C"],
    1,
    "E = F/q, so the unit is N/C (also V/m).",
  ),
  class12Pyq(
    "physics",
    "electric-charges-and-fields",
    "Gauss's law states that the electric flux through a closed surface is",
    ["q ε0", "q/ε0", "ε0/q", "q²/ε0"],
    1,
    "ΦE = q_enclosed / ε0 for any closed Gaussian surface.",
  ),
  class12Pyq(
    "physics",
    "electric-charges-and-fields",
    "The electric field due to an infinite plane sheet of surface charge density σ is",
    ["σ/ε0", "σ/2ε0", "2σ/ε0", "σ/4πε0"],
    1,
    "From Gauss's law, E = σ/(2ε0) and is independent of distance from the sheet.",
  ),
  class12Pyq(
    "physics",
    "electric-charges-and-fields",
    "The electric field due to an infinite line charge of linear density λ at perpendicular distance r is",
    ["λ/(2πε0 r)", "λ/(4πε0 r)", "λ/(2πε0 r²)", "λ/(4πε0 r²)"],
    0,
    "A cylindrical Gaussian surface gives E · 2πrℓ = λℓ/ε0, so E = λ/(2πε0 r).",
  ),
  class12Pyq(
    "physics",
    "electric-charges-and-fields",
    "The electric field inside a uniformly charged thin spherical shell is",
    ["maximum at the centre", "σ/ε0", "zero", "kQ/R²"],
    2,
    "For r < R, q_enclosed = 0, so Gauss's law gives E = 0.",
  ),
  class12Pyq(
    "physics",
    "electric-charges-and-fields",
    "The electric dipole moment of charges +q and −q separated by 2a is",
    ["qa", "2qa", "q/(2a)", "2q/a"],
    1,
    "p = q × 2a = 2qa, directed from −q to +q.",
  ),
  class12Pyq(
    "physics",
    "electric-charges-and-fields",
    "The electric field on the axial line of a short dipole of moment p at distance r is",
    ["kp/r³", "2kp/r³", "kp/r²", "4kp/r³"],
    1,
    "E_axial = (1/4πε0) (2p/r³), along the direction of p.",
  ),
  class12Pyq(
    "physics",
    "electric-charges-and-fields",
    "The electric field on the equatorial line of a short dipole is",
    ["2kp/r³ along p", "kp/r³ opposite to p", "kp/r² along p", "zero"],
    1,
    "E_eq = (1/4πε0) (p/r³), antiparallel to the dipole moment.",
  ),
  class12Pyq(
    "physics",
    "electric-charges-and-fields",
    "Torque on an electric dipole of moment p in a uniform electric field E is",
    ["p · E", "p × E", "p/E", "E/p"],
    1,
    "τ = p E sinθ; in vector form τ = p × E.",
  ),
  class12Pyq(
    "physics",
    "electric-charges-and-fields",
    "A charge Q is placed at the centre of a cube. The electric flux through one face is",
    ["Q/ε0", "Q/2ε0", "Q/6ε0", "Q/8ε0"],
    2,
    "Total flux through the cube is Q/ε0. By symmetry each of the 6 faces gets Q/6ε0.",
  ),
  class12Pyq(
    "physics",
    "electric-charges-and-fields",
    "Electric charge is quantized. The charge on a body is always",
    ["a fraction of e", "an integral multiple of e", "equal to e only", "independent of e"],
    1,
    "q = ±ne, where n = 0, 1, 2, … and e is the elementary charge.",
  ),
  class12Pyq(
    "physics",
    "electric-charges-and-fields",
    "The force on a charge q placed in a uniform electric field E is",
    ["q/E", "E/q", "qE", "q²E"],
    2,
    "By definition E = F/q, so F = qE.",
  ),
  class12Pyq(
    "physics",
    "electric-charges-and-fields",
    "The electrostatic force between two charges is F. If each charge is doubled and the separation is halved, the new force is",
    ["F", "4F", "8F", "16F"],
    3,
    "F' = k(2q)(2q)/(r/2)² = 4 kq² /(r²/4) = 16F.",
  ),
  class12Pyq(
    "physics",
    "electric-charges-and-fields",
    "Outside a uniformly charged insulating solid sphere, the electric field is the same as that of",
    ["an electric dipole at the centre", "a point charge equal to total charge at the centre", "a uniformly charged ring", "zero"],
    1,
    "For r > R, Gauss's law gives E = kQ/r², identical to a point charge Q at the centre.",
  ),
  class12Pyq(
    "physics",
    "electric-charges-and-fields",
    "The SI unit of electric flux is",
    ["N m² C⁻¹", "N C", "C m⁻²", "N m⁻²"],
    0,
    "ΦE = E · A, so the unit is N m²/C (also V m).",
  ),
  class12Pyq(
    "physics",
    "electric-charges-and-fields",
    "The net force on an electric dipole placed in a uniform electric field is",
    ["pE", "zero", "pE sinθ", "2qE"],
    1,
    "Forces on +q and −q are equal and opposite, so net F = 0; a torque may still act.",
  ),
  class12Pyq(
    "physics",
    "electric-charges-and-fields",
    "Gauss's law is valid for",
    ["only point charges", "only spherical surfaces", "any closed surface", "only a cube"],
    2,
    "∮ E · dA = q_enclosed/ε0 holds for every closed surface, of any shape.",
  ),
  class12Pyq(
    "physics",
    "electric-charges-and-fields",
    "Linear charge density λ is defined as",
    ["charge per unit volume", "charge per unit area", "charge per unit length", "total charge on a body"],
    2,
    "λ = dq/dl; σ is surface density and ρ is volume density.",
  ),
];

const electrostaticPotentialAndCapacitance: PracticeQuestionSeed[] = [
  class12Pyq(
    "physics",
    "electrostatic-potential-and-capacitance",
    "The electrostatic potential due to a point charge q at distance r is",
    ["(1/4πε0) q/r²", "(1/4πε0) q/r", "(1/4πε0) q²/r", "q ε0 / r"],
    1,
    "V = (1/4πε0) q/r, taking V = 0 at infinity.",
  ),
  class12Pyq(
    "physics",
    "electrostatic-potential-and-capacitance",
    "The relation between electric field E and potential V along a line is",
    ["E = dV/dr", "E = −dV/dr", "E = V/r²", "E = −V r"],
    1,
    "E is the negative gradient of V; in one dimension E = −dV/dr.",
  ),
  class12Pyq(
    "physics",
    "electrostatic-potential-and-capacitance",
    "Work done in moving a test charge on an equipotential surface is",
    ["maximum", "qV", "zero", "qE · dr"],
    2,
    "ΔV = 0 on an equipotential, so W = q ΔV = 0.",
  ),
  class12Pyq(
    "physics",
    "electrostatic-potential-and-capacitance",
    "Capacitance of a parallel-plate capacitor with plate area A and separation d (vacuum) is",
    ["ε0 A d", "ε0 A / d", "A /(ε0 d)", "ε0 d / A"],
    1,
    "C = ε0 A/d for a vacuum (or air) parallel-plate capacitor.",
  ),
  class12Pyq(
    "physics",
    "electrostatic-potential-and-capacitance",
    "The equivalent capacitance of two capacitors C1 and C2 connected in series is",
    ["C1 + C2", "C1 C2 /(C1 + C2)", "(C1 + C2)/C1 C2", "C1 − C2"],
    1,
    "1/Cs = 1/C1 + 1/C2, so Cs = C1 C2/(C1 + C2).",
  ),
  class12Pyq(
    "physics",
    "electrostatic-potential-and-capacitance",
    "Capacitors C1 and C2 in parallel have equivalent capacitance",
    ["C1 + C2", "C1 C2 /(C1 + C2)", "C1 − C2", "1/C1 + 1/C2"],
    0,
    "Charges add at the same potential, so Cp = C1 + C2.",
  ),
  class12Pyq(
    "physics",
    "electrostatic-potential-and-capacitance",
    "Energy stored in a capacitor of capacitance C charged to potential V is",
    ["CV", "(1/2) CV²", "CV²", "(1/2) C/V"],
    1,
    "U = (1/2) CV² = (1/2) QV = Q²/(2C).",
  ),
  class12Pyq(
    "physics",
    "electrostatic-potential-and-capacitance",
    "When a dielectric of dielectric constant K completely fills a capacitor (battery disconnected), capacitance",
    ["becomes K times", "becomes 1/K times", "remains the same", "becomes K² times"],
    0,
    "C' = K C. With charge fixed, V decreases by K and energy decreases.",
  ),
  class12Pyq(
    "physics",
    "electrostatic-potential-and-capacitance",
    "Potential energy of an electric dipole p in a uniform field E is",
    ["p E", "−p · E", "p × E", "p/E"],
    1,
    "U = −p E cosθ = −p · E, taking U = 0 when θ = 90°.",
  ),
  class12Pyq(
    "physics",
    "electrostatic-potential-and-capacitance",
    "Work done by an external agent in slowly moving charge q from A to B without acceleration is",
    ["q (VA − VB)", "q (VB − VA)", "q E d", "zero always"],
    1,
    "W_ext = ΔU = q (VB − VA) when kinetic energy is unchanged.",
  ),
  class12Pyq(
    "physics",
    "electrostatic-potential-and-capacitance",
    "The electrostatic potential inside a charged conducting sphere is",
    ["zero", "maximum at the centre", "constant and equal to the surface potential", "inversely proportional to r"],
    2,
    "E = 0 inside a conductor, so V is constant and equals V_surface.",
  ),
  class12Pyq(
    "physics",
    "electrostatic-potential-and-capacitance",
    "Capacitance of an isolated spherical conductor of radius R is",
    ["4πε0 / R", "4πε0 R", "4πR / ε0", "ε0 / R"],
    1,
    "V = (1/4πε0) Q/R, so C = Q/V = 4πε0 R.",
  ),
  class12Pyq(
    "physics",
    "electrostatic-potential-and-capacitance",
    "The energy density of an electrostatic field E in vacuum is",
    ["(1/2) ε0 E²", "ε0 E²", "(1/2) E²/ε0", "ε0 E"],
    0,
    "u = (1/2) ε0 E² joule per cubic metre.",
  ),
  class12Pyq(
    "physics",
    "electrostatic-potential-and-capacitance",
    "Two capacitors 4 μF and 6 μF are connected in series. The equivalent capacitance is",
    ["10 μF", "5 μF", "2.4 μF", "24 μF"],
    2,
    "Cs = (4 × 6)/(4 + 6) = 24/10 = 2.4 μF.",
  ),
  class12Pyq(
    "physics",
    "electrostatic-potential-and-capacitance",
    "If the plate separation of a parallel-plate capacitor is halved, its capacitance",
    ["halves", "doubles", "becomes four times", "remains the same"],
    1,
    "C ∝ 1/d, so reducing d to d/2 doubles C.",
  ),
  class12Pyq(
    "physics",
    "electrostatic-potential-and-capacitance",
    "The potential due to a short dipole on its axial line at distance r is",
    ["kp/r²", "kp/r³", "2kp/r²", "zero"],
    0,
    "V_axial = (1/4πε0) p/r²; equatorial potential of a dipole is zero.",
  ),
  class12Pyq(
    "physics",
    "electrostatic-potential-and-capacitance",
    "Electrostatic potential is a",
    ["vector quantity", "scalar quantity", "tensor", "dimensionless quantity"],
    1,
    "V is a scalar; potentials add algebraically (superposition).",
  ),
  class12Pyq(
    "physics",
    "electrostatic-potential-and-capacitance",
    "A dielectric slab is inserted between the plates of a capacitor connected to a battery. The charge on the plates",
    ["decreases", "increases", "becomes zero", "remains the same"],
    1,
    "Battery keeps V constant. C → KC so Q = CV increases by factor K.",
  ),
  class12Pyq(
    "physics",
    "electrostatic-potential-and-capacitance",
    "The SI unit of capacitance is the farad, which is equivalent to",
    ["C V", "C V⁻¹", "V C⁻¹", "N C⁻¹"],
    1,
    "C = Q/V, so 1 F = 1 C/V.",
  ),
  class12Pyq(
    "physics",
    "electrostatic-potential-and-capacitance",
    "On an equipotential surface, the electric field is",
    ["parallel to the surface", "perpendicular to the surface", "zero always", "at 45° to the surface"],
    1,
    "E = −∇V is normal to surfaces of constant V; no tangential component.",
  ),
];

const currentElectricity: PracticeQuestionSeed[] = [
  class12Pyq(
    "physics",
    "current-electricity",
    "Ohm's law (V = IR) is valid for",
    ["all materials under all conditions", "ohmic conductors at constant temperature", "semiconductors only", "electrolytes only"],
    1,
    "Ohm's law holds for ohmic devices whose V–I graph is a straight line through the origin.",
  ),
  class12Pyq(
    "physics",
    "current-electricity",
    "The relation between current I and drift speed vd is",
    ["I = n e vd", "I = n e A vd", "I = n e A / vd", "I = vd /(n e A)"],
    1,
    "I = n e A vd, where n is number density of charge carriers.",
  ),
  class12Pyq(
    "physics",
    "current-electricity",
    "Drift velocity of electrons in a metal is of order",
    ["10⁸ m/s", "10⁻⁴ m/s", "3 × 10⁸ m/s", "10² m/s"],
    1,
    "vd is typically 10⁻⁴ to 10⁻³ m/s, much smaller than thermal speeds.",
  ),
  class12Pyq(
    "physics",
    "current-electricity",
    "Resistivity ρ of a wire is given by",
    ["ρ = R ℓ / A", "ρ = R A / ℓ", "ρ = R A ℓ", "ρ = ℓ /(R A)"],
    1,
    "R = ρ ℓ/A, hence ρ = R A/ℓ. Resistivity is material-dependent.",
  ),
  class12Pyq(
    "physics",
    "current-electricity",
    "Kirchhoff's junction rule is based on conservation of",
    ["energy", "charge", "momentum", "mass"],
    1,
    "Σ I = 0 at a junction: charge cannot accumulate there.",
  ),
  class12Pyq(
    "physics",
    "current-electricity",
    "Kirchhoff's loop rule is based on conservation of",
    ["charge", "energy", "momentum", "mass"],
    1,
    "The algebraic sum of p.d. around a closed loop is zero (energy conservation).",
  ),
  class12Pyq(
    "physics",
    "current-electricity",
    "A Wheatstone bridge is balanced when",
    ["P/Q = R/S", "P/Q = S/R", "P + Q = R + S", "P Q = R S"],
    0,
    "The standard balance condition is P/Q = R/S (no current in the galvanometer).",
  ),
  class12Pyq(
    "physics",
    "current-electricity",
    "In a meter bridge, the unknown resistance X is (ℓ = balancing length from the known-R end)",
    ["X = R (ℓ)/(100 − ℓ)", "X = R (100 − ℓ)/ℓ", "X = R ℓ", "X = 100 R / ℓ"],
    1,
    "If R is in the left gap and balance is at ℓ cm, X/R = (100 − ℓ)/ℓ.",
  ),
  class12Pyq(
    "physics",
    "current-electricity",
    "A potentiometer is preferred over a voltmeter for measuring emf of a cell because",
    ["it has higher resistance", "it draws no current from the cell at null point", "it is cheaper", "it uses a galvanometer"],
    1,
    "At balance, current from the test cell is zero, so true emf is measured.",
  ),
  class12Pyq(
    "physics",
    "current-electricity",
    "Terminal voltage V of a cell of emf E and internal resistance r delivering current I is",
    ["V = E + I r", "V = E − I r", "V = I r − E", "V = E"],
    1,
    "V = E − Ir when the cell is discharging through an external circuit.",
  ),
  class12Pyq(
    "physics",
    "current-electricity",
    "Internal resistance r of a cell can be obtained from",
    ["r = (E/V − 1) R", "r = (V/E − 1) R", "r = E R / V", "r = V R / E"],
    0,
    "V = E R/(R + r) gives r = R(E − V)/V = (E/V − 1)R.",
  ),
  class12Pyq(
    "physics",
    "current-electricity",
    "Three resistors of 2 Ω, 3 Ω and 6 Ω are connected in parallel. The equivalent resistance is",
    ["11 Ω", "1 Ω", "2 Ω", "0.5 Ω"],
    1,
    "1/Rp = 1/2 + 1/3 + 1/6 = 1, so Rp = 1 Ω.",
  ),
  class12Pyq(
    "physics",
    "current-electricity",
    "Electrical power dissipated in a resistor R carrying current I is",
    ["I R", "I² R", "I / R", "I² / R"],
    1,
    "P = I² R = V I = V²/R.",
  ),
  class12Pyq(
    "physics",
    "current-electricity",
    "The temperature coefficient of resistance α is defined by",
    ["R = R0 (1 + α ΔT)", "R = R0 α ΔT", "R = R0 /(1 + α ΔT)", "R = α / R0"],
    0,
    "Rt = R0 [1 + α(t − t0)] for metals over a limited range.",
  ),
  class12Pyq(
    "physics",
    "current-electricity",
    "Conductivity σ of a material is related to resistivity ρ by",
    ["σ = ρ", "σ = 1/ρ", "σ = ρ²", "σ = 1/ρ²"],
    1,
    "σ = 1/ρ. Also J = σ E.",
  ),
  class12Pyq(
    "physics",
    "current-electricity",
    "Mobility μ of a charge carrier is",
    ["vd / E", "E / vd", "vd E", "n e vd"],
    0,
    "μ = vd/E; current density J = n e μ E.",
  ),
  class12Pyq(
    "physics",
    "current-electricity",
    "n identical cells each of emf E and internal resistance r are connected in series. The equivalent emf and internal resistance are",
    ["E, r", "nE, nr", "nE, r/n", "E/n, nr"],
    1,
    "Series: emfs add (nE) and internal resistances add (nr).",
  ),
  class12Pyq(
    "physics",
    "current-electricity",
    "In a balanced Wheatstone bridge, the current in the galvanometer branch is",
    ["maximum", "E/R", "zero", "infinite"],
    2,
    "Balance means no potential difference across the galvanometer, so IG = 0.",
  ),
  class12Pyq(
    "physics",
    "current-electricity",
    "The colour code for a carbon resistor of 1 kΩ with 5% tolerance is",
    ["brown black red gold", "brown black brown gold", "brown black orange gold", "red black red gold"],
    0,
    "1 kΩ = 10 × 10² Ω: brown (1), black (0), red (×100), gold (±5%).",
  ),
  class12Pyq(
    "physics",
    "current-electricity",
    "Emf of a cell is the potential difference across its terminals when",
    ["a large current is drawn", "no current is drawn from the cell", "it is short-circuited", "it is being charged"],
    1,
    "E is the open-circuit terminal p.d.; when I = 0, V = E.",
  ),
];

const movingChargesAndMagnetism: PracticeQuestionSeed[] = [
  class12Pyq(
    "physics",
    "moving-charges-and-magnetism",
    "The Lorentz magnetic force on a charge q moving with velocity v in field B is",
    ["q (v · B)", "q (v × B)", "q B / v", "q v / B"],
    1,
    "F_m = q (v × B). The full Lorentz force is q[E + v × B].",
  ),
  class12Pyq(
    "physics",
    "moving-charges-and-magnetism",
    "Force on a current-carrying conductor in a magnetic field is",
    ["F = I (ℓ · B)", "F = I (ℓ × B)", "F = I ℓ / B", "F = B / (I ℓ)"],
    1,
    "F = I ℓ B sinθ, or F = I (ℓ × B).",
  ),
  class12Pyq(
    "physics",
    "moving-charges-and-magnetism",
    "Magnetic field at the centre of a circular coil of radius R carrying current I is",
    ["μ0 I /(2π R)", "μ0 I /(2 R)", "μ0 I / R", "μ0 I /(4π R)"],
    1,
    "Biot–Savart gives B = μ0 I /(2R) at the centre, perpendicular to the plane.",
  ),
  class12Pyq(
    "physics",
    "moving-charges-and-magnetism",
    "Magnetic field due to an infinite straight wire at perpendicular distance r is",
    ["μ0 I /(2π r)", "μ0 I /(2 r)", "μ0 I /(4π r)", "μ0 I / r"],
    0,
    "Ampere's law: ∮ B · dl = μ0 I gives B = μ0 I /(2π r).",
  ),
  class12Pyq(
    "physics",
    "moving-charges-and-magnetism",
    "Magnetic field inside a long solenoid with n turns per unit length carrying I is",
    ["μ0 n I", "μ0 n I / 2", "μ0 I /(2π n)", "μ0 I / n"],
    0,
    "Ampere's law for a long solenoid yields B = μ0 n I along the axis.",
  ),
  class12Pyq(
    "physics",
    "moving-charges-and-magnetism",
    "Force per unit length between two long parallel wires carrying I1 and I2 separated by d is",
    ["μ0 I1 I2 /(2π d)", "μ0 I1 I2 /(4π d)", "μ0 I1 I2 / d", "μ0 I1 I2 /(2 d)"],
    0,
    "F/ℓ = μ0 I1 I2 /(2π d). This is the basis of the definition of the ampere.",
  ),
  class12Pyq(
    "physics",
    "moving-charges-and-magnetism",
    "The cyclotron frequency of a charged particle is",
    ["q B / (2π m)", "q B / m", "2π m /(q B)", "m /(q B)"],
    0,
    "f = qB/(2π m), independent of speed (non-relativistic).",
  ),
  class12Pyq(
    "physics",
    "moving-charges-and-magnetism",
    "Radius of the circular path of a charged particle in a uniform magnetic field is",
    ["mv /(q B)", "q B /(m v)", "m v B / q", "q v /(m B)"],
    0,
    "qvB = mv²/r gives r = mv/(qB).",
  ),
  class12Pyq(
    "physics",
    "moving-charges-and-magnetism",
    "Torque on a magnetic dipole of moment m in a uniform field B is",
    ["m · B", "m × B", "m / B", "B / m"],
    1,
    "τ = m B sinθ = m × B, analogous to an electric dipole.",
  ),
  class12Pyq(
    "physics",
    "moving-charges-and-magnetism",
    "Magnetic moment of a current loop is",
    ["m = I / A", "m = I A", "m = I A²", "m = A / I"],
    1,
    "m = I A, directed by the right-hand rule normal to the loop.",
  ),
  class12Pyq(
    "physics",
    "moving-charges-and-magnetism",
    "In a velocity selector, the speed of undeflected particles is",
    ["v = E B", "v = E / B", "v = B / E", "v = E / B²"],
    1,
    "Electric and magnetic forces balance: qE = qvB ⇒ v = E/B.",
  ),
  class12Pyq(
    "physics",
    "moving-charges-and-magnetism",
    "Work done by the magnetic force on a charged particle is",
    ["q v B", "maximum", "zero", "q v B sinθ"],
    2,
    "F_m is always perpendicular to v, so power F · v = 0.",
  ),
  class12Pyq(
    "physics",
    "moving-charges-and-magnetism",
    "A charged particle moving parallel to a uniform magnetic field",
    ["moves in a circle", "is undeflected (straight line at constant speed)", "moves in a helix", "comes to rest"],
    1,
    "v × B = 0 when v ∥ B, so F = 0 and the path is a straight line.",
  ),
  class12Pyq(
    "physics",
    "moving-charges-and-magnetism",
    "Ampere's circuital law is",
    ["∮ B · dl = μ0 I", "∮ B · dl = I / μ0", "∮ B · dA = μ0 I", "∮ B · dl = 0"],
    0,
    "∮ B · dl = μ0 I_enclosed (steady currents; Maxwell later added displacement current).",
  ),
  class12Pyq(
    "physics",
    "moving-charges-and-magnetism",
    "The SI unit of magnetic field is tesla. 1 T is equal to",
    ["1 N A⁻¹ m⁻¹", "1 N A m", "1 N A⁻¹ m", "1 Wb"],
    0,
    "From F = I ℓ B, 1 T = 1 N A⁻¹ m⁻¹ = 1 Wb m⁻².",
  ),
  class12Pyq(
    "physics",
    "moving-charges-and-magnetism",
    "Pitch of the helical path of a charge in a magnetic field (v∥ along B) is",
    ["2π m v∥ /(q B)", "2π m v⊥ /(q B)", "m v /(q B)", "q B /(2π m)"],
    0,
    "T = 2π m/(qB) and pitch = v∥ T = 2π m v∥ /(qB).",
  ),
  class12Pyq(
    "physics",
    "moving-charges-and-magnetism",
    "Magnetic field at the centre of a current-carrying circular arc of angle θ (radius R) is",
    ["(θ/2π) μ0 I /(2R)", "(θ/4π) μ0 I / R", "μ0 I /(2R)", "zero"],
    0,
    "Full loop gives μ0 I/(2R); an arc subtending θ contributes the fraction θ/(2π).",
  ),
  class12Pyq(
    "physics",
    "moving-charges-and-magnetism",
    "Two parallel wires carrying currents in the same direction",
    ["repel each other", "attract each other", "experience no force", "rotate about their axes"],
    1,
    "Like currents attract; unlike currents repel.",
  ),
  class12Pyq(
    "physics",
    "moving-charges-and-magnetism",
    "Current sensitivity of a moving-coil galvanometer is",
    ["θ / I = N A B / k", "I / θ", "N B / (k A)", "k /(N A B)"],
    0,
    "τ = N I A B = k θ, so θ/I = NAB/k.",
  ),
  class12Pyq(
    "physics",
    "moving-charges-and-magnetism",
    "Magnetic field inside a long tightly wound toroid is",
    ["μ0 N I /(2π r)", "μ0 N I / r", "zero", "μ0 I /(2π r)"],
    0,
    "∮ B · dl = B · 2π r = μ0 N I, so B = μ0 N I /(2π r).",
  ),
];

const magnetismAndMatter: PracticeQuestionSeed[] = [
  class12Pyq(
    "physics",
    "magnetism-and-matter",
    "Gauss's law for magnetism states that",
    ["∮ B · dA = q/ε0", "∮ B · dA = 0", "∮ B · dl = μ0 I", "∮ B · dA = μ0"],
    1,
    "∮ B · dA = 0: isolated magnetic monopoles are not observed; field lines are closed.",
  ),
  class12Pyq(
    "physics",
    "magnetism-and-matter",
    "Magnetic declination at a place is the angle between",
    ["geographic meridian and magnetic meridian", "B and BH", "BH and BV", "the axis of the earth and magnetic axis"],
    0,
    "Declination is the angle from true north (geographic meridian) to magnetic north.",
  ),
  class12Pyq(
    "physics",
    "magnetism-and-matter",
    "Angle of dip at the magnetic equator is",
    ["90°", "45°", "0°", "60°"],
    2,
    "At the magnetic equator the total field is horizontal, so dip δ = 0°.",
  ),
  class12Pyq(
    "physics",
    "magnetism-and-matter",
    "Horizontal component of the earth's magnetic field is related to dip δ by",
    ["BH = B sin δ", "BH = B cos δ", "BH = B tan δ", "BH = B / cos δ"],
    1,
    "BH = B cos δ and BV = B sin δ, with tan δ = BV/BH.",
  ),
  class12Pyq(
    "physics",
    "magnetism-and-matter",
    "Angle of dip at the magnetic poles is",
    ["0°", "45°", "90°", "180°"],
    2,
    "At the poles B is vertical, so δ = 90° and BH = 0.",
  ),
  class12Pyq(
    "physics",
    "magnetism-and-matter",
    "For a diamagnetic material, relative permeability μr is",
    ["slightly greater than 1", "slightly less than 1", "of the order of 10³", "exactly 0"],
    1,
    "Diamagnets have χ < 0 and μr = 1 + χ slightly less than 1.",
  ),
  class12Pyq(
    "physics",
    "magnetism-and-matter",
    "Which of the following is a paramagnetic substance?",
    ["bismuth", "copper", "aluminium", "lead"],
    2,
    "Aluminium is paramagnetic; Bi, Cu and Pb are diamagnetic.",
  ),
  class12Pyq(
    "physics",
    "magnetism-and-matter",
    "Ferromagnetic materials lose their spontaneous magnetisation above the",
    ["boiling point", "Curie temperature", "melting point", "Néel temperature only"],
    1,
    "Above the Curie temperature they behave as paramagnets.",
  ),
  class12Pyq(
    "physics",
    "magnetism-and-matter",
    "Magnetic susceptibility χ is related to relative permeability by",
    ["χ = μr + 1", "χ = μr − 1", "χ = 1/μr", "χ = μr"],
    1,
    "μr = 1 + χ, hence χ = μr − 1.",
  ),
  class12Pyq(
    "physics",
    "magnetism-and-matter",
    "Intensity of magnetisation M is defined as",
    ["magnetic moment per unit volume", "magnetic moment per unit mass", "B / μ0", "H / μ0"],
    0,
    "M = m_net / V. Also B = μ0 (H + M) in SI.",
  ),
  class12Pyq(
    "physics",
    "magnetism-and-matter",
    "The relation among B, H and M in SI units is",
    ["B = μ0 (H + M)", "B = μ0 H − M", "B = H + M", "B = μ0 H / M"],
    0,
    "B = μ0 (H + M) is the standard constitutive relation.",
  ),
  class12Pyq(
    "physics",
    "magnetism-and-matter",
    "Soft iron is preferred for electromagnets because it has",
    ["high retentivity and high coercivity", "low retentivity and low coercivity", "high retentivity and low coercivity", "low retentivity and high coercivity"],
    1,
    "A small hysteresis loop (low retentivity and coercivity) means easy magnetisation and demagnetisation.",
  ),
  class12Pyq(
    "physics",
    "magnetism-and-matter",
    "Steel is used for permanent magnets because it has",
    ["low retentivity and low coercivity", "high retentivity and high coercivity", "low retentivity and high coercivity", "high retentivity and low coercivity"],
    1,
    "Permanent magnets need to retain magnetisation (high retentivity) and resist demagnetisation (high coercivity).",
  ),
  class12Pyq(
    "physics",
    "magnetism-and-matter",
    "Magnetic field on the axial line of a short bar magnet (magnetic moment m) is",
    ["(μ0 / 4π) m / r³", "(μ0 / 4π) 2m / r³", "(μ0 / 4π) m / r²", "zero"],
    1,
    "B_axial = (μ0 / 4π) (2m / r³), analogous to the electric dipole.",
  ),
  class12Pyq(
    "physics",
    "magnetism-and-matter",
    "Magnetic field on the equatorial line of a short bar magnet is",
    ["(μ0 / 4π) 2m / r³", "(μ0 / 4π) m / r³", "(μ0 / 4π) m / r²", "(μ0 / 4π) 4m / r³"],
    1,
    "B_eq = (μ0 / 4π) (m / r³), opposite to the direction of m.",
  ),
  class12Pyq(
    "physics",
    "magnetism-and-matter",
    "Which material is ferromagnetic?",
    ["sodium", "copper", "nickel", "aluminium"],
    2,
    "Fe, Co, Ni and some alloys are ferromagnetic.",
  ),
  class12Pyq(
    "physics",
    "magnetism-and-matter",
    "Diamagnetic substances are characterised by",
    ["χ > 0 and μr > 1", "χ < 0 and μr < 1", "χ ≫ 1", "permanent atomic dipoles"],
    1,
    "Induced dipoles oppose the field: χ is small and negative.",
  ),
  class12Pyq(
    "physics",
    "magnetism-and-matter",
    "The area of a B–H hysteresis loop is a measure of",
    ["retentivity only", "energy loss per cycle per unit volume", "Curie temperature", "susceptibility"],
    1,
    "Hysteresis loss equals the loop area and appears as heat.",
  ),
  class12Pyq(
    "physics",
    "magnetism-and-matter",
    "A magnetic dipole of moment m is aligned with a uniform field B. Its potential energy is",
    ["+m B", "−m B", "zero", "m B / 2"],
    1,
    "U = −m · B. Minimum (−mB) when m is parallel to B (stable).",
  ),
  class12Pyq(
    "physics",
    "magnetism-and-matter",
    "The magnetic meridian is",
    ["a vertical plane containing the geographic north–south line", "a vertical plane containing the earth's magnetic field at the place", "the equator", "a horizontal plane"],
    1,
    "Magnetic meridian is the vertical plane in which the free compass needle lies.",
  ),
];

const electromagneticInduction: PracticeQuestionSeed[] = [
  class12Pyq(
    "physics",
    "electromagnetic-induction",
    "Faraday's law of electromagnetic induction is",
    ["ε = ΦB", "ε = −dΦB / dt", "ε = B ℓ v", "ε = L I"],
    1,
    "The induced emf equals the negative rate of change of magnetic flux.",
  ),
  class12Pyq(
    "physics",
    "electromagnetic-induction",
    "Lenz's law is a consequence of conservation of",
    ["charge", "energy", "momentum", "mass"],
    1,
    "The induced current opposes the change in flux, otherwise energy would not be conserved.",
  ),
  class12Pyq(
    "physics",
    "electromagnetic-induction",
    "Motional emf in a rod of length ℓ moving with speed v perpendicular to B is",
    ["B ℓ / v", "B ℓ v", "B v / ℓ", "ℓ v / B"],
    1,
    "ε = B ℓ v when B, ℓ and v are mutually perpendicular.",
  ),
  class12Pyq(
    "physics",
    "electromagnetic-induction",
    "Self-induced emf in a coil is",
    ["ε = L I", "ε = −L dI/dt", "ε = −M dI/dt", "ε = I dL/dt"],
    1,
    "By definition L = Φ/I (for a linear inductor), so ε = −L dI/dt.",
  ),
  class12Pyq(
    "physics",
    "electromagnetic-induction",
    "Energy stored in an inductor carrying current I is",
    ["L I", "(1/2) L I²", "L I²", "(1/2) L / I"],
    1,
    "U = (1/2) L I², stored in the magnetic field.",
  ),
  class12Pyq(
    "physics",
    "electromagnetic-induction",
    "Mutual inductance M of two coils satisfies",
    ["M12 ≠ M21 always", "M12 = M21 = M", "M = L1 + L2", "M = L1 L2"],
    1,
    "M12 = M21 = M (reciprocity) for a linear medium.",
  ),
  class12Pyq(
    "physics",
    "electromagnetic-induction",
    "Eddy currents are used in",
    ["reducing energy loss in transformer cores", "electromagnetic damping and induction furnaces", "increasing flux leakage", "producing static charges"],
    1,
    "Eddy currents provide damping (galvanometers) and heating (induction furnace); they are reduced in transformer cores by laminations.",
  ),
  class12Pyq(
    "physics",
    "electromagnetic-induction",
    "Magnetic flux through a surface is",
    ["ΦB = B × A", "ΦB = B · A", "ΦB = B / A", "ΦB = A / B"],
    1,
    "ΦB = B A cosθ = B · A. SI unit is the weber.",
  ),
  class12Pyq(
    "physics",
    "electromagnetic-induction",
    "The SI unit of inductance is the henry. 1 H equals",
    ["1 V s A⁻¹", "1 V A", "1 T m", "1 Wb A"],
    0,
    "ε = L dI/dt ⇒ 1 H = 1 V s/A = 1 Wb/A.",
  ),
  class12Pyq(
    "physics",
    "electromagnetic-induction",
    "A coil of N turns has flux Φ through each turn. The induced emf is",
    ["−dΦ/dt", "−N dΦ/dt", "−Φ dN/dt", "N Φ"],
    1,
    "Flux linkage is NΦ, so ε = −N dΦ/dt.",
  ),
  class12Pyq(
    "physics",
    "electromagnetic-induction",
    "Emf induced in a rod of length ℓ rotating with angular speed ω in a uniform B (axis at one end, B perpendicular to the plane) is",
    ["B ω ℓ", "(1/2) B ω ℓ²", "B ω ℓ²", "2 B ω ℓ²"],
    1,
    "ε = (1/2) B ω ℓ², obtained by integrating B v dr with v = ω r.",
  ),
  class12Pyq(
    "physics",
    "electromagnetic-induction",
    "Self-inductance of a long solenoid (n turns per unit length, area A, length ℓ) is",
    ["μ0 n A ℓ", "μ0 n² A ℓ", "μ0 n² A / ℓ", "μ0 n A / ℓ"],
    1,
    "Φ = B A = μ0 n I A; N = nℓ, so L = N Φ/I = μ0 n² A ℓ.",
  ),
  class12Pyq(
    "physics",
    "electromagnetic-induction",
    "The time constant of an LR circuit is",
    ["R L", "L / R", "R / L", "1/(L R)"],
    1,
    "τ = L/R. Current grows as I = I0 (1 − e^(−t/τ)).",
  ),
  class12Pyq(
    "physics",
    "electromagnetic-induction",
    "Laminated cores are used in transformers to",
    ["increase eddy currents", "reduce eddy-current losses", "increase hysteresis loss", "decrease flux"],
    1,
    "Thin insulated laminations break eddy paths and cut I²R heating.",
  ),
  class12Pyq(
    "physics",
    "electromagnetic-induction",
    "If the magnetic flux through a coil changes from 0.1 Wb to 0.3 Wb in 0.1 s, the magnitude of average induced emf (N = 1) is",
    ["0.2 V", "2 V", "20 V", "0.02 V"],
    1,
    "|ε| = ΔΦ/Δt = 0.2 / 0.1 = 2 V.",
  ),
  class12Pyq(
    "physics",
    "electromagnetic-induction",
    "The working of an AC generator is based on",
    ["Ohm's law", "electromagnetic induction", "photoelectric effect", "Ampere's law only"],
    1,
    "A coil rotating in a magnetic field produces a changing flux and hence an induced emf.",
  ),
  class12Pyq(
    "physics",
    "electromagnetic-induction",
    "Coefficient of coupling k of two coils is",
    ["k = M / √(L1 L2)", "k = M (L1 + L2)", "k = L1 L2 / M", "k = M L1 L2"],
    0,
    "0 ≤ k ≤ 1, with M = k √(L1 L2).",
  ),
  class12Pyq(
    "physics",
    "electromagnetic-induction",
    "A metallic plate is allowed to fall through a magnetic field. It falls slower than in free space because of",
    ["air friction only", "eddy currents opposing the motion (Lenz)", "electrostatic induction", "increase of weight"],
    1,
    "Changing flux induces eddy currents whose magnetic force opposes the fall.",
  ),
  class12Pyq(
    "physics",
    "electromagnetic-induction",
    "Mutual inductance of two coaxial solenoids is proportional to",
    ["n1 + n2", "n1 n2", "n1 / n2", "n1 − n2"],
    1,
    "M = μ0 n1 n2 π r² ℓ for a long pair (r = radius of the inner solenoid).",
  ),
  class12Pyq(
    "physics",
    "electromagnetic-induction",
    "The direction of induced current is given by",
    ["Coulomb's law", "Lenz's law", "Gauss's law", "Snell's law"],
    1,
    "Lenz's law fixes the sense so that the induced current opposes the flux change.",
  ),
];

const alternatingCurrent: PracticeQuestionSeed[] = [
  class12Pyq(
    "physics",
    "alternating-current",
    "The rms value of an alternating current I = I0 sin ωt is",
    ["I0", "I0 / 2", "I0 / √2", "I0 √2"],
    2,
    "Irms = I0 / √2 ≈ 0.707 I0 for a sinusoidal current.",
  ),
  class12Pyq(
    "physics",
    "alternating-current",
    "Peak value of household 220 V AC is approximately",
    ["220 V", "110 V", "311 V", "440 V"],
    2,
    "V0 = Vrms √2 = 220 √2 ≈ 311 V.",
  ),
  class12Pyq(
    "physics",
    "alternating-current",
    "Inductive reactance XL is",
    ["1/(ω L)", "ω L", "ω / L", "L / ω"],
    1,
    "XL = ωL = 2π f L. It increases with frequency.",
  ),
  class12Pyq(
    "physics",
    "alternating-current",
    "Capacitive reactance XC is",
    ["ω C", "1/(ω C)", "ω / C", "C / ω"],
    1,
    "XC = 1/(ωC). It decreases as frequency increases.",
  ),
  class12Pyq(
    "physics",
    "alternating-current",
    "Impedance of a series LCR circuit is",
    ["Z = R + XL + XC", "Z = √[R² + (XL − XC)²]", "Z = R (XL − XC)", "Z = √[R² + XL XC]"],
    1,
    "Z = √[R² + (XL − XC)²]; current I = V/Z.",
  ),
  class12Pyq(
    "physics",
    "alternating-current",
    "The resonant angular frequency of a series LCR circuit is",
    ["ω0 = √(LC)", "ω0 = 1/√(LC)", "ω0 = L/C", "ω0 = R/L"],
    1,
    "At resonance XL = XC ⇒ ω0 L = 1/(ω0 C) ⇒ ω0 = 1/√(LC).",
  ),
  class12Pyq(
    "physics",
    "alternating-current",
    "At resonance in a series LCR circuit, the current is",
    ["minimum", "maximum", "zero", "independent of R"],
    1,
    "Z is minimum and equal to R, so I = V/R is maximum.",
  ),
  class12Pyq(
    "physics",
    "alternating-current",
    "Power factor of a series LCR circuit is",
    ["sin φ", "cos φ = R/Z", "tan φ", "Z/R"],
    1,
    "cos φ = R/Z. It is 1 at resonance (purely resistive).",
  ),
  class12Pyq(
    "physics",
    "alternating-current",
    "Average power in an AC circuit is",
    ["Vrms Irms", "Vrms Irms cos φ", "V0 I0", "zero always"],
    1,
    "Pav = Vrms Irms cos φ = (1/2) V0 I0 cos φ.",
  ),
  class12Pyq(
    "physics",
    "alternating-current",
    "Quality factor Q of a series LCR circuit is",
    ["R / (ω0 L)", "ω0 L / R", "ω0 R / L", "L /(R C)"],
    1,
    "Q = ω0 L / R = 1/(ω0 C R). High Q means a sharp resonance.",
  ),
  class12Pyq(
    "physics",
    "alternating-current",
    "For an ideal transformer, Vs / Vp equals",
    ["Np / Ns", "Ns / Np", "Ip / Is always only", "1"],
    1,
    "Vs/Vp = Ns/Np. Also Vs Is = Vp Ip for an ideal transformer.",
  ),
  class12Pyq(
    "physics",
    "alternating-current",
    "The period of LC oscillations is",
    ["2π √(LC)", "2π √(L/C)", "2π / √(LC)", "√(LC)"],
    0,
    "T = 2π √(LC), analogous to a mass–spring period 2π √(m/k).",
  ),
  class12Pyq(
    "physics",
    "alternating-current",
    "Average power consumed by a pure inductor over a cycle is",
    ["Vrms Irms", "zero", "I² XL", "(1/2) LI²"],
    1,
    "φ = 90°, cos φ = 0, so Pav = 0 (energy is stored and returned).",
  ),
  class12Pyq(
    "physics",
    "alternating-current",
    "In a pure inductor, the current",
    ["leads the voltage by π/2", "lags the voltage by π/2", "is in phase with voltage", "lags by π"],
    1,
    "v = V0 sin ωt, i = I0 sin(ωt − π/2) for a pure L.",
  ),
  class12Pyq(
    "physics",
    "alternating-current",
    "In a pure capacitor, the current",
    ["lags the voltage by π/2", "leads the voltage by π/2", "is in phase", "leads by π"],
    1,
    "i = I0 sin(ωt + π/2) when v = V0 sin ωt.",
  ),
  class12Pyq(
    "physics",
    "alternating-current",
    "Wattless current in an AC circuit is the component",
    ["I cos φ", "I sin φ", "I", "I / Z"],
    1,
    "The quadrature component I sin φ contributes no average power.",
  ),
  class12Pyq(
    "physics",
    "alternating-current",
    "A step-up transformer",
    ["increases current and voltage", "increases voltage and decreases current", "decreases voltage", "works on DC"],
    1,
    "Ns > Np raises voltage; for constant power, current falls. Transformers need AC.",
  ),
  class12Pyq(
    "physics",
    "alternating-current",
    "Impedance of a series RC circuit is",
    ["√(R² + XC²)", "R + XC", "√(R² − XC²)", "R XC"],
    0,
    "Z = √[R² + XC²] with tan φ = XC/R (current leads).",
  ),
  class12Pyq(
    "physics",
    "alternating-current",
    "The bandwidth of a series LCR resonant circuit is",
    ["ω0", "R / L", "L / R", "1/√(LC)"],
    1,
    "Δω = R/L = ω0 / Q between half-power frequencies.",
  ),
  class12Pyq(
    "physics",
    "alternating-current",
    "The form factor of a sinusoidal AC is Irms / Iav, equal to",
    ["1", "π /(2√2) ≈ 1.11", "√2", "2/π"],
    1,
    "Irms = I0/√2, Iav = 2I0/π, so form factor = π/(2√2) ≈ 1.11.",
  ),
];

const electromagneticWaves: PracticeQuestionSeed[] = [
  class12Pyq(
    "physics",
    "electromagnetic-waves",
    "Displacement current is given by",
    ["Id = ε0 dΦE / dt", "Id = μ0 dΦE / dt", "Id = ε0 ΦE", "Id = dΦB / dt"],
    0,
    "Maxwell's correction: Id = ε0 dΦE/dt, so ∮ B · dl = μ0 (Ic + Id).",
  ),
  class12Pyq(
    "physics",
    "electromagnetic-waves",
    "Speed of electromagnetic waves in vacuum is",
    ["√(μ0 ε0)", "1/√(μ0 ε0)", "μ0 / ε0", "ε0 / μ0"],
    1,
    "c = 1/√(μ0 ε0) ≈ 3 × 10⁸ m/s.",
  ),
  class12Pyq(
    "physics",
    "electromagnetic-waves",
    "Electromagnetic waves are",
    ["longitudinal", "transverse", "neither", "longitudinal in vacuum only"],
    1,
    "E and B oscillate perpendicular to each other and to the direction of propagation.",
  ),
  class12Pyq(
    "physics",
    "electromagnetic-waves",
    "The ratio E0 / B0 for a plane EM wave in vacuum equals",
    ["c", "1/c", "c²", "μ0 / ε0"],
    0,
    "E0 = c B0, so E0/B0 = c.",
  ),
  class12Pyq(
    "physics",
    "electromagnetic-waves",
    "The correct increasing order of wavelengths is",
    ["radio, visible, X-rays", "X-rays, visible, radio", "visible, X-rays, radio", "radio, X-rays, visible"],
    1,
    "λ_X-ray < λ_visible < λ_radio. Frequency order is the reverse.",
  ),
  class12Pyq(
    "physics",
    "electromagnetic-waves",
    "Microwaves are used in radar because they",
    ["are absorbed by the atmosphere completely", "have short wavelengths and can be formed into narrow beams", "are visible", "have zero frequency"],
    1,
    "Short λ allows directional antennas and good resolution of distant objects.",
  ),
  class12Pyq(
    "physics",
    "electromagnetic-waves",
    "Infrared radiation is associated with",
    ["ionisation of atoms", "heating / greenhouse effect", "photoelectric effect only", "radio communication only"],
    1,
    "IR is thermal radiation; CO2 and water vapour absorb IR (greenhouse).",
  ),
  class12Pyq(
    "physics",
    "electromagnetic-waves",
    "Ultraviolet radiation from the sun is largely absorbed by",
    ["oxygen in the troposphere", "the ozone layer in the stratosphere", "clouds only", "the ionosphere's radio layer"],
    1,
    "Stratospheric ozone absorbs most solar UV-B and UV-C.",
  ),
  class12Pyq(
    "physics",
    "electromagnetic-waves",
    "Gamma rays are typically produced in",
    ["an LC oscillator", "radioactive decay of nuclei", "a microwave oven", "an IR lamp"],
    1,
    "γ-rays originate from nuclear transitions (and other high-energy processes).",
  ),
  class12Pyq(
    "physics",
    "electromagnetic-waves",
    "The direction of propagation of an EM wave is that of",
    ["E", "B", "E × B", "E · B"],
    2,
    "The Poynting vector S = (1/μ0) E × B points along the velocity of the wave.",
  ),
  class12Pyq(
    "physics",
    "electromagnetic-waves",
    "Average intensity of a plane EM wave in vacuum is",
    ["c ε0 E0²", "(1/2) c ε0 E0²", "c ε0 E0", "E0 B0 / μ0"],
    1,
    "I = (1/2) c ε0 E0² = (1/2) (E0 B0)/μ0.",
  ),
  class12Pyq(
    "physics",
    "electromagnetic-waves",
    "EM waves are produced by",
    ["charges at rest", "charges moving with constant velocity", "accelerated charges", "neutrons at rest"],
    2,
    "Only accelerated charges radiate electromagnetic waves.",
  ),
  class12Pyq(
    "physics",
    "electromagnetic-waves",
    "In an electromagnetic wave, the energy is shared between E and B fields",
    ["unequally, more in E", "unequally, more in B", "equally on average", "only in E"],
    2,
    "Average energy densities (1/2)ε0 E² and B²/(2μ0) are equal.",
  ),
  class12Pyq(
    "physics",
    "electromagnetic-waves",
    "Which part of the EM spectrum is used for satellite communication?",
    ["X-rays", "microwaves", "ultraviolet", "gamma rays"],
    1,
    "Microwaves penetrate the ionosphere and are used for satellite links.",
  ),
  class12Pyq(
    "physics",
    "electromagnetic-waves",
    "Visible light occupies roughly the wavelength range",
    ["400 nm to 700 nm", "400 m to 700 m", "4 nm to 7 nm", "400 μm to 700 μm"],
    0,
    "Violet ~400 nm to red ~700 nm.",
  ),
  class12Pyq(
    "physics",
    "electromagnetic-waves",
    "X-rays are used in medicine because they",
    ["are visible", "can penetrate tissues to different extents", "have zero energy", "are radio waves"],
    1,
    "Differential absorption by bone and soft tissue produces a radiograph.",
  ),
  class12Pyq(
    "physics",
    "electromagnetic-waves",
    "The Ampere–Maxwell law includes",
    ["only conduction current", "conduction plus displacement current", "only displacement current", "neither current"],
    1,
    "∮ B · dl = μ0 (Ic + ε0 dΦE/dt), restoring continuity of current.",
  ),
  class12Pyq(
    "physics",
    "electromagnetic-waves",
    "EM waves can travel through vacuum because they",
    ["need air as a medium", "are oscillations of E and B that sustain each other", "are sound waves", "require aether"],
    1,
    "A changing E produces B and a changing B produces E; no material medium is needed.",
  ),
  class12Pyq(
    "physics",
    "electromagnetic-waves",
    "Frequency of radio waves used in AM broadcast is of order",
    ["10 Hz", "10³–10⁶ Hz (kHz–MHz)", "10²⁰ Hz", "10¹⁵ Hz"],
    1,
    "AM radio is typically hundreds of kHz; FM is around 100 MHz.",
  ),
  class12Pyq(
    "physics",
    "electromagnetic-waves",
    "Dimensional formula of ε0 dΦE/dt (displacement current) is the same as that of",
    ["electric field", "magnetic field", "electric current", "potential"],
    2,
    "Id has the dimension of current so that it can sit beside Ic in Ampere's law.",
  ),
];

const rayOpticsAndOpticalInstruments: PracticeQuestionSeed[] = [
  class12Pyq(
    "physics",
    "ray-optics-and-optical-instruments",
    "The mirror formula (Cartesian sign convention) is",
    ["1/v − 1/u = 1/f", "1/v + 1/u = 1/f", "v + u = f", "v u = f"],
    1,
    "For spherical mirrors, 1/v + 1/u = 1/f.",
  ),
  class12Pyq(
    "physics",
    "ray-optics-and-optical-instruments",
    "The thin-lens formula is",
    ["1/v + 1/u = 1/f", "1/v − 1/u = 1/f", "v − u = f", "1/f = v u"],
    1,
    "1/v − 1/u = 1/f with the usual Cartesian signs (light from left).",
  ),
  class12Pyq(
    "physics",
    "ray-optics-and-optical-instruments",
    "Lateral magnification by a lens is",
    ["m = h / h'", "m = v / u", "m = u / v", "m = f / u"],
    1,
    "m = h'/h = v/u (signs included). |m| > 1 means a magnified image.",
  ),
  class12Pyq(
    "physics",
    "ray-optics-and-optical-instruments",
    "Power of a lens of focal length f (in metre) is",
    ["P = f", "P = 1/f dioptre", "P = f²", "P = 1/f²"],
    1,
    "P = 1/f (f in m). A convex lens has positive power.",
  ),
  class12Pyq(
    "physics",
    "ray-optics-and-optical-instruments",
    "Two thin lenses in contact have equivalent focal length F given by",
    ["F = f1 + f2", "1/F = 1/f1 + 1/f2", "F = f1 f2", "1/F = f1 + f2"],
    1,
    "P = P1 + P2, so 1/F = 1/f1 + 1/f2.",
  ),
  class12Pyq(
    "physics",
    "ray-optics-and-optical-instruments",
    "Critical angle ic for TIR from a medium of refractive index μ to air is",
    ["sin ic = μ", "sin ic = 1/μ", "ic = μ", "tan ic = 1/μ"],
    1,
    "μ sin ic = 1 · sin 90° ⇒ sin ic = 1/μ.",
  ),
  class12Pyq(
    "physics",
    "ray-optics-and-optical-instruments",
    "For a thin prism of angle A, the deviation is",
    ["δ = (μ + 1) A", "δ = (μ − 1) A", "δ = μ A", "δ = A / (μ − 1)"],
    1,
    "δ = (μ − 1)A for small A (in radians, or consistent small-angle units).",
  ),
  class12Pyq(
    "physics",
    "ray-optics-and-optical-instruments",
    "Snell's law of refraction is",
    ["μ1 sin i = μ2 sin r", "μ1 / sin i = μ2 / sin r", "i = μ r", "μ = i / r"],
    0,
    "n1 sin i = n2 sin r at an interface.",
  ),
  class12Pyq(
    "physics",
    "ray-optics-and-optical-instruments",
    "Magnifying power of a simple microscope (image at D) is",
    ["f / D", "1 + D/f", "D f", "f / (f + D)"],
    1,
    "m = 1 + D/f when the image is at the near point D (≈ 25 cm).",
  ),
  class12Pyq(
    "physics",
    "ray-optics-and-optical-instruments",
    "Magnifying power of a compound microscope (normal adjustment, image at D) is approximately",
    ["(L / f0) (D / fe)", "(f0 / L) (fe / D)", "f0 / fe", "fe / f0"],
    0,
    "m ≈ (v0/u0)(1 + D/fe) ≈ (L/f0)(D/fe) in the usual approximation.",
  ),
  class12Pyq(
    "physics",
    "ray-optics-and-optical-instruments",
    "Angular magnification of an astronomical telescope in normal adjustment is",
    ["fe / f0", "f0 / fe", "f0 + fe", "f0 fe"],
    1,
    "m = f0 / fe, and tube length f0 + fe.",
  ),
  class12Pyq(
    "physics",
    "ray-optics-and-optical-instruments",
    "Refraction at a spherical surface separating media μ1 and μ2 is given by",
    ["μ2/v − μ1/u = (μ2 − μ1)/R", "μ1/v − μ2/u = (μ2 − μ1)/R", "1/v − 1/u = 1/R", "μ2/v + μ1/u = (μ2 − μ1)/R"],
    0,
    "The standard formula is μ2/v − μ1/u = (μ2 − μ1)/R.",
  ),
  class12Pyq(
    "physics",
    "ray-optics-and-optical-instruments",
    "Optical fibres work on the principle of",
    ["diffraction", "total internal reflection", "polarisation", "interference"],
    1,
    "Light is guided by repeated TIR at the core–cladding interface.",
  ),
  class12Pyq(
    "physics",
    "ray-optics-and-optical-instruments",
    "Lens maker's formula for a thin lens in air is",
    ["1/f = (μ − 1)(1/R1 − 1/R2)", "1/f = (μ + 1)(R1 + R2)", "f = μ (R1 − R2)", "1/f = μ (1/R1 + 1/R2)"],
    0,
    "1/f = (μ − 1)(1/R1 − 1/R2) with Cartesian signs on the radii.",
  ),
  class12Pyq(
    "physics",
    "ray-optics-and-optical-instruments",
    "Apparent depth of an object in a denser medium of refractive index μ (normal view) is",
    ["μ × real depth", "real depth / μ", "real depth × μ²", "real depth − μ"],
    1,
    "d_app = d_real / μ for small-angle (paraxial) viewing.",
  ),
  class12Pyq(
    "physics",
    "ray-optics-and-optical-instruments",
    "A convex lens of focal length 20 cm forms a real image at 60 cm. The object distance is",
    ["15 cm", "30 cm", "40 cm", "−20 cm"],
    1,
    "1/v − 1/u = 1/f ⇒ 1/60 − 1/u = 1/20 ⇒ −1/u = 1/20 − 1/60 = 1/30 ⇒ u = −30 cm.",
  ),
  class12Pyq(
    "physics",
    "ray-optics-and-optical-instruments",
    "Power of a combination of two thin lenses in contact is",
    ["P1 P2", "P1 + P2", "P1 − P2", "P1 / P2"],
    1,
    "P = P1 + P2 when the lenses are in contact.",
  ),
  class12Pyq(
    "physics",
    "ray-optics-and-optical-instruments",
    "Dispersion of light by a prism occurs because",
    ["μ is the same for all colours", "μ depends on wavelength (μ_violet > μ_red)", "speed of light is infinite", "prisms absorb red light"],
    1,
    "μ(λ) is larger for violet, so δv > δr and a spectrum is formed.",
  ),
  class12Pyq(
    "physics",
    "ray-optics-and-optical-instruments",
    "An object is placed at 2f of a convex lens. The image is",
    ["virtual and erect at f", "real, inverted and same size at 2f", "real and magnified at infinity", "at the lens"],
    1,
    "For u = −2f, v = +2f; m = −1 (real, inverted, same size).",
  ),
  class12Pyq(
    "physics",
    "ray-optics-and-optical-instruments",
    "The final image formed by an astronomical telescope in normal adjustment is",
    ["real, inverted and highly magnified", "virtual, inverted and magnified (angularly)", "virtual and erect", "real and erect"],
    1,
    "The objective forms a real inverted image at its focus; the eyepiece used as a simple microscope gives a virtual inverted angularly magnified image.",
  ),
];

const waveOptics: PracticeQuestionSeed[] = [
  class12Pyq(
    "physics",
    "wave-optics",
    "Huygens' principle states that every point on a wavefront acts as a source of",
    ["electrons", "secondary spherical wavelets", "photons of fixed energy", "magnetic monopoles"],
    1,
    "The envelope of secondary wavelets gives the new wavefront.",
  ),
  class12Pyq(
    "physics",
    "wave-optics",
    "In YDSE, fringe width β is",
    ["λ d / D", "λ D / d", "d D / λ", "λ / (D d)"],
    1,
    "β = λ D / d, where D is screen distance and d is slit separation.",
  ),
  class12Pyq(
    "physics",
    "wave-optics",
    "Path difference for a bright fringe in YDSE is",
    ["(2n − 1) λ/2", "n λ", "λ / n", "(n + 1/2) λ"],
    1,
    "Constructive interference: Δ = nλ (n = 0, 1, 2, …).",
  ),
  class12Pyq(
    "physics",
    "wave-optics",
    "Path difference for a dark fringe in YDSE is",
    ["n λ", "(2n − 1) λ/2", "n λ/4", "2 n λ"],
    1,
    "Destructive interference: Δ = (2n − 1)λ/2.",
  ),
  class12Pyq(
    "physics",
    "wave-optics",
    "Two sources are coherent if they",
    ["have the same amplitude only", "maintain a constant phase difference and same frequency", "are of different colours", "are infinitely far apart"],
    1,
    "Sustained interference needs a stable phase relation (usually from one wavefront).",
  ),
  class12Pyq(
    "physics",
    "wave-optics",
    "If slit separation d in YDSE is decreased, fringe width",
    ["decreases", "increases", "remains the same", "becomes zero"],
    1,
    "β ∝ 1/d, so smaller d gives wider fringes.",
  ),
  class12Pyq(
    "physics",
    "wave-optics",
    "In YDSE, if the whole apparatus is immersed in a medium of refractive index μ, fringe width becomes",
    ["μ β", "β / μ", "β", "μ² β"],
    1,
    "Wavelength in the medium is λ/μ, so β' = β/μ.",
  ),
  class12Pyq(
    "physics",
    "wave-optics",
    "Maximum intensity in YDSE with two equal sources of intensity I0 is",
    ["I0", "2 I0", "4 I0", "0"],
    2,
    "I = 4 I0 cos²(φ/2); maxima have Imax = 4 I0, minima 0.",
  ),
  class12Pyq(
    "physics",
    "wave-optics",
    "Brewster's law is",
    ["μ = sin ip", "μ = tan ip", "μ = cos ip", "ip = μ"],
    1,
    "μ = tan ip. At polarising angle, reflected light is completely polarised.",
  ),
  class12Pyq(
    "physics",
    "wave-optics",
    "Malus's law for intensity through an analyser is",
    ["I = I0 sin² θ", "I = I0 cos² θ", "I = I0 cos θ", "I = I0 / cos² θ"],
    1,
    "I = I0 cos²θ, where θ is the angle between polariser and analyser axes.",
  ),
  class12Pyq(
    "physics",
    "wave-optics",
    "For single-slit diffraction, the first minimum occurs when",
    ["a sin θ = λ", "a sin θ = λ/2", "a sin θ = 2λ", "a = λ sin θ / 2"],
    0,
    "a sin θ = nλ for minima (n = ±1, ±2, …); first minimum n = 1.",
  ),
  class12Pyq(
    "physics",
    "wave-optics",
    "Width of the central maximum in single-slit diffraction (screen at D) is",
    ["λ D / a", "2 λ D / a", "a D / λ", "λ a / D"],
    1,
    "The first minima lie at y = ± λ D/a, so central width = 2λ D/a.",
  ),
  class12Pyq(
    "physics",
    "wave-optics",
    "Unpolarised light of intensity I0 passing through a polaroid emerges with intensity",
    ["I0", "I0 / 2", "I0 / 4", "0"],
    1,
    "An ideal polariser transmits half the intensity of unpolarised light.",
  ),
  class12Pyq(
    "physics",
    "wave-optics",
    "Phase difference corresponding to path difference Δ is",
    ["(2π / λ) Δ", "(λ / 2π) Δ", "2π λ Δ", "Δ / λ"],
    0,
    "φ = (2π/λ) Δ = (2π/λ) d sinθ in YDSE.",
  ),
  class12Pyq(
    "physics",
    "wave-optics",
    "When a thin transparent sheet of thickness t and refractive index μ is introduced in front of one slit in YDSE, the fringe pattern",
    ["disappears", "shifts toward the slit with the sheet by (μ − 1)t D/d", "shifts away from that slit", "has smaller β only"],
    1,
    "Effective path increase is (μ − 1)t; shift = [(μ − 1)t/λ] β toward that slit.",
  ),
  class12Pyq(
    "physics",
    "wave-optics",
    "Resolving power of a telescope is proportional to",
    ["wavelength λ", "diameter of objective D", "1/D", "focal length of eyepiece only"],
    1,
    "RP = D / (1.22 λ); a larger objective improves resolution.",
  ),
  class12Pyq(
    "physics",
    "wave-optics",
    "Interference fringes are obtained only if the two waves have",
    ["different frequencies", "nearly equal amplitudes and are coherent", "orthogonal polarisations always", "zero amplitude"],
    1,
    "Coherence plus comparable amplitudes give good contrast (visibility).",
  ),
  class12Pyq(
    "physics",
    "wave-optics",
    "In YDSE, λ = 500 nm, d = 0.1 mm, D = 1 m. Fringe width is",
    ["5 mm", "0.5 mm", "5 cm", "0.05 mm"],
    0,
    "β = λ D/d = (5 × 10⁻⁷)(1)/(10⁻⁴) = 5 × 10⁻³ m = 5 mm.",
  ),
  class12Pyq(
    "physics",
    "wave-optics",
    "Polarisation of light demonstrates that light waves are",
    ["longitudinal", "transverse", "stationary", "sound-like"],
    1,
    "Only transverse waves can be polarised; sound in air cannot.",
  ),
  class12Pyq(
    "physics",
    "wave-optics",
    "The condition 2μ t = n λ (normal incidence) is for",
    ["YDSE bright fringes", "interference in a thin film (depending on phase change)", "Brewster polarisation", "single-slit first min"],
    1,
    "Thin-film interference depends on path 2μt and any π phase change on reflection.",
  ),
];

const dualNatureOfRadiationAndMatter: PracticeQuestionSeed[] = [
  class12Pyq(
    "physics",
    "dual-nature-of-radiation-and-matter",
    "Einstein's photoelectric equation is",
    ["Kmax = hν + φ", "Kmax = hν − φ", "Kmax = φ − hν", "Kmax = hν / φ"],
    1,
    "Kmax = hν − φ0, where φ0 is the work function.",
  ),
  class12Pyq(
    "physics",
    "dual-nature-of-radiation-and-matter",
    "Maximum kinetic energy of photoelectrons is related to stopping potential Vs by",
    ["Kmax = Vs / e", "Kmax = e Vs", "Kmax = e / Vs", "Kmax = h Vs"],
    1,
    "e Vs = Kmax = hν − φ.",
  ),
  class12Pyq(
    "physics",
    "dual-nature-of-radiation-and-matter",
    "Threshold frequency ν0 and work function φ are related by",
    ["φ = h / ν0", "φ = h ν0", "φ = ν0 / h", "φ = h c ν0"],
    1,
    "φ = h ν0 = h c / λ0.",
  ),
  class12Pyq(
    "physics",
    "dual-nature-of-radiation-and-matter",
    "If the intensity of incident light is increased (ν > ν0), then",
    ["Kmax increases", "stopping potential increases", "photocurrent increases", "threshold frequency decreases"],
    2,
    "Intensity raises the number of photons and thus photocurrent; Kmax depends only on ν.",
  ),
  class12Pyq(
    "physics",
    "dual-nature-of-radiation-and-matter",
    "de Broglie wavelength of a particle is",
    ["λ = h / p", "λ = p / h", "λ = h p", "λ = h / E"],
    0,
    "λ = h/p = h/(mv) for a non-relativistic particle.",
  ),
  class12Pyq(
    "physics",
    "dual-nature-of-radiation-and-matter",
    "de Broglie wavelength of an electron accelerated through V volts is approximately",
    ["12.27 / √V Å", "12.27 √V Å", "150 / V Å", "√(150 V) Å"],
    0,
    "λ(Å) ≈ 12.27 / √V, equivalently √(150/V) Å.",
  ),
  class12Pyq(
    "physics",
    "dual-nature-of-radiation-and-matter",
    "Energy of a photon of wavelength λ is",
    ["h c λ", "h c / λ", "h λ / c", "c / (h λ)"],
    1,
    "E = hν = hc/λ. Momentum of the photon is h/λ.",
  ),
  class12Pyq(
    "physics",
    "dual-nature-of-radiation-and-matter",
    "Momentum of a photon of wavelength λ is",
    ["h λ", "h / λ", "λ / h", "h c / λ"],
    1,
    "p = E/c = h/λ.",
  ),
  class12Pyq(
    "physics",
    "dual-nature-of-radiation-and-matter",
    "The graph of stopping potential Vs versus frequency ν is a straight line of slope",
    ["h / e", "e / h", "h", "φ / e"],
    0,
    "e Vs = hν − φ ⇒ Vs = (h/e)ν − φ/e. Slope is h/e.",
  ),
  class12Pyq(
    "physics",
    "dual-nature-of-radiation-and-matter",
    "Wave nature of electrons was confirmed experimentally by",
    ["Millikan's oil-drop experiment", "Davisson–Germer experiment", "Hertz's experiment", "Rutherford's α-scattering"],
    1,
    "Davisson and Germer observed electron diffraction from a nickel crystal.",
  ),
  class12Pyq(
    "physics",
    "dual-nature-of-radiation-and-matter",
    "Photoelectric effect cannot be explained by the wave theory because wave theory predicts that",
    ["Kmax depends on frequency", "emission is instantaneous and Kmax independent of intensity", "Kmax should depend on intensity and there may be a time lag", "a threshold frequency exists"],
    2,
    "Classically, energy should accumulate with intensity and Kmax should grow with intensity; experiment contradicts both.",
  ),
  class12Pyq(
    "physics",
    "dual-nature-of-radiation-and-matter",
    "Work function of a metal is 2 eV. The threshold wavelength is approximately (hc = 12400 eV Å)",
    ["6200 Å", "3100 Å", "12400 Å", "2000 Å"],
    0,
    "λ0 = hc/φ = 12400/2 = 6200 Å.",
  ),
  class12Pyq(
    "physics",
    "dual-nature-of-radiation-and-matter",
    "If the wavelength of incident radiation is halved (still above threshold), Kmax of photoelectrons",
    ["remains the same", "becomes less than double", "more than doubles (Kmax' = 2hν − φ > 2(hν − φ))", "becomes zero"],
    2,
    "K = hc/λ − φ. Halving λ doubles hν, so K' = 2hν − φ = 2(K + φ) − φ = 2K + φ > 2K.",
  ),
  class12Pyq(
    "physics",
    "dual-nature-of-radiation-and-matter",
    "Photocurrent is zero when the retarding potential is equal to or greater than",
    ["work function in volts", "stopping potential", "1 V always", "threshold frequency"],
    1,
    "At V = −Vs, even the fastest electrons cannot reach the collector.",
  ),
  class12Pyq(
    "physics",
    "dual-nature-of-radiation-and-matter",
    "The dual nature of radiation means radiation behaves as",
    ["wave only", "particle only", "wave and particle in complementary situations", "neither"],
    2,
    "Interference shows wave nature; photoelectric effect shows particle (photon) nature.",
  ),
  class12Pyq(
    "physics",
    "dual-nature-of-radiation-and-matter",
    "For photons, the relation between energy E and momentum p is",
    ["E = p² /(2m)", "E = p c", "E = p / c", "E = p c²"],
    1,
    "For a massless photon E = p c = hc/λ.",
  ),
  class12Pyq(
    "physics",
    "dual-nature-of-radiation-and-matter",
    "An electron and a proton have the same de Broglie wavelength. Then",
    ["they have the same speed", "they have the same momentum", "the electron has greater KE", "the proton has greater KE"],
    1,
    "λ = h/p ⇒ same λ means same p. KE = p²/(2m) is larger for the lighter electron.",
  ),
  class12Pyq(
    "physics",
    "dual-nature-of-radiation-and-matter",
    "The intercept of the Vs–ν graph on the ν-axis is",
    ["work function φ", "threshold frequency ν0", "h/e", "stopping potential"],
    1,
    "Vs = 0 when ν = ν0. The |Vs|-intercept is φ/e.",
  ),
  class12Pyq(
    "physics",
    "dual-nature-of-radiation-and-matter",
    "Number of photoelectrons emitted per second is proportional to",
    ["frequency of light", "intensity of light (for ν > ν0)", "work function", "stopping potential"],
    1,
    "Each photon (above threshold) can free one electron; more intensity means more photons.",
  ),
  class12Pyq(
    "physics",
    "dual-nature-of-radiation-and-matter",
    "Planck's constant can be determined from the photoelectric experiment using",
    ["the slope of Vs versus ν multiplied by e", "the intercept on the I-axis", "intensity of light", "the charge of the proton"],
    0,
    "Slope of Vs–ν is h/e, so h = e × slope.",
  ),
];

const atoms: PracticeQuestionSeed[] = [
  class12Pyq(
    "physics",
    "atoms",
    "Bohr's quantisation of angular momentum is",
    ["m v r = n h", "m v r = n h / 2π", "m v r = h / n", "m v r = 2π n / h"],
    1,
    "mvr = n ħ = nh/(2π), n = 1, 2, 3, ….",
  ),
  class12Pyq(
    "physics",
    "atoms",
    "Radius of the nth Bohr orbit of hydrogen is",
    ["rn = a0 / n²", "rn = n² a0", "rn = n a0", "rn = a0 / n"],
    1,
    "rn = n² a0 / Z, with a0 ≈ 0.529 Å. For H, Z = 1.",
  ),
  class12Pyq(
    "physics",
    "atoms",
    "Energy of the electron in the nth orbit of hydrogen is",
    ["En = −13.6 n² eV", "En = −13.6 / n² eV", "En = 13.6 / n eV", "En = −13.6 n eV"],
    1,
    "En = −13.6 Z² / n² eV. For hydrogen Z = 1.",
  ),
  class12Pyq(
    "physics",
    "atoms",
    "The Lyman series of hydrogen lies in the",
    ["visible region", "ultraviolet region", "infrared region", "X-ray region"],
    1,
    "Lyman: n2 → n = 1, UV. Balmer is visible; Paschen, Brackett, Pfund are IR.",
  ),
  class12Pyq(
    "physics",
    "atoms",
    "The Balmer series corresponds to transitions ending at",
    ["n = 1", "n = 2", "n = 3", "n = 4"],
    1,
    "Balmer: n = 3, 4, 5, … → n = 2 (visible).",
  ),
  class12Pyq(
    "physics",
    "atoms",
    "Ionisation energy of the hydrogen atom in the ground state is",
    ["3.4 eV", "10.2 eV", "13.6 eV", "1.51 eV"],
    2,
    "Energy to take n = 1 electron to infinity: 13.6 eV.",
  ),
  class12Pyq(
    "physics",
    "atoms",
    "Rydberg's formula for hydrogen is",
    ["1/λ = R (n1² − n2²)", "1/λ = R (1/n1² − 1/n2²)", "λ = R (1/n1² − 1/n2²)", "1/λ = R n1 n2"],
    1,
    "1/λ = R (1/n1² − 1/n2²) with n2 > n1.",
  ),
  class12Pyq(
    "physics",
    "atoms",
    "Speed of the electron in the nth Bohr orbit is proportional to",
    ["n", "1/n", "n²", "1/n²"],
    1,
    "vn = α c Z / n ∝ 1/n (α is the fine-structure constant).",
  ),
  class12Pyq(
    "physics",
    "atoms",
    "The photon energy for the transition n = 2 → n = 1 in hydrogen is",
    ["3.4 eV", "10.2 eV", "13.6 eV", "1.89 eV"],
    1,
    "ΔE = 13.6 (1 − 1/4) = 10.2 eV (first line of Lyman).",
  ),
  class12Pyq(
    "physics",
    "atoms",
    "Ground-state energy of hydrogen is −13.6 eV. The first excitation energy is",
    ["13.6 eV", "10.2 eV", "3.4 eV", "1.51 eV"],
    1,
    "E2 − E1 = −3.4 − (−13.6) = 10.2 eV.",
  ),
  class12Pyq(
    "physics",
    "atoms",
    "Maximum number of spectral lines when an electron jumps from n = n2 to n = 1 is",
    ["n2", "n2 (n2 − 1)/2", "2 n2", "n2²"],
    1,
    "Number of lines = n(n − 1)/2 for a jump from level n to the ground state.",
  ),
  class12Pyq(
    "physics",
    "atoms",
    "For a hydrogen-like ion of atomic number Z, En is",
    ["−13.6 / n² eV", "−13.6 Z / n² eV", "−13.6 Z² / n² eV", "−13.6 Z² n² eV"],
    2,
    "En = −13.6 Z² / n² eV; rn = n² a0 / Z.",
  ),
  class12Pyq(
    "physics",
    "atoms",
    "In Bohr's model, kinetic energy and total energy are related by",
    ["KE = E", "KE = −E", "KE = −2E", "KE = 2E"],
    1,
    "KE = +13.6/n², E = −13.6/n², so KE = −E. Also PE = 2E = −2 KE.",
  ),
  class12Pyq(
    "physics",
    "atoms",
    "The shortest wavelength of the Lyman series is",
    ["1/R", "4/(3R)", "9/(8R)", "R"],
    0,
    "n2 → ∞ to n1 = 1 gives 1/λ = R, so λmin = 1/R (series limit).",
  ),
  class12Pyq(
    "physics",
    "atoms",
    "Paschen series of hydrogen lies in the",
    ["UV", "visible", "infrared", "microwave only"],
    2,
    "Paschen: transitions to n = 3, infrared.",
  ),
  class12Pyq(
    "physics",
    "atoms",
    "A limitation of Rutherford's nuclear model is that",
    ["the atom is mostly empty", "orbiting electrons should radiate and spiral in", "most α particles go undeviated", "the nucleus is positive"],
    1,
    "Accelerated charges radiate classically, so the atom would be unstable; Bohr postulated non-radiating orbits.",
  ),
  class12Pyq(
    "physics",
    "atoms",
    "Impact parameter in α-scattering is the",
    ["radius of the nucleus", "perpendicular distance of the initial velocity line from the nucleus", "distance of closest approach always", "scattering angle"],
    1,
    "b is the impact parameter; large b means small deflection.",
  ),
  class12Pyq(
    "physics",
    "atoms",
    "Frequency of the photon emitted in a Bohr transition is",
    ["(E_i − E_f)/h", "(E_i + E_f)/h", "h (E_i − E_f)", "E_i E_f / h"],
    0,
    "hν = Ei − Ef (Ei > Ef).",
  ),
  class12Pyq(
    "physics",
    "atoms",
    "The ratio of radii of the 3rd and 1st Bohr orbits of hydrogen is",
    ["3 : 1", "9 : 1", "1 : 9", "√3 : 1"],
    1,
    "rn ∝ n², so r3/r1 = 9/1.",
  ),
  class12Pyq(
    "physics",
    "atoms",
    "Potential energy of the electron in the ground state of hydrogen is",
    ["−13.6 eV", "−27.2 eV", "+13.6 eV", "0"],
    1,
    "PE = −k e² / r = −27.2 eV; KE = +13.6 eV; total = −13.6 eV.",
  ),
];

const nuclei: PracticeQuestionSeed[] = [
  class12Pyq(
    "physics",
    "nuclei",
    "Mass defect Δm of a nucleus is",
    ["mass of protons − mass of neutrons", "Zm_p + (A − Z)m_n − M_nucleus", "M_nucleus − A u", "A u − Z m_e"],
    1,
    "Δm = [Z mp + (A − Z) mn] − M; binding energy is Δm c².",
  ),
  class12Pyq(
    "physics",
    "nuclei",
    "Binding energy of a nucleus is",
    ["Δm c", "Δm c²", "Δm / c²", "A × 931 eV"],
    1,
    "BE = Δm c². Often expressed as Δm (in u) × 931 MeV.",
  ),
  class12Pyq(
    "physics",
    "nuclei",
    "1 atomic mass unit (u) is equivalent to about",
    ["931 keV", "931 MeV", "13.6 eV", "1 eV"],
    1,
    "1 u c² ≈ 931 MeV.",
  ),
  class12Pyq(
    "physics",
    "nuclei",
    "Binding energy per nucleon is maximum near",
    ["hydrogen", "iron-56", "uranium", "helium-4 only"],
    1,
    "The BE/A curve peaks around 56Fe; those nuclei are most stable.",
  ),
  class12Pyq(
    "physics",
    "nuclei",
    "The radioactive decay law is",
    ["N = N0 λ t", "N = N0 e^(−λ t)", "N = N0 e^(λ t)", "N = λ / t"],
    1,
    "N = N0 e^(−λt). Activity A = λ N.",
  ),
  class12Pyq(
    "physics",
    "nuclei",
    "Half-life T1/2 and decay constant λ are related by",
    ["T1/2 = λ", "T1/2 = 0.693 / λ", "T1/2 = λ / 0.693", "T1/2 = 1/λ"],
    1,
    "T1/2 = ln 2 / λ ≈ 0.693/λ. Mean life τ = 1/λ.",
  ),
  class12Pyq(
    "physics",
    "nuclei",
    "Mean life τ of a radioactive sample is",
    ["0.693 / λ", "1 / λ", "λ", "T1/2 / 0.693"],
    1,
    "τ = 1/λ = T1/2 / 0.693 ≈ 1.44 T1/2.",
  ),
  class12Pyq(
    "physics",
    "nuclei",
    "Activity of a radioactive sample is",
    ["A = N / λ", "A = λ N", "A = λ / N", "A = N λ t"],
    1,
    "A = −dN/dt = λN. SI unit is the becquerel (1 Bq = 1 decay/s).",
  ),
  class12Pyq(
    "physics",
    "nuclei",
    "In α-decay, the mass number A and atomic number Z of the parent change by",
    ["A → A − 4, Z → Z − 2", "A → A − 2, Z → Z − 1", "A → A − 4, Z → Z − 1", "A → A + 4, Z → Z + 2"],
    0,
    "An α particle is ⁴He, so A decreases by 4 and Z by 2.",
  ),
  class12Pyq(
    "physics",
    "nuclei",
    "In β⁻ decay, a nucleus emits an electron and its Z",
    ["decreases by 1", "increases by 1", "decreases by 2", "is unchanged"],
    1,
    "n → p + e⁻ + ν̄e, so Z increases by 1 while A is unchanged.",
  ),
  class12Pyq(
    "physics",
    "nuclei",
    "Nuclear fission is favoured for",
    ["very light nuclei", "heavy nuclei such as ²³⁵U", "iron-56", "all nuclei equally"],
    1,
    "Heavy nuclei have lower BE/A than medium-mass fragments, so splitting releases energy.",
  ),
  class12Pyq(
    "physics",
    "nuclei",
    "Nuclear fusion is the source of energy in",
    ["atom bombs of the fission type only", "the sun and stars", "chemical fuels", "radioactive β decay only"],
    1,
    "Light nuclei fuse to heavier ones with higher BE/A (e.g. H → He in the sun).",
  ),
  class12Pyq(
    "physics",
    "nuclei",
    "Nuclear radius R varies with mass number A as",
    ["R = R0 A", "R = R0 A^{1/3}", "R = R0 / A", "R = R0 A²"],
    1,
    "R = R0 A^{1/3} with R0 ≈ 1.2 fm, from constant nuclear density.",
  ),
  class12Pyq(
    "physics",
    "nuclei",
    "Isotopes of an element have",
    ["same A, different Z", "same Z, different A", "same N, different Z", "same A and Z"],
    1,
    "Same atomic number Z (same element), different neutron number and A.",
  ),
  class12Pyq(
    "physics",
    "nuclei",
    "Q-value of a nuclear reaction is",
    ["always negative", "(initial rest mass − final rest mass) c²", "equal to BE of the product only", "independent of masses"],
    1,
    "Q = (Σ mi − Σ mf) c². Q > 0 is exoergic.",
  ),
  class12Pyq(
    "physics",
    "nuclei",
    "After n half-lives, the remaining number of nuclei is",
    ["N0 / n", "N0 / 2^n", "N0 2^n", "N0 / 2n"],
    1,
    "N = N0 / 2^n after n half-lives.",
  ),
  class12Pyq(
    "physics",
    "nuclei",
    "γ-rays from a nucleus",
    ["change A and Z", "change Z only", "are photons; A and Z unchanged", "are helium nuclei"],
    2,
    "γ emission is de-excitation of the daughter; no change in A or Z.",
  ),
  class12Pyq(
    "physics",
    "nuclei",
    "Density of nuclear matter is approximately",
    ["10³ kg m⁻³", "10¹⁷ kg m⁻³", "10⁸ kg m⁻³", "1 kg m⁻³"],
    1,
    "ρ ≈ 2 × 10¹⁷ kg/m³ and is roughly independent of A.",
  ),
  class12Pyq(
    "physics",
    "nuclei",
    "A moderator in a nuclear reactor is used to",
    ["absorb neutrons completely", "slow down fast neutrons", "accelerate neutrons", "increase uranium mass"],
    1,
    "Light nuclei (H2O, D2O, graphite) slow neutrons so they can cause fission of ²³⁵U.",
  ),
  class12Pyq(
    "physics",
    "nuclei",
    "If 10% of a radioactive sample decays in 5 days, the fraction left after 20 days is approximately",
    ["0.9^4", "0.1^4", "0.66", "zero"],
    0,
    "In 5 days, 90% remains. In 20 days = 4 such intervals, remaining fraction = (0.9)^4.",
  ),
];

const semiconductorElectronics: PracticeQuestionSeed[] = [
  class12Pyq(
    "physics",
    "semiconductor-electronics",
    "An intrinsic semiconductor has",
    ["only donor impurities", "equal numbers of electrons and holes (ideally)", "only holes", "a filled conduction band at 0 K"],
    1,
    "In a pure semiconductor ni = n = p (thermally generated pairs).",
  ),
  class12Pyq(
    "physics",
    "semiconductor-electronics",
    "n-type semiconductors are obtained by doping with",
    ["trivalent atoms (B, Al, Ga)", "pentavalent atoms (P, As, Sb)", "tetravalent atoms only", "noble gases"],
    1,
    "Group-V donors contribute extra electrons; majority carriers are electrons.",
  ),
  class12Pyq(
    "physics",
    "semiconductor-electronics",
    "p-type semiconductors are obtained by doping with",
    ["pentavalent impurities", "trivalent impurities", "hexavalent impurities", "no impurities"],
    1,
    "Group-III acceptors create holes; majority carriers are holes.",
  ),
  class12Pyq(
    "physics",
    "semiconductor-electronics",
    "In a p–n junction under forward bias",
    ["the barrier height increases", "the barrier height decreases and current is large", "no current flows", "the depletion layer widens"],
    1,
    "Forward bias reduces the potential barrier; depletion width decreases and current rises.",
  ),
  class12Pyq(
    "physics",
    "semiconductor-electronics",
    "In reverse bias of a p–n junction, the depletion layer",
    ["becomes narrower", "becomes wider", "disappears", "is unaffected"],
    1,
    "Reverse bias increases barrier height and widens the depletion region; current is tiny (saturation).",
  ),
  class12Pyq(
    "physics",
    "semiconductor-electronics",
    "A p–n junction diode conducts significantly when it is",
    ["reverse biased", "forward biased", "unbiased only", "heated to 0 K"],
    1,
    "Forward bias (p to +) gives a large current after the knee voltage.",
  ),
  class12Pyq(
    "physics",
    "semiconductor-electronics",
    "The output frequency of a full-wave rectifier for input frequency f is",
    ["f/2", "f", "2f", "4f"],
    2,
    "Both halves of the AC cycle are used, so ripple frequency is 2f.",
  ),
  class12Pyq(
    "physics",
    "semiconductor-electronics",
    "A Zener diode is used as a voltage regulator when it is",
    ["forward biased", "reverse biased in the breakdown region", "unbiased", "used as an LED"],
    1,
    "In reverse Zener/avalanche breakdown the voltage stays nearly constant over a current range.",
  ),
  class12Pyq(
    "physics",
    "semiconductor-electronics",
    "An LED emits light when it is",
    ["reverse biased", "forward biased", "used in Zener breakdown", "unbiased"],
    1,
    "Forward-bias recombination of electrons and holes emits photons (E_g determines colour).",
  ),
  class12Pyq(
    "physics",
    "semiconductor-electronics",
    "A photodiode is normally operated in",
    ["forward bias", "reverse bias", "the Zener region as a regulator", "open circuit only"],
    1,
    "Reverse-bias photocurrent is proportional to incident light intensity.",
  ),
  class12Pyq(
    "physics",
    "semiconductor-electronics",
    "The output of an AND gate is 1 only when",
    ["any one input is 1", "both inputs are 1", "both inputs are 0", "inputs are different"],
    1,
    "Y = A · B. Truth: 1 only for (1,1).",
  ),
  class12Pyq(
    "physics",
    "semiconductor-electronics",
    "The Boolean expression for an OR gate is",
    ["Y = A · B", "Y = A + B", "Y = Ā", "Y = A ⊕ B"],
    1,
    "Y = A + B; output is 1 if at least one input is 1.",
  ),
  class12Pyq(
    "physics",
    "semiconductor-electronics",
    "A NOT gate",
    ["adds two bits", "inverts the input", "gives 1 only if both inputs are 1", "is the same as XOR"],
    1,
    "Y = Ā. It is a single-input inverter.",
  ),
  class12Pyq(
    "physics",
    "semiconductor-electronics",
    "NAND is called a universal gate because",
    ["it is faster than AND", "any Boolean function can be realised using only NAND gates", "it has two outputs", "it cannot implement NOT"],
    1,
    "NOT, AND and OR (hence all logic) can be built from NAND alone.",
  ),
  class12Pyq(
    "physics",
    "semiconductor-electronics",
    "The output of a NAND gate is 0 when",
    ["any input is 0", "both inputs are 1", "both inputs are 0", "inputs are different"],
    1,
    "Y = (A · B)̄. Output is 0 only for A = B = 1.",
  ),
  class12Pyq(
    "physics",
    "semiconductor-electronics",
    "The output of a NOR gate is 1 only when",
    ["both inputs are 1", "both inputs are 0", "any one input is 1", "inputs are different"],
    1,
    "Y = (A + B)̄. Output is 1 only for (0,0). NOR is also universal.",
  ),
  class12Pyq(
    "physics",
    "semiconductor-electronics",
    "The output of an XOR gate is 1 when",
    ["both inputs are 1", "both inputs are 0", "the two inputs are different", "always"],
    2,
    "Y = A ⊕ B = A ĀB + Ā B. High when inputs are unequal.",
  ),
  class12Pyq(
    "physics",
    "semiconductor-electronics",
    "The Boolean identity A + Ā equals",
    ["0", "1", "A", "Ā"],
    1,
    "A + Ā = 1 (complement law). Also A · Ā = 0.",
  ),
  class12Pyq(
    "physics",
    "semiconductor-electronics",
    "Barrier potential of a silicon p–n junction at room temperature is about",
    ["0.1 V", "0.3 V", "0.7 V", "5 V"],
    2,
    "Si ≈ 0.7 V, Ge ≈ 0.3 V (typical knee/cut-in values).",
  ),
  class12Pyq(
    "physics",
    "semiconductor-electronics",
    "A solar cell is a p–n junction that",
    ["emits light when forward biased", "converts light into electrical energy (photovoltaic)", "is used only as a Zener regulator", "amplifies current"],
    1,
    "Illumination generates e–h pairs; the junction field separates them and produces emf.",
  ),
];

export const class12PhysicsQuestions: PracticeQuestionSeed[] = [
  ...electricChargesAndFields,
  ...electrostaticPotentialAndCapacitance,
  ...currentElectricity,
  ...movingChargesAndMagnetism,
  ...magnetismAndMatter,
  ...electromagneticInduction,
  ...alternatingCurrent,
  ...electromagneticWaves,
  ...rayOpticsAndOpticalInstruments,
  ...waveOptics,
  ...dualNatureOfRadiationAndMatter,
  ...atoms,
  ...nuclei,
  ...semiconductorElectronics,
];

assertTwentyPerChapter(class12PhysicsQuestions, [
  "electric-charges-and-fields",
  "electrostatic-potential-and-capacitance",
  "current-electricity",
  "moving-charges-and-magnetism",
  "magnetism-and-matter",
  "electromagnetic-induction",
  "alternating-current",
  "electromagnetic-waves",
  "ray-optics-and-optical-instruments",
  "wave-optics",
  "dual-nature-of-radiation-and-matter",
  "atoms",
  "nuclei",
  "semiconductor-electronics",
]);
