import { assertTwentyPerChapter, class12Pyq, type PracticeQuestionSeed } from "./types";

export const class12MathematicsQuestions: PracticeQuestionSeed[] = [
  // 1. Relations and Functions
  class12Pyq("mathematics", "relations-and-functions", "Let R be the relation on Z defined by aRb iff a − b is even. Then R is", ["an equivalence relation", "reflexive only", "symmetric only", "not transitive"], 0, "a − b even is reflexive, symmetric and transitive, so R is an equivalence relation (congruence modulo 2)."),
  class12Pyq("mathematics", "relations-and-functions", "The number of equivalence relations on the set {1, 2, 3} that contain (1, 2) is", ["1", "2", "3", "4"], 1, "If (1, 2) belongs to an equivalence, {1, 2} lie in one class. Either 3 is separate, or all three are together: two such relations."),
  class12Pyq("mathematics", "relations-and-functions", "The function f : R → R given by f(x) = x² is", ["one-one and onto", "one-one but not onto", "onto but not one-one", "neither one-one nor onto"], 3, "f(1) = f(−1) so it is not one-one, and negatives are not in the range, so it is not onto."),
  class12Pyq("mathematics", "relations-and-functions", "The function f : R → R given by f(x) = x³ is", ["one-one and onto", "one-one but not onto", "onto but not one-one", "neither one-one nor onto"], 0, "x³ is strictly increasing and every real has a unique real cube root, so f is bijective."),
  class12Pyq("mathematics", "relations-and-functions", "The number of one-one functions from a set of 3 elements to a set of 4 elements is", ["12", "24", "64", "81"], 1, "P(4, 3) = 4 × 3 × 2 = 24."),
  class12Pyq("mathematics", "relations-and-functions", "The function f : N → N defined by f(n) = n + 1 is", ["one-one and onto", "one-one but not onto", "onto but not one-one", "neither one-one nor onto"], 1, "f(n) = f(m) implies n = m, but 1 has no preimage in N, so f is one-one but not onto."),
  class12Pyq("mathematics", "relations-and-functions", "The smallest equivalence relation on a non-empty set A is", ["the universal relation", "the identity relation", "the empty relation", "any symmetric relation"], 1, "The identity (equality) relation is the smallest reflexive, symmetric and transitive relation on A."),
  class12Pyq("mathematics", "relations-and-functions", "If a set A has 3 elements, the number of relations on A is", ["8", "9", "256", "512"], 3, "A relation is any subset of A × A, which has 9 ordered pairs, so there are 2⁹ = 512 relations."),
  class12Pyq("mathematics", "relations-and-functions", "f : [0, π] → [−1, 1] defined by f(x) = sin x is", ["one-one and onto", "one-one but not onto", "onto but not one-one", "neither one-one nor onto"], 2, "sin x attains every value in [−1, 1] on [0, π], but sin(π/6) = sin(5π/6), so it is onto but not one-one."),
  class12Pyq("mathematics", "relations-and-functions", "If f(x) = 2x − 3, then f⁻¹(x) is", ["(x + 3)/2", "(x − 3)/2", "2x + 3", "3 − 2x"], 0, "Set y = 2x − 3; then x = (y + 3)/2, so f⁻¹(x) = (x + 3)/2."),
  class12Pyq("mathematics", "relations-and-functions", "The binary operation * on R defined by a * b = a + b − ab is", ["commutative but not associative", "associative but not commutative", "both commutative and associative", "neither commutative nor associative"], 2, "a * b = 1 − (1 − a)(1 − b), which is commutative and associative."),
  class12Pyq("mathematics", "relations-and-functions", "The identity element for a * b = a + b − ab on R is", ["1", "0", "−1", "2"], 1, "a * e = a gives a + e − ae = a, so e(1 − a) = 0 for all a, hence e = 0."),
  class12Pyq("mathematics", "relations-and-functions", "The relation R = {(a, b) : a ≤ b} on R is", ["an equivalence relation", "reflexive and symmetric only", "reflexive and transitive but not symmetric", "symmetric and transitive only"], 2, "≤ is reflexive and transitive, but not symmetric, so it is a partial order, not an equivalence."),
  class12Pyq("mathematics", "relations-and-functions", "For the equivalence x ≡ y (mod 5) on Z, the equivalence class of 0 is", ["{1, 2, 3, 4, 5}", "the set of multiples of 5", "the odd integers", "integers not divisible by 5"], 1, "[0] = {n ∈ Z : 5 divides n}, the multiples of 5."),
  class12Pyq("mathematics", "relations-and-functions", "If f and g are bijective functions, then f ∘ g is", ["one-one only", "onto only", "bijective", "neither one-one nor onto"], 2, "A composition of bijections is a bijection."),
  class12Pyq("mathematics", "relations-and-functions", "The number of onto functions from {1, 2, 3} to {a, b} is", ["6", "8", "9", "4"], 0, "2³ − 2 = 6 (exclude the two constant functions)."),
  class12Pyq("mathematics", "relations-and-functions", "A function f : A → B is invertible if and only if it is", ["one-one", "onto", "one-one and onto", "continuous"], 2, "Invertibility is equivalent to being bijective."),
  class12Pyq("mathematics", "relations-and-functions", "The relation R = {(1, 2), (2, 1), (2, 3), (3, 2)} on {1, 2, 3} is", ["transitive", "reflexive", "symmetric but neither reflexive nor transitive", "an equivalence relation"], 2, "R = R⁻¹ so it is symmetric, but (1, 1) ∉ R and (1, 2), (2, 3) do not force (1, 3) ∈ R."),
  class12Pyq("mathematics", "relations-and-functions", "If f : R → R is given by f(x) = ax + b with a ≠ 0, then f is", ["one-one but not onto", "onto but not one-one", "bijective", "a constant function"], 2, "A non-constant linear polynomial is a bijection from R onto R."),
  class12Pyq("mathematics", "relations-and-functions", "The number of equivalence relations on the set {1, 2, 3} is", ["1", "2", "3", "5"], 3, "The Bell number B₃ = 5 (the partitions of a 3-element set)."),

  // 2. Inverse Trigonometric Functions
  class12Pyq("mathematics", "inverse-trigonometric-functions", "The principal value of sin⁻¹(1/2) is", ["π/6", "π/3", "π/2", "5π/6"], 0, "sin(π/6) = 1/2 and π/6 lies in [−π/2, π/2]."),
  class12Pyq("mathematics", "inverse-trigonometric-functions", "For x ∈ [−1, 1], sin⁻¹ x + cos⁻¹ x equals", ["0", "π/2", "π", "π/4"], 1, "This is a standard identity: sin⁻¹ x + cos⁻¹ x = π/2."),
  class12Pyq("mathematics", "inverse-trigonometric-functions", "The principal value of tan⁻¹(1) is", ["π/4", "π/2", "3π/4", "π"], 0, "tan(π/4) = 1 and π/4 ∈ (−π/2, π/2)."),
  class12Pyq("mathematics", "inverse-trigonometric-functions", "The domain of sin⁻¹ x is", ["R", "[−1, 1]", "[0, 1]", "(−π/2, π/2)"], 1, "sin⁻¹ is defined only for x ∈ [−1, 1]."),
  class12Pyq("mathematics", "inverse-trigonometric-functions", "The range of tan⁻¹ x is", ["[0, π]", "[−π/2, π/2]", "(−π/2, π/2)", "[0, π] excluding π/2"], 2, "The principal branch of tan⁻¹ has range (−π/2, π/2)."),
  class12Pyq("mathematics", "inverse-trigonometric-functions", "The value of sin⁻¹(sin 3π/4) is", ["3π/4", "π/4", "π/2", "−π/4"], 1, "sin(3π/4) = √2/2 and the principal value of sin⁻¹(√2/2) is π/4."),
  class12Pyq("mathematics", "inverse-trigonometric-functions", "For x > 0, tan⁻¹ x + tan⁻¹(1/x) equals", ["π/4", "π/2", "0", "π"], 1, "If x > 0 then tan⁻¹ x + tan⁻¹(1/x) = π/2."),
  class12Pyq("mathematics", "inverse-trigonometric-functions", "The principal value of cos⁻¹(−1) is", ["0", "π/2", "π", "−π"], 2, "cos π = −1 and π lies in the range [0, π] of cos⁻¹."),
  class12Pyq("mathematics", "inverse-trigonometric-functions", "The range of cos⁻¹ x is", ["[0, π]", "(−π/2, π/2)", "[−π/2, π/2]", "[0, π/2]"], 0, "By definition the principal range of cos⁻¹ is [0, π]."),
  class12Pyq("mathematics", "inverse-trigonometric-functions", "sin⁻¹(−√3/2) equals", ["−π/3", "π/3", "2π/3", "−2π/3"], 0, "sin(−π/3) = −√3/2 and −π/3 ∈ [−π/2, π/2]."),
  class12Pyq("mathematics", "inverse-trigonometric-functions", "The principal value of cot⁻¹(−1) is", ["π/4", "−π/4", "3π/4", "π/2"], 2, "The range of cot⁻¹ is (0, π), and cot(3π/4) = −1."),
  class12Pyq("mathematics", "inverse-trigonometric-functions", "The domain of sec⁻¹ x is", ["[−1, 1]", "R", "(−∞, −1] ∪ [1, ∞)", "(0, π)"], 2, "sec⁻¹ x is defined for |x| ≥ 1."),
  class12Pyq("mathematics", "inverse-trigonometric-functions", "tan⁻¹(1/2) + tan⁻¹(1/3) equals", ["π/4", "π/3", "π/2", "π/6"], 0, "(1/2)(1/3) < 1, so the sum is tan⁻¹(1) = π/4."),
  class12Pyq("mathematics", "inverse-trigonometric-functions", "sin(2 sin⁻¹(3/5)) equals", ["7/25", "24/25", "3/5", "4/5"], 1, "sin(2θ) = 2 sin θ cos θ = 2(3/5)(4/5) = 24/25."),
  class12Pyq("mathematics", "inverse-trigonometric-functions", "cos(tan⁻¹(3/4)) equals", ["3/5", "4/5", "3/4", "5/4"], 1, "If tan θ = 3/4 then the adjacent side is 4 and the hypotenuse is 5, so cos θ = 4/5."),
  class12Pyq("mathematics", "inverse-trigonometric-functions", "tan⁻¹ √3 − sec⁻¹(−2) equals", ["π/3", "−π/3", "π", "0"], 1, "tan⁻¹ √3 = π/3 and sec⁻¹(−2) = 2π/3, so the difference is −π/3."),
  class12Pyq("mathematics", "inverse-trigonometric-functions", "If |x| < 1, then 2 tan⁻¹ x equals", ["tan⁻¹(2x/(1 − x²))", "tan⁻¹(2x/(1 + x²))", "2x", "π/2"], 0, "This is the double-angle formula for tan⁻¹, valid for |x| < 1."),
  class12Pyq("mathematics", "inverse-trigonometric-functions", "For x ∈ [−1, 1], cos⁻¹ x + cos⁻¹(−x) equals", ["0", "π/2", "π", "2π"], 2, "cos⁻¹(−x) = π − cos⁻¹ x, so the sum is π."),
  class12Pyq("mathematics", "inverse-trigonometric-functions", "tan⁻¹ x + cot⁻¹ x equals", ["π/4", "π/2", "π", "0"], 1, "This is a standard identity for all real x."),
  class12Pyq("mathematics", "inverse-trigonometric-functions", "The value of tan⁻¹ 1 + tan⁻¹ 2 + tan⁻¹ 3 is", ["π", "π/2", "π/4", "0"], 0, "tan⁻¹ 2 + tan⁻¹ 3 = 3π/4, and adding tan⁻¹ 1 = π/4 gives π."),

  // 3. Matrices
  class12Pyq("mathematics", "matrices", "If A is a skew-symmetric matrix of odd order, then |A| equals", ["1", "−1", "0", "the order of A"], 2, "|A| = |Aᵀ| = |−A| = (−1)ⁿ |A| and n is odd, so |A| = −|A|, hence |A| = 0."),
  class12Pyq("mathematics", "matrices", "A square matrix A is invertible if and only if", ["A is symmetric", "A is skew-symmetric", "|A| ≠ 0", "A is diagonal"], 2, "A is non-singular (invertible) precisely when its determinant is non-zero."),
  class12Pyq("mathematics", "matrices", "(AB)⁻¹ equals", ["A⁻¹ B⁻¹", "B⁻¹ A⁻¹", "AB", "BA"], 1, "The inverse of a product reverses the order: (AB)⁻¹ = B⁻¹ A⁻¹."),
  class12Pyq("mathematics", "matrices", "If A is a symmetric matrix, then Aᵀ equals", ["−A", "A", "A⁻¹", "I"], 1, "By definition a symmetric matrix satisfies Aᵀ = A."),
  class12Pyq("mathematics", "matrices", "Any square matrix can be expressed uniquely as the sum of", ["two diagonal matrices", "a symmetric and a skew-symmetric matrix", "two identity matrices", "a row matrix and a column matrix"], 1, "A = (A + Aᵀ)/2 + (A − Aᵀ)/2, the unique symmetric–skew-symmetric splitting."),
  class12Pyq("mathematics", "matrices", "If A is skew-symmetric, then every diagonal element of A is", ["1", "−1", "0", "equal to the trace"], 2, "aᵢᵢ = −aᵢᵢ implies 2aᵢᵢ = 0, so each diagonal entry is 0."),
  class12Pyq("mathematics", "matrices", "The number of all 2 × 2 matrices with each entry 0 or 1 is", ["4", "8", "16", "32"], 2, "There are 4 entries, each with 2 choices, so 2⁴ = 16 such matrices."),
  class12Pyq("mathematics", "matrices", "(Aᵀ)ᵀ equals", ["Aᵀ", "−A", "A", "A⁻¹"], 2, "Taking transpose twice returns the original matrix."),
  class12Pyq("mathematics", "matrices", "If A is invertible, then (Aᵀ)⁻¹ equals", ["(A⁻¹)ᵀ", "Aᵀ", "A⁻¹", "A"], 0, "The inverse of the transpose is the transpose of the inverse."),
  class12Pyq("mathematics", "matrices", "If A = [[1, 2], [3, 4]], then A⁻¹ is", ["[[−2, 1], [3/2, −1/2]]", "[[4, −2], [−3, 1]]", "[[1, 0], [0, 1]]", "[[2, 1], [1, 2]]"], 0, "|A| = −2 and A⁻¹ = (1/|A|) adj A = [[−2, 1], [3/2, −1/2]]."),
  class12Pyq("mathematics", "matrices", "Matrix multiplication is", ["always commutative", "always associative", "never associative", "commutative only for the zero matrix"], 1, "Matrix multiplication is associative whenever the products are defined, but not commutative in general."),
  class12Pyq("mathematics", "matrices", "If AB = I, then", ["A = B", "B = A⁻¹", "A is singular", "B is the zero matrix"], 1, "B is a right inverse of A; for square matrices this means B = A⁻¹."),
  class12Pyq("mathematics", "matrices", "A matrix A satisfying A² = A is called", ["nilpotent", "idempotent", "involutory", "orthogonal"], 1, "Idempotent matrices satisfy A² = A."),
  class12Pyq("mathematics", "matrices", "A matrix A satisfying A² = I is called", ["idempotent", "nilpotent", "involutory", "singular"], 2, "Involutory matrices satisfy A² = I, so A⁻¹ = A."),
  class12Pyq("mathematics", "matrices", "If A is an orthogonal matrix, then", ["Aᵀ A = I", "A + Aᵀ = I", "A² = O", "|A| = 0"], 0, "Orthogonal means A⁻¹ = Aᵀ, equivalently Aᵀ A = I."),
  class12Pyq("mathematics", "matrices", "If A is 2 × 3 and B is 3 × 4, then AB is of order", ["2 × 4", "3 × 3", "4 × 2", "2 × 3"], 0, "An m × n matrix times an n × p matrix is m × p, here 2 × 4."),
  class12Pyq("mathematics", "matrices", "A diagonal matrix whose diagonal entries are all equal is called a", ["identity matrix", "scalar matrix", "null matrix", "row matrix"], 1, "A scalar matrix is kI, a diagonal matrix with equal diagonal entries."),
  class12Pyq("mathematics", "matrices", "The inverse of the 2 × 2 identity matrix I is", ["the zero matrix", "I", "2I", "undefined"], 1, "I I = I, so I⁻¹ = I."),
  class12Pyq("mathematics", "matrices", "The matrix A = [[0, 1], [−1, 0]] is", ["symmetric", "skew-symmetric", "an identity matrix", "a null matrix"], 1, "Aᵀ = [[0, −1], [1, 0]] = −A, so A is skew-symmetric."),
  class12Pyq("mathematics", "matrices", "For any square matrix A, the matrix A + Aᵀ is always", ["skew-symmetric", "symmetric", "singular", "an identity matrix"], 1, "(A + Aᵀ)ᵀ = Aᵀ + A = A + Aᵀ."),

  // 4. Determinants
  class12Pyq("mathematics", "determinants", "If two rows of a determinant are identical, its value is", ["1", "−1", "0", "2"], 2, "Identical rows make the rows linearly dependent, so the determinant vanishes."),
  class12Pyq("mathematics", "determinants", "|Aᵀ| equals", ["−|A|", "|A|", "1/|A|", "0"], 1, "A matrix and its transpose have the same determinant."),
  class12Pyq("mathematics", "determinants", "|AB| equals", ["|A| + |B|", "|A| |B|", "|A| − |B|", "|Aᵀ| + |B|"], 1, "The determinant of a product is the product of the determinants."),
  class12Pyq("mathematics", "determinants", "If A is an n × n matrix, then |kA| equals", ["k |A|", "kⁿ |A|", "n k |A|", "|A|/k"], 1, "Each of the n rows contributes a factor k."),
  class12Pyq("mathematics", "determinants", "If A is 3 × 3 and |A| = 5, then |A⁻¹| is", ["5", "1/5", "125", "−5"], 1, "|A⁻¹| = 1/|A| = 1/5."),
  class12Pyq("mathematics", "determinants", "Interchanging two rows of a determinant", ["does not change its value", "multiplies it by 2", "changes its sign", "makes it zero"], 2, "A single row interchange multiplies the determinant by −1."),
  class12Pyq("mathematics", "determinants", "If A is 3 × 3 and |A| = 2, then |adj A| is", ["2", "4", "8", "1"], 1, "|adj A| = |A|^{n−1} = 2² = 4."),
  class12Pyq("mathematics", "determinants", "A (adj A) equals", ["I", "|A| I", "O", "A⁻¹"], 1, "A (adj A) = (adj A) A = |A| I."),
  class12Pyq("mathematics", "determinants", "If one row of a determinant is entirely zero, the value is", ["1", "0", "−1", "undefined"], 1, "A zero row makes the determinant zero."),
  class12Pyq("mathematics", "determinants", "If two rows of a determinant are proportional, the value is", ["1", "0", "the ratio of the rows", "−1"], 1, "Proportional rows are linearly dependent, so the determinant is 0."),
  class12Pyq("mathematics", "determinants", "|A²| equals", ["2|A|", "|A|²", "|A|", "0"], 1, "|A²| = |A| |A| = |A|²."),
  class12Pyq("mathematics", "determinants", "The square system AX = B has a unique solution if and only if", ["|A| = 0", "|A| ≠ 0", "B = 0", "A is symmetric"], 1, "Unique solution exists precisely when A is invertible, i.e. |A| ≠ 0."),
  class12Pyq("mathematics", "determinants", "If A is upper triangular, then |A| equals", ["0", "the sum of the diagonal entries", "the product of the diagonal entries", "1"], 2, "The determinant of a triangular matrix is the product of its diagonal elements."),
  class12Pyq("mathematics", "determinants", "The area of the triangle with vertices (0, 0), (1, 0) and (0, 2) is", ["1", "2", "1/2", "0"], 0, "Area = (1/2) |1 · 2 − 0 · 0| = 1."),
  class12Pyq("mathematics", "determinants", "If A is a skew-symmetric matrix of order 3, then |A| is", ["1", "0", "−1", "3"], 1, "A skew-symmetric matrix of odd order is singular."),
  class12Pyq("mathematics", "determinants", "Multiplying one row of a determinant by k multiplies the value by", ["kⁿ", "k", "n", "1/k"], 1, "A common factor in a single row factors out as k."),
  class12Pyq("mathematics", "determinants", "The value of det I₃, where I₃ is the 3 × 3 identity, is", ["0", "1", "3", "−1"], 1, "The identity matrix has determinant 1."),
  class12Pyq("mathematics", "determinants", "If A is 2 × 2 and |A| = 4, then |3A| is", ["12", "36", "4", "9"], 1, "|3A| = 3² |A| = 9 × 4 = 36."),
  class12Pyq("mathematics", "determinants", "The cofactor of aᵢⱼ is", ["the minor Mᵢⱼ", "(−1)^{i+j} Mᵢⱼ", "−Mᵢⱼ always", "|A|"], 1, "Cᵢⱼ = (−1)^{i+j} times the corresponding minor."),
  class12Pyq("mathematics", "determinants", "If A is 3 × 3 and |A| = −2, then |−A| is", ["−2", "2", "8", "−8"], 1, "|−A| = (−1)³ |A| = −(−2) = 2."),

  // 5. Continuity and Differentiability
  class12Pyq("mathematics", "continuity-and-differentiability", "If f is differentiable at a, then f is", ["discontinuous at a", "continuous at a", "constant near a", "monotonic near a"], 1, "Differentiability at a point implies continuity at that point."),
  class12Pyq("mathematics", "continuity-and-differentiability", "The function f(x) = |x| is", ["differentiable at 0", "continuous at 0 but not differentiable at 0", "discontinuous at 0", "not continuous anywhere"], 1, "|x| is continuous everywhere; the left and right derivatives at 0 differ."),
  class12Pyq("mathematics", "continuity-and-differentiability", "The function f(x) = x |x| at x = 0 is", ["not continuous", "continuous but not differentiable", "differentiable", "undefined"], 2, "f(x) = x² for x ≥ 0 and f(x) = −x² for x < 0, so f'(0) = 0."),
  class12Pyq("mathematics", "continuity-and-differentiability", "Rolle's theorem requires f(a) = f(b) together with f being", ["continuous only on (a, b)", "continuous on [a, b] and differentiable on (a, b)", "differentiable only at a and b", "a polynomial"], 1, "These are the standard hypotheses of Rolle's theorem."),
  class12Pyq("mathematics", "continuity-and-differentiability", "By Lagrange's mean value theorem, there exists c ∈ (a, b) such that f'(c) equals", ["f(a) + f(b)", "(f(b) − f(a))/(b − a)", "f(b) − f(a)", "0"], 1, "MVT states f'(c) = (f(b) − f(a))/(b − a)."),
  class12Pyq("mathematics", "continuity-and-differentiability", "d/dx (sin⁻¹ x) equals", ["1/(1 + x²)", "1/√(1 − x²)", "−1/√(1 − x²)", "√(1 − x²)"], 1, "The standard derivative of sin⁻¹ x is 1/√(1 − x²) for |x| < 1."),
  class12Pyq("mathematics", "continuity-and-differentiability", "d/dx (aˣ) equals", ["aˣ", "aˣ logₑ a", "x a^{x−1}", "1/aˣ"], 1, "aˣ = e^{x log a}, so its derivative is aˣ log a."),
  class12Pyq("mathematics", "continuity-and-differentiability", "d/dx (logₑ x) equals", ["x", "1/x", "log x", "eˣ"], 1, "The derivative of the natural logarithm is 1/x for x > 0."),
  class12Pyq("mathematics", "continuity-and-differentiability", "d/dx (tan⁻¹ x) equals", ["1/(1 + x²)", "1/(1 − x²)", "√(1 + x²)", "1/x"], 0, "This is the standard derivative of tan⁻¹ x."),
  class12Pyq("mathematics", "continuity-and-differentiability", "The converse of “differentiable ⇒ continuous” is", ["always true", "not necessarily true", "true only at 0", "true only for polynomials"], 1, "|x| is continuous at 0 but not differentiable there, so the converse fails."),
  class12Pyq("mathematics", "continuity-and-differentiability", "For x > 0, d/dx (xˣ) equals", ["xˣ", "xˣ (1 + log x)", "x^{x−1}", "xˣ log x"], 1, "Write xˣ = e^{x log x}; differentiating gives xˣ (1 + log x)."),
  class12Pyq("mathematics", "continuity-and-differentiability", "The greatest integer function [x] is discontinuous at", ["every integer", "every non-integer", "only 0", "no real number"], 0, "[x] has a jump discontinuity at each integer."),
  class12Pyq("mathematics", "continuity-and-differentiability", "d/dx (e^{ax}) equals", ["e^{ax}", "a e^{ax}", "a eˣ", "x e^{ax}"], 1, "Chain rule: derivative of e^{ax} is a e^{ax}."),
  class12Pyq("mathematics", "continuity-and-differentiability", "If f'(x) = 0 for all x in an interval (a, b), then on (a, b) the function f is", ["increasing", "decreasing", "constant", "quadratic"], 2, "A function with vanishing derivative on an interval is constant there."),
  class12Pyq("mathematics", "continuity-and-differentiability", "The chain rule states that d/dx [f(g(x))] equals", ["f'(x) g'(x)", "f'(g(x)) g'(x)", "f(g'(x))", "g'(f(x))"], 1, "Differentiate the outer function at g(x) and multiply by g'(x)."),
  class12Pyq("mathematics", "continuity-and-differentiability", "f(x) = |x − 1| is not differentiable at", ["0", "1", "−1", "every real number"], 1, "The corner of |x − 1| is at x = 1."),
  class12Pyq("mathematics", "continuity-and-differentiability", "f is continuous at x = a if and only if", ["lim_{x→a} f(x) exists", "f(a) is defined", "lim_{x→a} f(x) = f(a)", "f'(a) exists"], 2, "Continuity requires the limit to exist and equal the function value."),
  class12Pyq("mathematics", "continuity-and-differentiability", "d/dx (cos⁻¹ x) equals", ["1/√(1 − x²)", "−1/√(1 − x²)", "1/(1 + x²)", "−1/(1 + x²)"], 1, "The derivative of cos⁻¹ x is the negative of that of sin⁻¹ x."),
  class12Pyq("mathematics", "continuity-and-differentiability", "If y = sin 2x, then dy/dx at x = π/4 is", ["0", "2", "−2", "1"], 0, "dy/dx = 2 cos 2x; at x = π/4 one has 2 cos(π/2) = 0."),
  class12Pyq("mathematics", "continuity-and-differentiability", "Logarithmic differentiation is especially useful for", ["sums of linear terms only", "products, quotients and functions of the form [u(x)]^{v(x)}", "constant functions", "definite integrals"], 1, "Taking log reduces products, quotients and exponential-variable powers to sums."),

  // 6. Application of Derivatives
  class12Pyq("mathematics", "application-of-derivatives", "The slope of the tangent to y = f(x) at x = a is", ["f(a)", "f'(a)", "−1/f'(a)", "f''(a)"], 1, "By definition the derivative is the slope of the tangent."),
  class12Pyq("mathematics", "application-of-derivatives", "If f'(a) ≠ 0, the slope of the normal at x = a is", ["f'(a)", "−f'(a)", "−1/f'(a)", "1/f'(a)"], 2, "The normal is perpendicular to the tangent, so its slope is −1/f'(a)."),
  class12Pyq("mathematics", "application-of-derivatives", "f is strictly increasing on an interval I if", ["f'(x) < 0 on I", "f'(x) > 0 on I", "f'(x) = 0 on I", "f''(x) > 0 on I"], 1, "A positive derivative implies the function is strictly increasing."),
  class12Pyq("mathematics", "application-of-derivatives", "At a local maximum with f''(c) existing, one has f'(c) = 0 and", ["f''(c) > 0", "f''(c) < 0", "f''(c) = 0 always", "f(c) = 0"], 1, "The second-derivative test: f''(c) < 0 indicates a local maximum."),
  class12Pyq("mathematics", "application-of-derivatives", "At a local minimum with f''(c) existing and non-zero, typically", ["f''(c) > 0", "f''(c) < 0", "f(c) < 0", "f''(c) = 1"], 0, "f''(c) > 0 indicates a local minimum."),
  class12Pyq("mathematics", "application-of-derivatives", "The maximum value of sin x + cos x is", ["1", "2", "√2", "1/√2"], 2, "sin x + cos x = √2 sin(x + π/4), whose maximum is √2."),
  class12Pyq("mathematics", "application-of-derivatives", "The minimum value of x + 1/x for x > 0 is", ["0", "1", "2", "−2"], 2, "AM–GM, or f'(x) = 1 − 1/x² = 0 at x = 1, gives the minimum 2."),
  class12Pyq("mathematics", "application-of-derivatives", "The equation of the tangent to y = x² at (1, 1) is", ["y = x", "y = 2x − 1", "y = 2x + 1", "y = x + 1"], 1, "f'(x) = 2x so the slope at x = 1 is 2; y − 1 = 2(x − 1) gives y = 2x − 1."),
  class12Pyq("mathematics", "application-of-derivatives", "A point where f'(x) = 0 (or f' does not exist) is called", ["an inflection point always", "a critical point", "an asymptote", "a point of discontinuity"], 1, "Critical (stationary) points are where the derivative vanishes or fails to exist."),
  class12Pyq("mathematics", "application-of-derivatives", "The rate of change of the area A = πr² of a circle with respect to r is", ["πr", "2πr", "πr²", "2r"], 1, "dA/dr = 2πr, the circumference."),
  class12Pyq("mathematics", "application-of-derivatives", "If f' changes from positive to negative at c, then x = c is a", ["local minimum", "local maximum", "point of inflection only", "discontinuity"], 1, "The first-derivative test: + to − yields a local maximum."),
  class12Pyq("mathematics", "application-of-derivatives", "A continuous function on a closed interval [a, b] attains its absolute max/min", ["only at the endpoints", "only where f' = 0", "at a critical point or an endpoint", "nowhere in general"], 2, "Extreme Value Theorem: extrema occur at critical points or endpoints."),
  class12Pyq("mathematics", "application-of-derivatives", "The function f(x) = x² is decreasing on", ["(0, ∞)", "(−∞, 0]", "[0, ∞)", "R"], 1, "f'(x) = 2x ≤ 0 on (−∞, 0], so f is decreasing there."),
  class12Pyq("mathematics", "application-of-derivatives", "The linear approximation is f(x + Δx) ≈", ["f(x) + f'(x) Δx", "f'(x) only", "f(x) Δx", "f''(x) Δx"], 0, "This is the differential approximation dy = f'(x) dx."),
  class12Pyq("mathematics", "application-of-derivatives", "A point of inflection typically satisfies", ["f'(x) = 0 only", "f''(x) = 0 and a change of concavity", "f(x) = 0", "f'(x) > 0"], 1, "Concavity changes at an inflection point, which often requires f'' = 0."),
  class12Pyq("mathematics", "application-of-derivatives", "For y = x³ − 3x, a local maximum occurs at", ["x = 1", "x = −1", "x = 0", "x = 3"], 1, "y' = 3(x² − 1); y'' = 6x, so y''(−1) < 0 and x = −1 is a local max."),
  class12Pyq("mathematics", "application-of-derivatives", "The tangent to y = f(x) is parallel to the x-axis when", ["f'(x) = 1", "f'(x) = 0", "f'(x) is undefined", "f''(x) = 0"], 1, "A horizontal tangent has slope 0."),
  class12Pyq("mathematics", "application-of-derivatives", "The normal to y = x at the point (1, 1) is", ["y = x", "y = −x + 2", "y = −x", "y = 2x"], 1, "The tangent has slope 1, so the normal has slope −1: y − 1 = −(x − 1)."),
  class12Pyq("mathematics", "application-of-derivatives", "If the radius of a circle increases at 0.5 cm/s, then dA/dt when r = 2 cm is", ["2π cm²/s", "π cm²/s", "4π cm²/s", "0.5 cm²/s"], 0, "dA/dt = 2πr dr/dt = 2π · 2 · 0.5 = 2π cm²/s."),
  class12Pyq("mathematics", "application-of-derivatives", "The absolute maximum of f(x) = x + 1/x on [1, 2] occurs at", ["x = 1", "x = 2", "x = 1.5", "every point of [1, 2]"], 1, "f(1) = 2 and f(2) = 2.5, and f' ≥ 0 on [1, 2], so the maximum is at x = 2."),

  // 7. Integrals
  class12Pyq("mathematics", "integrals", "∫ sin x dx equals", ["cos x + C", "−cos x + C", "sin x + C", "−sin x + C"], 1, "The antiderivative of sin x is −cos x."),
  class12Pyq("mathematics", "integrals", "∫ dx/x equals", ["x + C", "logₑ |x| + C", "1/x² + C", "eˣ + C"], 1, "The standard integral of 1/x is log |x| + C."),
  class12Pyq("mathematics", "integrals", "∫ eˣ dx equals", ["eˣ + C", "x eˣ + C", "log x + C", "e^{−x} + C"], 0, "The exponential function is its own antiderivative."),
  class12Pyq("mathematics", "integrals", "∫ dx/(1 + x²) equals", ["sin⁻¹ x + C", "tan⁻¹ x + C", "sec⁻¹ x + C", "log(1 + x²) + C"], 1, "This is the standard integral giving tan⁻¹ x."),
  class12Pyq("mathematics", "integrals", "∫ dx/√(1 − x²) equals", ["tan⁻¹ x + C", "sin⁻¹ x + C", "cos⁻¹ x + C", "sec⁻¹ x + C"], 1, "This is the standard integral giving sin⁻¹ x."),
  class12Pyq("mathematics", "integrals", "∫ sec² x dx equals", ["sec x + C", "tan x + C", "cot x + C", "cos x + C"], 1, "The derivative of tan x is sec² x."),
  class12Pyq("mathematics", "integrals", "∫ xⁿ dx (n ≠ −1) equals", ["n x^{n−1} + C", "x^{n+1}/(n + 1) + C", "xⁿ/n + C", "n xⁿ + C"], 1, "The power rule for integration holds when n ≠ −1."),
  class12Pyq("mathematics", "integrals", "∫₀^π sin x dx equals", ["0", "1", "2", "π"], 2, "[−cos x]₀^π = −(−1) − (−1) = 2."),
  class12Pyq("mathematics", "integrals", "The property ∫₀^a f(x) dx equals", ["∫₀^a f(a − x) dx", "∫₀^a f(a + x) dx", "0 always", "f(a) − f(0)"], 0, "The substitution t = a − x yields this standard property."),
  class12Pyq("mathematics", "integrals", "∫_{−a}^a of an odd integrable function equals", ["2 ∫₀^a of the function", "0", "a", "undefined always"], 1, "The contributions of an odd function on [−a, 0] and [0, a] cancel."),
  class12Pyq("mathematics", "integrals", "∫_{−a}^a of an even integrable function equals", ["0", "2 ∫₀^a of the function", "∫₀^{2a} of the function", "a"], 1, "An even function doubles the integral from 0 to a."),
  class12Pyq("mathematics", "integrals", "∫ log x dx equals", ["1/x + C", "x log x − x + C", "x log x + C", "log x − x + C"], 1, "Integration by parts with u = log x, dv = dx gives x log x − x + C."),
  class12Pyq("mathematics", "integrals", "∫ eˣ [f(x) + f'(x)] dx equals", ["eˣ + C", "eˣ f(x) + C", "f(x) + C", "eˣ f'(x) + C"], 1, "The integrand is the derivative of eˣ f(x)."),
  class12Pyq("mathematics", "integrals", "∫ tan x dx equals", ["sec x + C", "log |sec x| + C", "log |sin x| + C", "cos x + C"], 1, "∫ tan x dx = ∫ sin x/cos x dx = −log |cos x| = log |sec x| + C."),
  class12Pyq("mathematics", "integrals", "∫₀^{π/2} sin² x dx equals", ["π/2", "π/4", "1", "0"], 1, "sin² x = (1 − cos 2x)/2, so the integral is π/4."),
  class12Pyq("mathematics", "integrals", "∫₀^{π/2} sinⁿ x dx equals", ["∫₀^{π/2} cosⁿ x dx", "0", "1", "π/2"], 0, "The substitution t = π/2 − x interchanges sin and cos."),
  class12Pyq("mathematics", "integrals", "∫ dx/(x² − a²) equals", ["(1/(2a)) log |(x − a)/(x + a)| + C", "tan⁻¹(x/a) + C", "(1/a) tan⁻¹(x/a) + C", "log(x² − a²) + C"], 0, "This is the standard logarithmic form for the difference of squares."),
  class12Pyq("mathematics", "integrals", "∫ sec x tan x dx equals", ["tan x + C", "sec x + C", "sec² x + C", "cos x + C"], 1, "The derivative of sec x is sec x tan x."),
  class12Pyq("mathematics", "integrals", "∫_a^b f(x) dx equals", ["∫_b^a f(x) dx", "−∫_b^a f(x) dx", "0 always", "f(b) − f(a)"], 1, "Reversing the limits of a definite integral changes its sign."),
  class12Pyq("mathematics", "integrals", "Integration by parts states that ∫ u dv equals", ["uv + ∫ v du", "uv − ∫ v du", "u'v − ∫ v du", "uv"], 1, "This is the integral form of the product rule."),

  // 8. Application of Integrals
  class12Pyq("mathematics", "application-of-integrals", "The area under y = x from x = 0 to x = 1 is", ["1", "1/2", "0", "2"], 1, "∫₀¹ x dx = 1/2, the area of a right triangle of legs 1."),
  class12Pyq("mathematics", "application-of-integrals", "The area of the circle x² + y² = a² is", ["2πa", "πa²", "4a²", "πa"], 1, "4 ∫₀^a √(a² − x²) dx = πa²."),
  class12Pyq("mathematics", "application-of-integrals", "The area bounded by y = x² and y = x is", ["1/2", "1/3", "1/6", "1"], 2, "They meet at 0 and 1; ∫₀¹ (x − x²) dx = 1/2 − 1/3 = 1/6."),
  class12Pyq("mathematics", "application-of-integrals", "The area of the ellipse x²/a² + y²/b² = 1 is", ["πab", "πa²", "4ab", "2πab"], 0, "The standard area of the ellipse is πab."),
  class12Pyq("mathematics", "application-of-integrals", "The area under y = sin x from 0 to π is", ["0", "1", "2", "π"], 2, "∫₀^π sin x dx = 2."),
  class12Pyq("mathematics", "application-of-integrals", "The area bounded by the parabola y² = 4ax and its latus rectum is", ["4a²/3", "8a²/3", "2a²", "4a²"], 1, "The latus rectum is x = a; the area is 2 ∫₀^a 2√(ax) dy-form, equal to 8a²/3."),
  class12Pyq("mathematics", "application-of-integrals", "The area common to y = x² and x = y² is", ["1/3", "1/2", "2/3", "1"], 0, "∫₀¹ (√x − x²) dx = 2/3 − 1/3 = 1/3."),
  class12Pyq("mathematics", "application-of-integrals", "The area of the region |x| + |y| ≤ 1 is", ["1", "2", "4", "√2"], 1, "The region is a diamond with diagonals of length 2, so area 2."),
  class12Pyq("mathematics", "application-of-integrals", "The area under y = eˣ from 0 to 1 is", ["e", "e − 1", "1", "e + 1"], 1, "∫₀¹ eˣ dx = e − 1."),
  class12Pyq("mathematics", "application-of-integrals", "The area bounded by y = |x − 1| and the x-axis from x = 0 to x = 2 is", ["0", "1", "2", "4"], 1, "Two right triangles of area 1/2 each give total area 1."),
  class12Pyq("mathematics", "application-of-integrals", "The area in the first quadrant bounded by y = √x, the x-axis and x = 4 is", ["8/3", "16/3", "4", "8"], 1, "∫₀⁴ x^{1/2} dx = (2/3) x^{3/2} from 0 to 4 = 16/3."),
  class12Pyq("mathematics", "application-of-integrals", "The area of the triangle bounded by the axes and the line x + y = 1 is", ["1", "1/2", "2", "0"], 1, "It is a right triangle with legs of length 1, so area 1/2."),
  class12Pyq("mathematics", "application-of-integrals", "The area under y = 1/x from 1 to e is", ["e", "1", "0", "e − 1"], 1, "∫₁^e dx/x = log e − log 1 = 1."),
  class12Pyq("mathematics", "application-of-integrals", "The area bounded by y = x³ and the x-axis from x = −1 to x = 1 (taken positively) is", ["0", "1/2", "1", "2"], 1, "2 ∫₀¹ x³ dx = 2 · (1/4) = 1/2."),
  class12Pyq("mathematics", "application-of-integrals", "The area between y = x² and the line y = 2x is", ["2/3", "4/3", "1", "8/3"], 1, "They meet at 0 and 2; ∫₀² (2x − x²) dx = 4 − 8/3 = 4/3."),
  class12Pyq("mathematics", "application-of-integrals", "The area enclosed by y = cos x and y = sin x from x = 0 to x = π/4 is", ["√2 − 1", "1", "√2", "1/2"], 0, "∫₀^{π/4} (cos x − sin x) dx = √2 − 1."),
  class12Pyq("mathematics", "application-of-integrals", "The area bounded by y² = x and the line x = 4 is", ["16/3", "32/3", "8/3", "4"], 1, "2 ∫₀⁴ √x dx = (4/3) x^{3/2} from 0 to 4 = 32/3."),
  class12Pyq("mathematics", "application-of-integrals", "The area bounded by y = x², the x-axis and the lines x = 1 and x = 2 is", ["7/3", "8/3", "1", "3"], 0, "∫₁² x² dx = [x³/3]₁² = 8/3 − 1/3 = 7/3."),
  class12Pyq("mathematics", "application-of-integrals", "The area in the first quadrant under x² + y² = 1 is", ["π", "π/2", "π/4", "1"], 2, "A quarter of the unit circle has area π/4."),
  class12Pyq("mathematics", "application-of-integrals", "The area under the upper semicircle y = √(a² − x²) from −a to a is", ["πa²", "πa²/2", "2πa", "a²"], 1, "This is the area of a semicircle of radius a."),

  // 9. Differential Equations
  class12Pyq("mathematics", "differential-equations", "The order of d²y/dx² + (dy/dx)³ + y = 0 is", ["1", "2", "3", "not defined"], 1, "The highest derivative present is y'', so the order is 2."),
  class12Pyq("mathematics", "differential-equations", "The degree of d²y/dx² + (dy/dx)³ + y = 0 is", ["1", "2", "3", "not defined"], 0, "The equation is polynomial in y'' of power 1, so the degree is 1."),
  class12Pyq("mathematics", "differential-equations", "The degree of sin(y'') + y' = 0 is", ["1", "2", "0", "not defined"], 3, "Degree is defined only when the DE is a polynomial in the highest-order derivative."),
  class12Pyq("mathematics", "differential-equations", "The order of a differential equation equals the number of", ["its degree", "arbitrary constants in the general solution", "independent variables", "particular solutions"], 1, "Eliminating n arbitrary constants from a family yields an nth-order DE."),
  class12Pyq("mathematics", "differential-equations", "The general solution of dy/dx = y/x (x ≠ 0) is", ["y = x + C", "y = Cx", "y = C/x", "y = C x²"], 1, "Separating variables gives dy/y = dx/x, so log |y| = log |x| + k, hence y = Cx."),
  class12Pyq("mathematics", "differential-equations", "The integrating factor of dy/dx + P(x) y = Q(x) is", ["e^{∫ Q dx}", "e^{∫ P dx}", "∫ P dx", "P/Q"], 1, "IF = e^{∫ P dx} converts the left side into an exact derivative."),
  class12Pyq("mathematics", "differential-equations", "The differential equation dy/dx + y = 0 has solution", ["y = C eˣ", "y = C e^{−x}", "y = Cx", "y = C"], 1, "Separable: dy/y = −dx, so y = C e^{−x}."),
  class12Pyq("mathematics", "differential-equations", "The equation d²y/dx² = 0 has general solution", ["y = C", "y = Cx", "y = C₁ x + C₂", "y = C x²"], 2, "Integrating twice introduces two arbitrary constants."),
  class12Pyq("mathematics", "differential-equations", "A particular solution of dy/dx = 2x with y(0) = 1 is", ["y = x²", "y = x² + 1", "y = 2x + 1", "y = 1"], 1, "y = x² + C and y(0) = 1 give C = 1."),
  class12Pyq("mathematics", "differential-equations", "The equation x dx + y dy = 0 is", ["linear in y of first degree only", "variable separable", "of order 2", "a partial differential equation"], 1, "Separating gives x dx = −y dy, which integrates to x² + y² = C."),
  class12Pyq("mathematics", "differential-equations", "For a homogeneous first-order equation, the usual substitution is", ["y = vx", "x = v²", "y = v + x", "y = e^v"], 0, "Putting y = vx reduces a homogeneous DE to a separable equation in v and x."),
  class12Pyq("mathematics", "differential-equations", "The order of (y'')² + (y')³ + y⁴ = 0 is", ["1", "2", "3", "4"], 1, "The highest derivative is still y'', so the order is 2."),
  class12Pyq("mathematics", "differential-equations", "The degree of (y'')² + (y')³ + y⁴ = 0 is", ["1", "2", "3", "4"], 1, "The highest derivative y'' appears to the power 2."),
  class12Pyq("mathematics", "differential-equations", "The solution of dy/dx = ky (k constant) is", ["y = kx + C", "y = C e^{kx}", "y = k eˣ", "y = C/k"], 1, "This is the exponential-growth/decay equation."),
  class12Pyq("mathematics", "differential-equations", "The family of lines y = mx + c with c fixed and m arbitrary has a DE of order", ["0", "1", "2", "3"], 1, "One arbitrary parameter yields a first-order equation."),
  class12Pyq("mathematics", "differential-equations", "A linear first-order DE has the form", ["dy/dx + P(x) y = Q(x)", "y dy/dx = Q(x)", "d²y/dx² + y = 0", "y = Px + Q"], 0, "This is the standard linear first-order form."),
  class12Pyq("mathematics", "differential-equations", "The differential equation of the family of circles x² + y² = r² (r arbitrary) is", ["x + y y' = 0", "x + y y' = r", "y' = x/y", "xy' − y = 0"], 0, "Differentiating: 2x + 2y y' = 0, so x + y y' = 0."),
  class12Pyq("mathematics", "differential-equations", "The number of arbitrary constants in the general solution of a 3rd-order DE is", ["1", "2", "3", "0"], 2, "The general solution of an nth-order DE contains n arbitrary constants."),
  class12Pyq("mathematics", "differential-equations", "The solution of dy/dx = 1 with y(0) = 0 is", ["y = 1", "y = x", "y = x²", "y = eˣ"], 1, "y = x + C and y(0) = 0 give y = x."),
  class12Pyq("mathematics", "differential-equations", "If the general solution is y = C₁ eˣ + C₂ e^{−x}, the order of the DE is", ["1", "2", "0", "3"], 1, "Two independent arbitrary constants mean the equation is of order 2."),

  // 10. Vector Algebra
  class12Pyq("mathematics", "vector-algebra", "a · b equals", ["|a| |b| sin θ", "|a| |b| cos θ", "|a × b|", "0 always"], 1, "The definition of the scalar (dot) product is |a| |b| cos θ."),
  class12Pyq("mathematics", "vector-algebra", "|a × b| equals", ["|a| |b| cos θ", "|a| |b| sin θ", "a · b", "|a| + |b|"], 1, "The magnitude of the cross product is |a| |b| sin θ."),
  class12Pyq("mathematics", "vector-algebra", "a · a equals", ["0", "|a|", "|a|²", "1"], 2, "a · a = |a| |a| cos 0 = |a|²."),
  class12Pyq("mathematics", "vector-algebra", "a × a equals", ["|a|²", "0", "a", "1"], 1, "The angle between a vector and itself is 0, so sin 0 = 0 and the cross product vanishes."),
  class12Pyq("mathematics", "vector-algebra", "Non-zero vectors a and b are perpendicular if and only if", ["a · b = 1", "a · b = 0", "a × b = 0", "|a| = |b|"], 1, "cos θ = 0 iff a · b = 0."),
  class12Pyq("mathematics", "vector-algebra", "Non-zero vectors a and b are parallel if and only if", ["a · b = 0", "a × b = 0", "a + b = 0", "|a × b| = 1"], 1, "sin θ = 0 iff a × b = 0."),
  class12Pyq("mathematics", "vector-algebra", "|a × b|² + (a · b)² equals", ["|a|² + |b|²", "|a|² |b|²", "0", "|a + b|²"], 1, "sin² θ + cos² θ = 1 yields this Lagrange identity."),
  class12Pyq("mathematics", "vector-algebra", "A unit vector in the direction of a non-zero vector a is", ["a", "a / |a|", "|a| a", "−a"], 1, "Dividing by the magnitude produces a vector of length 1."),
  class12Pyq("mathematics", "vector-algebra", "The scalar projection of a on b is", ["(a · b)/|b|", "|a × b|", "|a| |b|", "a + b"], 0, "proj_b a has magnitude |a| cos θ = (a · b)/|b|."),
  class12Pyq("mathematics", "vector-algebra", "î × ĵ equals", ["î", "ĵ", "k̂", "0"], 2, "The standard right-handed triad gives î × ĵ = k̂."),
  class12Pyq("mathematics", "vector-algebra", "î · ĵ equals", ["1", "0", "k̂", "−1"], 1, "The standard basis vectors are orthonormal, so î · ĵ = 0."),
  class12Pyq("mathematics", "vector-algebra", "The scalar triple product [a b c] = a · (b × c) equals the volume of the", ["triangle", "parallelogram", "parallelepiped formed by a, b, c", "sphere"], 2, "|[a b c]| is the volume of the parallelepiped with those adjacent edges."),
  class12Pyq("mathematics", "vector-algebra", "Vectors a, b, c are coplanar if and only if", ["a · b = 0", "[a b c] = 0", "a × b = c", "|a| = 1"], 1, "Coplanarity is equivalent to a vanishing scalar triple product."),
  class12Pyq("mathematics", "vector-algebra", "a × b equals", ["b × a", "−(b × a)", "a · b", "b · a"], 1, "The cross product is anti-commutative."),
  class12Pyq("mathematics", "vector-algebra", "The scalar product is commutative, so a · b equals", ["−(b · a)", "b · a", "a × b", "0"], 1, "The dot product satisfies a · b = b · a."),
  class12Pyq("mathematics", "vector-algebra", "|a + b|² equals", ["|a|² + |b|²", "|a|² + |b|² + 2 a · b", "|a|² + |b|² − 2 a · b", "2 |a| |b|"], 1, "Expand (a + b) · (a + b)."),
  class12Pyq("mathematics", "vector-algebra", "If |a + b| = |a − b|, then", ["a is parallel to b", "a is perpendicular to b", "a = 0", "|a| = |b|"], 1, "Squaring both sides yields 4 a · b = 0, so a ⊥ b."),
  class12Pyq("mathematics", "vector-algebra", "The position vector of the midpoint of A(a) and B(b) is", ["a + b", "(a + b)/2", "a − b", "b − a"], 1, "The section formula for the midpoint is (a + b)/2."),
  class12Pyq("mathematics", "vector-algebra", "A vector of magnitude 5 in the direction of î + ĵ + k̂ is", ["5(î + ĵ + k̂)", "(5/√3)(î + ĵ + k̂)", "√3 (î + ĵ + k̂)", "î + ĵ + k̂"], 1, "|î + ĵ + k̂| = √3, so multiply the unit vector by 5."),
  class12Pyq("mathematics", "vector-algebra", "If l, m, n are direction cosines of a vector, then", ["l + m + n = 1", "l² + m² + n² = 1", "lmn = 1", "l² + m² = n²"], 1, "cos² α + cos² β + cos² γ = 1."),

  // 11. Three Dimensional Geometry
  class12Pyq("mathematics", "three-dimensional-geometry", "Direction cosines l, m, n of a line satisfy", ["l + m + n = 0", "l² + m² + n² = 1", "lm + mn + nl = 1", "l = m = n"], 1, "This is the fundamental identity for direction cosines."),
  class12Pyq("mathematics", "three-dimensional-geometry", "Direction ratios of the line joining (1, 2, 3) and (4, 6, 8) are", ["1, 2, 3", "3, 4, 5", "4, 6, 8", "1, 1, 1"], 1, "The differences of coordinates are 3, 4, 5."),
  class12Pyq("mathematics", "three-dimensional-geometry", "The vector equation of a line through A with position vector a, parallel to b, is", ["r = a × b", "r = a + λb", "r · b = a", "r = λa"], 1, "This is the standard vector form of a line."),
  class12Pyq("mathematics", "three-dimensional-geometry", "Cartesian equations of a line through (x₁, y₁, z₁) with DRs a, b, c are", ["ax + by + cz = 0", "(x − x₁)/a = (y − y₁)/b = (z − z₁)/c", "x/a = y/b = z/c only", "x = a, y = b, z = c"], 1, "This is the symmetric form of the line."),
  class12Pyq("mathematics", "three-dimensional-geometry", "The equation of the xy-plane is", ["x = 0", "y = 0", "z = 0", "x + y = 0"], 2, "Every point of the xy-plane has z-coordinate 0."),
  class12Pyq("mathematics", "three-dimensional-geometry", "The vector equation of a plane with normal n through a point with PV a is", ["r · n = a · n", "r × n = a", "r = n", "r · a = n"], 0, "r · n = d with d = a · n is the plane through A with normal n."),
  class12Pyq("mathematics", "three-dimensional-geometry", "The angle θ between two planes with normals n₁, n₂ satisfies", ["cos θ = |n₁ · n₂| / (|n₁| |n₂|)", "sin θ = n₁ · n₂", "θ = 90° always", "cos θ = |n₁ × n₂|"], 0, "The angle between planes equals the angle between their normals."),
  class12Pyq("mathematics", "three-dimensional-geometry", "The distance from (x₀, y₀, z₀) to the plane ax + by + cz + d = 0 is", ["|ax₀ + by₀ + cz₀ + d| / √(a² + b² + c²)", "ax₀ + by₀ + cz₀", "√(a² + b² + c²)", "|d|"], 0, "This is the standard point-to-plane distance formula."),
  class12Pyq("mathematics", "three-dimensional-geometry", "Two lines with direction ratios aᵢ, bᵢ, cᵢ are parallel if", ["a₁a₂ + b₁b₂ + c₁c₂ = 0", "a₁/a₂ = b₁/b₂ = c₁/c₂", "a₁ = b₁ = c₁", "they intersect"], 1, "Parallel lines have proportional direction ratios."),
  class12Pyq("mathematics", "three-dimensional-geometry", "Two lines with direction ratios aᵢ, bᵢ, cᵢ are perpendicular if", ["a₁a₂ + b₁b₂ + c₁c₂ = 0", "the DRs are proportional", "they are coplanar", "they intersect"], 0, "The direction vectors have vanishing dot product."),
  class12Pyq("mathematics", "three-dimensional-geometry", "Two planes aᵢx + bᵢy + cᵢz + dᵢ = 0 are perpendicular if", ["a₁a₂ + b₁b₂ + c₁c₂ = 0", "a₁/a₂ = b₁/b₂ = c₁/c₂", "d₁ = d₂", "they always intersect in a line"], 0, "Planes are perpendicular when their normals are perpendicular."),
  class12Pyq("mathematics", "three-dimensional-geometry", "The distance between the parallel planes ax + by + cz + d₁ = 0 and ax + by + cz + d₂ = 0 is", ["|d₁ − d₂| / √(a² + b² + c²)", "|d₁ + d₂|", "0", "√(d₁² + d₂²)"], 0, "Subtracting the constants and dividing by the norm of the normal gives the distance."),
  class12Pyq("mathematics", "three-dimensional-geometry", "If a line with direction vector b is parallel to the plane r · n = d, then", ["b · n = 0", "b × n = 0", "b = n", "|b| = 1"], 0, "The direction of the line is perpendicular to the normal of the plane."),
  class12Pyq("mathematics", "three-dimensional-geometry", "The angle φ between a line with direction b and a plane with normal n satisfies", ["sin φ = |b · n| / (|b| |n|)", "cos φ = |b · n| / (|b| |n|)", "φ = 0 always", "tan φ = b · n"], 0, "CBSE takes φ as the angle between the line and the plane, so sin φ = |b · n| / (|b| |n|)."),
  class12Pyq("mathematics", "three-dimensional-geometry", "The direction cosines of the x-axis are", ["(0, 1, 0)", "(1, 0, 0)", "(0, 0, 1)", "(1, 1, 1)"], 1, "The x-axis makes angles 0°, 90°, 90° with the axes."),
  class12Pyq("mathematics", "three-dimensional-geometry", "Two lines that are neither parallel nor intersecting are called", ["coplanar", "skew", "perpendicular", "coincident"], 1, "Skew lines do not lie in one plane and do not meet."),
  class12Pyq("mathematics", "three-dimensional-geometry", "A plane through the origin has equation of the form", ["ax + by + cz = 1", "ax + by + cz = 0", "x = y = z = 1", "z = 1"], 1, "Substituting (0, 0, 0) forces the constant term to vanish."),
  class12Pyq("mathematics", "three-dimensional-geometry", "If a line with DCs l, m, n lies in the plane ax + by + cz + d = 0, then", ["al + bm + cn = 0", "the DRs are parallel to (a, b, c)", "d = 1", "the line must be the x-axis"], 0, "The direction of the line is perpendicular to the normal of the plane."),
  class12Pyq("mathematics", "three-dimensional-geometry", "The foot of the perpendicular from the origin to ax + by + cz + d = 0 (d ≠ 0) lies in the direction of", ["(1, 1, 1)", "(a, b, c)", "(d, d, d)", "(0, 0, 1)"], 1, "The perpendicular from the origin to the plane is along the normal (a, b, c)."),
  class12Pyq("mathematics", "three-dimensional-geometry", "The intercept form of a plane with intercepts a, b, c on the axes is", ["x/a + y/b + z/c = 1", "ax + by + cz = 1", "x + y + z = abc", "xyz = abc"], 0, "This is the standard intercept form of the plane."),

  // 12. Linear Programming
  class12Pyq("mathematics", "linear-programming", "In the corner-point method, the optimal value of a linear objective occurs at", ["the origin only", "a corner point of the feasible region", "an interior point always", "infinity always"], 1, "A linear function on a convex polygonal region attains its optimum at a vertex."),
  class12Pyq("mathematics", "linear-programming", "The feasible region of an LPP is", ["always unbounded", "the intersection of the half-planes defined by the constraints", "a circle", "always a triangle"], 1, "Each linear inequality describes a half-plane; their intersection is the feasible set."),
  class12Pyq("mathematics", "linear-programming", "An LPP in two variables can be solved by the", ["simplex method only", "graphical method", "quadratic formula", "definite integral"], 1, "Two decision variables allow a graphical (corner-point) solution."),
  class12Pyq("mathematics", "linear-programming", "Decision variables in a standard CBSE LPP satisfy", ["x ≥ 0, y ≥ 0", "x ≤ 0, y ≤ 0", "x + y = 1", "x, y unrestricted always"], 0, "Non-negativity of the variables is part of the standard form."),
  class12Pyq("mathematics", "linear-programming", "If the feasible region is empty, the LPP has", ["infinitely many solutions", "no solution (infeasible)", "a unique maximum", "an unbounded solution"], 1, "No point satisfies all constraints, so the problem is infeasible."),
  class12Pyq("mathematics", "linear-programming", "If the feasible region is bounded, a linear objective", ["may have neither max nor min", "attains both its maximum and its minimum", "is always zero", "has only a maximum"], 1, "A continuous function on a closed bounded set attains its extrema; for a polygon they occur at corners."),
  class12Pyq("mathematics", "linear-programming", "If the feasible region is unbounded, the maximum of Z", ["always exists", "may not exist", "is always at (0, 0)", "equals the minimum"], 1, "Z may increase without bound along an unbounded ray."),
  class12Pyq("mathematics", "linear-programming", "If Z takes the same optimal value at two adjacent corner points, then", ["there is no solution", "every point of that edge is also optimal", "the problem is infeasible", "Z is unbounded"], 1, "A linear function constant at two vertices is constant on the joining segment."),
  class12Pyq("mathematics", "linear-programming", "The objective function of an LPP is", ["linear", "quadratic", "exponential", "trigonometric"], 0, "Both the objective and the constraints are linear."),
  class12Pyq("mathematics", "linear-programming", "The constraints of an LPP are", ["linear inequalities (or equations)", "circles", "of the form y = x²", "transcendental equations"], 0, "Feasibility is defined by linear inequalities."),
  class12Pyq("mathematics", "linear-programming", "The corner points of the region x ≥ 0, y ≥ 0, x + y ≤ 1 are", ["(0, 0), (1, 0), (0, 1)", "(1, 1) only", "(0, 0) only", "(1, 1) and (2, 2)"], 0, "The feasible set is the triangle with those three vertices."),
  class12Pyq("mathematics", "linear-programming", "The maximum of Z = x + y subject to x ≥ 0, y ≥ 0, x + y ≤ 2 is", ["0", "1", "2", "unbounded"], 2, "On the edge x + y = 2 one has Z = 2, which is the maximum."),
  class12Pyq("mathematics", "linear-programming", "The feasible region of a system of linear inequalities is", ["always a convex set", "always concave", "a parabola", "never a polygon"], 0, "Intersection of half-planes is convex."),
  class12Pyq("mathematics", "linear-programming", "Iso-profit (or iso-cost) lines are", ["the lines Z = constant", "the constraint lines only", "the coordinate axes", "normals to the feasible region"], 0, "Level curves of a linear objective are straight lines."),
  class12Pyq("mathematics", "linear-programming", "For Z = 3x + 4y at the point (0, 2), the value of Z is", ["3", "8", "6", "0"], 1, "Z = 3 · 0 + 4 · 2 = 8."),
  class12Pyq("mathematics", "linear-programming", "The non-negativity restrictions of a two-variable LPP are", ["x ≥ 0, y ≥ 0", "x + y ≥ 0 only", "x ≤ y", "x, y ≤ 1"], 0, "Variables representing quantities are taken to be non-negative."),
  class12Pyq("mathematics", "linear-programming", "An unbounded feasible region in the direction of increasing Z means", ["Z has no finite maximum", "Z has a unique minimum only", "the problem is infeasible", "Z = 0"], 0, "The objective can be made arbitrarily large."),
  class12Pyq("mathematics", "linear-programming", "The graphical method applies when the number of decision variables is", ["one", "two", "three or more only", "any number equally easily on paper"], 1, "The plane can display two variables; higher dimensions need other methods."),
  class12Pyq("mathematics", "linear-programming", "Min Z = x + 2y subject to x ≥ 0, y ≥ 0, x + y ≥ 1, evaluated at the corners (1, 0) and (0, 1), is", ["0", "1", "2", "3"], 1, "Z(1, 0) = 1 and Z(0, 1) = 2, so the minimum on those corners is 1."),
  class12Pyq("mathematics", "linear-programming", "A redundant constraint", ["does not change the feasible region", "always passes through the origin", "makes the problem infeasible", "is the same as the objective"], 0, "It is implied by the other inequalities, so it can be omitted."),

  // 13. Probability
  class12Pyq("mathematics", "probability", "P(A | B) equals (P(B) > 0)", ["P(A) P(B)", "P(A ∩ B)/P(B)", "P(A)/P(B)", "P(A ∪ B)"], 1, "This is the definition of conditional probability."),
  class12Pyq("mathematics", "probability", "Events A and B are independent if and only if", ["P(A ∩ B) = 0", "P(A ∩ B) = P(A) P(B)", "P(A ∪ B) = 1", "P(A) = P(B)"], 1, "Independence means the joint probability factors."),
  class12Pyq("mathematics", "probability", "If A and B are mutually exclusive, then", ["P(A ∩ B) = 0", "P(A ∩ B) = P(A) P(B)", "P(A) = 1", "they are independent"], 0, "Mutually exclusive events cannot occur together."),
  class12Pyq("mathematics", "probability", "Two mutually exclusive events with P(A) > 0 and P(B) > 0 are", ["independent", "not independent", "exhaustive", "sure events"], 1, "P(A ∩ B) = 0 ≠ P(A) P(B), so they are dependent."),
  class12Pyq("mathematics", "probability", "The mean of a binomial distribution B(n, p) is", ["npq", "np", "nq", "√(npq)"], 1, "E(X) = np for X ~ B(n, p)."),
  class12Pyq("mathematics", "probability", "The variance of B(n, p) is", ["np", "npq", "n/p", "q/n"], 1, "Var(X) = np(1 − p) = npq."),
  class12Pyq("mathematics", "probability", "If X ~ B(n, p), then P(X = r) is", ["C(n, r) pʳ q^{n−r}", "pʳ", "np", "qⁿ"], 0, "This is the binomial probability mass function."),
  class12Pyq("mathematics", "probability", "P(A ∪ B) equals", ["P(A) + P(B)", "P(A) + P(B) − P(A ∩ B)", "P(A) P(B)", "P(A | B)"], 1, "The addition theorem of probability."),
  class12Pyq("mathematics", "probability", "If P(A) = 1/2, P(B) = 1/3 and A, B are independent, then P(A ∩ B) is", ["1", "5/6", "1/6", "1/3"], 2, "Independence gives (1/2)(1/3) = 1/6."),
  class12Pyq("mathematics", "probability", "A fair coin is tossed 3 times. P(exactly 2 heads) is", ["1/8", "3/8", "1/2", "1/3"], 1, "C(3, 2) (1/2)³ = 3/8."),
  class12Pyq("mathematics", "probability", "P(A | A) equals (P(A) > 0)", ["0", "1", "P(A)", "1/2"], 1, "Given that A has occurred, the conditional probability of A is 1."),
  class12Pyq("mathematics", "probability", "If P(A) = 0.4, P(B) = 0.5 and P(A ∪ B) = 0.7, then P(A ∩ B) is", ["0.2", "0.9", "0.1", "0.3"], 0, "P(A ∩ B) = 0.4 + 0.5 − 0.7 = 0.2."),
  class12Pyq("mathematics", "probability", "Bayes' theorem is used to find", ["P(Eᵢ | A) from P(A | Eᵢ) and the priors P(Eᵢ)", "only P(A ∪ B)", "the mean of X", "P(A) without data"], 0, "It converts likelihoods and prior probabilities into posterior probabilities."),
  class12Pyq("mathematics", "probability", "If A and B are independent, then A and B' are", ["mutually exclusive", "also independent", "sure events", "always dependent"], 1, "P(A ∩ B') = P(A) − P(A) P(B) = P(A) P(B')."),
  class12Pyq("mathematics", "probability", "E(X) for a discrete random variable is", ["Σ xᵢ² pᵢ", "Σ xᵢ pᵢ", "Σ pᵢ", "Var(X)"], 1, "The expectation is the probability-weighted sum of the values."),
  class12Pyq("mathematics", "probability", "Var(X) equals", ["E(X²) − [E(X)]²", "E(X) − E(X²)", "[E(X)]²", "E(X²)"], 0, "This is the computational formula for variance."),
  class12Pyq("mathematics", "probability", "The theorem of total probability states that P(A) equals", ["Σ P(Eᵢ) P(A | Eᵢ) for a partition {Eᵢ}", "P(A | B)", "1 − P(A)", "P(A)²"], 0, "Conditioning on a partition and using the law of total probability."),
  class12Pyq("mathematics", "probability", "If X ~ B(6, 1/2), then P(X = 3) equals", ["1/2", "20/64", "1/64", "15/64"], 1, "C(6, 3) (1/2)⁶ = 20/64."),
  class12Pyq("mathematics", "probability", "A bag contains 3 red and 2 black balls. The probability of drawing a red ball is", ["2/5", "3/5", "1/2", "1"], 1, "There are 3 red balls out of 5, so the probability is 3/5."),
  class12Pyq("mathematics", "probability", "If P(A) = 0.3, P(B) = 0.4 and A, B are mutually exclusive, then P(A ∪ B) is", ["0.12", "0.7", "0.1", "1"], 1, "For mutually exclusive events, P(A ∪ B) = P(A) + P(B) = 0.7."),
];

assertTwentyPerChapter(class12MathematicsQuestions, [
  "relations-and-functions",
  "inverse-trigonometric-functions",
  "matrices",
  "determinants",
  "continuity-and-differentiability",
  "application-of-derivatives",
  "integrals",
  "application-of-integrals",
  "differential-equations",
  "vector-algebra",
  "three-dimensional-geometry",
  "linear-programming",
  "probability",
]);
