import { assertTwentyPerChapter, cbsePyq, type PracticeQuestionSeed } from "./types";

export const class10ScienceQuestions: PracticeQuestionSeed[] = [
  // --- Chemical Reactions and Equations ---
  cbsePyq(
    "class-10",
    "science",
    "chemical-reactions-and-equations",
    "The balanced chemical equation for the reaction of iron with steam is",
    [
      "Fe + H2O → FeO + H2",
      "2Fe + 3H2O → Fe2O3 + 3H2",
      "3Fe + 4H2O → Fe3O4 + 4H2",
      "Fe + 2H2O → Fe(OH)2 + H2",
    ],
    2,
    "Iron and steam form magnetite and hydrogen: 3Fe + 4H2O → Fe3O4 + 4H2.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "chemical-reactions-and-equations",
    "The reaction CaO + H2O → Ca(OH)2 is an example of a",
    ["decomposition reaction", "combination reaction", "displacement reaction", "double displacement reaction"],
    1,
    "Two reactants combine to give a single product, so it is a combination reaction (slaking of lime).",
  ),
  cbsePyq(
    "class-10",
    "science",
    "chemical-reactions-and-equations",
    "On strong heating, limestone (CaCO3) undergoes",
    ["combination", "displacement", "thermal decomposition", "double displacement"],
    2,
    "CaCO3 → CaO + CO2 is thermal decomposition used to make quick lime.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "chemical-reactions-and-equations",
    "Electrolysis of water produces hydrogen and oxygen in the volume ratio",
    ["1 : 1", "1 : 2", "2 : 1", "1 : 8"],
    2,
    "2H2O → 2H2 + O2, so the volume ratio H2 : O2 is 2 : 1.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "chemical-reactions-and-equations",
    "When iron nails are dipped in copper sulphate solution, the colour of the solution changes from blue to",
    ["red", "colourless", "green", "yellow"],
    2,
    "Iron displaces copper and FeSO4 formed is pale green.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "chemical-reactions-and-equations",
    "Which of the following is a precipitation reaction?",
    [
      "NaOH + HCl → NaCl + H2O",
      "BaCl2 + Na2SO4 → BaSO4 + 2NaCl",
      "H2 + Cl2 → 2HCl",
      "CaO + CO2 → CaCO3",
    ],
    1,
    "BaSO4 is an insoluble white precipitate formed by double displacement.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "chemical-reactions-and-equations",
    "In the reaction 2Cu + O2 → 2CuO, copper is",
    ["reduced", "oxidised", "neither oxidised nor reduced", "precipitated"],
    1,
    "Copper gains oxygen, so it is oxidised.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "chemical-reactions-and-equations",
    "Respiration is regarded as an",
    ["endothermic process", "exothermic process", "photochemical process", "neutralisation process"],
    1,
    "Oxidation of glucose in cells releases energy, so respiration is exothermic.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "chemical-reactions-and-equations",
    "Which of the following is an endothermic process?",
    ["burning of natural gas", "respiration", "decomposition of calcium carbonate", "slaking of lime"],
    2,
    "Breaking CaCO3 into CaO and CO2 requires continuous heat input.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "chemical-reactions-and-equations",
    "The photolytic decomposition of silver chloride is used in",
    ["whitewashing", "black and white photography", "extraction of iron", "baking cakes"],
    1,
    "2AgCl → 2Ag + Cl2 in sunlight; the grey silver deposit is the basis of photography.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "chemical-reactions-and-equations",
    "Rancidity of oils and fats can be slowed by",
    ["keeping oil in an open pan", "adding antioxidants", "raising the temperature", "exposing oil to sunlight"],
    1,
    "Antioxidants and flushing with nitrogen slow oxidation of fats (rancidity).",
  ),
  cbsePyq(
    "class-10",
    "science",
    "chemical-reactions-and-equations",
    "The brown gas evolved on heating lead nitrate is",
    ["nitric oxide (NO)", "nitrous oxide (N2O)", "nitrogen dioxide (NO2)", "nitrogen (N2)"],
    2,
    "2Pb(NO3)2 → 2PbO + 4NO2 + O2; NO2 is reddish-brown.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "chemical-reactions-and-equations",
    "The chemical formula of quick lime is",
    ["Ca(OH)2", "CaCO3", "CaO", "CaSO4"],
    2,
    "Quick lime is calcium oxide, CaO; slaked lime is Ca(OH)2.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "chemical-reactions-and-equations",
    "Which of the following is a redox reaction?",
    [
      "CaCO3 → CaO + CO2",
      "Na2SO4 + BaCl2 → BaSO4 + 2NaCl",
      "MnO2 + 4HCl → MnCl2 + 2H2O + Cl2",
      "AgNO3 + NaCl → AgCl + NaNO3",
    ],
    2,
    "HCl is oxidised to Cl2 while MnO2 is reduced to MnCl2.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "chemical-reactions-and-equations",
    "The reaction 2H2 + O2 → 2H2O is a",
    ["displacement reaction", "combination reaction", "double displacement reaction", "decomposition reaction"],
    1,
    "Hydrogen and oxygen combine to form a single product, water.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "chemical-reactions-and-equations",
    "Zn + H2SO4 → ZnSO4 + H2 is an example of a",
    ["combination reaction", "decomposition reaction", "displacement reaction", "double displacement reaction"],
    2,
    "Zinc displaces hydrogen from the acid.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "chemical-reactions-and-equations",
    "A substance is said to be oxidised if it",
    ["gains hydrogen", "loses oxygen", "gains oxygen", "always gains electrons"],
    2,
    "In Class 10, oxidation is gain of oxygen or loss of hydrogen.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "chemical-reactions-and-equations",
    "Rusting of iron requires the presence of",
    ["only oxygen", "only water", "both air and moisture", "only carbon dioxide"],
    2,
    "Both oxygen (air) and water are needed for rust, Fe2O3·xH2O, to form.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "chemical-reactions-and-equations",
    "The substance used for whitewashing that slowly forms a hard coating of CaCO3 with CO2 is",
    ["CaCO3", "Ca(OH)2", "CaSO4", "Na2CO3"],
    1,
    "Slaked lime Ca(OH)2 reacts with CO2 to give CaCO3, which gives a shiny finish.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "chemical-reactions-and-equations",
    "The balanced equation for complete combustion of methane is",
    [
      "CH4 + O2 → CO2 + H2O",
      "CH4 + 2O2 → CO2 + 2H2O",
      "2CH4 + O2 → 2CO2 + 2H2O",
      "CH4 + O2 → C + 2H2O",
    ],
    1,
    "One CH4 molecule needs two O2 molecules to give CO2 and two H2O.",
  ),

  // --- Acids, Bases and Salts ---
  cbsePyq(
    "class-10",
    "science",
    "acids-bases-and-salts",
    "A solution of pH 7 is",
    ["strongly acidic", "weakly acidic", "neutral", "strongly basic"],
    2,
    "On the pH scale, 7 is the neutral point (pure water at 25 °C).",
  ),
  cbsePyq(
    "class-10",
    "science",
    "acids-bases-and-salts",
    "Tooth enamel starts corroding when the pH in the mouth is",
    ["higher than 7.5", "equal to 7", "lower than 5.5", "exactly 6.9"],
    2,
    "Bacteria produce acids from sugar; enamel (calcium hydroxyapatite) dissolves below pH 5.5.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "acids-bases-and-salts",
    "The acid present in vinegar is",
    ["citric acid", "acetic acid", "tartaric acid", "lactic acid"],
    1,
    "Vinegar is a dilute solution of ethanoic (acetic) acid.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "acids-bases-and-salts",
    "The chemical formula of plaster of Paris is",
    ["CaSO4 · 2H2O", "CaSO4 · 1/2 H2O", "CaSO4", "CaSO4 · H2O"],
    1,
    "POP is calcium sulphate hemihydrate, CaSO4 · ½ H2O.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "acids-bases-and-salts",
    "The chemical formula of bleaching powder is",
    ["CaCl2", "CaOCl2", "Ca(OCl)2 · CaCl2", "NaOCl"],
    1,
    "Bleaching powder is CaOCl2, made by passing Cl2 over dry slaked lime.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "acids-bases-and-salts",
    "Baking soda is",
    ["Na2CO3", "NaHCO3", "NaOH", "NaCl"],
    1,
    "Baking soda is sodium hydrogencarbonate, NaHCO3.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "acids-bases-and-salts",
    "Washing soda crystals have the formula",
    ["Na2CO3", "NaHCO3", "Na2CO3 · 10H2O", "Na2CO3 · H2O"],
    2,
    "Washing soda is sodium carbonate decahydrate, Na2CO3 · 10H2O.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "acids-bases-and-salts",
    "Which of the following can be used as an olfactory indicator?",
    ["phenolphthalein", "methyl orange", "vanilla essence", "litmus"],
    2,
    "The odour of vanilla (or onion/clove) is lost in basic medium, so it is an olfactory indicator.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "acids-bases-and-salts",
    "Which of the following is a strong acid?",
    ["CH3COOH", "H2CO3", "HCl", "H2S"],
    2,
    "HCl ionises almost completely in water and is a strong acid.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "acids-bases-and-salts",
    "Rain is called acid rain when its pH is",
    ["equal to 7", "greater than 7", "less than 5.6", "exactly 6.0"],
    2,
    "Normal rain is slightly acidic (~5.6) due to dissolved CO2; acid rain has pH < 5.6.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "acids-bases-and-salts",
    "An antacid tablet typically contains",
    ["HCl", "NaOH", "Mg(OH)2", "H2SO4"],
    2,
    "Mild bases such as Mg(OH)2 or NaHCO3 neutralise excess stomach acid.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "acids-bases-and-salts",
    "Gypsum is",
    ["CaSO4 · 1/2 H2O", "CaSO4 · 2H2O", "CaSO4", "CaOCl2"],
    1,
    "Gypsum is calcium sulphate dihydrate, CaSO4 · 2H2O.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "acids-bases-and-salts",
    "Phenolphthalein remains colourless in",
    ["NaOH solution", "lime water", "HCl solution", "soap solution"],
    2,
    "Phenolphthalein is colourless in acidic medium and pink in basic medium.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "acids-bases-and-salts",
    "Methyl orange shows which colour in a strongly acidic solution?",
    ["yellow", "pink", "red", "colourless"],
    2,
    "Methyl orange is red in acid and yellow in base.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "acids-bases-and-salts",
    "The products of the chlor-alkali process are",
    ["NaCl, H2 and O2", "NaOH, Cl2 and H2", "NaOH, HCl and O2", "Na2CO3, Cl2 and H2"],
    1,
    "Electrolysis of brine gives NaOH, chlorine and hydrogen.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "acids-bases-and-salts",
    "Which solution has the highest pH?",
    ["lemon juice", "tomato juice", "pure water", "milk of magnesia"],
    3,
    "Milk of magnesia is a basic suspension, so its pH is greater than 7.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "acids-bases-and-salts",
    "When plaster of Paris is mixed with water, it",
    ["remains a powder", "sets into a hard mass", "gives bleaching powder", "dissolves completely as a salt solution"],
    1,
    "POP rehydrates to gypsum and sets into a hard mass with slight expansion.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "acids-bases-and-salts",
    "The salt used in a soda-acid fire extinguisher is",
    ["NaCl", "NaHCO3", "Na2SO4", "CaCO3"],
    1,
    "NaHCO3 reacts with acid to release CO2, which smothers the fire.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "acids-bases-and-salts",
    "Acids produce which ions in aqueous solution?",
    ["OH−", "H+ (H3O+)", "Na+", "Cl− only"],
    1,
    "Arrhenius acids ionise in water to give hydrogen (hydronium) ions.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "acids-bases-and-salts",
    "Plaster of Paris is obtained by heating gypsum at about",
    ["273 K", "373 K", "573 K", "673 K"],
    1,
    "At 373 K, CaSO4 · 2H2O loses 1½ H2O and becomes CaSO4 · ½ H2O (POP).",
  ),

  // --- Metals and Non-metals ---
  cbsePyq(
    "class-10",
    "science",
    "metals-and-non-metals",
    "The most reactive metal among the following is",
    ["Cu", "Fe", "Na", "Ag"],
    2,
    "Sodium stands high in the reactivity series and reacts vigorously with water.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "metals-and-non-metals",
    "Which metal is often found in the free (native) state in nature?",
    ["Na", "Ca", "Au", "Al"],
    2,
    "Gold is very unreactive and occurs native; Na, Ca and Al are too reactive.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "metals-and-non-metals",
    "The bond in NaCl is",
    ["covalent", "metallic", "ionic", "hydrogen"],
    2,
    "Na transfers an electron to Cl, forming Na+ and Cl− held by electrostatic attraction.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "metals-and-non-metals",
    "Which oxide is amphoteric?",
    ["Na2O", "Al2O3", "CO2", "SO2"],
    1,
    "Al2O3 (and ZnO) react with both acids and bases.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "metals-and-non-metals",
    "Aqua regia is a mixture of concentrated HCl and concentrated HNO3 in the ratio",
    ["1 : 3", "3 : 1", "1 : 1", "2 : 1"],
    1,
    "Aqua regia is 3 parts conc. HCl + 1 part conc. HNO3 and can dissolve gold and platinum.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "metals-and-non-metals",
    "In electrolytic refining of copper, the anode is made of",
    ["pure copper", "impure copper", "graphite only", "zinc"],
    1,
    "Impure copper is the anode; pure copper is deposited on the cathode.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "metals-and-non-metals",
    "The thermite reaction used to join railway tracks is",
    [
      "Fe2O3 + 2Al → 2Fe + Al2O3",
      "2Fe + 3H2O → Fe2O3 + 3H2",
      "CuO + H2 → Cu + H2O",
      "ZnO + C → Zn + CO",
    ],
    0,
    "Molten iron produced by reduction of Fe2O3 with aluminium welds the tracks.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "metals-and-non-metals",
    "Anodising is a process used to thicken the oxide layer on",
    ["iron", "copper", "aluminium", "gold"],
    2,
    "Aluminium is anodised electrolytically to grow a protective Al2O3 coat.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "metals-and-non-metals",
    "Which metal reacts vigorously with cold water?",
    ["Fe", "Zn", "K", "Cu"],
    2,
    "Potassium (and sodium) react violently with cold water, releasing H2.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "metals-and-non-metals",
    "Which non-metal is a good conductor of electricity?",
    ["sulphur", "phosphorus", "graphite", "chlorine"],
    2,
    "Graphite has delocalised electrons and conducts electricity.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "metals-and-non-metals",
    "Bronze is an alloy of",
    ["Cu and Zn", "Cu and Sn", "Fe and C", "Al and Mg"],
    1,
    "Bronze is copper + tin; brass is copper + zinc.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "metals-and-non-metals",
    "Brass is an alloy of",
    ["Cu and Sn", "Cu and Zn", "Fe and Ni", "Pb and Sn"],
    1,
    "Brass is copper + zinc.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "metals-and-non-metals",
    "Highly reactive metals such as Na and Ca are extracted by",
    ["reduction with carbon", "reduction with aluminium", "electrolytic reduction of their molten chlorides", "roasting only"],
    2,
    "Carbon cannot reduce these oxides; electrolysis of molten salts is used.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "metals-and-non-metals",
    "Galvanisation is coating iron with",
    ["tin", "copper", "zinc", "chromium"],
    2,
    "A zinc coat protects iron even if scratched, because zinc is more reactive.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "metals-and-non-metals",
    "Stainless steel is an alloy of iron with",
    ["Cu and Zn", "Ni and Cr", "Sn and Pb", "Al and Mg"],
    1,
    "Stainless steel contains iron, nickel and chromium (and some carbon).",
  ),
  cbsePyq(
    "class-10",
    "science",
    "metals-and-non-metals",
    "Which metal can displace copper from copper sulphate solution?",
    ["Ag", "Au", "Zn", "Pt"],
    2,
    "Zinc is above copper in the reactivity series and displaces Cu from CuSO4.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "metals-and-non-metals",
    "Sulphide ores are concentrated by",
    ["hydraulic washing", "magnetic separation", "froth flotation", "electrolysis"],
    2,
    "Froth flotation is used for sulphide ores such as ZnS and CuFeS2.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "metals-and-non-metals",
    "Roasting is mainly used for which type of ore?",
    ["carbonate ores", "sulphide ores", "oxide ores", "chloride ores"],
    1,
    "Sulphide ores are heated in air (roasting) to convert them to oxides; carbonates are calcined.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "metals-and-non-metals",
    "Ionic compounds conduct electricity when they are",
    ["in the solid state", "molten or in aqueous solution", "in powdered solid form only", "always, in every state"],
    1,
    "Ions are free to move in the molten state or in solution, not in the solid lattice.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "metals-and-non-metals",
    "A metal that does not react with dilute HCl to give hydrogen is",
    ["Mg", "Zn", "Fe", "Cu"],
    3,
    "Copper is below hydrogen in the reactivity series, so it cannot displace H2 from acids.",
  ),

  // --- Carbon and Its Compounds ---
  cbsePyq(
    "class-10",
    "science",
    "carbon-and-its-compounds",
    "Successive members of a homologous series differ by",
    ["CH3", "CH2", "CH", "C2H2"],
    1,
    "Each next member differs by a −CH2− unit (mass 14 u).",
  ),
  cbsePyq(
    "class-10",
    "science",
    "carbon-and-its-compounds",
    "The general formula of alkanes is",
    ["CnH2n", "CnH2n+2", "CnH2n−2", "CnH2n+1"],
    1,
    "Saturated open-chain hydrocarbons (alkanes) have formula CnH2n+2.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "carbon-and-its-compounds",
    "The general formula of alkenes is",
    ["CnH2n+2", "CnH2n", "CnH2n−2", "CnHn"],
    1,
    "Alkenes are unsaturated with a C=C bond and formula CnH2n.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "carbon-and-its-compounds",
    "The number of covalent bonds in a methane molecule is",
    ["1", "2", "3", "4"],
    3,
    "Carbon forms four C−H single bonds in CH4.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "carbon-and-its-compounds",
    "Ethanol is oxidised by alkaline KMnO4 to",
    ["ethene", "methane", "ethanoic acid", "ethyne"],
    2,
    "Alkaline KMnO4 (or acidified K2Cr2O7) oxidises ethanol to ethanoic acid.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "carbon-and-its-compounds",
    "Soap forms scum with hard water because of",
    ["Na+ ions", "Ca2+ and Mg2+ ions", "Cl− ions", "SO42− ions only"],
    1,
    "Ca2+ and Mg2+ give insoluble calcium/magnesium salts of fatty acids (scum).",
  ),
  cbsePyq(
    "class-10",
    "science",
    "carbon-and-its-compounds",
    "In a soap micelle in water, the hydrophobic tails are",
    ["on the outer surface", "towards the centre", "dissolved as free ions", "bonded to Ca2+"],
    1,
    "Hydrophobic hydrocarbon tails point inward; hydrophilic −COO− heads face water.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "carbon-and-its-compounds",
    "Addition reactions are characteristic of",
    ["alkanes", "saturated hydrocarbons", "unsaturated hydrocarbons", "ionic compounds"],
    2,
    "Alkenes and alkynes add H2, Br2, etc. across the multiple bond.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "carbon-and-its-compounds",
    "Chlorination of methane in sunlight is an example of a",
    ["addition reaction", "substitution reaction", "esterification", "saponification"],
    1,
    "H atoms of methane are substituted by Cl in the presence of sunlight.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "carbon-and-its-compounds",
    "Esterification is the reaction of a carboxylic acid with an",
    ["alkane", "alcohol (in presence of conc. H2SO4)", "alkene", "soap"],
    1,
    "Acid + alcohol → ester + water; conc. H2SO4 is a dehydrating catalyst.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "carbon-and-its-compounds",
    "Saponification is the alkaline hydrolysis of",
    ["an alcohol", "an ester (oil/fat) to give soap", "an alkane", "ethene"],
    1,
    "Esters of fatty acids react with NaOH to give soap and glycerol.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "carbon-and-its-compounds",
    "The functional group of carboxylic acids is",
    ["−OH", "−CHO", "−COOH", "−C=O"],
    2,
    "Carboxylic acids contain the carboxyl group −COOH.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "carbon-and-its-compounds",
    "The hardest allotrope of carbon is",
    ["graphite", "diamond", "fullerene", "coke"],
    1,
    "Diamond has a rigid 3-D tetrahedral network of C−C bonds.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "carbon-and-its-compounds",
    "Graphite conducts electricity because",
    ["it is a metal", "each carbon has a free electron", "it contains ions", "it is an electrolyte"],
    1,
    "Each C is bonded to three others; the fourth electron is delocalised.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "carbon-and-its-compounds",
    "An unsaturated hydrocarbon decolourises",
    ["litmus solution", "bromine water", "phenolphthalein", "lime water"],
    1,
    "Br2 adds across C=C/C≡C, so reddish-brown bromine water is decolourised.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "carbon-and-its-compounds",
    "The IUPAC name of CH3COOH is",
    ["methanoic acid", "ethanoic acid", "propanoic acid", "acetic alcohol"],
    1,
    "Two carbon atoms with −COOH give ethanoic acid.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "carbon-and-its-compounds",
    "The next homologue of C2H5OH is",
    ["CH3OH", "C3H7OH", "C2H4", "CH3COOH"],
    1,
    "Adding CH2 to ethanol gives propanol, C3H7OH.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "carbon-and-its-compounds",
    "Unlike soaps, synthetic detergents",
    ["cannot clean clothes", "work well even in hard water", "are always biodegradable", "do not form micelles"],
    1,
    "Calcium and magnesium salts of detergents are soluble, so they lather in hard water.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "carbon-and-its-compounds",
    "Complete combustion of ethanol produces",
    ["CO and H2", "CO2 and H2O", "CH4 and O2", "only carbon"],
    1,
    "C2H5OH + 3O2 → 2CO2 + 3H2O (complete combustion).",
  ),
  cbsePyq(
    "class-10",
    "science",
    "carbon-and-its-compounds",
    "Ethanol reacts with sodium metal to liberate",
    ["oxygen", "carbon dioxide", "hydrogen", "chlorine"],
    2,
    "2C2H5OH + 2Na → 2C2H5ONa + H2.",
  ),

  // --- Life Processes ---
  cbsePyq(
    "class-10",
    "science",
    "life-processes",
    "The site of photosynthesis in a plant cell is the",
    ["mitochondrion", "chloroplast", "nucleus", "vacuole"],
    1,
    "Chlorophyll in chloroplasts captures light for photosynthesis.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "life-processes",
    "Photosynthesis requires chlorophyll and sunlight to convert carbon dioxide and water into",
    [
      "proteins and nitrogen",
      "glucose and oxygen",
      "lactic acid and carbon dioxide",
      "ethanol and oxygen",
    ],
    1,
    "Green plants make glucose and release O2: 6CO2 + 6H2O → C6H12O6 + 6O2.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "life-processes",
    "Stomata mainly help in",
    ["absorption of minerals from soil", "gaseous exchange and transpiration", "transport of food in phloem", "photosynthesis in roots"],
    1,
    "Guard cells open stomata for CO2 entry and water-vapour loss.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "life-processes",
    "The enzyme present in saliva that breaks down starch is",
    ["pepsin", "trypsin", "salivary amylase", "lipase"],
    2,
    "Ptyalin (salivary amylase) converts starch to maltose in the mouth.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "life-processes",
    "Pepsin acts in the stomach in a",
    ["strongly basic medium", "neutral medium", "acidic medium", "alcoholic medium"],
    2,
    "HCl makes the stomach acidic (pH ~2), which activates pepsinogen to pepsin.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "life-processes",
    "Bile is produced by the",
    ["pancreas", "liver", "gall bladder", "stomach"],
    1,
    "The liver secretes bile; the gall bladder only stores it.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "life-processes",
    "The inner wall of the small intestine has villi to",
    ["kill bacteria", "increase surface area for absorption", "produce HCl", "store bile"],
    1,
    "Villi and microvilli greatly increase the absorptive surface.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "life-processes",
    "The end products of aerobic respiration are",
    ["lactic acid and energy", "ethanol, CO2 and energy", "CO2, H2O and energy", "only ATP with no CO2"],
    2,
    "Complete oxidation of glucose yields CO2, H2O and a large amount of ATP.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "life-processes",
    "During vigorous exercise, anaerobic respiration in human muscle produces",
    ["ethanol", "lactic acid", "acetic acid", "pyruvic acid only with no further change"],
    1,
    "Lack of oxygen leads to lactic acid, causing muscle cramps.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "life-processes",
    "Anaerobic respiration in yeast produces",
    ["lactic acid only", "ethanol and carbon dioxide", "only water", "ammonia"],
    1,
    "Alcoholic fermentation: glucose → ethanol + CO2 + energy.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "life-processes",
    "Gaseous exchange in the human lungs occurs in the",
    ["trachea", "bronchi", "alveoli", "diaphragm"],
    2,
    "Thin-walled, moist alveoli provide a large surface for O2–CO2 diffusion.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "life-processes",
    "Double circulation in mammals means that",
    ["blood flows through the heart once in one complete circuit", "blood passes through the heart twice in one complete circuit of the body", "there are two hearts", "veins carry oxygenated blood only"],
    1,
    "Pulmonary and systemic circuits keep oxygenated and deoxygenated blood separate.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "life-processes",
    "Oxygenated blood from the lungs enters the heart at the",
    ["right atrium", "left atrium", "right ventricle", "left ventricle"],
    1,
    "Pulmonary veins empty oxygen-rich blood into the left atrium.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "life-processes",
    "Arteries differ from veins in that arteries",
    ["always carry deoxygenated blood", "have thick elastic walls and carry blood away from the heart", "have valves throughout their length", "carry blood towards the heart"],
    1,
    "Arteries carry blood away from the heart under high pressure; walls are thick and elastic.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "life-processes",
    "The functional filtration unit of the kidney is the",
    ["neuron", "nephron", "alveolus", "villus"],
    1,
    "Each nephron (Bowman's capsule + tubule) filters blood and forms urine.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "life-processes",
    "Transpiration is the loss of water from plants mainly through",
    ["root hairs", "stomata", "xylem vessels only as liquid water to soil", "phloem"],
    1,
    "Most transpiration is stomatal evaporation of water vapour.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "life-processes",
    "Translocation of food in plants occurs through",
    ["xylem", "phloem", "stomata", "cambium only"],
    1,
    "Phloem transports sucrose (and other organics) from leaves to other parts.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "life-processes",
    "Organisms that synthesise their own food from inorganic sources are called",
    ["heterotrophs", "autotrophs", "parasites", "saprophytes"],
    1,
    "Autotrophs (green plants, some bacteria) make food; others consume it.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "life-processes",
    "The energy currency of the cell is",
    ["DNA", "ATP", "NADH only", "glucose stored as such in all cells"],
    1,
    "ATP stores and transfers usable energy from respiration.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "life-processes",
    "Haemoglobin is present in",
    ["WBCs", "RBCs", "platelets", "plasma proteins only"],
    1,
    "Iron-containing haemoglobin in red blood cells transports oxygen.",
  ),

  // --- Control and Coordination ---
  cbsePyq(
    "class-10",
    "science",
    "control-and-coordination",
    "The gap between two neurons is called a",
    ["dendrite", "synapse", "axon", "impulse"],
    1,
    "A synapse is the junction where the impulse passes from one neuron to the next.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "control-and-coordination",
    "The path taken by a reflex action is called a",
    ["neural circuit of the cerebrum only", "reflex arc", "hormonal pathway", "sensory nerve only"],
    1,
    "Receptor → sensory neuron → spinal cord → motor neuron → effector.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "control-and-coordination",
    "The part of the brain that controls posture and balance is the",
    ["cerebrum", "cerebellum", "medulla", "hypothalamus"],
    1,
    "The cerebellum coordinates voluntary muscles for balance and posture.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "control-and-coordination",
    "Involuntary actions such as blood pressure and salivation are controlled by the",
    ["cerebrum", "cerebellum", "medulla oblongata", "spinal cord only"],
    2,
    "The medulla regulates involuntary functions including heartbeat and breathing.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "control-and-coordination",
    "Thinking, memory and voluntary actions are associated with the",
    ["cerebellum", "medulla", "cerebrum", "pons only"],
    2,
    "The cerebrum is the largest part and is the seat of intelligence and voluntary control.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "control-and-coordination",
    "Phototropism in shoots is mainly due to the hormone",
    ["abscisic acid", "auxin", "cytokinin", "insulin"],
    1,
    "Auxin accumulates on the shaded side and promotes cell elongation, bending the shoot towards light.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "control-and-coordination",
    "Which plant hormone is a growth inhibitor that causes wilting of leaves?",
    ["auxin", "gibberellin", "cytokinin", "abscisic acid"],
    3,
    "ABA promotes dormancy and stomatal closure, leading to wilting under stress.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "control-and-coordination",
    "Gibberellins mainly help in",
    ["falling of leaves", "stem elongation and germination of seeds", "closing of stomata", "ripening of fruit only"],
    1,
    "Gibberellins promote stem growth, seed germination and bolting.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "control-and-coordination",
    "Cytokinins are associated with",
    ["cell division", "wilting", "phototropism only", "nerve impulse"],
    0,
    "Cytokinins promote cell division and delay senescence of leaves.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "control-and-coordination",
    "The emergency hormone secreted during stress is",
    ["insulin", "thyroxine", "adrenaline", "oestrogen"],
    2,
    "Adrenaline from adrenal glands raises heartbeat and blood supply to muscles.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "control-and-coordination",
    "Thyroxine regulates",
    ["blood sugar only", "metabolism of carbohydrates, proteins and fats", "uterine contraction", "sleep only"],
    1,
    "Thyroid thyroxine controls the basal metabolic rate; iodine is needed to make it.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "control-and-coordination",
    "Deficiency of iodine in the diet causes",
    ["diabetes", "goitre", "gigantism", "anaemia only"],
    1,
    "Low thyroxine leads to swelling of the thyroid gland (goitre).",
  ),
  cbsePyq(
    "class-10",
    "science",
    "control-and-coordination",
    "Insulin is secreted by the",
    ["thyroid", "adrenal", "pancreas", "pituitary"],
    2,
    "Islets of Langerhans in the pancreas secrete insulin, which lowers blood glucose.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "control-and-coordination",
    "Diabetes mellitus is caused by deficiency of",
    ["thyroxine", "adrenaline", "insulin", "growth hormone"],
    2,
    "Insufficient insulin means glucose is not taken up properly, so blood sugar stays high.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "control-and-coordination",
    "Growth hormone is secreted by the",
    ["thyroid", "pituitary gland", "pancreas", "ovary"],
    1,
    "The pituitary secretes GH; excess causes gigantism, deficiency causes dwarfism.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "control-and-coordination",
    "The movement of a plant part towards gravity is called",
    ["phototropism", "geotropism", "hydrotropism", "chemotropism"],
    1,
    "Roots are positively geotropic; shoots are negatively geotropic.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "control-and-coordination",
    "A nerve impulse is transmitted from dendrite to",
    ["synapse then cell body only, never along the axon", "cell body and then along the axon to the nerve ending", "directly to the effector without an axon", "the hormone gland only"],
    1,
    "Information travels dendrite → cell body → axon → nerve ending at the synapse.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "control-and-coordination",
    "Chemical coordination in plants is brought about by",
    ["nerves", "phytohormones", "nephrons", "antibodies"],
    1,
    "Plants have no nervous system; auxin, GA, cytokinin, ABA and ethylene coordinate growth.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "control-and-coordination",
    "The spinal cord is concerned with",
    ["thinking", "reflex actions and conduction of impulses", "secretion of thyroxine", "pumping of blood"],
    1,
    "Many reflexes are integrated in the spinal cord, which also carries messages to and from the brain.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "control-and-coordination",
    "Testosterone is produced in the",
    ["ovary", "testes", "thyroid", "pancreas"],
    1,
    "Leydig cells of the testes secrete testosterone, the male sex hormone.",
  ),

  // --- How Do Organisms Reproduce ---
  cbsePyq(
    "class-10",
    "science",
    "how-do-organisms-reproduce",
    "Amoeba reproduces asexually by",
    ["budding", "binary fission", "spore formation", "fragmentation"],
    1,
    "The nucleus divides and the cytoplasm splits into two daughter amoebae.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "how-do-organisms-reproduce",
    "In Leishmania, binary fission occurs",
    ["in any plane", "in a definite orientation due to a whip-like flagellum", "only by budding", "only sexually"],
    1,
    "The flagellum imposes a plane of division, unlike Amoeba.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "how-do-organisms-reproduce",
    "Yeast multiplies asexually by",
    ["binary fission", "budding", "fragmentation", "regeneration of the whole body from any cell"],
    1,
    "A small bud grows on the parent cell and separates as a new yeast.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "how-do-organisms-reproduce",
    "Spirogyra multiplies by",
    ["budding", "binary fission", "fragmentation", "spore formation in sporangia like Rhizopus"],
    2,
    "The filament breaks into fragments, each of which grows into a new filament.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "how-do-organisms-reproduce",
    "Planaria can give rise to a complete organism from a cut piece by",
    ["budding", "regeneration", "binary fission", "vegetative propagation"],
    1,
    "Specialised cells proliferate and differentiate to rebuild the missing parts.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "how-do-organisms-reproduce",
    "Rhizopus reproduces asexually by",
    ["binary fission", "budding", "spores produced in sporangia", "fragmentation of leaves"],
    2,
    "Tiny spores in sporangia are released and germinate on a moist surface.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "how-do-organisms-reproduce",
    "Which of the following is an example of vegetative propagation?",
    ["Amoeba splitting", "yeast budding", "potato tuber eyes growing into new plants", "Planaria regeneration"],
    2,
    "Eyes (buds) on a potato tuber are vegetative buds that grow into new plants.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "how-do-organisms-reproduce",
    "Tissue culture is a method of",
    ["sexual reproduction", "growing many plants from a few cells in a nutrient medium", "fertilisation in vitro only in animals", "spore germination in soil"],
    1,
    "Explants are grown on artificial medium to produce plantlets (micropropagation).",
  ),
  cbsePyq(
    "class-10",
    "science",
    "how-do-organisms-reproduce",
    "Transfer of pollen from anther to stigma is called",
    ["fertilisation", "pollination", "germination", "implantation"],
    1,
    "Pollination may be self or cross; it precedes fertilisation.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "how-do-organisms-reproduce",
    "After pollination, the male gamete reaches the egg through the",
    ["style by a pollen tube", "xylem", "stomata", "root hair"],
    0,
    "The pollen tube grows through the style and ovary to deliver gametes to the ovule.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "how-do-organisms-reproduce",
    "The male reproductive part of a flower is the",
    ["carpel (pistil)", "stamen", "sepal", "petal"],
    1,
    "Stamens (anther + filament) produce pollen; carpels are female.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "how-do-organisms-reproduce",
    "A flower that has either stamens or carpels, but not both, is",
    ["bisexual", "unisexual", "complete always", "asexual"],
    1,
    "Papaya and watermelon have unisexual flowers; mustard and Hibiscus are bisexual.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "how-do-organisms-reproduce",
    "In humans, fertilisation normally occurs in the",
    ["uterus", "ovary", "oviduct (fallopian tube)", "vagina"],
    2,
    "The sperm meets the ovum in the fallopian tube; the zygote then implants in the uterus.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "how-do-organisms-reproduce",
    "The placenta in humans",
    ["produces eggs", "provides a surface for exchange of nutrients, O2 and wastes between mother and foetus", "stores urine", "is the site of fertilisation"],
    1,
    "Embryo blood and maternal blood exchange materials across the placental villi without mixing fully.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "how-do-organisms-reproduce",
    "If the egg is not fertilised, the thickened uterine lining is shed as",
    ["ovulation", "implantation", "menstruation", "gestation"],
    2,
    "The menstrual cycle sheds the endometrium roughly every 28 days if no pregnancy occurs.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "how-do-organisms-reproduce",
    "Copper-T is a contraceptive that acts as an",
    ["oral pill of hormones only", "intrauterine device (IUD)", "surgical method of vasectomy", "barrier on the penis"],
    1,
    "Copper-T is placed in the uterus and prevents implantation / is toxic to sperms.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "how-do-organisms-reproduce",
    "HIV is transmitted by",
    ["casual hugging", "sharing food", "sexual contact and infected blood", "mosquito bite as the usual route in textbooks"],
    2,
    "HIV spreads via unprotected sex, infected needles, blood and from mother to child.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "how-do-organisms-reproduce",
    "Testes are located in the scrotum because",
    ["they need a temperature slightly lower than body temperature for sperm formation", "urine is stored there", "eggs mature there", "fertilisation occurs there"],
    0,
    "Sperm production requires 2–3 °C below core body temperature.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "how-do-organisms-reproduce",
    "The process of fusion of male and female gametes is called",
    ["pollination", "fertilisation", "germination", "regeneration"],
    1,
    "Fertilisation produces a zygote, restoring the diploid number.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "how-do-organisms-reproduce",
    "Sexual reproduction is important because it",
    ["produces clones only", "introduces variation in the offspring", "never involves gametes", "occurs only in plants"],
    1,
    "Variation from mixing of DNA helps survival when the environment changes.",
  ),

  // --- Heredity ---
  cbsePyq(
    "class-10",
    "science",
    "heredity",
    "Mendel conducted his famous experiments on",
    ["Drosophila", "garden pea (Pisum sativum)", "Neurospora", "mice only"],
    1,
    "Pea plants have contrasting traits, short life cycle and true-breeding varieties.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "heredity",
    "A trait that appears in the F1 generation when two pure contrasting parents are crossed is",
    ["recessive", "dominant", "acquired", "lethal always"],
    1,
    "The dominant allele expresses itself in the heterozygote (F1).",
  ),
  cbsePyq(
    "class-10",
    "science",
    "heredity",
    "In a monohybrid cross of tall (TT) and dwarf (tt) pea, the F2 phenotypic ratio is",
    ["1 : 1", "1 : 2 : 1", "3 : 1", "9 : 3 : 3 : 1"],
    2,
    "F2 is 3 tall : 1 dwarf (genotypes 1 TT : 2 Tt : 1 tt).",
  ),
  cbsePyq(
    "class-10",
    "science",
    "heredity",
    "The phenotypic ratio in the F2 generation of a Mendelian dihybrid cross is",
    ["3 : 1", "1 : 2 : 1", "9 : 3 : 3 : 1", "1 : 1 : 1 : 1"],
    2,
    "Independent assortment of two traits gives 9 : 3 : 3 : 1 in F2.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "heredity",
    "Genes are located on",
    ["ribosomes", "chromosomes", "the cell wall", "vacuoles"],
    1,
    "Chromosomes made of DNA carry genes in a linear order.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "heredity",
    "In humans, the sex of the child is determined by",
    ["the mother's XX egg always", "the sex chromosome in the sperm (X or Y)", "the climate", "the number of eggs released"],
    1,
    "Eggs carry X; sperms carry X or Y. XY zygote is male, XX is female.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "heredity",
    "The number of chromosomes in a human somatic cell is",
    ["23", "46", "22", "44"],
    1,
    "Humans have 23 pairs (46) chromosomes; gametes have 23.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "heredity",
    "A cut tail of a mouse is an example of an",
    ["inherited trait that will appear in all offspring", "acquired trait that is not passed to offspring", "dominant gene", "sex-linked trait"],
    1,
    "Acquired characters do not change the germ-line DNA, so they are not inherited.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "heredity",
    "A cross between TT and tt pea plants produces F1 plants that are",
    ["all dwarf", "all tall (Tt)", "half tall, half dwarf", "3/4 tall"],
    1,
    "All F1 are heterozygous Tt and tall because T is dominant.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "heredity",
    "The genetic constitution of an organism is called its",
    ["phenotype", "genotype", "karyotype only when it is a plant", "acquired character"],
    1,
    "Genotype is the allele combination; phenotype is the visible expression.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "heredity",
    "Two alternative forms of a gene are called",
    ["chromosomes", "alleles", "nucleotides only", "phenotypes"],
    1,
    "Alleles occupy the same locus and control contrasting expressions of a trait.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "heredity",
    "An organism with two identical alleles for a trait is",
    ["heterozygous", "homozygous", "a hybrid always", "haploid always"],
    1,
    "TT or tt is homozygous; Tt is heterozygous.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "heredity",
    "Human males have sex chromosomes",
    ["XX", "XY", "YY", "XO in all cases"],
    1,
    "Males are XY; females are XX.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "heredity",
    "Mendel's factors are now known as",
    ["chromosomes only without DNA", "genes", "proteins in the diet", "hormones"],
    1,
    "Mendel's hereditary factors are genes.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "heredity",
    "Dwarfness in Mendel's pea plants was due to the genotype",
    ["TT", "Tt", "tt", "T-"],
    2,
    "Dwarf is recessive and appears only in homozygous tt plants.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "heredity",
    "A cross of round yellow (RRYY) with wrinkled green (rryy) seeds gives F1 that are all",
    ["wrinkled green", "round green", "round yellow (RrYy)", "wrinkled yellow"],
    2,
    "Round (R) and yellow (Y) are dominant, so RrYy seeds are round and yellow.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "heredity",
    "The chance of a couple having a male or a female child is",
    ["3 : 1 in favour of male", "equal (1 : 1)", "always female first", "determined only by the mother"],
    1,
    "Half the sperms carry X and half carry Y, so the probability is 50% each.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "heredity",
    "Independent assortment is observed when",
    ["alleles of two different traits separate independently during gamete formation", "only one trait is studied", "acquired traits mix", "chromosomes do not exist"],
    0,
    "Mendel's second law: factors for different characters assort independently.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "heredity",
    "Variation is useful because it",
    ["always harms the species", "provides raw material for survival of some individuals when the environment changes", "stops reproduction", "eliminates all recessive traits at once"],
    1,
    "Different traits may be advantageous in a new environment, so variation aids survival.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "heredity",
    "If a tall pea plant is crossed with a dwarf plant and about half the progeny are dwarf, the tall parent is",
    ["TT", "Tt", "tt", "a new species"],
    1,
    "A test-cross-like 1 : 1 ratio of tall : dwarf shows the tall parent was heterozygous Tt.",
  ),

  // --- Light – Reflection and Refraction ---
  cbsePyq(
    "class-10",
    "science",
    "light-reflection-and-refraction",
    "The mirror formula is",
    ["1/v − 1/u = 1/f", "1/v + 1/u = 1/f", "v + u = f", "m = f/u"],
    1,
    "For spherical mirrors, 1/v + 1/u = 1/f (New Cartesian sign convention).",
  ),
  cbsePyq(
    "class-10",
    "science",
    "light-reflection-and-refraction",
    "The lens formula is",
    ["1/v + 1/u = 1/f", "1/v − 1/u = 1/f", "P = v + u", "m = u/v"],
    1,
    "For thin lenses, 1/v − 1/u = 1/f.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "light-reflection-and-refraction",
    "Magnification produced by a spherical mirror is",
    ["m = h/h′ = u/v", "m = h′/h = v/u", "m = f/v", "m = u + v"],
    1,
    "m = height of image / height of object = v/u for a mirror.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "light-reflection-and-refraction",
    "According to the laws of reflection, the angle of incidence is equal to the",
    ["angle of refraction", "angle of reflection", "glancing angle always", "critical angle"],
    1,
    "i = r, and the incident ray, reflected ray and normal lie in one plane.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "light-reflection-and-refraction",
    "Snell's law is written as",
    ["n = sin r / sin i", "n21 = sin i / sin r", "n = i / r", "n = v/c"],
    1,
    "Relative refractive index n21 = sin i / sin r = v1/v2.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "light-reflection-and-refraction",
    "The SI unit of power of a lens is the",
    ["watt", "joule", "dioptre", "newton"],
    2,
    "Power P = 1/f (f in metres) is expressed in dioptre (D).",
  ),
  cbsePyq(
    "class-10",
    "science",
    "light-reflection-and-refraction",
    "A convex lens is also called a",
    ["diverging lens", "converging lens", "plane lens", "cylindrical mirror"],
    1,
    "A convex lens converges a parallel beam to its focus (in air, for a usual thin lens).",
  ),
  cbsePyq(
    "class-10",
    "science",
    "light-reflection-and-refraction",
    "A concave mirror is used as a",
    ["rear-view mirror in vehicles", "shaving or dentist's mirror", "always as a diverging device for distant objects at infinity only", "spectacle lens for myopia"],
    1,
    "When the object is between pole and focus, a concave mirror gives a magnified erect virtual image.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "light-reflection-and-refraction",
    "The image formed by a plane mirror is",
    ["real, inverted and diminished", "virtual, erect and laterally inverted", "real and erect", "virtual and inverted"],
    1,
    "Plane mirrors form virtual, erect images of the same size, laterally inverted.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "light-reflection-and-refraction",
    "The absolute refractive index of a medium is",
    ["v/c", "c/v", "sin r / sin i always equal to 1", "f/u"],
    1,
    "n = speed of light in vacuum / speed of light in the medium = c/v.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "light-reflection-and-refraction",
    "A convex mirror is commonly used as a",
    ["solar concentrator", "rear-view mirror", "shaving mirror", "projector lens"],
    1,
    "It always forms a diminished erect virtual image and has a wide field of view.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "light-reflection-and-refraction",
    "The power of a convex lens of focal length 20 cm is",
    ["+5 D", "−5 D", "+0.2 D", "+20 D"],
    0,
    "f = +0.20 m, so P = 1/0.20 = +5 D.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "light-reflection-and-refraction",
    "If two thin lenses of powers +2 D and −1 D are in contact, the combination has power",
    ["+3 D", "+1 D", "−2 D", "+2 D"],
    1,
    "P = P1 + P2 = 2 + (−1) = +1 D.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "light-reflection-and-refraction",
    "For a real object, the object distance u in the New Cartesian convention is taken as",
    ["positive", "negative", "zero", "always equal to f"],
    1,
    "Incident light travels left to right; object distance is negative.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "light-reflection-and-refraction",
    "The speed of light in vacuum is",
    ["3 × 10^6 m/s", "3 × 10^8 m/s", "3 × 10^5 km/ms", "330 m/s"],
    1,
    "c = 3 × 10^8 m/s in vacuum.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "light-reflection-and-refraction",
    "An object is placed at the centre of curvature of a concave mirror. The image is",
    ["virtual, erect and magnified", "real, inverted and of the same size at C", "real, inverted and highly diminished at F", "no image"],
    1,
    "Object at C → real inverted image of same size also at C.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "light-reflection-and-refraction",
    "A ray of light travelling from a rarer to a denser medium",
    ["bends away from the normal", "bends towards the normal", "does not refract", "is always totally reflected"],
    1,
    "Speed decreases in the denser medium, so the ray bends towards the normal.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "light-reflection-and-refraction",
    "If the refractive index of glass is 3/2 and c = 3 × 10^8 m/s, the speed of light in glass is",
    ["2 × 10^8 m/s", "4.5 × 10^8 m/s", "3 × 10^8 m/s", "1.5 × 10^8 m/s"],
    0,
    "v = c/n = (3 × 10^8)/(3/2) = 2 × 10^8 m/s.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "light-reflection-and-refraction",
    "The focal length of a spherical mirror is related to its radius of curvature by",
    ["f = R", "f = R/2", "f = 2R", "f = 1/R"],
    1,
    "For spherical mirrors, f = R/2.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "light-reflection-and-refraction",
    "A negative magnification for a spherical mirror means the image is",
    ["virtual and erect", "real and inverted", "of the same size always", "at infinity"],
    1,
    "m is negative for a real inverted image (usual for a concave mirror with object beyond F).",
  ),

  // --- The Human Eye and the Colourful World ---
  cbsePyq(
    "class-10",
    "science",
    "human-eye-and-colourful-world",
    "The light-sensitive screen of the human eye is the",
    ["cornea", "iris", "retina", "pupil"],
    2,
    "The retina contains rods and cones; the image is formed there.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "human-eye-and-colourful-world",
    "The amount of light entering the eye is controlled by the",
    ["ciliary muscles", "iris", "retina", "optic nerve"],
    1,
    "The iris adjusts pupil size, regulating the light that enters.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "human-eye-and-colourful-world",
    "Most of the refraction of light in the eye occurs at the",
    ["retina", "iris", "outer surface of the cornea", "optic nerve"],
    2,
    "The cornea–air interface provides the largest change in refractive index.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "human-eye-and-colourful-world",
    "The least distance of distinct vision for a normal adult eye is about",
    ["25 m", "25 cm", "2.5 cm", "infinity"],
    1,
    "The near point of a normal eye is 25 cm.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "human-eye-and-colourful-world",
    "The far point of a normal eye is",
    ["25 cm", "25 m", "infinity", "1 m"],
    2,
    "A normal eye can focus parallel rays from infinity on the retina.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "human-eye-and-colourful-world",
    "Myopia (short-sightedness) is corrected by a",
    ["convex lens", "concave lens", "cylindrical lens only", "prism"],
    1,
    "A diverging (concave) lens forms a virtual image of a distant object at the far point.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "human-eye-and-colourful-world",
    "Hypermetropia (long-sightedness) is corrected by a",
    ["concave lens", "convex lens", "plane glass", "convex mirror"],
    1,
    "A converging lens adds the extra power needed to focus a nearby object on the retina.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "human-eye-and-colourful-world",
    "Presbyopia in old age is often corrected by",
    ["a concave lens only", "bifocal lenses", "an opaque disc", "removing the cornea"],
    1,
    "Bifocals combine a concave upper part (distant) and a convex lower part (near).",
  ),
  cbsePyq(
    "class-10",
    "science",
    "human-eye-and-colourful-world",
    "The splitting of white light into seven colours by a prism is called",
    ["scattering", "dispersion", "reflection", "interference"],
    1,
    "Different colours have different refractive indices, so they deviate differently.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "human-eye-and-colourful-world",
    "In the visible spectrum, the colour that is least deviated by a prism is",
    ["violet", "blue", "green", "red"],
    3,
    "Red has the longest wavelength and the smallest refractive index in glass, so least deviation.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "human-eye-and-colourful-world",
    "Twinkling of stars is due to",
    ["dispersion by the prism-like eye", "atmospheric refraction", "scattering of light by dust only", "reflection from the moon"],
    1,
    "Changing air density continuously shifts the apparent position and brightness of a star.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "human-eye-and-colourful-world",
    "The Sun is visible about two minutes before actual sunrise because of",
    ["scattering", "atmospheric refraction", "dispersion in space", "total internal reflection in water"],
    1,
    "Atmosphere bends sunlight, so the Sun appears raised; sunset is similarly delayed.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "human-eye-and-colourful-world",
    "The Tyndall effect is the",
    ["dispersion of light by a prism", "scattering of light by colloidal particles", "reflection from a plane mirror", "refraction in a glass slab without deviation"],
    1,
    "Path of light becomes visible when scattered by colloid particles (dust, milk, fog).",
  ),
  cbsePyq(
    "class-10",
    "science",
    "human-eye-and-colourful-world",
    "The sky appears blue because of",
    ["reflection from the ocean", "scattering of shorter wavelengths of sunlight by air molecules", "dispersion in raindrops only at noon", "absorption of blue by ozone only"],
    1,
    "Blue light is scattered more (Rayleigh scattering ∝ 1/λ^4) than red.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "human-eye-and-colourful-world",
    "The Sun appears reddish at sunrise and sunset because",
    ["the Sun emits only red light then", "blue and violet are scattered away over a longer atmospheric path", "the Moon reflects red", "prisms form in the eye"],
    1,
    "Sunlight travels a longer path; shorter wavelengths scatter out, leaving red-orange.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "human-eye-and-colourful-world",
    "Danger signals are red because red light is",
    ["scattered the most", "scattered the least and can be seen from far", "absorbed completely by air", "the only colour the eye detects"],
    1,
    "Long-wavelength red is least scattered, so it remains visible at large distances.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "human-eye-and-colourful-world",
    "A rainbow is formed due to",
    ["only reflection in raindrops", "dispersion, refraction and total internal reflection in raindrops", "scattering by dust alone", "diffraction at clouds"],
    1,
    "Sunlight is dispersed and internally reflected in water droplets.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "human-eye-and-colourful-world",
    "The ability of the eye lens to adjust its focal length is called",
    ["myopia", "accommodation", "presbyopia", "dispersion"],
    1,
    "Ciliary muscles change the lens curvature so that near and distant objects are focused.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "human-eye-and-colourful-world",
    "The blind spot of the eye is the region where",
    ["vision is sharpest", "the optic nerve leaves the retina and there are no rods or cones", "the cornea is thickest", "only cones are present"],
    1,
    "No photoreceptors at the optic disc, so an image there is not perceived.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "human-eye-and-colourful-world",
    "In myopia, the image of a distant object is formed",
    ["on the retina", "behind the retina", "in front of the retina", "on the cornea"],
    2,
    "The eyeball is too long or the lens too converging, so the focus lies in front of the retina.",
  ),

  // --- Electricity ---
  cbsePyq(
    "class-10",
    "science",
    "electricity",
    "Ohm's law states that",
    ["V ∝ 1/I at constant temperature", "V = IR, with V proportional to I if R is constant", "I = VR", "P = V/I"],
    1,
    "At constant temperature, potential difference across a conductor is proportional to current; V = IR.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "electricity",
    "The SI unit of resistance is the",
    ["volt", "ampere", "ohm", "watt"],
    2,
    "1 ohm = 1 volt per ampere.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "electricity",
    "Resistance of a uniform conductor is given by",
    ["R = ρA/l", "R = ρl/A", "R = ρlA", "R = A/(ρl)"],
    1,
    "R is proportional to length and inversely proportional to cross-sectional area; ρ is resistivity.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "electricity",
    "The SI unit of electrical resistivity is",
    ["ohm", "ohm-metre", "ohm/metre", "siemens"],
    1,
    "From R = ρl/A, ρ has unit Ω m.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "electricity",
    "The equivalent resistance of three resistors in series is",
    ["less than the smallest", "R1 + R2 + R3", "1/R1 + 1/R2 + 1/R3", "always zero"],
    1,
    "Series resistances add: Req = R1 + R2 + R3.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "electricity",
    "For two resistors in parallel, the equivalent resistance Req satisfies",
    ["Req = R1 + R2", "1/Req = 1/R1 + 1/R2", "Req = R1 R2", "Req = R1 − R2"],
    1,
    "Reciprocals add in a parallel combination.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "electricity",
    "In a series combination of resistors, the quantity that remains the same is",
    ["potential difference across each", "current", "resistance of each", "power in each always"],
    1,
    "The same current flows through every resistor in series.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "electricity",
    "In a parallel combination of resistors, the quantity that remains the same is",
    ["current in each branch", "potential difference across each", "resistance of each", "charge stored"],
    1,
    "Each parallel branch is connected across the same two points, so V is the same.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "electricity",
    "Joule's law of heating is",
    ["H = IRt", "H = I^2 Rt", "H = V/t", "H = I/R"],
    1,
    "Heat produced H = I^2 Rt (also = VIt = V^2 t/R).",
  ),
  cbsePyq(
    "class-10",
    "science",
    "electricity",
    "Electric power consumed in a resistor is",
    ["P = V/I", "P = VI = I^2 R = V^2/R", "P = IR", "P = QV only with no time"],
    1,
    "Power is the rate of energy consumption: P = VI and equivalent forms.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "electricity",
    "The commercial unit of electrical energy is the",
    ["joule", "watt", "kilowatt-hour", "ampere-hour only"],
    2,
    "1 kWh is the energy used by a 1 kW device in 1 hour.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "electricity",
    "1 kWh is equal to",
    ["3.6 × 10^3 J", "3.6 × 10^6 J", "3.6 × 10^5 J", "1000 J"],
    1,
    "1 kWh = 1000 W × 3600 s = 3.6 × 10^6 J.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "electricity",
    "The SI unit of potential difference is the",
    ["ampere", "ohm", "volt", "coulomb"],
    2,
    "Potential difference is measured in volt (V); 1 V = 1 J/C.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "electricity",
    "The SI unit of electric current is the",
    ["volt", "ampere", "ohm", "watt"],
    1,
    "Current I = Q/t is measured in ampere.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "electricity",
    "Nichrome is used in heating elements because it has",
    ["very low resistivity and low melting point", "high resistivity and high melting point", "zero resistance", "only magnetic properties"],
    1,
    "High ρ gives large heat for a given I; high melting point prevents melting.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "electricity",
    "Resistance of a wire increases if we",
    ["increase its thickness", "increase its length", "decrease its temperature for metals always to zero", "use a thicker copper rod of same length"],
    1,
    "R ∝ l, so a longer wire has greater resistance.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "electricity",
    "Two 4 Ω resistors connected in parallel have equivalent resistance",
    ["8 Ω", "4 Ω", "2 Ω", "1 Ω"],
    2,
    "1/Req = 1/4 + 1/4 = 1/2, so Req = 2 Ω.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "electricity",
    "If a 4 Ω and a 6 Ω resistor are in series, the equivalent resistance is",
    ["2.4 Ω", "10 Ω", "24 Ω", "1.5 Ω"],
    1,
    "Series: 4 + 6 = 10 Ω.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "electricity",
    "The relation between charge Q, current I and time t is",
    ["I = Q t", "Q = I t", "Q = I/t", "t = Q I"],
    1,
    "Current is charge flowing per unit time, so Q = It.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "electricity",
    "Conventional current in a circuit is taken to flow from",
    ["negative to positive terminal", "positive to negative terminal", "earth to cloud always", "both ways equally in a DC battery circuit"],
    1,
    "By convention, current is the direction of flow of positive charge, + to −.",
  ),

  // --- Magnetic Effects of Electric Current ---
  cbsePyq(
    "class-10",
    "science",
    "magnetic-effects-of-electric-current",
    "Oersted discovered that",
    ["a magnet produces electricity always", "a current-carrying conductor produces a magnetic field", "like poles attract", "the Earth has no magnetism"],
    1,
    "A compass needle near a current-carrying wire deflects, showing a magnetic field.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "magnetic-effects-of-electric-current",
    "The direction of the magnetic field around a straight current-carrying conductor is given by the",
    ["Fleming's left-hand rule only", "right-hand thumb rule", "Ohm's law", "Snell's law"],
    1,
    "If the thumb points in the direction of current, curled fingers give the field direction.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "magnetic-effects-of-electric-current",
    "Magnetic field lines",
    ["intersect at the poles", "never intersect each other", "are open curves starting from south", "exist only inside a magnet"],
    1,
    "If they intersect, the field would have two directions at one point, which is impossible.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "magnetic-effects-of-electric-current",
    "The magnetic field inside a long current-carrying solenoid is",
    ["zero", "uniform and along the axis", "radial like a bar magnet's exterior only", "strongest at the outer surface and zero on the axis"],
    1,
    "A solenoid produces a nearly uniform axial field in its interior, like a bar magnet.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "magnetic-effects-of-electric-current",
    "A strong electromagnet should have",
    ["few turns, small current and a wooden core", "many turns, large current and a soft iron core", "a copper core only", "zero current"],
    1,
    "B increases with n, I and the high permeability of soft iron.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "magnetic-effects-of-electric-current",
    "Fleming's left-hand rule is used to find the direction of",
    ["induced current in a generator", "force on a current-carrying conductor in a magnetic field", "magnetic field of the Earth only", "resistance"],
    1,
    "Forefinger B, middle finger I, thumb force — the motor rule.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "magnetic-effects-of-electric-current",
    "Fleming's right-hand rule is used in the",
    ["electric motor", "electric generator (induced current)", "electromagnet winding direction only", "household fuse rating"],
    1,
    "Motion, field and induced current are mutually perpendicular (generator rule).",
  ),
  cbsePyq(
    "class-10",
    "science",
    "magnetic-effects-of-electric-current",
    "The force on a current-carrying conductor of length l in a uniform field B (I perpendicular to B) is",
    ["F = B / I l", "F = B I l", "F = I / B l", "F = B + I + l"],
    1,
    "F = BIl sin θ; when θ = 90°, F = BIl.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "magnetic-effects-of-electric-current",
    "The frequency of AC in Indian household supply is",
    ["60 Hz", "50 Hz", "220 Hz", "5 Hz"],
    1,
    "Mains AC in India is 50 Hz at about 220 V.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "magnetic-effects-of-electric-current",
    "The potential difference of domestic electric supply in India is about",
    ["110 V", "220 V", "440 V for all homes as single phase", "12 V"],
    1,
    "Household single-phase supply is 220 V.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "magnetic-effects-of-electric-current",
    "A fuse wire is used in a domestic circuit to",
    ["increase current", "break the circuit if current exceeds a safe value", "store charge", "step down voltage"],
    1,
    "The fuse melts (or an MCB trips) during overloading or short circuit.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "magnetic-effects-of-electric-current",
    "Earthing of electrical appliances is done to",
    ["increase power", "protect the user by providing a low-resistance path for leakage current", "reduce the bill", "convert AC to DC"],
    1,
    "A live-to-body fault current flows to earth, and the fuse/MCB can blow.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "magnetic-effects-of-electric-current",
    "Overloading in a domestic circuit occurs when",
    ["too many appliances of high power are connected to one socket", "the earth wire is thick", "only one bulb is on", "the fuse rating is very high and unused"],
    0,
    "Total current then exceeds the wiring/fuse rating and heating can cause fire.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "magnetic-effects-of-electric-current",
    "A short circuit occurs when",
    ["live and neutral wires come in direct contact", "only the earth wire breaks", "the appliance is switched off", "the fuse is of correct rating"],
    0,
    "Resistance of the circuit becomes very small, so a large current flows.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "magnetic-effects-of-electric-current",
    "In the older colour code used in many CBSE questions, the live wire is",
    ["green", "black", "red", "yellow"],
    2,
    "Conventionally live is red, neutral black and earth green (newer code: brown, blue, green-yellow).",
  ),
  cbsePyq(
    "class-10",
    "science",
    "magnetic-effects-of-electric-current",
    "The magnetic field around a long straight current-carrying wire consists of",
    ["straight lines parallel to the wire", "concentric circles in a plane perpendicular to the wire", "radial lines from the wire", "no field at all"],
    1,
    "Iron filings form concentric circles centred on the wire.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "magnetic-effects-of-electric-current",
    "The essential difference between AC and DC is that",
    ["AC never produces heat", "in AC the current reverses direction periodically, while in DC it does not", "DC cannot produce a magnetic field", "AC has zero frequency"],
    1,
    "Direct current is unidirectional; alternating current changes direction with time.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "magnetic-effects-of-electric-current",
    "Electromagnetic induction is the production of induced current by",
    ["a stationary magnet near a closed coil with no flux change", "change of magnetic flux through a circuit", "heating a resistor", "chemical reaction in a cell"],
    1,
    "Faraday: an emf is induced whenever magnetic flux linked with a coil changes.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "magnetic-effects-of-electric-current",
    "The pattern of the magnetic field of a current-carrying circular loop at its centre is",
    ["circular in the plane of the loop", "straight and perpendicular to the plane of the loop", "zero always", "radial in the plane of the loop"],
    1,
    "Field lines pass through the centre at right angles to the plane of the loop.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "magnetic-effects-of-electric-current",
    "An electric motor converts",
    ["electrical energy into mechanical energy", "mechanical energy into electrical energy", "heat into light", "chemical energy into heat only"],
    0,
    "A motor uses the force on a current in a magnetic field to produce rotation.",
  ),

  // --- Our Environment ---
  cbsePyq(
    "class-10",
    "science",
    "our-environment",
    "An ecosystem consists of",
    ["only plants", "only animals", "biotic and abiotic components interacting together", "only decomposers"],
    2,
    "Living organisms plus physical factors (soil, water, air, light) form an ecosystem.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "our-environment",
    "Producers in an ecosystem are",
    ["herbivores", "green plants and other autotrophs", "carnivores", "decomposers only"],
    1,
    "Autotrophs convert solar energy into chemical energy of food.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "our-environment",
    "In the food chain grass → grasshopper → frog → snake, the frog is a",
    ["producer", "primary consumer", "secondary consumer", "decomposer"],
    2,
    "Grasshopper is primary consumer; frog eats it, so frog is secondary consumer.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "our-environment",
    "The number of trophic levels in grass → insect → frog → snake is",
    ["two", "three", "four", "five"],
    2,
    "Four organisms form four trophic levels (producer + three consumers).",
  ),
  cbsePyq(
    "class-10",
    "science",
    "our-environment",
    "According to the 10% law of energy transfer, if producers have 10,000 J, the energy available to herbivores is about",
    ["10,000 J", "1,000 J", "100 J", "10 J"],
    1,
    "Only about 10% of energy passes to the next trophic level (Lindeman).",
  ),
  cbsePyq(
    "class-10",
    "science",
    "our-environment",
    "Biological magnification refers to",
    ["increase in body size of organisms", "progressive increase in concentration of harmful chemicals at successive trophic levels", "increase in number of producers", "decrease of ozone"],
    1,
    "Non-degradable pesticides like DDT accumulate and become most concentrated in top carnivores.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "our-environment",
    "Ozone in the stratosphere is formed when UV radiation splits oxygen molecules and the atoms combine with O2. Ozone protects us by absorbing",
    ["infrared heat only", "harmful ultraviolet radiation", "all visible light", "radio waves"],
    1,
    "The ozone layer absorbs UV-B, reducing DNA damage and skin cancer risk.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "our-environment",
    "Depletion of the ozone layer is mainly caused by",
    ["oxygen", "nitrogen", "chlorofluorocarbons (CFCs)", "water vapour only"],
    2,
    "Chlorine from CFCs catalytically destroys ozone in the stratosphere.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "our-environment",
    "Which of the following is biodegradable?",
    ["plastic bag", "DDT", "vegetable peels", "glass bottle"],
    2,
    "Kitchen waste is broken down by microbes; plastics, DDT and glass are non-biodegradable.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "our-environment",
    "Decomposers in an ecosystem are typically",
    ["green plants", "herbivores", "bacteria and fungi", "top carnivores"],
    2,
    "Saprophytes recycle nutrients by breaking down dead organic matter.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "our-environment",
    "A food web is",
    ["a single straight chain of organisms", "an interconnected network of food chains", "only abiotic factors", "energy coming from soil minerals"],
    1,
    "Many food chains interlink because most organisms eat, and are eaten by, more than one species.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "our-environment",
    "The flow of energy in an ecosystem is",
    ["cyclic", "unidirectional", "bidirectional between all trophic levels equally", "from carnivores to producers"],
    1,
    "Energy comes from the Sun and is lost as heat at each step; it does not cycle like nutrients.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "our-environment",
    "UNEP's 1987 agreement to freeze CFC production is linked to protecting the",
    ["hydrosphere only", "ozone layer", "Earth's core", "tropospheric oxygen we breathe as O2 only"],
    1,
    "The Montreal Protocol (after UNEP efforts) aimed to reduce ozone-depleting substances.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "our-environment",
    "Non-biodegradable wastes are harmful because they",
    ["are always radioactive", "persist in the environment and may enter food chains", "decompose too fast", "increase oxygen in water"],
    1,
    "Plastics and many chemicals remain for years and can biomagnify.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "our-environment",
    "The first trophic level in a food chain is always occupied by",
    ["herbivores", "producers", "carnivores", "parasites"],
    1,
    "Autotrophs form trophic level 1; energy enters the living world here.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "our-environment",
    "Food chains are generally short because",
    ["organisms do not eat one another", "there is a large loss of energy at each trophic level", "the Sun provides no energy", "decomposers stop all chains at level 2"],
    1,
    "After a few transfers too little energy remains to support another level.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "our-environment",
    "Which organism in a pond ecosystem is a producer?",
    ["fish", "frog", "phytoplankton / algae", "crane"],
    2,
    "Algae and phytoplankton photosynthesise and form the base of aquatic food chains.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "our-environment",
    "Garden waste is better disposed of by",
    ["dumping in a river", "composting / vermicomposting", "burning plastics with it", "storing in sealed plastic forever"],
    1,
    "Biodegradable waste can be converted into manure by microbes or earthworms.",
  ),
  cbsePyq(
    "class-10",
    "science",
    "our-environment",
    "If 1000 J of energy is available at the producer level, energy reaching the tertiary consumer (fourth trophic level) is about",
    ["100 J", "10 J", "1 J", "1000 J"],
    2,
    "10% each step: 1000 → 100 (herbivore) → 10 (secondary) → 1 J (tertiary).",
  ),
  cbsePyq(
    "class-10",
    "science",
    "our-environment",
    "Which of the following is an abiotic component of an ecosystem?",
    ["bacteria", "fungi", "temperature", "earthworm"],
    2,
    "Temperature, light, soil and water are physical (abiotic) factors.",
  ),
];

assertTwentyPerChapter(class10ScienceQuestions, [
  "chemical-reactions-and-equations",
  "acids-bases-and-salts",
  "metals-and-non-metals",
  "carbon-and-its-compounds",
  "life-processes",
  "control-and-coordination",
  "how-do-organisms-reproduce",
  "heredity",
  "light-reflection-and-refraction",
  "human-eye-and-colourful-world",
  "electricity",
  "magnetic-effects-of-electric-current",
  "our-environment",
]);
