import { assertTwentyPerChapter, cbsePyq, type PracticeQuestionSeed } from "./types";

export const class11ChemistryQuestions: PracticeQuestionSeed[] = [
  // --- Some Basic Concepts of Chemistry ---
  cbsePyq(
    "class-11",
    "chemistry",
    "some-basic-concepts-of-chemistry",
    "Which pair of compounds illustrates the law of multiple proportions?",
    ["H2O and H2O2", "NaCl and KCl", "CH4 and SiH4", "HCl and HBr"],
    0,
    "Hydrogen combines with oxygen in H2O and H2O2 in simple whole-number mass ratios, which is the law of multiple proportions.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "some-basic-concepts-of-chemistry",
    "The number of moles present in 22 g of CO2 is",
    ["0.25", "0.50", "1.00", "2.00"],
    1,
    "Molar mass of CO2 is 44 g mol−1, so 22 g corresponds to 0.50 mol.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "some-basic-concepts-of-chemistry",
    "The empirical formula of a compound with molecular formula C6H12O6 is",
    ["CHO", "CH2O", "C2H4O2", "C6H12O6"],
    1,
    "Dividing C6H12O6 by 6 gives the simplest ratio CH2O.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "some-basic-concepts-of-chemistry",
    "In the reaction 2H2 + O2 → 2H2O, if 2 mol of H2 and 2 mol of O2 are mixed, the limiting reagent is",
    ["O2", "H2", "H2O", "neither H2 nor O2"],
    1,
    "2 mol H2 require only 1 mol O2, so hydrogen is consumed first and is limiting.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "some-basic-concepts-of-chemistry",
    "One mole of any substance contains",
    [
      "6.022 × 10^23 entities",
      "3.011 × 10^23 entities",
      "12 g of the substance",
      "22.4 molecules only",
    ],
    0,
    "By definition, 1 mol contains Avogadro's number of specified entities.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "some-basic-concepts-of-chemistry",
    "The molarity of a solution containing 4.0 g of NaOH in 250 mL of solution is",
    ["0.1 M", "0.2 M", "0.4 M", "0.8 M"],
    2,
    "Moles of NaOH = 4/40 = 0.10; volume = 0.250 L; molarity = 0.40 M.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "some-basic-concepts-of-chemistry",
    "The number of significant figures in 0.0250 is",
    ["2", "3", "4", "5"],
    1,
    "Leading zeros are not significant; 2, 5 and the trailing zero give three significant figures.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "some-basic-concepts-of-chemistry",
    "The mass percent of hydrogen in H2O is approximately",
    ["5.6%", "11.1%", "33.3%", "88.9%"],
    1,
    "Mass of H in 18 g water is 2 g, so percentage of hydrogen is (2/18)×100 ≈ 11.1%.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "some-basic-concepts-of-chemistry",
    "The law of conservation of mass was given by",
    ["Dalton", "Proust", "Lavoisier", "Avogadro"],
    2,
    "Lavoisier established that mass is conserved in a chemical reaction.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "some-basic-concepts-of-chemistry",
    "The mole fraction of the solute in a binary solution is equal to",
    [
      "n_solute / n_solvent",
      "n_solute / (n_solute + n_solvent)",
      "n_solvent / (n_solute + n_solvent)",
      "mass of solute / mass of solution",
    ],
    1,
    "Mole fraction of solute is moles of solute divided by total moles of solute and solvent.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "some-basic-concepts-of-chemistry",
    "The number of molecules in 11.2 L of O2 at STP is",
    ["6.022 × 10^23", "3.011 × 10^23", "1.204 × 10^23", "12.044 × 10^23"],
    1,
    "11.2 L at STP is 0.50 mol, which contains 0.50 × 6.022 × 10^23 molecules.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "some-basic-concepts-of-chemistry",
    "Which concentration unit does not change with temperature?",
    ["molarity", "normality", "molality", "formality of a volume-based solution"],
    2,
    "Molality is moles of solute per kilogram of solvent, so it is independent of volume and temperature.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "some-basic-concepts-of-chemistry",
    "1 amu is defined as",
    [
      "1/12 of the mass of a C-12 atom",
      "1/16 of the mass of an O-16 atom",
      "mass of one hydrogen atom",
      "mass of one proton only",
    ],
    0,
    "The unified atomic mass unit is one-twelfth the mass of a carbon-12 atom.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "some-basic-concepts-of-chemistry",
    "The volume occupied by 1 mole of an ideal gas at STP (273 K, 1 atm) is",
    ["22.4 L", "22.4 mL", "11.2 L", "24.0 L"],
    0,
    "One mole of an ideal gas occupies 22.4 L at 273 K and 1 atm.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "some-basic-concepts-of-chemistry",
    "The number of oxygen atoms in 4.4 g of CO2 is",
    ["6.022 × 10^22", "1.204 × 10^23", "3.011 × 10^23", "6.022 × 10^23"],
    1,
    "4.4 g CO2 is 0.10 mol and contains 0.20 mol oxygen atoms, i.e. 1.204 × 10^23 atoms.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "some-basic-concepts-of-chemistry",
    "For N2 + 3H2 → 2NH3, if 28 g of N2 and 8 g of H2 react, the limiting reagent is",
    ["H2", "N2", "NH3", "both N2 and H2"],
    1,
    "28 g N2 is 1 mol and 8 g H2 is 4 mol; 1 mol N2 needs only 3 mol H2, so N2 is limiting.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "some-basic-concepts-of-chemistry",
    "Precision of a measurement refers to",
    [
      "closeness to the true value",
      "closeness of two or more measurements to one another",
      "the number of decimal places only",
      "absence of systematic error only",
    ],
    1,
    "Precision describes how closely repeated measurements agree; accuracy is closeness to the true value.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "some-basic-concepts-of-chemistry",
    "The number of atoms in 0.5 mol of oxygen gas (O2) is",
    ["3.011 × 10^23", "6.022 × 10^23", "1.204 × 10^24", "1.506 × 10^23"],
    1,
    "0.50 mol O2 contains 1.0 mol of oxygen atoms, equal to 6.022 × 10^23 atoms.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "some-basic-concepts-of-chemistry",
    "Which postulate of Dalton's atomic theory was later modified?",
    [
      "Matter is made of atoms",
      "Atoms of different elements have different properties",
      "Atoms are indivisible and atoms of an element are identical in mass",
      "Compounds are formed by combination of atoms",
    ],
    2,
    "Discovery of subatomic particles and isotopes showed that atoms are divisible and not all atoms of an element have the same mass.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "some-basic-concepts-of-chemistry",
    "Gay-Lussac's law of combining volumes applies to",
    [
      "solids at the same temperature",
      "liquids at the same pressure",
      "gases measured under similar conditions of temperature and pressure",
      "solutions of the same molarity",
    ],
    2,
    "Gaseous reactants and products combine in simple volume ratios when compared at the same T and P.",
  ),

  // --- Structure of Atom ---
  cbsePyq(
    "class-11",
    "chemistry",
    "structure-of-atom",
    "An electron with quantum numbers n = 3, l = 2, ml = +2, ms = +1/2 occupies a",
    ["3s orbital", "3p orbital", "3d orbital", "4d orbital"],
    2,
    "l = 2 corresponds to a d subshell and n = 3, so the electron is in 3d.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "structure-of-atom",
    "According to the Aufbau principle, electrons enter",
    [
      "orbitals of highest energy first",
      "orbitals of lowest energy first",
      "only s orbitals first in every shell",
      "degenerate orbitals with paired spins first",
    ],
    1,
    "Electrons occupy available orbitals in order of increasing energy (n + l rule).",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "structure-of-atom",
    "Pauli's exclusion principle states that",
    [
      "electrons occupy degenerate orbitals singly first",
      "no two electrons in an atom can have the same set of four quantum numbers",
      "energy is absorbed in discrete quanta only",
      "the position and momentum of an electron can both be known exactly",
    ],
    1,
    "Each orbital holds at most two electrons of opposite spin, so all four quantum numbers cannot be identical.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "structure-of-atom",
    "Hund's rule of maximum multiplicity is applied while filling",
    ["a single orbital", "orbitals of different n", "degenerate orbitals", "only s orbitals"],
    2,
    "Degenerate orbitals are occupied singly with parallel spins before pairing occurs.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "structure-of-atom",
    "The de Broglie wavelength of a particle of mass m and velocity v is",
    ["λ = h/mv", "λ = mv/h", "λ = hν", "λ = mc^2"],
    0,
    "de Broglie relation is λ = h/p = h/mv for a non-relativistic particle.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "structure-of-atom",
    "Heisenberg's uncertainty principle is expressed as",
    ["Δx · Δp ≥ h/4π", "Δx · Δp = h", "ΔE · Δt = 0", "Δx · Δv = h/m"],
    0,
    "The product of uncertainties in position and momentum is at least h/4π.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "structure-of-atom",
    "In the photoelectric effect, the kinetic energy of the ejected electron is",
    ["hν", "hν + φ", "hν − φ", "φ − hν"],
    2,
    "Einstein's equation is KE_max = hν − φ, where φ is the work function.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "structure-of-atom",
    "The energy of an electron in the nth orbit of a hydrogen atom is",
    ["−13.6 n^2 eV", "−13.6 / n^2 eV", "−13.6 n eV", "+13.6 / n^2 eV"],
    1,
    "Bohr's formula is En = −13.6/n^2 eV for hydrogen.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "structure-of-atom",
    "The maximum number of electrons that can be accommodated in a shell with n = 3 is",
    ["8", "9", "18", "32"],
    2,
    "A shell holds at most 2n^2 electrons, so for n = 3 the maximum is 18.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "structure-of-atom",
    "The azimuthal quantum number l determines",
    [
      "the size of the orbital only",
      "the shape (subshell) of the orbital",
      "the spin of the electron",
      "the nuclear charge",
    ],
    1,
    "l = 0, 1, 2, 3 corresponds to s, p, d, f subshells and thus orbital shape.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "structure-of-atom",
    "The ground-state electronic configuration of Cr (Z = 24) is",
    ["[Ar] 4s2 3d4", "[Ar] 4s1 3d5", "[Ar] 4s2 3d5", "[Ar] 3d6"],
    1,
    "Half-filled 3d5 with 4s1 is extra stable, so chromium is [Ar] 4s1 3d5.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "structure-of-atom",
    "The number of orbitals in the n = 4 shell is",
    ["4", "8", "16", "32"],
    2,
    "Number of orbitals in a shell is n^2, so n = 4 has 16 orbitals.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "structure-of-atom",
    "For a 4d electron, the values of n and l are",
    ["n = 4, l = 1", "n = 4, l = 2", "n = 3, l = 2", "n = 4, l = 3"],
    1,
    "The 4d subshell has principal quantum number 4 and azimuthal quantum number 2.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "structure-of-atom",
    "The number of radial nodes in a 3p orbital is",
    ["0", "1", "2", "3"],
    1,
    "Radial nodes = n − l − 1 = 3 − 1 − 1 = 1.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "structure-of-atom",
    "The dual nature of matter was proposed by",
    ["Einstein", "Planck", "de Broglie", "Heisenberg"],
    2,
    "de Broglie suggested that particles have an associated wavelength λ = h/p.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "structure-of-atom",
    "Possible values of the magnetic quantum number for a p-orbital are",
    ["0 only", "−1, 0, +1", "−2, −1, 0, +1, +2", "+1/2 and −1/2"],
    1,
    "For l = 1, ml can be −1, 0 or +1 (three p orbitals).",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "structure-of-atom",
    "Splitting of spectral lines in a magnetic field is known as the",
    ["Stark effect", "Zeeman effect", "photoelectric effect", "Compton effect"],
    1,
    "The Zeeman effect is the splitting of spectral lines in an external magnetic field.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "structure-of-atom",
    "Isotopes of an element have",
    [
      "same mass number, different atomic number",
      "same atomic number, different mass number",
      "same number of neutrons",
      "different numbers of protons",
    ],
    1,
    "Isotopes have the same Z (protons) but different A (neutrons).",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "structure-of-atom",
    "The maximum number of unpaired electrons in the 3d subshell is",
    ["3", "5", "7", "10"],
    1,
    "Five degenerate 3d orbitals can each hold one unpaired electron (Hund's rule).",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "structure-of-atom",
    "The frequency (ν) and wavelength (λ) of electromagnetic radiation are related by",
    ["c = νλ", "c = ν/λ", "E = λ/ν", "ν = cλ"],
    0,
    "Speed of light c equals the product of frequency and wavelength.",
  ),

  // --- Classification of Elements and Periodicity ---
  cbsePyq(
    "class-11",
    "chemistry",
    "classification-of-elements-and-periodicity",
    "According to the modern periodic law, the properties of elements are a periodic function of their",
    ["atomic mass", "atomic number", "mass number", "neutron number"],
    1,
    "Moseley's work showed that atomic number, not atomic mass, is the basis of periodicity.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "classification-of-elements-and-periodicity",
    "On moving from left to right across a period, the atomic radius generally",
    ["increases", "decreases", "remains constant", "first decreases then increases sharply"],
    1,
    "Effective nuclear charge increases across a period, pulling electrons closer and decreasing radius.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "classification-of-elements-and-periodicity",
    "On moving down a group, the first ionization enthalpy generally",
    ["increases", "decreases", "remains the same", "becomes zero"],
    1,
    "Atomic size increases down a group, so the outermost electron is less tightly held.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "classification-of-elements-and-periodicity",
    "The most electronegative element is",
    ["oxygen", "chlorine", "fluorine", "nitrogen"],
    2,
    "Fluorine has the highest Pauling electronegativity (4.0).",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "classification-of-elements-and-periodicity",
    "The electron gain enthalpy of chlorine is more negative than that of fluorine because",
    [
      "fluorine has a higher nuclear charge",
      "the small size of fluorine causes strong electron–electron repulsion in 2p",
      "chlorine is more electronegative than fluorine",
      "fluorine has a vacant d orbital",
    ],
    1,
    "Added electron faces greater inter-electronic repulsion in compact 2p of F than in 3p of Cl.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "classification-of-elements-and-periodicity",
    "Among the isoelectronic species N3−, O2−, F− and Na+, the smallest ion is",
    ["N3−", "O2−", "F−", "Na+"],
    3,
    "For isoelectronic species, ionic radius decreases as nuclear charge increases; Na+ has Z = 11.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "classification-of-elements-and-periodicity",
    "s-block elements are those in which the last electron enters",
    ["an ns orbital", "an np orbital", "an (n−1)d orbital", "an (n−2)f orbital"],
    0,
    "Groups 1 and 2 have the differentiating electron in the ns subshell.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "classification-of-elements-and-periodicity",
    "A well-known diagonal relationship exists between",
    ["Li and Mg", "Be and Na", "B and Si only in group 18", "Na and Ca"],
    0,
    "Lithium and magnesium show similar chemistry because of comparable size and polarizing power.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "classification-of-elements-and-periodicity",
    "The second ionization enthalpy of sodium is abnormally high because",
    [
      "Na has a large atomic radius",
      "Na+ has a stable noble-gas configuration",
      "sodium has a high electron gain enthalpy",
      "the 3s electron is loosely held",
    ],
    1,
    "Removing a second electron from Na+ means breaking the neon configuration, which requires much more energy.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "classification-of-elements-and-periodicity",
    "Metallic character of elements in a group generally",
    ["decreases down the group", "increases down the group", "is maximum at the top", "does not change"],
    1,
    "Ionization enthalpy falls and atomic size rises down a group, so metallic character increases.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "classification-of-elements-and-periodicity",
    "In the second period, the element with the highest first ionization enthalpy is",
    ["Li", "N", "F", "Ne"],
    3,
    "Noble gas neon has a closed-shell configuration and the highest IE1 in period 2.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "classification-of-elements-and-periodicity",
    "Compared with the parent atom, a cation is",
    ["larger", "smaller", "equal in size", "always paramagnetic"],
    1,
    "Loss of electrons increases Z_eff per remaining electron and often removes an outer shell, shrinking the ion.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "classification-of-elements-and-periodicity",
    "The correct order of electronegativity is",
    ["F > O > Cl > N", "F > Cl > O > N", "O > F > N > Cl", "N > Cl > O > F"],
    0,
    "Pauling values: F (4.0) > O (3.5) > Cl (3.16) > N (3.04).",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "classification-of-elements-and-periodicity",
    "In d-block elements the last electron enters",
    ["ns", "np", "(n−1)d", "(n−2)f"],
    2,
    "Transition elements are defined by filling of the (n−1)d subshell.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "classification-of-elements-and-periodicity",
    "The number of valence electrons in a group 14 element is",
    ["2", "3", "4", "6"],
    2,
    "Group 14 elements have the ns2 np2 configuration, i.e. four valence electrons.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "classification-of-elements-and-periodicity",
    "Electron gain enthalpy of noble gases is",
    ["highly negative", "nearly zero or positive", "equal to their ionization enthalpy", "always more negative than that of halogens"],
    1,
    "Adding an electron to a closed shell is unfavourable, so ΔegH is positive or only slightly negative.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "classification-of-elements-and-periodicity",
    "In an isoelectronic series, ionic radius decreases with",
    ["decreasing nuclear charge", "increasing nuclear charge", "increasing number of electrons", "decreasing mass number only"],
    1,
    "More protons pull the same number of electrons more tightly, so the ion is smaller.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "classification-of-elements-and-periodicity",
    "In the third period, the element with the largest atomic radius is",
    ["Na", "Al", "Cl", "Ar"],
    0,
    "Atomic radius decreases across period 3 as Z_eff rises; sodium has the largest atomic radius in the period.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "classification-of-elements-and-periodicity",
    "Across a period, effective nuclear charge",
    ["decreases", "increases", "remains constant", "becomes zero at the noble gas"],
    1,
    "Added protons are incompletely screened by electrons in the same shell, so Z_eff rises.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "classification-of-elements-and-periodicity",
    "Mendeleev arranged the then-known elements in order of increasing",
    ["atomic number", "atomic mass", "density", "ionization enthalpy"],
    1,
    "Mendeleev's periodic table was based on atomic masses (with some inversions later explained by atomic number).",
  ),

  // --- Chemical Bonding and Molecular Structure ---
  cbsePyq(
    "class-11",
    "chemistry",
    "chemical-bonding-and-molecular-structure",
    "According to VSEPR theory, the shape of NH3 is",
    ["trigonal planar", "tetrahedral", "trigonal pyramidal", "T-shaped"],
    2,
    "Four electron pairs (three bonding, one lone pair) give a pyramidal molecular shape.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "chemical-bonding-and-molecular-structure",
    "The hybridisation of carbon in CH4 is",
    ["sp", "sp2", "sp3", "sp3d"],
    2,
    "Four equivalent C–H bonds around carbon arise from sp3 hybridisation.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "chemical-bonding-and-molecular-structure",
    "The bond order of the N2 molecule is",
    ["1", "2", "3", "2.5"],
    2,
    "N2 has a triple bond; MOT also gives bond order (8 − 2)/2 = 3.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "chemical-bonding-and-molecular-structure",
    "The dipole moment of CO2 is zero because the molecule is",
    ["bent with equal C=O bonds", "linear with two equal and opposite bond dipoles", "tetrahedral", "polar with a lone pair on carbon"],
    1,
    "Linear O=C=O has equal C=O dipoles that cancel, so μ = 0.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "chemical-bonding-and-molecular-structure",
    "The H–O–H bond angle in water is approximately",
    ["90°", "104.5°", "109.5°", "180°"],
    1,
    "Two lone pairs compress the tetrahedral angle to about 104.5°.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "chemical-bonding-and-molecular-structure",
    "O2 is paramagnetic because it has",
    ["no unpaired electrons", "one unpaired electron", "two unpaired electrons", "a triple bond"],
    2,
    "MOT places one electron in each of π*2px and π*2py, so O2 has two unpaired electrons.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "chemical-bonding-and-molecular-structure",
    "The hybridisation of Be in BeCl2 (gaseous) is",
    ["sp", "sp2", "sp3", "sp3d"],
    0,
    "BeCl2 is linear with two electron pairs around Be, corresponding to sp hybridisation.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "chemical-bonding-and-molecular-structure",
    "The shape of SF6 is",
    ["tetrahedral", "square planar", "trigonal bipyramidal", "octahedral"],
    3,
    "Six bonding pairs and no lone pairs on S give an octahedral geometry (sp3d2).",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "chemical-bonding-and-molecular-structure",
    "The molecular geometry of XeF2 is",
    ["bent", "trigonal planar", "linear", "square pyramidal"],
    2,
    "Five electron pairs (two bonding, three equatorial lone pairs) give a linear XeF2 molecule.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "chemical-bonding-and-molecular-structure",
    "BF3 is trigonal planar because boron is",
    ["sp hybridised", "sp2 hybridised", "sp3 hybridised", "sp3d hybridised"],
    1,
    "Three bonding pairs and an empty p orbital correspond to sp2 hybridisation and 120° angles.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "chemical-bonding-and-molecular-structure",
    "Among HF, HCl, HBr and HI, intermolecular hydrogen bonding is strongest in",
    ["HF", "HCl", "HBr", "HI"],
    0,
    "Fluorine is the most electronegative, so HF forms the strongest hydrogen bonds.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "chemical-bonding-and-molecular-structure",
    "The bond order of O2+ is",
    ["1.5", "2.0", "2.5", "3.0"],
    2,
    "Removing an antibonding electron from O2 raises bond order from 2.0 to 2.5.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "chemical-bonding-and-molecular-structure",
    "The hybridisation of phosphorus in PCl5 is",
    ["sp3", "sp3d", "sp3d2", "sp2"],
    1,
    "Five P–Cl bonds in trigonal bipyramidal PCl5 require sp3d hybridisation.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "chemical-bonding-and-molecular-structure",
    "The formal charge on the central oxygen atom in ozone (O3) is",
    ["0", "+1", "−1", "+2"],
    1,
    "In the Lewis structure the central O has three bonds and one lone pair, giving formal charge +1.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "chemical-bonding-and-molecular-structure",
    "In a coordinate (dative) bond, the shared pair of electrons is contributed by",
    ["each atom equally", "one atom only", "the more electronegative atom only after ionization", "the nucleus"],
    1,
    "Both electrons of a coordinate bond are donated by a single Lewis base.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "chemical-bonding-and-molecular-structure",
    "BF3 is an exception to the octet rule because boron has",
    ["an expanded octet", "only six electrons in its valence shell", "a negative formal charge", "d orbitals in bonding"],
    1,
    "BF3 is electron-deficient: boron is surrounded by six electrons.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "chemical-bonding-and-molecular-structure",
    "Ionic character of a bond increases with",
    [
      "decrease in electronegativity difference",
      "increase in electronegativity difference",
      "increase in covalent radius of both atoms equally",
      "decrease in lattice energy only",
    ],
    1,
    "Greater Δχ shifts electron density toward one atom and increases ionic character.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "chemical-bonding-and-molecular-structure",
    "The number of lone pairs on the central atom in H2O is",
    ["0", "1", "2", "3"],
    2,
    "Oxygen has six valence electrons; two form O–H bonds and two remain as lone pairs.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "chemical-bonding-and-molecular-structure",
    "The two O–O bonds in ozone are equal because of",
    ["hybridisation of hydrogen", "resonance", "ionic bonding", "hydrogen bonding"],
    1,
    "Two equivalent resonance structures make the O–O bonds identical (bond order 1.5).",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "chemical-bonding-and-molecular-structure",
    "According to Fajan's rules, covalent character is favoured by a",
    ["large cation and small anion", "small cation and large anion", "low charge on the cation", "noble-gas configuration of the cation only"],
    1,
    "A small highly charged cation polarizes a large anion, increasing covalent character.",
  ),

  // --- Thermodynamics ---
  cbsePyq(
    "class-11",
    "chemistry",
    "thermodynamics",
    "The first law of thermodynamics is written as",
    ["ΔU = q − w (with w work done on the system)", "ΔU = q + w", "ΔG = ΔH − TΔS", "q = ΔU × w"],
    1,
    "CBSE convention: ΔU = q + w, with w = −PextΔV for expansion work.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "thermodynamics",
    "Which of the following is a state function?",
    ["q", "w", "heat capacity along a specified path only", "internal energy U"],
    3,
    "U depends only on the state of the system; q and w depend on the path.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "thermodynamics",
    "Hess's law states that the enthalpy change of a reaction is",
    [
      "dependent on the path taken",
      "independent of the path and equal to the sum of enthalpy changes of steps",
      "always zero",
      "equal to q at constant volume only",
    ],
    1,
    "Enthalpy is a state function, so ΔH is path-independent (Hess's law).",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "thermodynamics",
    "The standard enthalpy of formation of the most stable form of an element is",
    ["positive", "negative", "zero", "equal to its bond enthalpy"],
    2,
    "By definition, ΔfH° of C(graphite), H2(g), O2(g), etc. is zero.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "thermodynamics",
    "For a process to be spontaneous at constant T and P, ΔG must be",
    ["greater than zero", "equal to zero", "less than zero", "equal to ΔH always"],
    2,
    "A negative Gibbs energy change is the criterion of spontaneity at constant T and P.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "thermodynamics",
    "The Gibbs–Helmholtz equation relating ΔG, ΔH and ΔS is",
    ["ΔG = ΔH + TΔS", "ΔG = ΔH − TΔS", "ΔG = TΔS − ΔH", "ΔG = ΔU − TΔS"],
    1,
    "ΔG = ΔH − TΔS at constant temperature.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "thermodynamics",
    "For a spontaneous process, the entropy of the universe",
    ["decreases", "increases", "remains constant", "is always zero"],
    1,
    "The second law requires ΔS_univ > 0 for irreversible spontaneous processes.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "thermodynamics",
    "For an ideal gas, Cp − Cv equals",
    ["0", "R", "2R", "R/2"],
    1,
    "Molar heat capacities of an ideal gas differ by the gas constant R.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "thermodynamics",
    "The enthalpy of neutralization of a strong acid by a strong base is about",
    ["−13.7 kJ mol−1", "−57.3 kJ mol−1", "+57.3 kJ mol−1", "0"],
    1,
    "H+(aq) + OH−(aq) → H2O(l) releases about 57.3 kJ mol−1.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "thermodynamics",
    "Work done in irreversible expansion of a gas against constant external pressure is",
    ["−nRT ln(V2/V1)", "−Pext ΔV", "zero always", "C_v ΔT"],
    1,
    "Mechanical work against constant Pext is w = −PextΔV.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "thermodynamics",
    "An isolated system is one which",
    [
      "exchanges both matter and energy with surroundings",
      "exchanges energy but not matter",
      "exchanges neither matter nor energy",
      "exchanges matter but not energy",
    ],
    2,
    "An isolated system has no exchange of mass or energy with the surroundings.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "thermodynamics",
    "For an endothermic reaction, ΔH is",
    ["negative", "positive", "zero", "always equal to ΔU"],
    1,
    "Heat is absorbed at constant pressure when ΔH > 0.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "thermodynamics",
    "The third law of thermodynamics states that the entropy of a perfect crystal at 0 K is",
    ["infinity", "R", "zero", "negative"],
    2,
    "A perfectly ordered crystal at absolute zero has S = 0.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "thermodynamics",
    "Which of the following is an intensive property?",
    ["mass", "volume", "internal energy", "temperature"],
    3,
    "Temperature does not depend on the amount of substance; mass, V and U are extensive.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "thermodynamics",
    "The standard enthalpy of combustion of an organic compound is",
    ["always positive", "always negative", "zero for carbon", "equal to ΔfH° of CO2 only"],
    1,
    "Combustion is exothermic, so ΔcH° is negative.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "thermodynamics",
    "Bond enthalpy is the enthalpy change for",
    [
      "forming 1 mol of bonds in a gaseous molecule",
      "breaking 1 mol of a particular type of bond in gaseous species",
      "sublimation of 1 mol of solid",
      "ionization of 1 mol of atoms only",
    ],
    1,
    "Bond enthalpy is the energy required to break one mole of bonds in the gas phase.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "thermodynamics",
    "The enthalpy change for H2(g) + 1/2 O2(g) → H2O(l) is the",
    ["enthalpy of combustion of H2O", "enthalpy of formation of H2O(l)", "bond enthalpy of O–H only", "lattice enthalpy of ice"],
    1,
    "Formation of one mole of H2O(l) from elements in standard states is ΔfH° of water.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "thermodynamics",
    "Heat (q) and work (w) are",
    ["state functions", "path functions", "always zero in a cyclic process individually", "intensive properties"],
    1,
    "q and w depend on how the change is carried out, not only on initial and final states.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "thermodynamics",
    "At equilibrium, the Gibbs energy change for the process is",
    ["positive", "negative", "zero", "equal to ΔH"],
    2,
    "ΔG = 0 is the condition for equilibrium at constant T and P.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "thermodynamics",
    "Using Hess's law, ΔH for C(graphite) → C(diamond) can be obtained from",
    [
      "densities of graphite and diamond only",
      "enthalpies of combustion of graphite and diamond",
      "melting points of the two allotropes",
      "electrical conductivity data only",
    ],
    1,
    "ΔH_trans = ΔcH(graphite) − ΔcH(diamond), because combustion products are the same.",
  ),

  // --- Equilibrium ---
  cbsePyq(
    "class-11",
    "chemistry",
    "equilibrium",
    "For aA + bB ⇌ cC + dD, the equilibrium constant Kc is",
    [
      "[A]^a[B]^b / [C]^c[D]^d",
      "[C]^c[D]^d / [A]^a[B]^b",
      "([C][D]) / ([A][B])",
      "[C] + [D] − [A] − [B]",
    ],
    1,
    "Kc is the product of product concentrations over reactant concentrations, each raised to its stoichiometric coefficient.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "equilibrium",
    "For N2(g) + 3H2(g) ⇌ 2NH3(g), increasing the pressure at constant temperature",
    [
      "shifts equilibrium to the left",
      "shifts equilibrium to the right",
      "does not shift the equilibrium",
      "decreases Kc",
    ],
    1,
    "The forward reaction reduces the number of gas moles (4 → 2), so higher P favours NH3 (Le Chatelier).",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "equilibrium",
    "The pH of 0.01 M HCl is",
    ["1", "2", "12", "0.01"],
    1,
    "HCl is a strong acid; [H+] = 0.01 M, so pH = 2.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "equilibrium",
    "The ionic product of water Kw at 25 °C is",
    ["1.0 × 10^−7", "1.0 × 10^−14", "1.0 × 10^−1", "7"],
    1,
    "At 25 °C, Kw = [H+][OH−] = 1.0 × 10^−14.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "equilibrium",
    "Kp and Kc are related by",
    ["Kp = Kc", "Kp = Kc (RT)^Δn", "Kp = Kc / RT", "Kp = Kc + RT"],
    1,
    "Δn is the change in moles of gas (products − reactants); Kp = Kc(RT)^Δn.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "equilibrium",
    "Addition of a catalyst to a reversible reaction",
    ["increases Kc", "decreases Kc", "does not change Kc", "changes ΔG°"],
    2,
    "A catalyst speeds up forward and reverse rates equally and does not alter the equilibrium constant.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "equilibrium",
    "The conjugate base of H2PO4− is",
    ["H3PO4", "HPO4^2−", "PO4^3−", "H2PO3−"],
    1,
    "Loss of one proton from H2PO4− gives HPO4^2−.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "equilibrium",
    "The common ion effect refers to",
    [
      "increase in ionization of a weak electrolyte on adding a common ion",
      "suppression of ionization of a weak electrolyte by a strong electrolyte having a common ion",
      "increase in solubility of a salt",
      "decrease in Kw",
    ],
    1,
    "Le Chatelier's principle: extra common ion shifts ionization equilibrium toward the undissociated form.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "equilibrium",
    "An acidic buffer is a mixture of",
    [
      "a strong acid and a strong base",
      "a weak acid and its salt with a strong base",
      "a weak base and a strong acid only",
      "two strong acids",
    ],
    1,
    "Example: CH3COOH + CH3COONa, which resists pH change.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "equilibrium",
    "An aqueous solution of NH4Cl is acidic due to",
    ["oxidation of NH4+", "hydrolysis of NH4+", "hydrolysis of Cl−", "evaporation of ammonia"],
    1,
    "NH4+ hydrolyses to give H3O+, so the solution is acidic.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "equilibrium",
    "At 25 °C, pH + pOH equals",
    ["7", "14", "1", "0"],
    1,
    "pKw = 14 at 25 °C, so pH + pOH = 14.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "equilibrium",
    "If the reaction quotient Q is less than Kc, the reaction",
    ["is at equilibrium", "proceeds in the forward direction", "proceeds in the reverse direction", "stops completely"],
    1,
    "When Q < K, the system forms more products until Q = K.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "equilibrium",
    "For an exothermic reaction, increasing temperature",
    ["increases K", "decreases K", "does not affect K", "always increases the yield of products"],
    1,
    "Heat is a product of an exothermic reaction; higher T shifts equilibrium backward and lowers K.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "equilibrium",
    "Ostwald's dilution law for a weak acid (α << 1) is",
    ["Ka = αC", "Ka = α^2 C", "Ka = α / C", "Ka = C / α^2"],
    1,
    "For HA ⇌ H+ + A−, Ka ≈ α^2 C when dissociation is small.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "equilibrium",
    "The solubility product of AgCl is expressed as",
    ["Ksp = [Ag+] / [Cl−]", "Ksp = [Ag+][Cl−]", "Ksp = [AgCl(s)]", "Ksp = [Ag+] + [Cl−]"],
    1,
    "For AgCl(s) ⇌ Ag+ + Cl−, Ksp = [Ag+][Cl−].",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "equilibrium",
    "Strong electrolytes in aqueous solution are",
    ["only slightly ionized", "almost completely ionized", "unionized", "insoluble"],
    1,
    "Strong acids, strong bases and most salts ionize almost completely.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "equilibrium",
    "In the equilibrium CaCO3(s) ⇌ CaO(s) + CO2(g), Kc is equal to",
    ["[CaO][CO2] / [CaCO3]", "[CO2]", "[CaO]", "[CaCO3]"],
    1,
    "Pure solids have unit activity, so Kc (or Kp) depends only on the CO2 concentration (or pressure).",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "equilibrium",
    "A larger value of Ka for a weak acid means the acid is",
    ["weaker", "stronger", "less soluble", "more basic"],
    1,
    "Larger Ka corresponds to greater dissociation and a stronger weak acid.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "equilibrium",
    "According to Le Chatelier's principle, adding a product to an equilibrium mixture",
    ["shifts the equilibrium forward", "shifts the equilibrium backward", "increases Kc", "has no effect"],
    1,
    "The system consumes the added product by shifting toward reactants.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "equilibrium",
    "The pH of 10^−8 M HCl is",
    ["8", "6", "slightly less than 7", "0"],
    2,
    "Water's [H+] cannot be neglected; the solution is still acidic, so pH is just below 7, not 8.",
  ),

  // --- Redox Reactions ---
  cbsePyq(
    "class-11",
    "chemistry",
    "redox-reactions",
    "The oxidation number of Mn in KMnO4 is",
    ["+2", "+4", "+6", "+7"],
    3,
    "K is +1 and each O is −2: +1 + Mn + 4(−2) = 0, so Mn = +7.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "redox-reactions",
    "The oxidation number of Cr in K2Cr2O7 is",
    ["+3", "+4", "+6", "+7"],
    2,
    "2(+1) + 2Cr + 7(−2) = 0 gives Cr = +6.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "redox-reactions",
    "An oxidizing agent is a species that",
    ["is oxidized", "is reduced", "loses electrons", "increases the oxidation number of itself"],
    1,
    "The oxidizing agent gains electrons and is itself reduced.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "redox-reactions",
    "The reaction 2H2O2 → 2H2O + O2 is an example of",
    ["only oxidation", "only reduction", "disproportionation", "neutralization"],
    2,
    "Oxygen in H2O2 (−1) is both oxidized to O2 (0) and reduced to H2O (−2).",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "redox-reactions",
    "The oxidation number of sulphur in H2SO4 is",
    ["+2", "+4", "+6", "−2"],
    2,
    "2(+1) + S + 4(−2) = 0, so S = +6.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "redox-reactions",
    "The oxidation number of oxygen in OF2 is",
    ["−2", "−1", "+1", "+2"],
    3,
    "Fluorine is more electronegative and is −1 each, so O is +2.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "redox-reactions",
    "The oxidation number of oxygen in H2O2 is",
    ["−2", "−1", "0", "+1"],
    1,
    "In peroxides, each oxygen has oxidation number −1.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "redox-reactions",
    "The oxidation number of oxygen in KO2 (potassium superoxide) is",
    ["−2", "−1", "−1/2", "+2"],
    2,
    "K is +1 and O2− has a charge of −1, so each O is −1/2.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "redox-reactions",
    "The oxidation number of iron in Fe3O4 is",
    ["+2", "+3", "+8/3", "+4"],
    2,
    "Fe3O4 is a mixed oxide; average ON of Fe is +8/3.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "redox-reactions",
    "The oxidation number of nitrogen in HNO3 is",
    ["+3", "+4", "+5", "−3"],
    2,
    "+1 + N + 3(−2) = 0, so N = +5.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "redox-reactions",
    "The highest oxidation number shown by chlorine is",
    ["+1", "+3", "+5", "+7"],
    3,
    "Chlorine exhibits +7 in HClO4 and Cl2O7.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "redox-reactions",
    "A reducing agent is a species that",
    ["gains electrons", "is reduced", "loses electrons (is oxidized)", "always contains oxygen"],
    2,
    "The reducing agent donates electrons and is oxidized.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "redox-reactions",
    "Which of the following is not a redox reaction?",
    [
      "2Na + Cl2 → 2NaCl",
      "Zn + CuSO4 → ZnSO4 + Cu",
      "NaOH + HCl → NaCl + H2O",
      "2Mg + O2 → 2MgO",
    ],
    2,
    "Acid–base neutralization involves no change in oxidation numbers.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "redox-reactions",
    "The oxidation number of carbon in CCl4 is",
    ["0", "+2", "+4", "−4"],
    2,
    "Each Cl is −1, so C + 4(−1) = 0 gives C = +4.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "redox-reactions",
    "In 2Na + Cl2 → 2NaCl, sodium is",
    ["reduced", "oxidized", "neither oxidized nor reduced", "the oxidizing agent"],
    1,
    "Na goes from 0 to +1 (loss of electrons) and is oxidized.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "redox-reactions",
    "The average oxidation number of sulphur in Na2S2O3 is",
    ["+2", "+3", "+4", "+6"],
    0,
    "2(+1) + 2S + 3(−2) = 0, so average ON of S is +2.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "redox-reactions",
    "The oxidation number of phosphorus in H3PO4 is",
    ["+3", "+5", "−3", "+1"],
    1,
    "3(+1) + P + 4(−2) = 0, so P = +5.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "redox-reactions",
    "Spectator ions in a redox reaction are ions that",
    [
      "change their oxidation number",
      "do not take part in the actual redox change",
      "are always H+ and OH−",
      "are deposited at electrodes only",
    ],
    1,
    "They appear unchanged on both sides of the ionic equation.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "redox-reactions",
    "In acidic medium, MnO4− is typically reduced to",
    ["MnO2", "MnO4^2−", "Mn2+", "Mn"],
    2,
    "Permanganate in acid is a strong oxidant and is reduced to colourless Mn2+.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "redox-reactions",
    "The oxidation number of chromium in CrO5 is",
    ["+6", "+10", "+4", "+5"],
    0,
    "CrO5 has a peroxide structure: four O are −1 (peroxo) and one O is −2, so Cr is +6.",
  ),

  // --- Organic Chemistry: Some Basic Principles ---
  cbsePyq(
    "class-11",
    "chemistry",
    "organic-chemistry-some-basic-principles",
    "The inductive effect is the",
    [
      "delocalization of π electrons",
      "permanent displacement of σ electrons along a chain",
      "temporary polarization in an electric field only",
      "sharing of a lone pair to form a π bond",
    ],
    1,
    "±I is the permanent shift of sigma-bond electron density due to electronegativity differences.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "organic-chemistry-some-basic-principles",
    "Resonance (mesomeric) effect involves",
    [
      "only σ-bond polarization",
      "delocalization of π or lone-pair electrons",
      "breaking of all bonds in the molecule",
      "only intermolecular hydrogen bonding",
    ],
    1,
    "±R/±M arises from conjugation of π bonds or lone pairs with an adjacent π system.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "organic-chemistry-some-basic-principles",
    "The IUPAC name of CH3CH2CH2OH is",
    ["propan-2-ol", "propan-1-ol", "methoxyethane", "propanone"],
    1,
    "A three-carbon chain with −OH on carbon 1 is propan-1-ol.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "organic-chemistry-some-basic-principles",
    "Homolytic fission of a covalent bond produces",
    ["a cation and an anion", "free radicals", "only a carbocation", "only a carbanion"],
    1,
    "Each fragment takes one electron of the shared pair, giving radicals.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "organic-chemistry-some-basic-principles",
    "The correct order of carbocation stability is",
    ["methyl > 1° > 2° > 3°", "3° > 2° > 1° > methyl", "1° > 2° > 3° > methyl", "2° > 3° > 1° > methyl"],
    1,
    "Alkyl +I and hyperconjugation stabilize 3° carbocations most.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "organic-chemistry-some-basic-principles",
    "An electrophile is a species that is",
    ["electron rich", "electron deficient (Lewis acid)", "always negatively charged", "a free radical only"],
    1,
    "Electrophiles seek electrons; examples are H+, +NO2, AlCl3 and BF3.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "organic-chemistry-some-basic-principles",
    "Hyperconjugation involves delocalization of",
    [
      "π electrons only into a sigma bond",
      "electrons of a C–H σ bond of an alkyl group with an adjacent empty p orbital or π bond",
      "only lone pairs on oxygen",
      "d electrons of carbon",
    ],
    1,
    "No-bond resonance from α-C–H bonds stabilizes carbocations and alkenes.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "organic-chemistry-some-basic-principles",
    "The IUPAC name of CH3COCH3 is",
    ["propanal", "propan-2-one", "propan-1-ol", "ethanoic acid"],
    1,
    "A three-carbon ketone with the carbonyl at C-2 is propan-2-one (acetone).",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "organic-chemistry-some-basic-principles",
    "Alkyl groups generally show a",
    ["−I effect", "+I effect", "−R effect only", "no electronic effect"],
    1,
    "Alkyl groups are electron-releasing by the inductive effect (+I).",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "organic-chemistry-some-basic-principles",
    "The hybridisation of each carbon in ethyne (C2H2) is",
    ["sp3", "sp2", "sp", "sp3d"],
    2,
    "Each carbon in H−C≡C−H forms two sigma bonds and is sp hybridised.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "organic-chemistry-some-basic-principles",
    "Successive members of a homologous series differ by",
    ["CH3", "CH2", "OH", "CO"],
    1,
    "A homologous series differs by a −CH2− unit (14 u).",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "organic-chemistry-some-basic-principles",
    "Heterolytic fission of a C–Cl bond typically produces",
    ["two free radicals", "a carbocation and Cl−", "a carbanion and Cl+", "two carbocations"],
    1,
    "Chlorine takes both bonding electrons, giving R+ and Cl−.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "organic-chemistry-some-basic-principles",
    "The IUPAC name of (CH3)2CHCH2CH3 is",
    ["pentane", "2-methylbutane", "2,2-dimethylpropane", "2-methylpropane"],
    1,
    "The longest chain has four carbons with a methyl branch at C-2: 2-methylbutane.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "organic-chemistry-some-basic-principles",
    "Which group shows a −R (−M) effect?",
    ["−OH", "−OCH3", "−NH2", "−NO2"],
    3,
    "−NO2 withdraws electron density by resonance from an attached aromatic or unsaturated system.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "organic-chemistry-some-basic-principles",
    "A nucleophile is a species that",
    [
      "is electron deficient",
      "attacks electron-deficient centres (Lewis base)",
      "always has a positive charge",
      "cannot have a lone pair",
    ],
    1,
    "Nucleophiles donate an electron pair (OH−, CN−, NH3, H2O).",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "organic-chemistry-some-basic-principles",
    "The correct order of carbanion stability is",
    ["3° > 2° > 1°", "1° > 2° > 3°", "2° > 1° > 3°", "3° > 1° > 2°"],
    1,
    "Alkyl +I effect destablizes negative charge, so methyl/1° carbanions are more stable than 3°.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "organic-chemistry-some-basic-principles",
    "The functional group present in RCOOH is",
    ["hydroxyl only", "carbonyl only", "carboxyl", "ester"],
    2,
    "Carboxylic acids contain the carboxyl (−COOH) group.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "organic-chemistry-some-basic-principles",
    "Butane and 2-methylpropane are",
    ["position isomers", "chain isomers", "functional isomers", "metamers"],
    1,
    "They have the same molecular formula C4H10 but different carbon-chain branching.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "organic-chemistry-some-basic-principles",
    "The −NO2 group exerts a",
    ["+I effect", "−I effect", "no inductive effect", "+R effect only and no −I"],
    1,
    "Nitro is strongly electron-withdrawing by induction (−I) as well as by resonance.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "organic-chemistry-some-basic-principles",
    "Which of the following is an electrophilic reagent?",
    ["NH3", "OH−", "AlCl3", "CN−"],
    2,
    "AlCl3 is a Lewis acid and a classic electrophile in Friedel–Crafts reactions.",
  ),

  // --- Hydrocarbons ---
  cbsePyq(
    "class-11",
    "chemistry",
    "hydrocarbons",
    "The Wurtz reaction of 2CH3Br with sodium in dry ether gives",
    ["methane", "ethane", "ethene", "ethyne"],
    1,
    "2CH3Br + 2Na → CH3–CH3 + 2NaBr.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "hydrocarbons",
    "According to Markovnikov's rule, in the addition of HBr to propene the major product is",
    ["1-bromopropane", "2-bromopropane", "1,2-dibromopropane", "propane"],
    1,
    "H adds to the carbon already having more hydrogens, giving 2-bromopropane.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "hydrocarbons",
    "Hückel's rule for aromaticity requires",
    ["4n π electrons", "(4n + 2) π electrons", "4n + 1 π electrons", "an odd number of carbon atoms only"],
    1,
    "A planar cyclic conjugated system with 4n+2 π electrons is aromatic.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "hydrocarbons",
    "Ozonolysis of ethene followed by Zn/H2O gives",
    ["HCOOH", "HCHO", "CH3CHO", "CH3COOH"],
    1,
    "Cleavage of H2C=CH2 yields two molecules of methanal.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "hydrocarbons",
    "Friedel–Crafts alkylation of benzene is carried out using",
    ["RCl and anhydrous AlCl3", "RCOOH and NaOH", "conc. HNO3 only", "aqueous KMnO4"],
    0,
    "An alkyl halide with anhydrous AlCl3 generates an electrophile that substitutes on benzene.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "hydrocarbons",
    "Hydration of ethyne in the presence of HgSO4/H2SO4 gives",
    ["ethanol", "ethanal", "ethanoic acid", "propanone"],
    1,
    "Addition of water to HC≡CH followed by tautomerism produces acetaldehyde (ethanal).",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "hydrocarbons",
    "Baeyer's reagent (cold dilute alkaline KMnO4) is decolorized by",
    ["alkanes", "benzene", "alkenes", "methane only"],
    2,
    "Alkenes are oxidized to vicinal diols and purple MnO4− is reduced, so the colour disappears.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "hydrocarbons",
    "Alcoholic KOH with a haloalkane typically gives an",
    ["alcohol", "alkene", "alkane", "ether by SN2 only"],
    1,
    "Alcoholic KOH promotes dehydrohalogenation (β-elimination) to an alkene.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "hydrocarbons",
    "Kolbe electrolytic decarboxylation of sodium acetate gives",
    ["methane", "ethane", "ethene", "methanol"],
    1,
    "2CH3COO− → C2H6 + 2CO2 at the anode (Kolbe electrolysis).",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "hydrocarbons",
    "Nitration of benzene is carried out with",
    ["dilute HNO3", "conc. HNO3 + conc. H2SO4", "NO2 gas only", "NaNO2 / HCl"],
    1,
    "The mixed acid generates the nitronium ion +NO2, the electrophile.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "hydrocarbons",
    "Ethyne reacts with ammoniacal AgNO3 because it has",
    ["an acidic hydrogen on an sp carbon", "only sp2 hydrogens", "no π bonds", "a larger size than ethene"],
    0,
    "Terminal alkynes are acidic enough to form silver acetylide; ethene and ethane do not.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "hydrocarbons",
    "In the presence of peroxides, HBr adds to propene to give mainly",
    ["2-bromopropane", "1-bromopropane", "1,2-dibromopropane", "2,2-dibromopropane"],
    1,
    "The peroxide (Kharasch) effect causes anti-Markovnikov addition of HBr.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "hydrocarbons",
    "Lindlar's catalyst is used to convert an alkyne into a",
    ["alkane", "cis-alkene", "trans-alkene exclusively without catalyst control", "benzene"],
    1,
    "Poisoned Pd (Lindlar) stops hydrogenation at the cis-alkene stage.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "hydrocarbons",
    "Soda-lime decarboxylation of CH3COONa yields",
    ["ethane", "methane", "ethene", "methanol"],
    1,
    "CH3COONa + NaOH (CaO) → CH4 + Na2CO3.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "hydrocarbons",
    "Decolorization of bromine in CCl4 is a test for",
    ["alkanes", "unsaturation (alkenes/alkynes)", "aromaticity of benzene", "acidity of ethyne only"],
    1,
    "Alkenes and alkynes add Br2 and the reddish-brown colour disappears; benzene does not without a catalyst.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "hydrocarbons",
    "Benzene resists addition reactions mainly because of",
    ["its high boiling point", "aromatic resonance stability", "the presence of only sigma bonds", "its insolubility in water"],
    1,
    "Delocalized 6π electrons (aromaticity) make substitution preferred over addition.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "hydrocarbons",
    "Which substituent is ortho–para directing in electrophilic aromatic substitution?",
    ["−NO2", "−CHO", "−COOH", "−OH"],
    3,
    "−OH is a strongly activating o,p-director; −NO2, −CHO and −COOH are meta-directing.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "hydrocarbons",
    "Thermal cracking of alkanes produces",
    ["only carbon and hydrogen", "smaller alkanes and alkenes", "only aromatic compounds", "only alcohols"],
    1,
    "C–C cleavage at high temperature gives a mixture of lower alkanes and alkenes.",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "hydrocarbons",
    "Polymerization of ethene gives",
    ["PVC", "polythene", "Teflon", "Bakelite"],
    1,
    "n CH2=CH2 → (−CH2−CH2−)n, polythene (polyethylene).",
  ),
  cbsePyq(
    "class-11",
    "chemistry",
    "hydrocarbons",
    "Cis–trans isomerism in alkenes requires",
    [
      "free rotation about the C=C bond",
      "each doubly bonded carbon attached to two different groups",
      "at least four carbon atoms in a ring only",
      "an odd number of π electrons",
    ],
    1,
    "Restricted rotation about C=C and two different substituents on each carbon allow geometric isomers.",
  ),
];

assertTwentyPerChapter(class11ChemistryQuestions, [
  "some-basic-concepts-of-chemistry",
  "structure-of-atom",
  "classification-of-elements-and-periodicity",
  "chemical-bonding-and-molecular-structure",
  "thermodynamics",
  "equilibrium",
  "redox-reactions",
  "organic-chemistry-some-basic-principles",
  "hydrocarbons",
]);
